---
sidebar: sidebar 
permalink: hu-aix-70.html 
keywords: host utilities, aix, powervm, vios, 3.1, 7.0, netapp, ontap 
summary: AIX Host Utilitiesは、AIXホストに接続されているONTAPストレージの管理に役立ちます。 
---
= AIX Host Utilities 7.0のインストール
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
AIX Host Utilitiesは、AIXホストに接続されているONTAPストレージの管理に役立ちます。

AIX Host Utilitiesは次のプロトコルをサポートします。

* FC
* FCoE
* iSCSI


AIX Host Utilitiesは次の環境をサポートします。

* AIX MicrosoftマルチパスI/O（MPIO）（ネイティブOS）
* PowerVM
+
PowerVMの詳細については、『IBM PowerVM Live Partition Mobility Red Book』を参照してください。



.開始する前に
* 安定した運用を実現するために、iSCSI、FC、またはFCoE構成全体がサポートされていることを確認します。
+
を使用して構成を確認できます https://imt.netapp.com/matrix/#welcome["Interoperability Matrix Tool"^]。

* すべてのFCイニシエータおよびFCoEイニシエータで動的追跡を有効にする必要があります。



NOTE: NetApp AIX Host Utilitiesソフトウェアパッケージは、に圧縮形式で `tar.gz file`提供されていlink:https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/7.0["ネットアップサポートサイト"^]ます。AIX MPIOとONTAPストレージを使用する際には、AIX Host Utilitiesキットをインストールする必要があります。

.手順
. ホストにログインします。
+
** AIX ホストでは、 * root * としてログインします。
** PowerVMホストで、* padmin *としてログインし、 `oem_setup_env`コマンドを入力してrootユーザに切り替えます。


. に移動し https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/7.0["ネットアップサポートサイト"^]、Host Utilitiesが含まれている圧縮ファイルをホストのディレクトリにダウンロードします。
. ダウンロードを格納しているディレクトリに移動します。
. ファイルを解凍し、SAN Toolkitソフトウェアパッケージを展開します。
+
`# tar -xvf ntap_aix_host_utilities_7.0.tar.gz`

+
ファイルを解凍すると、次のディレクトリが作成されます `ntap_aix_host_utilities_7.0`。このディレクトリには、MPIO、NON_MPIO、SAN_Tool_Kitのいずれかのサブディレクトリが含まれています。

. AIX MPIO をインストールします。
+
`# installp -aXYd /var/tmp/ntap_aix_host_utilities_7.0/MPIO NetApp.MPIO_Host_Utilities_Kit`

. SAN Toolkit をインストールします。
+
`# installp -aXYd /var/tmp/ntap_aix_host_utilities_7.0/SAN_Tool_Kit/NetApp.SAN_toolkit`

. ホストをリブートします。
. インストールを確認します。
+
`# lslpp -l |grep -i netapp`

+
[listing]
----
NetApp.MPIO_Host_Utilities_Kit.config
                             7.0.0.0  COMMITTED  NetApp MPIO PCM Host Utilities
  NetApp.MPIO_Host_Utilities_Kit.fcp
                             7.0.0.0  COMMITTED  NetApp MPIO PCM Host Utilities
  NetApp.MPIO_Host_Utilities_Kit.iscsi
                             7.0.0.0  COMMITTED  NetApp MPIO PCM Host Utilities
  NetApp.MPIO_Host_Utilities_Kit.pcmodm
                             7.0.0.0  COMMITTED  NetApp MPIO PCM Host Utilities
NetApp.SAN_toolkit.sanlun  7.0.0.0  COMMITTED  NetApp SAN Toolkit sanlun
----
. ソフトウェアのバージョンを確認します。
+
`# sanlun version`

+
[listing]
----
7.0.725.3521
----
.  `lbp_enabled`次のコマンドを実行して、SCSI UNMAPパラメータがODMに追加されたことを確認します。
+
`# odmget -q "uniquetype=disk/fcp/NetAppMPIO" PdAt |grep  "lbp_enabled"`

+
[listing]
----
attribute = "lbp_enabled"
----
+
`# odmget -q "uniquetype=disk/fcp/NetAppMPIO and attribute=lbp_enabled" PdAt`

+
[listing]
----
PdAt:
        uniquetype = "disk/fcp/NetAppMPIO"
        attribute = "lbp_enabled"
        deflt = "true"
        values = "true,false"
        width = ""
        type = "R"
        generic = ""
        rep = "s"
        nls_index = 18
----




== SAN ツールキット

AIX Host Utilitiesは、IBM AIXホストにコマンドラインツールキットを提供するNetAppホストソフトウェアです。このツールキットは、 NetApp Host Utilities パッケージをインストールするときにインストールされます。このキットは、を提供します `sanlun` ユーティリティ。LUNおよびHost Bus Adapter（HBA；ホストバスアダプタ）の管理に役立ちます。。 `sanlun` コマンドは、ホストにマッピングされているLUNに関する情報、マルチパス、およびイニシエータグループの作成に必要な情報を返します。

* 例 *

次の例では 'lun lun lun show コマンドは LUN 情報を返します

[listing]
----
# sanlun lun show all
----
*出力例*

[listing]
----
controller(7mode)/ device host lun

vserver(Cmode) lun-pathname filename adapter protocol size mode
----------------------------------------------------------------
data_vserver   /vol/vol1/lun1 hdisk0 fcs0    FCP      60g C
data_vserver   /vol/vol2/lun2 hdisk0 fcs0    FCP      20g C
data_vserver   /vol/vol3/lun3 hdisk11 fcs0   FCP      20g C
data_vserver   /vol/vol4/lun4 hdisk14 fcs0   FCP      20g C
----

NOTE: このツールキットは、Host Utilitiesのすべての構成とプロトコルに共通です。そのため、すべてのコンポーネントがすべての構成に適用されるわけではありません。使用していないコンポーネントは、システムのパフォーマンスに影響しません。SAN Toolkitは、AIXおよびPowerVM / VIOS OSのバージョンでサポートされます。
