---
sidebar: sidebar 
permalink: hu-aix-70.html 
keywords: host utilities, aix, powervm, vios, 3.1, 7.0, netapp, ontap 
summary: AIX Host Utilitiesは、AIXホストに接続されているONTAPストレージの管理に役立ちます。 
---
= ONTAPストレージ用のAIXホストユーティリティ7.0をインストールする
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
AIX ホスト ユーティリティは、AIX ホストに接続されたONTAPストレージの管理に役立ちます。  NetApp、 ONTAPストレージ管理を改善し、 NetAppサポートによる構成情報収集を支援するために、AIX ホスト ユーティリティをインストールすることを強くお勧めします。

AIX ホスト ユーティリティ 7.0 は、次のトランスポート プロトコルと AIX 環境をサポートします。

* FC、FCoE、iSCSI
* AIX Microsoft マルチパス I/O (MPIO)
* PowerVM
+
PowerVM の詳細については、「IBM PowerVM Live Partition Mobility Red Book」を参照してください。



.このタスクについて
* AIX ホストに接続されたONTAPストレージを管理するには、AIX MPIO とともに AIX Host Utilities SAN Toolkit をインストールする必要があります。
* AIX ホスト ユーティリティをインストールしても、AIX ホストの設定は変更されません。


.開始する前に
* 使用link:https://mysupport.netapp.com/matrix/#welcome["Interoperability Matrix Tool"^]AIX OS、プロトコル、およびONTAPバージョンが SAN ブートをサポートしていることを確認します。
* 全てのFCおよびFCoEイニシエーターの動的トラッキングを有効にするには、 `chdev -l <fscsi_device> -a dyntrk=ye` AIX ホスト上のコマンド。


.手順
. ホストにログインします。
+
[role="tabbed-block"]
====
.AIX の場合
--
AIX ホストでは、 * root * としてログインします。

--
.PowerVM
--
PowerVM ホストの場合:

.. *padmin* としてログインします。
.. ルートユーザーになる:
+
[source, cli]
----
oem_setup_env
----


--
====
. に移動し https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/7.0["ネットアップサポートサイト"^]、Host Utilitiesが含まれている圧縮ファイルをホストのディレクトリにダウンロードします。
. ダウンロードを格納しているディレクトリに移動します。
. ファイルを解凍し、SAN Toolkitソフトウェアパッケージを展開します。
+
[source, cli]
----
tar -xvf ntap_aix_host_utilities_7.0.tar.gz
----
+
ファイルを解凍すると、次のディレクトリが作成されます `ntap_aix_host_utilities_7.0`。このディレクトリには、MPIO、NON_MPIO、SAN_Tool_Kitのいずれかのサブディレクトリが含まれています。

. AIX MPIO をインストールします。
+
[source, cli]
----
installp -aXYd /var/tmp/ntap_aix_host_utilities_7.0/MPIO NetApp.MPIO_Host_Utilities_Kit
----
. SAN Toolkit をインストールします。
+
[source, cli]
----
installp -aXYd /var/tmp/ntap_aix_host_utilities_7.0/SAN_Tool_Kit/NetApp.SAN_toolkit
----
. ホストをリブートします。
. インストールを確認します。
+
[source, cli]
----
lslpp -l |grep -i netapp
----
+
[listing]
----
NetApp.MPIO_Host_Utilities_Kit.config
                             7.0.0.0  COMMITTED  NetApp MPIO PCM Host Utilities
  NetApp.MPIO_Host_Utilities_Kit.fcp
                             7.0.0.0  COMMITTED  NetApp MPIO PCM Host Utilities
  NetApp.MPIO_Host_Utilities_Kit.iscsi
                             7.0.0.0  COMMITTED  NetApp MPIO PCM Host Utilities
  NetApp.MPIO_Host_Utilities_Kit.pcmodm
                             7.0.0.0  COMMITTED  NetApp MPIO PCM Host Utilities
NetApp.SAN_toolkit.sanlun  7.0.0.0  COMMITTED  NetApp SAN Toolkit sanlun
----
. ソフトウェアのバージョンを確認します。
+
[source, cli]
----
sanlun version
----
+
[listing]
----
7.0.725.3521
----
. SCSI UNMAPを確認する `lbp_enabled`パラメータが ODM に追加されます:
+
[source, cli]
----
odmget -q "uniquetype=disk/fcp/NetAppMPIO" PdAt |grep  "lbp_enabled"
----
+
[listing]
----
attribute = "lbp_enabled"
----
+
[source, cli]
----
odmget -q "uniquetype=disk/fcp/NetAppMPIO and attribute=lbp_enabled" PdAt`
----
+
[listing]
----
PdAt:
        uniquetype = "disk/fcp/NetAppMPIO"
        attribute = "lbp_enabled"
        deflt = "true"
        values = "true,false"
        width = ""
        type = "R"
        generic = ""
        rep = "s"
        nls_index = 18
----




== 次の手順

link:hu-aix-san-toolkit.html["AIX SAN ツールキットについて学ぶ"] 。
