---
sidebar: sidebar 
permalink: hu-aix-command-reference.html 
keywords: host utilities, aix, powervm, vios, 3.1, 7.2, 7.0, netapp, ontap 
summary: Host Utilitiesツールを使用してNetAppストレージ構成をエンドツーエンドで検証するには、AIX Host Utilitiesのサンプルコマンドリファレンスを使用します。 
---
= AIXホストユーティリティコマンドを使用してONTAPストレージ構成を確認します
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Host Utilitiesツールを使用してNetAppストレージ構成をエンドツーエンドで検証するには、AIX Host Utilitiesのサンプルコマンドリファレンスを使用します。



== ホストにマッピングされているすべてのホストイニシエータを一覧表示

ホストにマッピングされているホストイニシエータのリストを取得できます。

[source, cli]
----
sanlun fcp show adapter -v
----
[role="tabbed-block"]
====
.8.0
--
.AIX ホストユーティリティ 8.0 の例を表示
[%collapsible]
=====
[listing]
----
adapter name:      fcs4
WWPN:              100000109bf606a8
WWNN:              200000109bf606a8
driver name:       /usr/lib/drivers/pci/emfcdd
model:             df1000e31410150
model description: FC Adapter
serial number:     Y050HY22L002
hardware version:  Not Available
driver version:    7.2.5.201
firmware version:  00014000000057400007
Number of ports:   1
port type:         Fabric
port state:        Operational
supported speed:   32 GBit/sec
negotiated speed:  32 GBit/sec
OS device name:    fcs4
adapter name:      fcs5
WWPN:              100000109bf606a9
WWNN:              200000109bf606a9
driver name:       /usr/lib/drivers/pci/emfcdd
model:             df1000e31410150
model description: FC Adapter
serial number:     Y050HY22L002
hardware version:  Not Available
driver version:    7.2.5.201
firmware version:  00014000000057400007
Number of ports:   1
port type:         Fabric
port state:        Operational
supported speed:   32 GBit/sec
negotiated speed:  32 GBit/sec
OS device name:    fcs5
bash-3.2#
----
=====
--
.7.0と6.1
--
.AIX ホストユーティリティ 7.0 および 6.1 の例を表示
[%collapsible]
=====
[listing]
----
bash-3.2# sanlun fcp show adapter -v
adapter name: fcs0
WWPN: 100000109b22e143
WWNN: 200000109b22e143
driver name: /usr/lib/drivers/pci/emfcdd
model: df1000e31410150
model description: FC Adapter
serial number: YA50HY79S117
hardware version: Not Available
driver version: 7.2.5.0
firmware version: 00012000040025700027
Number of ports: 1
port type: Fabric
port state: Operational
supported speed: 16 GBit/sec
negotiated speed: Unknown
OS device name: fcs0
adapter name: fcs1
WWPN: 100000109b22e144
WWNN: 200000109b22e144
driver name: /usr/lib/drivers/pci/emfcdd
model: df1000e31410150
model description: FC Adapter
serial number: YA50HY79S117
hardware version: Not Available
driver version: 7.2.5.0
firmware version: 00012000040025700027
Number of ports: 1
port type: Fabric
port state: Operational
supported speed: 16 GBit/sec
negotiated speed: Unknown
OS device name: fcs1
bash-3.2#
----
=====
--
====


== ホストにマッピングされているすべての LUN をリストします

ホストにマッピングされているすべてのLUNのリストを取得できます。

[source, cli]
----
sanlun lun show -p -v all
----
[role="tabbed-block"]
====
.8.0
--
.AIX ホストユーティリティ 8.0 の例を表示
[%collapsible]
=====
[listing]
----
LUN: 88
LUN Size: 15g
Host Device: hdisk9
Mode: C
Multipath Provider: AIX Native
Multipathing Algorithm: round_robin

host    vserver  AIX   AIX MPIO
path    path     MPIO  host      vserver      path
state   type     path  adapter   LIF          priority
-----------------------------------------------------
up     primary   path0   fcs0    fc_aix_1     1
up     primary   path1   fcs1    fc_aix_2     1
up     secondary path2   fcs0    fc_aix_3     1
up     secondary path3   fcs1    fc_aix_4     1
----
=====
--
.7.0と6.1
--
.AIX ホストユーティリティ 7.0 および 6.1 の例を表示
[%collapsible]
=====
[listing]
----
ONTAP Path: vs_aix_clus:/vol/gpfs_205p2_207p1_vol_0_8/aix_205p2_207p1_lun
LUN: 88
LUN Size: 15g
Host Device: hdisk9
Mode: C
Multipath Provider: AIX Native
Multipathing Algorithm: round_robin

host    vserver  AIX   AIX MPIO
path    path     MPIO  host      vserver      path
state   type     path  adapter   LIF          priority
-----------------------------------------------------
up     primary   path0   fcs0    fc_aix_1     1
up     primary   path1   fcs1    fc_aix_2     1
up     secondary path2   fcs0    fc_aix_3     1
up     secondary path3   fcs1    fc_aix_4     1
----
=====
--
====


== 特定の SVM からホストにマッピングされているすべての LUN をリストします

指定したSVMからホストにマッピングされているすべてのLUNのリストを取得できます。

[source, cli]
----
sanlun lun show -p -v sanboot_unix
----
[role="tabbed-block"]
====
.8.0
--
.AIX ホストユーティリティ 8.0 の例を表示
[%collapsible]
=====
[listing]
----
ONTAP Path: sanboot_unix:/vol/aix_205p2_boot_0/boot_205p2_lun
LUN: 0
LUN Size: 80.0g
Host Device: hdisk85
Mode: C
Multipath Provider: AIX Native
Multipathing Algorithm: round_robin

host    vserver    AIX   AIX MPIO
path    path       MPIO  host    vserver    path
state   type       path  adapter LIF        priority
-------------------------------------------------
up      primary    path0 fcs0    sanboot_1   1
up      primary    path1 fcs1    sanboot_2   1
up      secondary  path2 fcs0    sanboot_3   1
up      secondary  path3 fcs1    sanboot_4   1
----
=====
--
.7.0と6.1
--
.AIX ホストユーティリティ 7.0 および 6.1 の例を表示
[%collapsible]
=====
[listing]
----
ONTAP Path: sanboot_unix:/vol/aix_205p2_boot_0/boot_205p2_lun
LUN: 0
LUN Size: 80.0g
Host Device: hdisk85
Mode: C
Multipath Provider: AIX Native
Multipathing Algorithm: round_robin

host    vserver    AIX   AIX MPIO
path    path       MPIO  host    vserver    path
state   type       path  adapter LIF        priority
-------------------------------------------------
up      primary    path0 fcs0    sanboot_1   1
up      primary    path1 fcs1    sanboot_2   1
up      secondary  path2 fcs0    sanboot_3   1
up      secondary  path3 fcs1    sanboot_4   1
----
=====
--
====


== ホストにマッピングされている特定の LUN のすべての属性を一覧表示します

ホストにマッピングされている指定したLUNのすべての属性のリストを取得できます。

[source, cli]
----
sanlun lun show -p -v vs_aix_clus:/vol/gpfs_205p2_207p1_vol_0_8/aix_205p2_207p1_lun
----
[role="tabbed-block"]
====
.8.0
--
.AIX ホストユーティリティ 8.0 の例を表示
[%collapsible]
=====
[listing]
----
ONTAP Path: vs_aix_clus:/vol/gpfs_205p2_207p1_vol_0_8/aix_205p2_207p1_lun
LUN: 88
LUN Size: 15g
Host Device: hdisk9
Mode: C
Multipath Provider: AIX Native
Multipathing Algorithm: round_robin

host     vserver   AIX   AIX MPIO
path     path      MPIO  host     vserver   path
state    type      path  adapter  LIF       priority
---------------------------------------------------------
up       primary   path0 fcs0    fc_aix_1   1
up       primary   path1 fcs1    fc_aix_2   1
up       secondary path2 fcs0    fc_aix_3   1
up       secondary path3 fcs1    fc_aix_4   1
----
=====
--
.7.0と6.1
--
.AIX ホストユーティリティ 7.0 および 6.1 の例を表示
[%collapsible]
=====
[listing]
----
ONTAP Path: vs_aix_clus:/vol/gpfs_205p2_207p1_vol_0_8/aix_205p2_207p1_lun
LUN: 88
LUN Size: 15g
Host Device: hdisk9
Mode: C
Multipath Provider: AIX Native
Multipathing Algorithm: round_robin

host     vserver   AIX   AIX MPIO
path     path      MPIO  host     vserver   path
state    type      path  adapter  LIF       priority
---------------------------------------------------------
up       primary   path0 fcs0    fc_aix_1   1
up       primary   path1 fcs1    fc_aix_2   1
up       secondary path2 fcs0    fc_aix_3   1
up       secondary path3 fcs1    fc_aix_4   1
----
=====
--
====


== ホストデバイスファイル名ごとにONTAP LUN属性を表示

ホストデバイスのファイル名を指定すると、ONTAP LUN属性のリストを取得できます。

[source, cli]
----
sanlun lun show -d /dev/hdisk1
----
[role="tabbed-block"]
====
.8.0
--
.AIX ホストユーティリティ 8.0 の例を表示
[%collapsible]
=====
[listing]
----
controller(7mode)/
device host lun
vserver(Cmode)     lun-pathname
-----------------------------------------------------------------------------
vs_aix_clus       /vol/gpfs_205p2_207p1_vol_0_0/aix_205p2_207p1_lun

filename adapter protocol size mode
-----------------------------------
hdisk1    fcs0    FCP     15g  C
----
=====
--
.7.0と6.1
--
.AIX ホストユーティリティ 7.0 および 6.1 の例を表示
[%collapsible]
=====
[listing]
----
controller(7mode)/
device host lun
vserver(Cmode)     lun-pathname
-----------------------------------------------------------------------------
vs_aix_clus       /vol/gpfs_205p2_207p1_vol_0_0/aix_205p2_207p1_lun

filename adapter protocol size mode
-----------------------------------
hdisk1    fcs0    FCP     15g  C
----
=====
--
====


== ホストに接続されているすべての SVM ターゲット LIF の WWPN を一覧表示します

ホストに接続されているすべてのSVMターゲットLIFのWWPNのリストを取得できます。

[source, cli]
----
sanlun lun show -wwpn
----
[role="tabbed-block"]
====
.8.0
--
.AIX ホストユーティリティ 8.0 の例を表示
[%collapsible]
=====
[listing]
----
controller(7mode)/
target device host lun
vserver(Cmode)          wwpn            lun-pathname
--------------------------------------------------------------------------------

vs_aix_clus          203300a098ba7afe  /vol/gpfs_205p2_207p1_vol_0_0/aix_205p2_207p1_lun
vs_aix_clus          203300a098ba7afe  /vol/gpfs_205p2_207p1_vol_0_9/aix_205p2_207p1_lun
vs_aix_clus          203300a098ba7afe  /vol/gpfs_205p2_207p1_vol_en_0_0/aix_205p2_207p1_lun_en
vs_aix_clus          202f00a098ba7afe  /vol/gpfs_205p2_207p1_vol_en_0_1/aix_205p2_207p1_lun_en

filename     adapter    size  mode
-----------------------------------
hdisk1       fcs0       15g    C
hdisk10      fcs0       15g    C
hdisk11      fcs0       15g    C
hdisk12      fcs0       15g    C
----
=====
--
.7.0と6.1
--
.AIX ホストユーティリティ 7.0 および 6.1 の例を表示
[%collapsible]
=====
[listing]
----
controller(7mode)/
target device host lun
vserver(Cmode)          wwpn            lun-pathname
--------------------------------------------------------------------------------

vs_aix_clus          203300a098ba7afe  /vol/gpfs_205p2_207p1_vol_0_0/aix_205p2_207p1_lun
vs_aix_clus          203300a098ba7afe  /vol/gpfs_205p2_207p1_vol_0_9/aix_205p2_207p1_lun
vs_aix_clus          203300a098ba7afe  /vol/gpfs_205p2_207p1_vol_en_0_0/aix_205p2_207p1_lun_en
vs_aix_clus          202f00a098ba7afe  /vol/gpfs_205p2_207p1_vol_en_0_1/aix_205p2_207p1_lun_en

filename     adapter    size  mode
-----------------------------------
hdisk1       fcs0       15g    C
hdisk10      fcs0       15g    C
hdisk11      fcs0       15g    C
hdisk12      fcs0       15g    C
----
=====
--
====