---
sidebar: sidebar 
permalink: hu-ol-95.html 
keywords: host utilities, oracle, linux, 9.5, netapp, ontap 
summary: ONTAP LUN を使用した FCP および iSCSI プロトコル操作を管理するには、Oracle Linux 9.5 ホストに Linux ホスト ユーティリティをインストールします。 
---
= ONTAPストレージを使用してFCPおよびiSCSI用にOracle Linux 9.5を構成する
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Linux Host Utilitiesソフトウェアは、ONTAPストレージに接続されたLinuxホスト用の管理ツールと診断ツールを提供します。Oracle Linux 9.5 ホストに Linux ホスト ユーティリティをインストールすると、ホスト ユーティリティを使用して ONTAP LUN での FCP および iSCSI プロトコル操作を管理できるようになります。


NOTE: ONTAP LUNはKVMハイパーバイザーに自動的にマッピングされるため、Kernel-Based Virtual Machine（KVM）を設定する必要はありません。



== 手順1：必要に応じてSANブートを有効にします。

SANブートを使用するようにホストを設定することで、導入を簡易化し、拡張性を向上させることができます。

.開始する前に
を使用link:https://mysupport.netapp.com/matrix/#welcome["Interoperability Matrix Tool"^]して、Linux OS、ホストバスアダプタ（HBA）、HBAファームウェア、HBAブートBIOS、およびONTAPバージョンがSANブートをサポートしていることを確認します。

.手順
. link:https://docs.netapp.com/us-en/ontap/san-admin/provision-storage.html["SANブートLUNを作成し、ホストにマップする"^]です。
. SAN ブート LUN がマッピングされているポートに対して、サーバ BIOS で SAN ブートを有効にします。
+
HBA BIOS を有効にする方法については、ベンダー固有のマニュアルを参照してください。

. 構成が正常に完了したことを確認するために、ホストをリブートし、OSが稼働していることを確認します。




== 手順2：Linux Host Utilitiesをインストールする

NetAppでは、ONTAP LUN管理をサポートし、テクニカルサポートによる設定データの収集を支援するために、Linux Host Utilitiesをインストールすることを強く推奨しています。

link:hu_luhu_71.html["Linux Host Utilities 7.1のインストール"]です。


NOTE: Linux Host Utilitiesをインストールしても、Linuxホストのホストタイムアウト設定は変更されません。



== 手順3：ホストのマルチパス構成を確認する

Oracle Linux 9.5でマルチパスを使用してONTAP LUNを管理できます。

ホストでマルチパスが正しく設定されていることを確認するには、ファイルが定義されていること、およびONTAP LUN用にNetAppの推奨設定が設定されていることを確認し `/etc/multipath.conf`ます。

.手順
. ファイルが終了することを確認し `/etc/multipath.conf`ます。ファイルが存在しない場合は、空のゼロバイトファイルを作成します。
+
[source, cli]
----
touch /etc/multipath.conf
----
. ファイルの初回作成時には `multipath.conf`、マルチパスサービスを有効にして開始し、推奨設定をロードしなければならない場合があります。
+
[source, cli]
----
systemctl enable multipathd
----
+
[source, cli]
----
systemctl start multipathd
----
. ホストをブートするたびに、空のゼロバイトファイルによって `/etc/multipath.conf`、NetApp推奨のホストマルチパスパラメータがデフォルト設定として自動的にロードされます。オペレーティングシステムは、ONTAP LUNを正しく認識および管理するマルチパスパラメータでコンパイルされているため、ホスト用のファイルを変更する必要はありません `/etc/multipath.conf`。
+
次の表に、Linux OS標準でコンパイルされたONTAP LUNのマルチパスパラメータの設定を示します。

+
.パラメータ設定の表示
[%collapsible]
====
[cols="2"]
|===
| パラメータ | 設定 


| detect_prio | はい。 


| DEV_DETION_TMO | " 無限 " 


| フェイルバック | 即時 


| fast_io_fail_TMO | 5. 


| の機能 | "2 pg_init_retries 50" 


| flush_on_last_del | はい。 


| hardware_handler | 0 


| パスの再試行なし | キュー 


| path_checker です | " tur " 


| path_grouping_policy | 「 group_by_prio 」 


| path_selector | "service-time 0" 


| polling _interval （ポーリング間隔） | 5. 


| Prio | ONTAP 


| プロダクト | LUN 


| retain_attached _hw_handler | はい。 


| RR_weight を指定します | " 均一 " 


| ユーザーフレンドリ名 | いいえ 


| ベンダー | ネットアップ 
|===
====
. ONTAP LUNのパラメータ設定とパスステータスを確認します。
+
[source, cli]
----
multipath -ll
----
+
デフォルトのマルチパスパラメータでは、ASA、AFF、およびFASの構成がサポートされます。このような構成では、1つのONTAP LUNに必要なパスは4つまでです。パスが4つ以上あると、ストレージ障害時にパスで問題が発生する可能性があります。

+
次の出力例は、ASA、AFF、またはFAS構成のONTAP LUNについて、正しいパラメータ設定とパスステータスを示しています。

+
[role="tabbed-block"]
====
.ASA構成
--
ASA構成では、特定のLUNへのすべてのパスが最適化され、アクティブな状態が維持されます。これにより、すべてのパスを同時に経由するI/O処理が行われるため、パフォーマンスが向上します。

.例を示します
[%collapsible]
=====
[listing]
----
multipath -ll
3600a098038303634722b4d59646c4436 dm-28 NETAPP,LUN C-Mode
size=10G features='3 queue_if_no_path pg_init_retries 50' hwhandler='1 alua' wp=rw
|-+- policy='service-time 0' prio=50 status=active
  |- 11:0:7:6   sdbz 68:208  active ready running
  |- 11:0:11:6  sddn 71:80   active ready running
  |- 11:0:15:6  sdfb 129:208 active ready running
  |- 12:0:1:6   sdgp 132:80  active ready running
----
=====
--
.AFFまたはFASの設定
--
AFFまたはFAS構成には、優先度の高いパスと低いパスの2つのグループを設定する必要があります。優先度の高いアクティブ/最適化パスは、アグリゲートが配置されているコントローラで処理されます。優先度の低いパスはアクティブですが、別のコントローラで処理されるため最適化されていません。最適化されていないパスは、最適化されたパスを使用できない場合にのみ使用されます。

次の例は、2つのアクティブ/最適化パスと2つのアクティブ/非最適化パスがあるONTAP LUNの出力を示しています。

.例を示します
[%collapsible]
=====
[listing]
----
multipath -ll
3600a0980383036347ffb4d59646c4436 dm-28 NETAPP,LUN C-Mode
size=10G features='3 queue_if_no_path pg_init_retries 50' hwhandler='1 alua' wp=rw
|-+- policy='service-time 0' prio=50 status=active
| |- 16:0:6:35 sdwb  69:624  active ready running
| |- 16:0:5:35 sdun  66:752  active ready running
`-+- policy='service-time 0' prio=10 status=enabled
  |- 15:0:0:35 sdaj  66:48   active ready running
  |- 15:0:1:35 sdbx  68:176  active ready running
----
=====
--
====




== 手順4：必要に応じて、マルチパスからデバイスを除外する

必要に応じて、不要なデバイスのWWIDをファイルの「blacklist」スタンザに追加することで、デバイスをマルチパスから除外できます `multipath.conf`。

.手順
. WWIDを確認します。
+
[source, cli]
----
/lib/udev/scsi_id -gud /dev/sda
----
+
sdaは、ブラックリストに追加するローカルSCSIディスクです。

+
WWIDの例はです `360030057024d0730239134810c0cb833`。

. 「blacklist」スタンザにWWIDを追加します。
+
[source, cli]
----
blacklist {
	     wwid   360030057024d0730239134810c0cb833
        devnode "^(ram|raw|loop|fd|md|dm-|sr|scd|st)[0-9]*"
        devnode "^hd[a-z]"
        devnode "^cciss.*"
}
----




== 手順5：ONTAP LUNのマルチパスパラメータをカスタマイズする

ホストが他のベンダーのLUNに接続されていて、マルチパスパラメータの設定が無視されている場合は、ONTAP LUNに固有のスタンザをファイルの後半の部分で追加して修正する必要があり `multipath.conf`ます。これを行わないと、ONTAP LUNが想定どおりに動作しない可能性があります。

ファイル、特にdefaultsセクションで、をオーバーライドする可能性のある設定を確認します `/etc/multipath.conf`<<multipath-parameter-settings,マルチパスパラメータノデフォルトセッテイ>>。


CAUTION: ONTAP LUNの推奨されるパラメータ設定は無視しないでください。これらの設定は、ホスト構成のパフォーマンスを最適化するために必要です。詳細については、NetAppサポート、OSベンダー、またはその両方にお問い合わせください。

次の例は、オーバーライドされたデフォルトを修正する方法を示しています。この例では `multipath.conf`、ファイルにONTAP LUNと互換性のないおよび `no_path_retry`の値が定義されて `path_checker`います。ONTAPストレージアレイはホストに接続されたままなので、これらのパラメータを削除することはできません。代わりに、および `no_path_retry`の値を修正する `path_checker`には、ONTAP LUNに特化したファイルにデバイススタンザを追加し `multipath.conf`ます。

[listing, subs="+quotes"]
----
defaults {
   path_checker      *readsector0*
   no_path_retry     *fail*
}

devices {
   device {
      vendor          "NETAPP"
      product         "LUN"
      no_path_retry   *queue*
      path_checker    *tur*
   }
}
----


== 手順6：既知の問題を確認する

既知の問題はありません。



== 次の手順

* link:hu_luhu_71_cmd.html["Linux Host Utilitiesツールの使用方法"]です。
* ASMミラーリングについて説明します。
+
Automatic Storage Management（ASM）ミラーリングでは、ASMが問題を認識して別の障害グループにスイッチオーバーできるように、Linuxマルチパス設定の変更が必要になる場合があります。ONTAP上のほとんどのASM構成では、外部冗長性が使用されます。つまり、データ保護は外付けアレイによって提供され、ASMはデータをミラーリングしません。一部のサイトでは、通常の冗長性を備えたASMを使用して、通常は異なるサイト間で双方向ミラーリングを提供します。詳細については、を参照してくださいlink:https://docs.netapp.com/us-en/ontap-apps-dbs/oracle/oracle-overview.html["ONTAP上のOracleデータベース"^]。


