---
sidebar: sidebar 
permalink: hu-solaris-command-reference.html 
keywords: host utilities, unified, solaris, 8.0, netapp, ontap 
summary: Solaris Host Utilities 8.0をONTAPで使用する方法について説明します。 
---
= Solarisホストユーティリティコマンドを使用してONTAPストレージ構成を確認します
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Solaris ホスト ユーティリティ サンプル コマンド リファレンスを使用すると、ホスト ユーティリティ ツールを使用してNetAppストレージ構成をエンドツーエンドで検証できます。



== ホストにマッピングされているすべてのホストイニシエータを一覧表示

ホストにマッピングされているすべてのホストイニシエータのリストを取得できます。

[source, cli]
----
sanlun fcp show adapter -v
----
[role="tabbed-block"]
====
.8.0
--
.Solaris ホストユーティリティ 8.0 の例を表示
[%collapsible]
=====
[listing]
----
adapter name:      qlc0
WWPN:              2100f4e9d40fe3e0
WWNN:              2000f4e9d40fe3e0
driver name:       qlc
model:             7023303
model description: 7101674, Sun Storage 16Gb FC PCIe Universal HBA, QLogic
serial number:     463916R+1912389772
hardware version:  Not Available
driver version:    230206-5.12
firmware version:  8.08.04
Number of ports:   1 of 2
port type:         Fabric
port state:        Operational
supported speed:   4 GBit/sec, 8 GBit/sec, 16 GBit/sec
negotiated speed:  16 GBit/sec
OS device name:    /dev/cfg/c4

adapter name:      qlc1
WWPN:              2100f4e9d40fe3e1
WWNN:              2000f4e9d40fe3e1
driver name:       qlc
model:             7023303
model description: 7101674, Sun Storage 16Gb FC PCIe Universal HBA, QLogic
serial number:     463916R+1912389772
hardware version:  Not Available
driver version:    230206-5.12
firmware version:  8.08.04
Number of ports:   2 of 2
port type:         Fabric
port state:        Operational
supported speed:   4 GBit/sec, 8 GBit/sec, 16 GBit/sec
negotiated speed:  16 GBit/sec
OS device name:    /dev/cfg/c5
----
=====
--
.6.2
--
.Solaris ホストユーティリティ 6.2 の例を表示
[%collapsible]
=====
[listing]
----
adapter name:      qlc3
WWPN:              21000024ff17a301
WWNN:              20000024ff17a301
driver name:       qlc
model:             7335902
model description: 7115462, Oracle Storage Dual-Port 32 Gb Fibre Channel PCIe HBA
serial number:     463916R+1720333838
hardware version:  Not Available
driver version:    210226-5.10
firmware version:  8.08.04
Number of ports:   1 of 2
port type:         Fabric
port state:        Operational
supported speed:   8 GBit/sec, 16 GBit/sec, 32 GBit/sec
negotiated speed:  32 GBit/sec
OS device name:    /dev/cfg/c7

adapter name:      qlc2
WWPN:              21000024ff17a300
WWNN:              20000024ff17a300
driver name:       qlc
model:             7335902
model description: 7115462, Oracle Storage Dual-Port 32 Gb Fibre Channel PCIe HBA
serial number:     463916R+1720333838
hardware version:  Not Available
driver version:    210226-5.10
firmware version:  8.08.04
Number of ports:   2 of 2
port type:         Fabric
port state:        Operational
supported speed:   8 GBit/sec, 16 GBit/sec, 32 GBit/sec
negotiated speed:  16 GBit/sec
OS device name:    /dev/cfg/c6
----
=====
--
====


== ホストにマッピングされているすべての LUN をリストします

ホストにマッピングされているすべてのLUNのリストを取得できます。

[source, cli]
----
sanlun lun show -p -v all
----
[role="tabbed-block"]
====
.8.0
--
.Solaris ホストユーティリティ 8.0 の例を表示
[%collapsible]
=====
[listing]
----

ONTAP Path: sanboot_unix:/vol/test1/lun1
       LUN: 0
       LUN Size: 21g
       Host Device: /dev/rdsk/c0t600A098038314B314E5D574632365A51d0s2
       Mode: C
       Multipath Provider: Sun Microsystems
       Multipath Policy: Native

----
=====
--
.6.2
--
.Solaris ホストユーティリティ 6.2 の例を表示
[%collapsible]
=====
[listing]
----

                    ONTAP Path: data_vserver:/vol1/lun1
                           LUN: 1
                      LUN Size: 10g
                   Host Device: /dev/rdsk/c0t600A0980383044485A3F4E694E4F775Ad0s2
                          Mode: C
            Multipath Provider: Sun Microsystems
              Multipath Policy: Native

----
=====
--
====


== 特定の SVM / リストからホストにマッピングされているすべての LUN をリストします。ホストにマッピングされている特定の LUN のすべての属性をリストします

特定の SVM からホストにマップされているすべての LUN のリストを取得できます。

[source, cli]
----
sanlun lun show -p -v <svm_name>
----
[role="tabbed-block"]
====
.8.0
--
.Solaris ホストユーティリティ 8.0 の例を表示
[%collapsible]
=====
[listing]
----
ONTAP Path: sanboot_unix:/vol/test1/lun1
       LUN: 0
       LUN Size: 20g
       Host Device: /dev/rdsk/c0t600A098038314B314E5D574632365A51d0s2
       Mode: C
       Multipath Provider: Sun Microsystems
       Multipath Policy: Native
----
=====
--
.6.2
--
.Solaris ホストユーティリティ 6.2 の例を表示
[%collapsible]
=====
[listing]
----
ONTAP Path: sanboot_unix:/vol/sol_boot/sanboot_lun
                           LUN: 0
                      LUN Size: 180.0g

----
=====
--
====


== ホストデバイスファイル名ごとにONTAP LUN属性を表示

ホストデバイスのファイル名を指定すると、すべてのONTAP LUN属性のリストを取得できます。

[source, cli]
----
sanlun lun show all
----
[role="tabbed-block"]
====
.8.0
--
.Solaris ホストユーティリティ 8.0 の例を表示
[%collapsible]
=====
[source, cli]
----
controller(7mode/E-Series)/                                         device
vserver(cDOT/FlashRay)       lun-pathname                           filename
---------------------------------------------------------------------------------------------------------------
sanboot_unix                /vol/test1/lun1                         /dev/rdsk/
c0t600A098038314B314E5D574632365A51d0s2

host adapter    protocol lun size   product
---------------------------------------------
qlc1            FCP      20g        cDOT
----
=====
--
.6.2
--
.Solaris ホストユーティリティ 6.2 の例を表示
[%collapsible]
=====
[listing]
----
controller(7mode/E-Series)/                                         device
vserver(cDOT/FlashRay)       lun-pathname                           filename
---------------------------------------------------------------------------------------------------------------
sanboot_unix                 /vol/sol_193_boot/chatsol_193_sanboot /dev/rdsk/c0t600A098038304437522B4E694E4A3043d0s2

host adapter    protocol lun size   product
---------------------------------------------
qlc3            FCP      180.0g     cDOT
----
=====
--
====