---
sidebar: sidebar 
permalink: hu-veritas-9x.html 
keywords: host utilities, veritas, infoscale, 9, netapp, ontap, sanhost, iscsi, red, hat linux, oracle, linux 
summary: RHEL および Oracle Linux ホスト用の Veritas Infoscale 9 と Linux ホスト ユーティリティを使用すると、 ONTAP LUN を使用した FC、FCoE、および iSCSI プロトコル操作を管理しやすくなります。 
---
= ONTAPストレージを使用して FC、FCoE、iSCSI 用に Veritas Infoscale 9 を構成する
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Linux ホスト ユーティリティ ソフトウェアは、 ONTAPストレージに接続された Linux ホスト用の管理および診断ツールを提供します。Oracle Linux (Red Hat 互換カーネル ベース)、Red Hat Enterprise Linux (RHEL)、および SUSE Linux Enterprise Server ホスト用の Veritas Infoscale 9 で Linux ホスト ユーティリティを使用して、 ONTAP LUN を使用した FC、FCoE、および iSCSI プロトコル操作の管理をサポートします。



== 手順1：必要に応じてSANブートを有効にします。

SANブートを使用するようにホストを設定することで、導入を簡易化し、拡張性を向上させることができます。

.開始する前に
* を使用link:https://mysupport.netapp.com/matrix/#welcome["Interoperability Matrix Tool"^]して、Linux OS、ホストバスアダプタ（HBA）、HBAファームウェア、HBAブートBIOS、およびONTAPバージョンがSANブートをサポートしていることを確認します。
* SAN ブート構成のサポートと既知の問題を確認するには、Veritas サポート ポータル (製品マトリックス、プラットフォーム検索、および HCL マトリックス) を参照してください。


.手順
. link:https://docs.netapp.com/us-en/ontap/san-admin/provision-storage.html["SANブートLUNを作成し、ホストにマップする"^]です。
. SAN ブート LUN がマッピングされているポートに対して、サーバ BIOS で SAN ブートを有効にします。
+
HBA BIOS を有効にする方法については、ベンダー固有のマニュアルを参照してください。

. 構成が正常に完了したことを確認するために、ホストをリブートし、OSが稼働していることを確認します。




== 手順2：Linux Host Utilitiesをインストールする

NetAppは強く推奨します link:hu-luhu-release-notes.html["Linuxホストユーティリティのインストール"] ONTAP LUN 管理をサポートし、構成データの収集に関するテクニカル サポートを支援します。


NOTE: Linux Host Utilitiesをインストールしても、Linuxホストのホストタイムアウト設定は変更されません。



== ステップ3: ホストのVeritas Dynamic Multipathing構成を確認する

ONTAP LUN を管理するには、Veritas Infoscale 9 と Veritas Dynamic Multipathing (VxDMP) を使用します。

VxDMP がホストに対して正しく設定されていることを確認するには、VxDMP 構成を確認し、アレイ サポート ライブラリ (ASL) とアレイ ポリシー モジュール (APM) の構成を確認する必要があります。NetAppストレージ システム用の ASL および APM パッケージは、Veritas ソフトウェアのインストール中にインストールされます。


NOTE: Veritas Infoscale、Linux Native Device Mapper、LVM ボリューム マネージャなどの異機種マルチパス環境の場合、構成設定については Veritas 製品管理ドキュメントを参照してください。

.開始する前に
構成がシステム要件を満たしていることを確認してください。参照 link:https://mysupport.netapp.com/matrix/#welcome["Interoperability Matrix Tool"^] および Veritas HCL マトリックス。

.手順
. ONTAPターゲット アレイが VxDMP マルチパスに接続されていることを確認します。
+
[source, cli]
----
vxdmpadm
----
+
.例を示します
[%collapsible]
====
[listing]
----
#vxdmpadm listenclosure
ENCLR_NAME        ENCLR_TYPE     ENCLR_SNO      STATUS       ARRAY_TYPE     LUN_COUNT    FIRMWARE
===================================================================================================
info_asa0         Info_ASA       81KDT+YTg35P         CONNECTED    ALUA       20         9161
infoscal1         Infoscal       81Ocq?Z7hPzC         CONNECTED    ALUA       23         9181
# vxdmpadm getdmpnode
NAME       STATE    ENCLR-TYPE  PATHS  ENBL  DSBL ENCLR-NAME
===================================================================
infoscal1_22         ENABLED      Infoscal     4      4     0     infoscal1
----
====
. ASL および APM パッケージの構成を確認します。NetApp、Veritas サポート ポータルにリストされている最新のサポート対象パッケージを使用することをお勧めします。
+
.ASLとAPMの設定例を表示
[%collapsible]
====
[listing]
----
#  vxdmpadm list dmpnode dmpnodename=infoscal1_22 | grep asl
asl             = libvxnetapp.so

# vxddladm listversion |grep libvxnetapp.so
libvxnetapp.so                  vm-8.0.0-rev-1   8.0

# rpm -qa |grep VRTSaslapm
VRTSaslapm-9.0.3-RHEL9.x86_64
#vxddladm listsupport libname=libvxnetapp.so
ATTR_NAME   ATTR_VALUE
=========================================
LIBNAME     libvxnetapp.so
VID         NETAPP
PID         All
ARRAY_TYPE  ALUA, A/A
----
====
. ストレージフェイルオーバー操作における最適なシステム構成のために、次の Veritas VxDMP チューニングパラメータがあることを確認してください。
+
[cols="2*"]
|===
| パラメータ | 設定 


| dmp_lun_retry_timeout | 60 


| dmp_path_age | 120 


| dmp_restore_interval の値です | 60 
|===
. DMP 調整パラメータをオンラインに設定します。
+
[source, cli]
----
# vxdmpadm settune dmp_tunable=value
----
. 調整可能パラメータが正しく設定されていることを確認します。
+
[source, cli]
----
# vxdmpadm gettune
----
+
次の例は、SAN ホスト上で有効な VxDMP 調整パラメータを示しています。

+
.例を示します
[%collapsible]
====
[listing]
----
# vxdmpadm gettune

Tunable                    Current Value    Default Value
dmp_cache_open                      on                on
dmp_daemon_count                    10                10
dmp_delayq_interval                 15                15
dmp_display_alua_states             on                on
dmp_fast_recovery                   on                on
dmp_health_time                     60                60
dmp_iostats_state              enabled           enabled
dmp_log_level                        1                 1
dmp_low_impact_probe                on                on
dmp_lun_retry_timeout               60                30
dmp_path_age                       120               300
dmp_pathswitch_blks_shift            9                 9
dmp_probe_idle_lun                  on                on
dmp_probe_threshold                  5                 5
dmp_restore_cycles                  10                10
dmp_restore_interval                60               300
dmp_restore_policy         check_disabled   check_disabled
dmp_restore_state              enabled           enabled
dmp_retry_count                      5                 5
dmp_scsi_timeout                    20                20
dmp_sfg_threshold                    1                 1
dmp_stat_interval                    1                 1
dmp_monitor_ownership               on                on
dmp_monitor_fabric                  on                on
dmp_native_support                 off               off
----
====
. プロトコルのタイムアウト値を設定します。
+
[role="tabbed-block"]
====
.FC / FCoE
--
FC および FCoE のデフォルトのタイムアウト値を使用します。

--
.iSCSI
--
設定する `replacement_timeout` パラメータ値を 120 に設定します。

iSCSI `replacement_timeout` パラメータは、タイムアウトしたパスまたはセッションが再確立されるまで iSCSI レイヤーが待機する時間を制御します。この時間が経過すると、そのパスまたはセッションに対するコマンドが失敗します。NetApp、 `replacement_timeout` iSCSI 構成ファイルで 120 に設定します。

.例
[listing]
----
# grep replacement_timeout /etc/iscsi/iscsid.conf
node.session.timeo.replacement_timeout = 120
----
--
====
. ONTAP LUNのパラメータ設定とパスステータスを確認します。
+
AFF、 FAS、またはASA構成では、単一のONTAP LUN に 4 つを超えるパスは必要ありません。パスが 4 つを超えると、ストレージ障害時に問題が発生する可能性があります。

+
次の例は、 ASA、 AFF、またはFAS構成におけるONTAP LUN の正しいパラメータ設定とパス ステータスを示しています。

+
[role="tabbed-block"]
====
.ASA構成
--
ASA構成では、特定のLUNへのすべてのパスが最適化され、アクティブな状態が維持されます。これにより、すべてのパスを同時に経由するI/O処理が行われるため、パフォーマンスが向上します。

.例を示します
[%collapsible]
=====
[listing]
----
# vxdmpadm getsubpaths dmpnodename=infoscal1_21
NAME   STATE[A]    PATH-TYPE[M] CTLR-NAME  ENCLR-TYPE  ENCLR-NAME   ATTRS  PRIORITY
===================================================================================
sdby   ENABLED(A)  Active/Optimized  c1    Infoscal    infoscal1    -      -
sddx   ENABLED(A)  Active/Optimized  c2    Infoscal    infoscal1    -      -
sdfe   ENABLED(A)  Active/Optimized  c1    Infoscal    infoscal1    -      -
sdfo   ENABLED(A)  Active/Optimized  c2    Infoscal    infoscal1    -      -
----
=====
--
.AFFまたはFASの設定
--
AFFまたはFAS構成には、優先度の高いパスと低いパスの2つのグループを設定する必要があります。優先度の高いアクティブ/最適化パスは、アグリゲートが配置されているコントローラで処理されます。優先度の低いパスはアクティブですが、別のコントローラで処理されるため最適化されていません。最適化されていないパスは、最適化されたパスを使用できない場合にのみ使用されます。

次の例は、2つのアクティブ/最適化パスと2つのアクティブ/非最適化パスがあるONTAP LUNの出力を示しています。

.例を示します
[%collapsible]
=====
[listing]
----
# vxdmpadm getsubpaths dmpnodename-sfrac0_47
NAME  STATE[A]   PATH-TYPE[M]   CTLR-NAME   ENCLR-TYPE  ENCLR-NAME  ATTRS  PRIORITY
===================================================================================
sdas  ENABLED     Active/Non-Optimized c13   SFRAC       sfrac0     -      -
sdb   ENABLED(A)  Active/Optimized     c14   SFRAC       sfrac0     -      -
sdcj  ENABLED(A)  Active/Optimized     c14   SFRAC       sfrac0     -      -
sdea  ENABLED     Active/Non-Optimized c14   SFRAC       sfrac0     -      -
----
=====
--
====




== ステップ4: 既知の問題

既知の問題はありません。



== 次の手順

* link:hu-luhu-command-reference.html["Linux Host Utilitiesツールの使用方法"] 。

