---
sidebar: sidebar 
permalink: hu-wuhu-release-notes.html 
keywords: host utilities, linux, 7.1, 7.2, netapp, ontap, release, notes 
summary: Release Notes for Windows Host Utilities 
---
= Windows Host Utilitiesリリースノート
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
リリース ノートでは、 ONTAPストレージ システムを使用して特定の Windows ホストを構成および管理する場合に関連する新機能、拡張機能、既知の問題、制限事項、および重要な注意事項について説明します。

Host Utilitiesでサポートされるオペレーティングシステムのバージョンと更新の具体的な情報については、を参照してlink:https://imt.netapp.com/matrix/#welcome["Interoperability Matrix Tool"^]ください。



== Windows ホストユーティリティ 8.0 の新機能

Windows Host Utilities 8.0 には、NVMe/FC ドライバーの追加パラメータ設定が含まれています。これらのパラメータは、Windows Host Utilities 8.0 をインストールすると自動的に読み込まれます。



== Windows ホストユーティリティ 7.2 の新機能

Windows Host Utilities 7.2では、NVMe/FCドライバパラメータの設定がサポートされ、新しいベンダーカードに関するバグが修正されています。



== Windows ホストユーティリティ 7.1 の新機能

Windows Host Utilities 7.1 には、E シリーズ ストレージ システム、 ONTAP 9 ソフトウェア、およびフェイルオーバーを高速化する拡張 iSCSI タイムアウトのサポートが含まれています。



== 既知の問題と制限事項

特定のホストのパフォーマンスに影響を及ぼす可能性のある次の既知の問題と制限事項に注意する必要があります。

[cols="30, 15, 30, 30"]
|===
| タイトル | 影響を受けるバージョン | 説明 | 回避策 


| を実行します `linux_gos_timeout-install.sh` スクリプトは、Red Hat Enterprise LinuxまたはSUSE Linux Enterprise Serverを実行するHyper-Vゲストには必要ありません | 7.1 | Red Hat Enterprise Linux 5、Red Hat Enterprise Linux 6、またはSUSE Linux Enterprise Server 11 Hyper-Vゲストでは、デフォルトのタイムアウト設定が使用されているため、スクリプトを実行してディスクタイムアウトを変更する必要がなくなりました `linux_gos_timeout-install.sh`。 `linux_gos_timeout-install.sh`以前のバージョンのHost Utilitiesに含まれていたスクリプトは、Windows Host Utilities 7.1バージョンには含まれなくなりました。Windows Host Utilities 7.1では、デフォルトのディスクタイムアウト設定が使用されます。 | 該当なし 
|===
link:https://mysupport.netapp.com/site/bugs-online/product["NetApp Bugs Online では"^] 既知の問題の詳細情報を提供します。可能な場合は、推奨される対処方法も示します。



== 次の手順

link:hu-wuhu-80.html["Windowsホストユーティリティのインストールについて学ぶ"]
