---
sidebar: sidebar 
permalink: hu_aix_72_sanbooting_aix.html 
keywords: host utilities, aix, netapp, ontap, configure, discover, configuring, discovering 
summary: AIX で LUN を検出して設定する方法について説明します 
---
= （ PowerVM を使用しない AIX MPIO ） AIX で LUN を検出して設定する
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
PowerVM なしで AIX を使用している場合は、 cfgmgr コマンドを使用して、ホストで LUN を検出できます。LUN を検出するためにホストをリブートする必要はありません。ホストで LUN が検出されたことを確認するには、 sanlun ユーティリティを使用できます。


NOTE: 以降の手順は、 PowerVM 環境を実行しているホストには適用されません。

.手順
. ホストに root としてログインします。
. AIX ホストで、次のコマンドを入力して、新しく作成した LUN を検出します。
+
"cfgmgr"

+
cfgmgr コマンドを使用すると、次のような利点があります。

+
** ファブリックにログインするイニシエータ。
** 新しいデバイスを確認するシステム。
** 新しいデバイスエントリを作成するシステム。


. NetApp LUN を含むすべての AIX ディスクを表示するには、次のコマンドを入力します。
+
「 lsdev - Cc disk 」を参照してください

+
ホストでは、 LUN がディスクとして表示されます。ホストのローカルディスクと同じ方法でこれらのディスクを使用できます。Host Utilities の一部としてインストールされたホスト設定の ODM ファイルでは、 LUN が NetApp FCP ディスクとして表示されます。

+
hdisk インスタンス番号を書き留めます。これらのパラメータは、パス設定の実行時に使用します。

+
次に、 lsdev -Cc disk コマンドで生成される、 FC を使用する環境の出力のタイプを示します。

+
[listing]
----
# lsdev -Cc disk
hdisk0 Available 08-08-00-5,0 16 Bit LVD SCSI Disk Drive
hdisk1 Available 08-08-00-8,0 16 Bit LVD SCSI Disk Drive
hdisk2 Available 04-08-02  MPIO NetApp FCP Default PCM Disk
hdisk3 Available 04-08-02  MPIO NetApp FCP Default PCM Disk
hdisk4 Available 04-08-02  MPIO NetApp FCP Default PCM Disk
hdisk5 Available 04-08-02  MPIO NetApp FCP Default PCM Disk
----
. 次のコマンドを入力して、セットアップに関する情報を取得します。
+
lsattr - El hdisk_name

+
このコマンドの出力は次のとおりです。

+
[listing]
----
# lsattr -El hdisk65
PCM   PCM/friend/NetApp   PCM Path Control Module          False
PR_key_value    none                             Persistant Reserve Key Value            True
algorithm       round_robin                      Algorithm                               True
clr_q           no                               Device CLEARS its Queue on error        True
dist_err_pcnt   0                                Distributed Error Sample Time           True
dist_tw_width   50                               Distributed Error Sample Time           True
hcheck_cmd      inquiry                          Health Check Command                    True
hcheck_interval 30                               Health Check Interval                   True
hcheck_mode     nonactive                        Health Check Mode                       True
location                                         Location Label                          True
lun_id          0x2000000000000                  Logical Unit Number ID                  False
lun_reset_spt   yes                              LUN Level Reset                         True
max_transfer    0x100000                         Maximum TRANSFER Size                   True
node_name       0x500a0980894ae0e0               FC Node Name                            False
pvid            00067fbad453a1da0000000000000000 Physical volume identifier              False
q_err           yes                              Use QERR bit                            True
q_type          simple                           Queuing TYPE                            True
qfull_dly       2                                Delay in seconds for SCSI TASK SET FULL True
queue_depth     64                               Queue DEPTH                             True
reassign_to     120                              REASSIGN time out value                 True
reserve_policy  no_reserve                       Reserve Policy                          True
rw_timeout      30                               READ/WRITE time out value               True
scsi_id         0xd10001                         SCSI ID                                 False
start_timeout   60                               START unit time out value               True
ww_name         0x500a0984994ae0e0               FC World Wide Name                      False
----
. ALUA をサポートする構成の場合は、 ALUA を使用してパス優先度を設定できます。ALUA が有効になっていることを確認します。
+
「 lun igroup show -instance igroup_name 」を参照してください

+
.. ALUA が有効になっていない場合は有効にします。
+
「 igroup set igroup_name alua yes



. ALUA をサポートしない構成の場合は、 dotpaths ユーティリティを実行してパス優先度を設定する必要があります。dotpaths ユーティリティは、 Host Utilities のインストール時にインストールします。ALUA が有効になっている場合は、 dotpaths ユーティリティを使用しないでください。
+
.. すべての Data ONTAP LUN に優先度を設定するには、次のように入力します。
+
「パス」

.. 特定のディスク・セットにプライオリティを設定するには、次のように入力します。
+
「 dotpaths [-HQv] [hdiskN...] 」

+
詳細モードを有効にし、すべての優先順位を表示するには、「 -v 」オプションを使用します。すべてまたは個々のディスクの優先順位を照会するには '-q オプションを使用します



. ホストで LUN が検出されたことを確認するには、次のコマンドを入力します。
+
「 #sanlun lun show 」というエラーが表示されます

+
この例は、 MPIO マルチパス環境での「 lun lun show 」コマンドの典型的な出力を示しています。

+
[listing]
----
sanlun lun show -p

                    ONTAP Path: fas3170-aix03:/vol/ibmbc_aix01b14_fcp_vol8/ibmbc-aix01b14_fcp_lun0
                           LUN: 8
                      LUN Size: 3g
           Controller CF State: Cluster Enabled
            Controller Partner: fas3170-aix04
                   Host Device: hdisk9
                          Mode: 7
            Multipath Provider: AIX Native
        Multipathing Algorithm: round_robin
--------- ----------- ------ ------- ---------------------------------------------- ----------
host      controller  AIX            controller                                     AIX MPIO
path      path        MPIO   host    target                                         path
state     type        path   adapter port                                           priority
--------- ----------- ------ ------- ---------------------------------------------- ----------
up        secondary   path0  fcs0    3b                                             1
up        primary     path1  fcs0    3a                                             1
up        secondary   path2  fcs0    3a                                             1
up        primary     path3  fcs0    3b                                             1
up        secondary   path4  fcs0    4b                                             1
up        secondary   path5  fcs0    4a                                             1
up        primary     path6  fcs0    4b                                             1
up        primary     path7  fcs0    4a                                             1
up        secondary   path8  fcs1    3b                                             1
up        primary     path9  fcs1    3a                                             1
up        secondary   path10 fcs1    3a                                             1
up        primary     path11 fcs1    3b                                             1
up        secondary   path12 fcs1    4b                                             1
up        secondary   path13 fcs1    4a                                             1
up        primary     path14 fcs1    4b                                             1
up        primary     path15 fcs1    4a                                             1
----

