---
sidebar: sidebar 
permalink: hu_aix_61.html 
keywords: host utilities, aix, powervm, vios, 3.1, 7.2 netapp, ontap 
summary: ONTAP で IBM AIX 7.2 または PowerVM VIOS 3.1 を使用する方法について説明します 
---
= ONTAPストレージ用のAIX Host Utilities 6.1のインストール
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
AIX ホスト ユーティリティは、AIX ホストに接続されたONTAPストレージの管理に役立ちます。  NetApp、 ONTAPストレージ管理を改善し、 NetAppサポートによる構成情報収集を支援するために、AIX ホスト ユーティリティをインストールすることを強くお勧めします。

AIX ホスト ユーティリティ 6.1 は、次のトランスポート プロトコルと AIX 環境をサポートします。

* FC、FCoE、iSCSI
* AIX Microsoft マルチパス I/O (MPIO)
* PowerVM
+
PowerVMの詳細については、『IBM PowerVM Live Partition Mobility Red Book』を参照してください。



.このタスクについて
* AIX ホストに接続されたONTAPストレージを管理するには、AIX MPIO とともに AIX Host Utilities SAN Toolkit をインストールする必要があります。
* AIX ホスト ユーティリティをインストールしても、AIX ホストの設定は変更されません。


.開始する前に
* 使用link:https://mysupport.netapp.com/matrix/#welcome["Interoperability Matrix Tool"^]AIX OS、プロトコル、およびONTAPバージョンが SAN ブートをサポートしていることを確認します。
* 全てのFCおよびFCoEイニシエーターの動的トラッキングを有効にするには、 `chdev -l <fscsi_device> -a dyntrk=ye` AIX ホスト上のコマンド。


.手順
. ホストにログインします。
+
[role="tabbed-block"]
====
.AIX の場合
--
AIX ホストでは、 * root * としてログインします。

--
.PowerVM
--
PowerVM ホストの場合:

.. *padmin* としてログインします。
.. ルートユーザーになる:
+
[source, cli]
----
oem_setup_env
----


--
====
. にアクセスします https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/6.1/downloads["ネットアップサポートサイト"^] を実行し、Host Utilitiesを含む圧縮ファイルをホストのディレクトリにダウンロードします。
. ダウンロードを格納しているディレクトリに移動します。
. ファイルを解凍して、 SAN Toolkit ソフトウェアパッケージを展開します。
+
[source, cli]
----
tar -xvf ntap_aix_host_utilities_6.1.tar.gz
----
+
ファイルを解凍すると 'ntap_aix_host_utilities_6.1' というディレクトリが作成されますこのディレクトリには、 MPIO 、 NON_MPIO 、または SAN_Tool_Kit のいずれかのサブディレクトリがあります

. AIX MPIO をインストールします。
+
[source, cli]
----
installp -aXYd /var/tmp/ntap_aix_host_utilities_6.1/MPIO NetApp.MPIO_Host_Utilities_Kit
----
. SAN Toolkit をインストールします。
+
[source, cli]
----
installp -aXYd /var/tmp/ntap_aix_host_utilities_6.1/SAN_Tool_Kit NetApp.SAN_toolkit
----
. ホストをリブートします。
. インストールを確認します。
+
[source, cli]
----
sanlun version
----




== 次の手順

link:hu-aix-san-toolkit.html["AIX SAN ツールキットについて学ぶ"] 。
