---
sidebar: sidebar 
permalink: hu_aix_72_sanbooting_powervm_vscsi.html 
keywords: host utilities, aix, powervm, 7.2 netapp, ontap, luns, configure, discover, configuring, discovering 
summary: PowerVM vSCSI で LUN の検出と設定を使用する方法について説明します 
---
= （ PowerVM vSCSI ） LUN の検出と構成
:toc: macro
:hardbreaks:
:toclevels: 1
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
PowerVM vSCSI サーバおよび VIO サーバを使用する場合は、 padmin ログインと、 LUN を設定および検出するための適切なコマンドを使用する必要があります。

.手順
. ホストに padmin としてログインします。
. AIX ホストで、次のコマンドを入力して、新しく作成した LUN を検出します。
+
cfgdev

+
cfgdev コマンドの原因は次のとおりです。

+
** ファブリックにログインするイニシエータ。
** 新しいデバイスを確認するシステム。
** 新しい LUN がデフォルト PCM を使用して MPIO デバイスとしてマッピングされる新しいデバイスエントリを作成するシステム。


. hdisk MPIO デバイスが作成されたことを確認するには、次のコマンドを入力します。
+
lsdev-type disk

+
ホストでは、 LUN がディスクとして表示されます。ホストのローカルディスクと同じ方法でこれらのディスクを使用できます。

+
hdisk インスタンス番号を書き留めます。これらのパラメータは、パス設定の実行時に使用します。

+
lsdev-type disk コマンドは ' 次のような出力を生成しますこの例の出力は省略されています。

+
[listing]
----
vioserver$ lsdev -type disk NetApp
name     status      description
hdisk0   Available   16 Bit LVD SCSI Disk Drive
hdisk1   Available   16 Bit LVD SCSI Disk Drive
hdisk2   Available   MPIO NetApp FCP Default PCM Disk
hdisk3   Available   MPIO NetApp FCP Default PCM Disk
hdisk4   Available   MPIO NetApp FCP Default PCM Disk
hdisk5   Available   MPIO NetApp FCP Default PCM Disk
hdisk6   Available   MPIO NetApp FCP Default PCM Disk
----
. セットアップに関する情報を取得するには、次のコマンドを入力します。
+
lsdev -dev hdisk_name -attr

+
lsdev -dev hdisk_name -attr' コマンドを実行すると ' 次の出力が生成されます

+
[listing]
----
vioserver$ lsdev -dev hdisk2 -attr
attribute value                   description                user-settable
PCM   PCM/friend/NetApp   PCM Path Control Module          False
PR_key_value    none                             Persistent Reserve Key Value            True
algorithm       round_robin                      Algorithm                               True
clr_q           no                               Device CLEARS its Queue on error        True
dist_err_pcnt   0                                Distributed Error Sample Time           True
dist_tw_width   50                               Distributed Error Sample Time           True
hcheck_cmd      inquiry                          Health Check Command                    True
hcheck_interval 30                               Health Check Interval                   True
hcheck_mode     nonactive                        Health Check Mode                       True
location                                         Location Label                          True
lun_id          0x2000000000000                  Logical Unit Number ID                  False
lun_reset_spt   yes                              LUN Level Reset                         True
max_transfer    0x100000                         Maximum TRANSFER Size                   True
node_name       0x500a0980894ae0e0               FC Node Name                            False
pvid            00067fbad453a1da0000000000000000 Physical volume identifier              False
q_err           yes                              Use QERR bit                            True
q_type          simple                           Queuing TYPE                            True
qfull_dly       2                                Delay in seconds for SCSI TASK SET FULL True
queue_depth     64                               Queue DEPTH                             True
reassign_to     120                              REASSIGN time out value                 True
reserve_policy  no_reserve                       Reserve Policy                          True
rw_timeout      30                               READ/WRITE time out value               True
scsi_id         0xd10001                         SCSI ID                                 False
start_timeout   60                               START unit time out value               True
ww_name         0x500a0984994ae0e0               FC World Wide Name                      False
----
. ALUA をサポートしない構成の場合は、 dotpaths ユーティリティを実行してパス優先度を設定する必要があります。dotpaths ユーティリティは、 Host Utilities のインストール時にインストールします。ALUA が有効になっている場合は、 dotpaths ユーティリティを使用しないでください。次のコマンドを入力して 'oem_setup_env' モードに切り替えて dotpaths を実行します
+
`oem_setup_env`

+
`oem_setup_env' モードを開始すると ' コマンド・ライン・プロンプトがドル記号からポンド記号に変わり 'exit などのコマンドを入力して停止するまで 'oem_setup_env' モードのままになります

+
`#vioserver $oem_setup_env`

. ALUA をサポートする構成の場合は、 ALUA を使用してパス優先度を設定できます。ALUA が有効になっていることを確認します。
+
「 lun igroup show -instance igroup_name 」を参照してください

+
.. ALUA が有効になっていない場合は有効にします。
+
「 igroup set igroup_name alua yes



. ALUA をサポートしない構成の場合は、 dotpaths ユーティリティを実行してパス優先度を設定する必要があります。dotpaths ユーティリティは、 Host Utilities のインストール時にインストールします。ALUA が有効になっている場合は、 dotpaths ユーティリティを使用しないでください。
+
.. すべての Data ONTAP LUN に優先度を設定するには、次のように入力します。
+
「パス」

.. 特定のディスク・セットにプライオリティを設定するには、次のように入力します。
+
「 dotpaths [-HQv] [hdiskN...] 」

+
詳細モードを有効にし、すべての優先順位を表示するには、「 -v 」オプションを使用します。すべてまたは個々のディスクの優先順位を照会するには '-q オプションを使用します

+
次に、 dotpaths ユーティリティの使用例を示します。

+
[listing]
----
vioserver# dotpaths -v
hdisk2 (path 0): Optimized path - Setting priority to 255
hdisk2 (path 1): Optimized path - Setting priority to 255
hdisk2 (path 2): Unoptimized path - Current priority of 1 is correct
hdisk2 (path 3): Unoptimized path - Current priority of 1 is correct
...
Path priority set and/or verified for 22 disks, 86 total paths.
vioserver#
----


. ホストで LUN が検出されたことを確認するには、次のコマンドを入力します。
+
「 #sanlun lun show -p 」というエラーが表示されます

+
この例は ' 直接接続構成の場合の 'lun lun lun lun show -p コマンドの典型的な出力を示していますまた 'hdisk9 に関する情報を表示するための 'lun lun lun show -d hdisk9-v` コマンドも含まれていますこのコマンドの出力は省略されました。

+
[listing]
----
sanlun lun show -p

                    ONTAP Path: fas3170-aix03:/vol/ibmbc_aix01b14_fcp_vol8/ibmbc-aix01b14_fcp_lun0
                           LUN: 8
                      LUN Size: 3g
           Controller CF State: Cluster Enabled
            Controller Partner: fas3170-aix04
                   Host Device: hdisk9
                          Mode: 7
            Multipath Provider: AIX Native
        Multipathing Algorithm: round_robin
--------- ----------- ------ ------- ------------- ----------
host      controller  AIX            controller    AIX MPIO
path      path        MPIO   host    target        path
state     type        path   adapter port          priority
--------- ----------- ------ ------- ------------- ----------
up        secondary   path0  fcs0    3b              1
up        primary     path1  fcs0    3a              1
up        secondary   path2  fcs0    3a              1
up        primary     path3  fcs0    3b              1
up        secondary   path4  fcs0    4b              1
up        secondary   path5  fcs0    4a              1
up        primary     path6  fcs0    4b              1
up        primary     path7  fcs0    4a              1
up        secondary   path8  fcs1    3b              1
up        primary     path9  fcs1    3a              1
up        secondary   path10 fcs1    3a              1
up        primary     path11 fcs1    3b              1
up        secondary   path12 fcs1    4b              1
up        secondary   path13 fcs1    4a              1
up        primary     path14 fcs1    4b              1
up        primary     path15 fcs1    4a              1
----
+
[listing]
----
sanlun lun show -vd hdisk10
                                                                      device          host                  lun
vserver              lun-pathname                                     filename        adapter    protocol   size    mode
------------------------------------------------------------------------------------------------------------------------
GPFS_p520_FC         /vol/GPFS_p520_FC_FlexVol_2/GPFS_p520_FC_LUN_2_4 hdisk10         fcs3       FCP        100g    C
             LUN Serial number: 1k/yM$-ia5HC
         Controller Model Name: N5600
          Vserver FCP nodename: 200200a0980c892f
          Vserver FCP portname: 200a00a0980c892f
              Vserver LIF name: GPFS_p520_FC_2
            Vserver IP address: 10.225.121.100
           Vserver volume name: GPFS_p520_FC_FlexVol_2  MSID::0x00000000000000000000000080000420
         Vserver snapshot name:
----

