---
sidebar: sidebar 
permalink: hu_aix_72.html 
keywords: host utilities, aix, powervm, vios, 3.1, 7.2 netapp, ontap 
summary: ONTAP で IBM AIX 7.2 または PowerVM VIOS 3.1 を使用する方法について説明します 
---
= ONTAPでIBM AIX 7.2またはPowerVM（VIOS 3.1）を使用する
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content




== AIX/VIOS Host Utilitiesのインストール

AIX MPIOとNetApp ONTAP ストレージを使用する場合、AIX Host Utilities Kitをインストールする必要があります。

Host Utilities ソフトウェアパッケージが格納された圧縮ファイルは、からダウンロードできます link:https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/6.1/downloads["ネットアップサポートサイト"^]。ファイルを展開したら、Host Utilitiesのインストールに必要な2つのソフトウェアパッケージを取得するために、ファイルを解凍する必要があります。

NetApp AIX Host Utilities 6.1 は最新リリースです。このリリースでは、以前のリリースで報告されたメモリリーク問題について説明しています。追加情報のリリースノートのセクションを参照してください。

.手順
. ホストにログインします。
+
** AIX ホストでは、 * root * としてログインします。
** PowerVM ホストで '*padmin* としてログインし 'root になるように 'oem_setup_env' コマンドを入力します


. Host Utilities が含まれている圧縮ファイルを、ネットアップサポートサイトからホスト上のディレクトリにダウンロードします。
. ダウンロードを格納しているディレクトリに移動します。
. ファイルを解凍して、 SAN Toolkit ソフトウェアパッケージを展開します。
+
tar -xvf ntap_aix_host_utilities_6.1.tar.gz

+
ファイルを解凍すると 'ntap_aix_host_utilities_6.1' というディレクトリが作成されますこのディレクトリには、 MPIO 、 NON_MPIO 、または SAN_Tool_Kit のいずれかのサブディレクトリがあります

. AIX MPIO をインストールします。
+
'installp-aXYd /var/tmp/ntap_aix_host_utilities_6.1/MPIO NetApp.mpio_Host_Utilities_Kit

. SAN ツールキットをインストールします :'installp-aXYd /var/tmp/ntap_aix_host_utilities_6.1/SAN_Tool_Kit NetApp.SAN_toolkit
. ホストをリブートします。




== SANツールキット

このツールキットは、NetApp Host Utilitiesパッケージをインストールすると自動的にインストールされます。このキットは、を提供します `sanlun` ユーティリティ。LUNとHBAの管理に役立ちます。。 `sanlun` コマンドは、ホストにマッピングされているLUNに関する情報、マルチパス、およびイニシエータグループの作成に必要な情報を返します。

.例
次の例では 'lun lun lun show コマンドは LUN 情報を返します

[listing]
----
#sanlun lun show

controller(7mode)/                  device      host       lun
vserver(Cmode)    lun-pathname     filename    adapter   protocol   size   mode
--------------------------------------------------------------------------------
data_vserver      /vol/vol1/lun1    hdisk0      fcs0       FCP       60g    C
data_vserver      /vol/vol2/lun2    hdisk0      fcs0       FCP       20g    C
data_vserver      /vol/vol3/lun3    hdisk11     fcs0       FCP       20g    C
data_vserver      /vol/vol4/lun4    hdisk14     fcs0       FCP       20g    C

----


== SAN ブート中です

.必要なもの
SAN ブートを使用する場合は、構成でサポートされている必要があります。を使用できます link:https://mysupport.netapp.com/matrix/imt.jsp?components=71102;&solution=1&isHWU&src=IMT["NetApp Interoperability Matrix Tool で確認できます"^] 使用している OS 、 HBA 、 HBA ファームウェア、 HBA ブート BIOS 、および ONTAP のバージョンがサポートされていることを確認します。

SAN ブートとは、 AIX / PowerVM ホストのブートデバイスとして SAN 接続ディスク（ LUN ）をセットアップするプロセスのことです。SAN ブート LUN は、 FC プロトコルまたは FCoE プロトコルで AIX Host Utilities を実行する AIX MPIO 環境で動作するようにセットアップできます。SAN ブート LUN を作成し、その LUN に新しい OS イメージをインストールする方法は、使用するプロトコルによって異なります。



== マルチパス

マルチパスを使用すると、ホストとストレージシステム間に複数のネットワークパスを設定できます。1 つのパスで障害が発生すると、トラフィックは残りのパスで継続されます。Host Utilities の AIX および PowerVM 環境では、 AIX のネイティブマルチパス解決策（ MPIO ）を使用します。

AIX の場合、 Path Control Module （ PCM ；パス制御モジュール）が複数のパスを制御します。PCM は、パス管理を処理するストレージベンダーが提供するコードです。これは、 Host Utilities のインストール時にインストールして有効にします。



=== Non-ASA の設定

ASA以外の構成では、優先度が異なる2つのパスグループが必要です。優先度が高いパスは「アクティブ / 最適化」です。つまり、アグリゲートが配置されているコントローラによって処理されます。優先度が低いパスはアクティブですが、別のコントローラから提供されるため最適化されません。最適化されていないパスは、使用可能な最適化されたパスがない場合にのみ使用されます。

.例
次の例は、 2 つのアクティブ / 最適化パスと 2 つのアクティブ / 非最適化パスを使用する ONTAP LUN に対する正しい出力を表示します。

[listing]
----
# sanlun lun show -p |grep -p hdisk78
                    ONTAP Path: vs_aix_clus:/vol/chataix_205p2_vol_en_1_7/jfs_205p2_lun_en
                           LUN: 37
                      LUN Size: 15g
                   Host Device: hdisk78
                          Mode: C
            Multipath Provider: AIX Native
        Multipathing Algorithm: round_robin
------- ---------- ------ ------- ---------- ----------
host    vserver    AIX                        AIX MPIO
path    path       MPIO   host    vserver         path
state   type       path   adapter LIF         priority
------- ---------- ------ ------- ---------- ----------
up      secondary  path0  fcs0    fc_aix_1        1
up      primary    path1  fcs0    fc_aix_2        1
up      primary    path2  fcs1    fc_aix_3        1
up      secondary  path3  fcs1    fc_aix_4        1

----


=== オールSANアレイ構成

ASA構成では、特定のLUNへのすべてのパスがアクティブで最適化されています。これにより、すべてのパスを同時に経由するI/O処理が行われるため、パフォーマンスが向上します。

.例
次の例は、 ONTAP LUN の正しい出力を表示します。


NOTE: ONTAP 9.8 for AIX Hosts 以降では、すべての SAN アレイ（ ASA ）構成がサポートされています。

[listing]
----
# sanlun lun show -p |grep -p hdisk78
                    ONTAP Path: vs_aix_clus:/vol/chataix_205p2_vol_en_1_7/jfs_205p2_lun_en
                           LUN: 37
                      LUN Size: 15g
                   Host Device: hdisk78
                          Mode: C
            Multipath Provider: AIX Native
        Multipathing Algorithm: round_robin
------ ------- ------ ------- --------- ----------
host   vserver  AIX                      AIX MPIO
path   path     MPIO   host    vserver     path
state  type     path   adapter LIF       priority
------ ------- ------ ------- --------- ----------
up     primary  path0  fcs0    fc_aix_1     1
up     primary  path1  fcs0    fc_aix_2     1
up     primary  path2  fcs1    fc_aix_3     1
up     primary  path3  fcs1    fc_aix_4     1
----


== 推奨設定

次に、ONTAP LUNの推奨されるパラメータ設定を示します。  ONTAP LUN の重要なパラメータは、 NetApp Host Utilities Kit をインストールしたあとに自動的に設定されます。

[cols="4*"]
|===
| パラメータ | 環境 | AIX の値 | 注 


| アルゴリズム | MPIO | Round_Robin （ラウンドロビン | Host Utilities で設定します 


| hcheck_cmd | MPIO | お問い合わせ | Host Utilities で設定します 


| hcheck_interval | MPIO | 30 | Host Utilities で設定します 


| hcheck_mode | MPIO | 非アクティブ | Host Utilities で設定します 


| lun_reset_spt | MPIO または非 MPIO | はい。 | Host Utilities で設定します 


| max_transfer を実行します | MPIO または非 MPIO | FC LUN ： 0x100000 バイト | Host Utilities で設定します 


| QFULL _ Dly | MPIO または非 MPIO | 2 秒の遅延 | Host Utilities で設定します 


| queue_depth | MPIO または非 MPIO | 64 | Host Utilities で設定します 


| RESERVE_policy | MPIO または非 MPIO | 予約なし | Host Utilities で設定します 


| rw_timeout（ディスク） | MPIO または非 MPIO | 30 秒 | OS のデフォルト値を使用します 


| dyntrk | MPIO または非 MPIO | はい。 | OS のデフォルト値を使用します 


| FC_err_recov | MPIO または非 MPIO | fast_fail | OS のデフォルト値を使用します 


| q_type | MPIO または非 MPIO | シンプル | OS のデフォルト値を使用します 


| num_cmd_elems | MPIO または非 MPIO | VIOS 用 AIX 3072 では 1024 | FC EN1B 、 FC EN1C 


| num_cmd_elems | MPIO または非 MPIO | AIX の場合は 1024 | FC EN0G 
|===


== MetroCluster の推奨設定

デフォルトでは、LUNへのパスがない場合、AIXオペレーティングシステムはI/Oタイムアウトを短縮します。この状況は、シングルスイッチの SAN ファブリック構成や MetroCluster 構成など、計画外のフェイルオーバーが発生する構成で発生することがあります。追加情報 および推奨されるデフォルト設定の変更については、を参照してください link:https://kb.netapp.com/app/answers/answer_view/a_id/1001318["NetApp KB1001318"^]



== SM-BCによるAIXサポート

ONTAP 9.11.1以降では、SM-BCでAIXがサポートされます。AIX構成では、プライマリクラスタが「アクティブ」クラスタになります。

AIX構成では、フェイルオーバー時にシステムが停止します。フェイルオーバーが発生するたびに、ホストで再スキャンを実行してI/O処理を再開する必要があります。

AIX for SM-BCを設定する方法については、ナレッジベースの記事を参照してください link:https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/SnapMirror/How_to_configure_an_AIX_host_for_SnapMirror_Business_Continuity_(SM-BC)["SnapMirrorのビジネス継続性を実現するためのAIXホストの構成方法（SM-BC）"^]。



== 既知の問題および制限

[cols="4*"]
|===
| NetApp バグ ID | タイトル | 説明 | パートナー ID 


| 1416221 | ストレージフェイルオーバー中に AIX 7200-05-01 で、仮想 iSCSI ディスク（ VIOS 3.1.x ）で I/O の中断が発生しました | VIOS 3.1.1 を介してマッピングされた仮想 iSCSI ディスク上の AIX 7.2 TL5 ホストでのストレージフェイルオーバー操作中に、 I/O の中断が発生することがありますデフォルトでは 'VIOC 上の仮想 iSCSI ディスク（ hdisk ）の Rw_timeout' 値は 45 秒になりますストレージフェイルオーバー時に 45 秒を超える I/O 遅延が発生すると、 I/O 障害が発生する可能性があります。この状況を回避するには、 BURT に記載されている回避策を参照してください。IBM と同様に 'APAR-IJ34739 （今後のリリース）を適用した後 'chdev' コマンドを使用して Rw_timeout 値を動的に変更できます | 該当なし 


| 1414700 | ストレージフェイルオーバー中に、 AIX 7.2 TL04 で仮想 iSCSI ディスク（ VIOS 3.1.x ）で I/O の停止が発生しました | VIOS 3.1.x を介してマッピングされた仮想 iSCSI ディスク上の AIX 7.2 TL4 ホストで、ストレージフェイルオーバー処理中に I/O が中断することがありますデフォルトでは、 VIOC 上の vSCSI アダプタの「 rw_timeout 」値は 45 秒です。ストレージのフェイルオーバー時に 45 秒以上の I/O 遅延が発生すると、 I/O 障害が発生する可能性があります。この状況を回避するには、 BURT に記載されている回避策を参照してください。 | 該当なし 


| 1307653 | SFO の障害およびストレート I/O 中に VIOS 3.1.1.10 で I/O の問題を確認する | VIOS 3.1.1 IO エラーは、 16 / 32GB FC アダプタでバックアップされた NPIV クライアントディスクに表示されることがあります。また 'vfchost' ドライバが ' クライアントからの I/O 要求の処理を停止する状態になることもありますIBM APAR IJ22290 IBM APAR IJ23222 を適用すると、問題が修正されます | 該当なし 
|===