---
sidebar: sidebar 
permalink: hu_citrix_7x.html 
keywords: host utilities, citrix, XenServer, 7 series, netapp, ontap, san, boot 
summary: ONTAP で Citrix XenServer 7.x を使用する方法について説明します 
---
= ONTAPでCitrix XenServerを使用する
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Citrix XenServer 7シリーズOSリリースでは、FC、FCoE、およびiSCSIプロトコルを使用するONTAP SANホストの設定を行うことができます。



== SAN ブート中です

.必要なもの
SAN ブートを使用する場合は、構成でサポートされている必要があります。を使用できます link:https://mysupport.netapp.com/matrix/imt.jsp?components=91241;&solution=236&isHWU&src=IMT["NetApp Interoperability Matrix Tool で確認できます"^] 使用している OS 、 HBA 、 HBA ファームウェア、 HBA ブート BIOS 、および ONTAP のバージョンがサポートされていることを確認します。

.手順
. SAN ブート LUN をホストにマッピングします。
. 複数のパスが使用可能であることを確認します。
+

NOTE: ホストOSが起動してパスで実行されると、複数のパスが使用可能になります。

. SAN ブート LUN がマッピングされているポートに対して、サーバ BIOS で SAN ブートを有効にします。
+
HBA BIOS を有効にする方法については、ベンダー固有のマニュアルを参照してください。

. ホストをリブートしてブートが成功したことを確認します。




== マルチパス

Citrix XenServer でのマルチパスのサポートは、 Device Mapper multipathd コンポーネントに基づいています。Device Mapper ノードは、 XenServer に提供されるすべての LUN に対して自動的には作成されず、 Storage Management Layer （ API ）で LUN がアクティブに使用されている場合にのみプロビジョニングされます。Citrix XenServer Storage Manager API プラグインは、マルチパスノードのアクティブ化と非アクティブ化を自動的に処理します。

Integrated Multipath Management のアーキテクチャとの互換性がないため、 Citrix XenCenter アプリケーションを使用してストレージ構成を管理することを推奨します。Device Mapper テーブルのステータスを手動で照会したり、システム上のアクティブな Device Mapper マルチパスノードのリストを表示したりする必要がある場合は、 /usr/sbin/mpathutil status コマンドを使用して ONTAP LUN の設定を確認できます。詳細については、 Citrix XenServer の標準的なベンダー提供のドキュメントを参照してください。



=== ASAイカイノコウセイ

ASA以外の構成では、優先度が異なる2つのパスグループが必要です。優先度が高いパスは「アクティブ / 最適化」です。つまり、アグリゲートが配置されているコントローラによって処理されます。優先度が低いパスはアクティブですが、別のコントローラから提供されるため最適化されません。最適化されていないパスは、最適化されたパスを使用できない場合にのみ使用されます。

.例
次の例は、 2 つのアクティブ / 最適化パスと 2 つのアクティブ / 非最適化パスを使用する ONTAP LUN に対する正しい出力を表示します。

[listing]
----
# mpathutil status
show topology
3600a098038303458772450714535317a dm-0 NETAPP  , LUN C-Mode
size=80G features='4 queue_if_no_path pg_init_retries 50 retain_attached_hw_handle' hwhandler='1 alua' wp=rw
|-+- policy='service-time 0' prio=50 status=active
| |- 2:0:2:0   sdc   8:32    active ready running
| |- 12:0:5:0  sdn   8:208   active ready running
| |- 2:0:6:0   sdg   8:96    active ready running
| `- 12:0:0:0  sdi   8:128   active ready running
|-+- policy='service-time 0' prio=10 status=enabled
  |- 2:0:0:0   sda   8:0     active ready running
  |- 2:0:1:0   sdb   8:16    active ready running
  |- 12:0:3:0  sd1   8:176   active ready running
  `-12:0:6:0   sdo   8:224   active ready running
[root@sanhost ~]#
----

NOTE: 1 つの LUN へのパスを余分に使用しないでください。必要なパスは最大 4 つです。8 個を超えるパスがストレージ障害時に原因パスの問題になる可能性があります。



=== オール SAN アレイ構成

All SAN Array （ ASA ）構成では、特定の論理ユニット（ LUN ）へのすべてのパスがアクティブで最適化されています。つまり、すべてのパスで同時に I/O を処理できるため、パフォーマンスが向上します。

.例
次の例は、4つのアクティブ/最適パスがすべて設定されたONTAP LUNに対する正しい出力を表示します。

[listing]
----
# mpathutil status
show topology
3600a098038303458772450714535317a dm-0 NETAPP  , LUN C-Mode
size=80G features='4 queue_if_no_path pg_init_retries 50 retain_attached_hw_handle' hwhandler='1 alua' wp=rw
|-+- policy='service-time 0' prio=50 status=active
| |- 2:0:2:0   sdc   8:32    active ready running
| |- 12:0:5:0  sdn   8:208   active ready running
| |- 2:0:6:0   sdg   8:96    active ready running
| `- 12:0:0:0  sdi   8:128   active ready running
[root@sanhost ~]#
----

NOTE: 1 つの LUN へのパスを余分に使用しないでください。必要なパスは最大 4 つです。8 個を超えるパスがストレージ障害時に原因パスの問題になる可能性があります。



=== 推奨設定

Citrix XenServer 7.x OS は、 ONTAP LUN を認識して正しく管理するために必要なすべての設定でコンパイルされます。Citrix XenServer 7.x の場合、空のゼロバイト「 /etc/multipath.conf 」ファイルが存在している必要がありますが、ファイルに特定の変更を加える必要はありません。

XenCenter Management Portal からホストマルチパスサービスを有効にし、マルチパスサービスが有効で実行されていることを確認します。

[listing]
----
# systemct1 status multipathd
multipathd.service - Device-Mapper Multipath Device Controller
  Loaded:  load (/usr/lib/systemd/system/multipathd.service; enabled; vendor preset: enabled)
 Drop-In:  /etc/systemd/system/multipathd.service.d
             slice.config
  Active:  active (running) since Fri YYYY-MM-DD 00:00:26 IST; 1 month 9 days ago
Main PID:  3789 (multipathd)
  CGroup:  /control.slice/multipathd.service
            3789  /sbin/multipathd
----
 `/etc/multipath.conf`マルチパスで管理したくないデバイスがある場合や、既存の設定がデフォルトよりも優先される場合を除き、ファイルにコンテンツを追加する必要はありません。 `multipath.conf`ファイルに次の構文を追加して、不要なデバイスを除外できます。

[listing]
----
# cat /etc/multipath.conf
blacklist {
     wwid    <DevId>
     devnode "^(ram|raw|loop|fd|md|dm-|sr|scd|st)[0-9]*"
     devnode "^hd[a-z]"
     devnode "^cciss.*"
}
----

NOTE: 「 * <devd>* 」を除外するデバイスの WWID の文字列に置き換えます。

.例
このCitrix XenServer 7.xの例では、 `sda` は、ブラックリストに追加する必要があるローカルSCSIディスクです。

. 次のコマンドを実行して WWID を特定します。
+
[listing]
----
# lib/udev/scsi_id -gud /dev/sda
3600a098038303458772450714535317a
----
. /etc/multipath.conf 内のブラックリストスタンザに、次の WWID を追加します。
+
[listing]
----
#cat /etc/multipath.conf
blacklist {
  wwid    3600a098038303458772450714535317a
  devnode "^(ram|raw|loop|fd|md|dm-|sr|scd|st)[0-9*]"
  devnode "^hd[a-z]"
  devnode "^cciss.*"
}
----


「 $multipathd show config 」コマンドを使用して、マルチパスパラメータのランタイム設定を参照します。デフォルト設定よりも優先される可能性がある古い設定については、必ず実行コンフィギュレーションを確認してください。特に、 defaults セクションで確認します。

次の表に、 ONTAP LUN の multipathd * パラメータと必要な値を示します。ホストが他のベンダーの LUN に接続されていて、これらのパラメータのいずれかが無視された場合は、 ONTAP LUN に特に適用される * multipath.conf * の後の行 AS によって修正する必要があります。そうしないと、 ONTAP LUN が想定どおりに機能しない可能性があります。以下のデフォルト設定は、影響を完全に把握したうえで、ネットアップや OS のベンダーに相談して無視してください。

[cols="2*"]
|===
| パラメータ | 設定 


| 「 detect_prio 」 | はい。 


| dev_los_TMO | " 無限 " 


| フェイルバック | 即時 


| 'fast_io_fail_tmo | 5. 


| 「特長」 | "3 queue_if_no_path pg_init_retries 50" 


| 「 flush_on_last_del` 」 | はい。 


| 'hardware_handler' | 0 


| 「 path_checker 」のようになります | " tur " 


| 「 path_grouping_policy 」と入力します | 「 group_by_prio 」 


| 「 path_selector` 」 | "service-time 0" 


| polling _interval | 5. 


| 「 prio` | ONTAP 


| 「 product 」を参照してください | LUN. * 


| retain_attached hw_handler | はい。 


| 「 RR_WEIGHT」 | " 均一 " 


| 「 user_friendly _ names 」 | いいえ 


| ベンダー | ネットアップ 
|===
.例
次の例は、オーバーライドされたデフォルトを修正する方法を示しています。この場合、 * multipath.conf * ファイルは、 ONTAP LUN と互換性のない * path_checker * および * detect_prio * の値を定義します。ホストに接続された他の SAN アレイが原因でパラメータを削除できない場合は、デバイススタンザを使用して ONTAP LUN 専用にパラメータを修正できます。

[listing]
----
# cat /etc/multipath.conf
defaults {
  path_checker readsector0
  detect_prio no
}
devices{
        device{
                vendor "NETAPP "
                product "LUN.*"
                path_checker tur
                detect_prio yes
        }
}
----

NOTE: Citrix XenServer では、サポート対象の構成で、 Linux および Windows ベースのすべてのゲスト VM に Citrix VM ツールを使用することを推奨しています。



== 既知の問題

Citrix XenServer with ONTAPリリースに関する既知の問題はありません。
