---
sidebar: sidebar 
permalink: hu_citrix_82.html 
keywords: host utilities, citrix, Hypervisor, 8 series, netapp, ontap, san, boot 
summary: Citrix Hypervisor 8.2 をマルチパス用に構成し、 ONTAPストレージでの FCP および iSCSI プロトコル操作用の特定のパラメーターと設定を設定します。 
---
= ONTAPストレージでFCPおよびiSCSI用にCitrix Hypervisor 8.2を構成する
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Citrix Hypervisor 8.2 をマルチパス用に構成し、 ONTAPストレージでの FCP および iSCSI プロトコル操作用の特定のパラメーターと設定を設定します。

[NOTE]
====
Linux Host Utilities ソフトウェア パッケージは、Citrix Hypervisor オペレーティング システムをサポートしていません。

====


[[step-1-optionally-enable-san-booting]]
== 手順1：必要に応じてSANブートを有効にします。

SANブートを使用するようにホストを設定することで、導入を簡易化し、拡張性を向上させることができます。

.開始する前に
を使用link:https://mysupport.netapp.com/matrix/#welcome["Interoperability Matrix Tool"^]して、Linux OS、ホストバスアダプタ（HBA）、HBAファームウェア、HBAブートBIOS、およびONTAPバージョンがSANブートをサポートしていることを確認します。

.手順
. link:https://docs.netapp.com/us-en/ontap/san-admin/provision-storage.html["SANブートLUNを作成し、ホストにマップする"^]です。
. SAN ブート LUN がマッピングされているポートに対して、サーバ BIOS で SAN ブートを有効にします。
+
HBA BIOS を有効にする方法については、ベンダー固有のマニュアルを参照してください。

. 構成が正常に完了したことを確認するために、ホストをリブートし、OSが稼働していることを確認します。




[[step-2-confirm-the-multipath-configuration-for-your-host]]
== ステップ2: ホストのマルチパス構成を確認する

Citrix Hypervisor 8.2 のマルチパスを使用して、ONTAP LUN を管理できます。

ホストでマルチパスが正しく設定されていることを確認するには、ファイルが定義されていること、およびONTAP LUN用にNetAppの推奨設定が設定されていることを確認し `/etc/multipath.conf`ます。

.手順
.  `/etc/multipath.conf`ファイルを見つけます。
+
参照 `/etc/multipath.conf`ファイルに NetApp デバイス固有の構成パラメータが含まれていない場合は、以下のカスタマイズされた `.conf drop-in`ファイルを使用してこれらのパラメータを追加してください。このファイルは以下の場所にあります `/etc/multipath/conf.d/`：

+

NOTE:  `/etc/multipath.conf`ファイルは変更しないでください。システムアップデート中にファイルの内容が上書きされる可能性があります。

+
.ファイルの内容を表示する
[%collapsible]
====
[source, cli]
----
$sudo tee -a /etc/multipath/conf.d/custom.conf >/dev/null <<'EOF'

defaults {
    polling_interval 5
}

blacklist {
    wwid <Insert_LUN_wwid_string>
    devnode "^(ram|raw|loop|fd|md|dm-|sr|scd|st)[0-9]*"
    devnode "^hd[a-z]"
    devnode "^cciss.*"
}

devices {
    device {
    vendor "NETAPP"
    product "LUN.*"
    user_friendly_names no
    path_checker "tur"
    prio "ontap"
    detect_prio yes
    path_grouping_policy "group_by_prio"
    path_selector "service-time 0"
    failback immediate
    fast_io_fail_tmo 5
    dev_loss_tmo infinity
    no_path_retry queue
    features "3 queue_if_no_path pg_init_retries 50"
    flush_on_last_del yes
    hardware_handler "0"
    retain_attached_hw_handler yes
    rr_weight uniform
  }
}

EOF
----
====
. マルチパスを初めて設定する場合は、推奨設定を読み込むために、マルチパスサービスを有効にして起動する必要がある場合があります。
+
[source, cli]
----
systemctl enable multipathd
----
+
[source, cli]
----
systemctl start multipathd
----
. ホストを起動するたびに、 `/etc/multipath/conf.d/custom.conf`ファイルが自動的に NetApp 推奨のホストマルチパスパラメータをデフォルト設定としてロードします。
+
次の表に、Linux OSで標準でコンパイルされたONTAP LUNのマルチパスパラメータの設定を示します。

+
.パラメータ設定の表示
[%collapsible]
====
[[multipath-parameter-settings]]
[cols="2"]
|===
| パラメータ | 設定 


| detect_prio | はい。 


| DEV_DETION_TMO | " 無限 " 


| フェイルバック | 即時 


| fast_io_fail_TMO | 5. 


| の機能 | "3 queue_if_no_path pg_init_retries 50" 


| flush_on_last_del | はい。 


| hardware_handler | 0 


| パスの再試行なし | キュー 


| path_checker です | " tur " 


| path_grouping_policy | 「 group_by_prio 」 


| path_selector | "service-time 0" 


| polling _interval （ポーリング間隔） | 5. 


| Prio | ONTAP 


| プロダクト | LUN 


| retain_attached _hw_handler | はい。 


| RR_weight を指定します | " 均一 " 


| ユーザーフレンドリ名 | いいえ 


| ベンダー | ネットアップ 
|===
====
. ONTAP LUNのパラメータ設定とパスステータスを確認します。
+
[source, cli]
----
/sbin/mpathutil status
----
+
デフォルトのマルチパス パラメータは、 ASA、 AFF、およびFAS構成をサポートします。これらの構成では、単一のONTAP LUN に 4 つを超えるパスは必要ありません。パスが 4 つを超えると、ストレージ障害時に問題が発生する可能性があります。

+
次の出力例は、ASA、AFF、またはFAS構成のONTAP LUNについて、正しいパラメータ設定とパスステータスを示しています。

+
[role="tabbed-block"]
====
.ASA構成
--
ASA構成では、特定のLUNへのすべてのパスが最適化され、アクティブな状態が維持されます。これにより、すべてのパスを同時に経由するI/O処理が行われるため、パフォーマンスが向上します。

.例を示します
[%collapsible]
=====
[listing]
----
/usr/sbin/mpathutil status
show topology
create: 3600a098038315045572b5930646f4b63 dm-1 NETAPP  ,LUN C-Mode
size=9.0G features='4 queue_if_no_path pg_init_retries 50 retain_attached_hw_handle' hwhandler='1 alua' wp=rw
`-+- policy='service-time 0' prio=50 status=active
  |- 15:0:0:0  sdb  8:16    active ready running
  |- 15:0:1:0  sdc  8:32    active ready running
  |- 16:0:0:0  sdcf 69:48   active ready running
  `- 16:0:1:0  sdcg 69:64   active ready running
----
=====
--
.AFFまたはFASの設定
--
AFFまたはFAS構成には、優先度の高いパスと低いパスの2つのグループを設定する必要があります。優先度の高いアクティブ/最適化パスは、アグリゲートが配置されているコントローラで処理されます。優先度の低いパスはアクティブですが、別のコントローラで処理されるため最適化されていません。最適化されていないパスは、最適化されたパスを使用できない場合にのみ使用されます。

次の例は、2つのアクティブ/最適化パスと2つのアクティブ/非最適化パスがあるONTAP LUNの出力を示しています。

.例を示します
[%collapsible]
=====
[listing]
----
/usr/sbin/mpathutil status
show topology
create: 3600a098038315045572b5930646f4b63 dm-1 NETAPP  ,LUN C-Mode
size=9.0G features='4 queue_if_no_path pg_init_retries 50 retain_attached_hw_handle' hwhandler='1 alua' wp=rw
|-+- policy='service-time 0' prio=50 status=active
  |- 15:0:0:0  sdb  8:16    active ready running
  `- 15:0:1:0  sdc  8:32    active ready running
`-+- policy='service-time 0' prio=50 status=active
     |- 16:0:0:0  sdcf 69:48   active ready running
     `- 16:0:1:0  sdcg 69:64   active ready running
----
=====
--
====




[[step-3-optionally-exclude-a-device-from-multipathing]]
== ステップ3: オプションでデバイスをマルチパスから除外する

必要に応じて、不要なデバイスの WWID を `/etc/multipath/conf.d/custom.conf`ファイルの「ブラックリスト」セクションに追加することで、マルチパスからデバイスを除外できます。

.手順
. WWIDを確認します。
+
[source, cli]
----
/lib/udev/scsi_id -gud /dev/sda
----
+
sdaは、ブラックリストに追加するローカルSCSIディスクです。

+
WWIDの例はです `360030057024d0730239134810c0cb833`。

. 「blacklist」スタンザにWWIDを追加します。
+
[source, cli]
----
blacklist {
        wwid   360030057024d0730239134810c0cb833
        devnode "^(ram|raw|loop|fd|md|dm-|sr|scd|st)[0-9]*"
        devnode "^hd[a-z]"
        devnode "^cciss.*"
}
----




[[step-4-customize-multipath-parameters-for-ontap-luns]]
== ステップ4: ONTAP LUNのマルチパスパラメータをカスタマイズする

ホストが他のベンダーの LUN に接続されていて、マルチパスパラメータ設定のいずれかが上書きされている場合は、ONTAP LUN に特定的に適用される `/etc/multipath/conf.d/custom.conf`ファイルのスタンザを変更して修正する必要があります。ファイル内を下にスクロールして、これらのスタンザを追加してください。パラメーターを修正しないと、ONTAP LUN が期待どおりに動作しない可能性があります。


CAUTION: ONTAP LUNの推奨されるパラメータ設定は無視しないでください。これらの設定は、ホスト構成のパフォーマンスを最適化するために必要です。詳細については、NetAppサポート、OSベンダー、またはその両方にお問い合わせください。

次の例は、オーバーライドされたデフォルト値を修正する方法を示しています。この例では、 `custom.conf drop-in`ファイルでONTAP LUNと互換性のない `path_checker`および `no_path_retry`の値が定義されていますが、ONTAPストレージアレイがまだホストに接続されているため、これらのパラメータを削除することはできません。代わりに、ONTAP LUNに固有に適用されるデバイススタンザを `custom.conf drop-in`ファイルに追加することで、 `path_checker`と `no_path_retry`の値を修正します。

.例を示します
[%collapsible]
====
[listing, subs="+quotes"]
----
defaults {
   path_checker      *readsector0*
   no_path_retry     *fail*
}

devices {
   device {
      vendor          "NETAPP"
      product         "LUN"
      no_path_retry   *queue*
      path_checker    *tur*
   }
}
----
====


[[step-5-review-the-known-issues]]
== ステップ5: 既知の問題を確認する

既知の問題はありません。
