---
sidebar: sidebar 
permalink: hu_hpux_60.html 
keywords: host utilities, unified, oracle, linux, 7.1, netapp, ontap 
summary: HP-UX Host Utilities 6.0とONTAPストレージの使用方法について説明します。 
---
= HP-UX Host Utilities 6.0 for ONTAPストレージのインストール
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
HP-UX ホスト ユーティリティは、HP-UX ホストに接続されたONTAPストレージの管理に役立ちます。 NetAppHP-UX ホスト ユーティリティのインストールを強く推奨していますが、必須ではありません。これらのユーティリティにより管理が改善され、 NetAppカスタマー サポートが構成に関する情報を収集しやすくなります。

HP-UX ホスト ユーティリティは次の環境をサポートします。

* ネイティブのMicrosoftマルチパスI/O（MPIO）
* Veritas Dynamic Multipathing（DMP；動的マルチパス）


.開始する前に
信頼性の高い操作のために、 https://imt.netapp.com/matrix/#welcome["Interoperability Matrix Tool"^] iSCSI、FC、または FCoE 構成がサポートされていることを確認します。

.手順
. HP-UX ホストにログインします。
. から HP-UX Host Utilities ファイル netapp_hpux_host_utilities_6.0_ia_pa.depot.gz` をダウンロードします link:https://mysupport.netapp.com/site/["ネットアップサポートサイト"^] を HP-UX ホストにインストールします。
. を解凍します。 `netapp_hpux_host_utilities_6.0_ia_pa.depot.gz` ファイル：
+
[source, cli]
----
gunzip netapp_hpux_host_utilities_6.0_ia_pa.depot.gz
----
+
デポファイルを解凍したディレクトリに、抽出したソフトウェアが配置されます。

. ソフトウェアをインストールします。
+
[source, cli]
----
swinstall -s /depot_path
----
+
「 depot_path 」は、デポファイルのパスと名前を提供します。

+
swinstall コマンドは 'HP-UX セットアップの状態を確認するインストール・スクリプトを実行しますシステムが要件を満たしている場合、このスクリプトは「 sanlun 」ユーティリティおよび診断スクリプトを「 /opt/NetApp/santools/bin 」ディレクトリにインストールします。

. インストールを確認します。
+
[source, cli]
----
sanlun version
----




== 次の手順

link:hu-hpux-sanlun-toolkit.html["SANツールキットについて学ぶ"] 。
