---
sidebar: sidebar 
permalink: hu_hpux_60.html 
keywords: host utilities, unified, oracle, linux, 7.1, netapp, ontap 
summary: HP-UX Unified Host Utilities 6.0とONTAPの使用方法について説明します。 
---
= HP-UX Host Utilities 6.0
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
HP-UX Host Utilitiesを使用すると、HP-UXホストをNetAppストレージに接続できます。

HP-UX Host Utilitiesは、複数のプロトコルと次の環境をサポートします。

* ネイティブMPIO
* Veritas Dynamic Multipathing（DMP；動的マルチパス）



NOTE: このドキュメントでは、使用している環境を示すために、Veritas DMP環境には「DMP」、HP-UXネイティブ環境には「MPIO」と指定することがあります。使用するコマンドは、使用するドライバによって異なる場合があります。このような場合は、環境とドライバの両方のタイプを指定します。

.必要なもの
* 安定した運用を実現するために、iSCSI、FC、またはFCoE構成全体がサポートされていることを確認します。


を使用できます link:https://mysupport.netapp.com/matrix/imt.jsp?components=71102;&solution=1&isHWU&src=IMT["NetApp Interoperability Matrix Tool で確認できます"^] 構成を確認します。

.このタスクについて
NetApp HP-UX Host Utilitiesソフトウェアパッケージは、にあります link:https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/6.0/downloads["ネットアップサポートサイト"^] 圧縮されたファイル。ファイルをダウンロードしたら、インストール前に解凍する必要があります。

.手順
. ホストにログインします。
. から HP-UX Host Utilities ファイル netapp_hpux_host_utilities_6.0_ia_pa.depot.gz` をダウンロードします link:https://mysupport.netapp.com/site/["ネットアップサポートサイト"^] を HP-UX ホストにインストールします。
. を解凍します。 `netapp_hpux_host_utilities_6.0_ia_pa.depot.gz` ファイル：
+
#gunzip netapp_hpux_host_utilities_6.0_ia_pa.depot.gz`

+
デポファイルを解凍したディレクトリに、抽出したソフトウェアが配置されます。

. ソフトウェアをインストールします。
+
「 #swinstall-s/depot_path 」

+
「 depot_path 」は、デポファイルのパスと名前を提供します。

+
swinstall コマンドは 'HP-UX セットアップの状態を確認するインストール・スクリプトを実行しますシステムが要件を満たしている場合、このスクリプトは「 sanlun 」ユーティリティおよび診断スクリプトを「 /opt/NetApp/santools/bin 」ディレクトリにインストールします。

. インストールを確認します。
+
「 anlun version 」を参照してください





== SAN ツールキット

HP-UX Host Utilitiesは、HP-UXホスト上にコマンドラインツールキットを提供するネットアップホストソフトウェアです。このツールキットは、 NetApp Host Utilities パッケージをインストールするときにインストールされます。このキットは、を提供します `sanlun` LUNおよびホストバスアダプタの管理に役立つユーティリティ。（HBA）。。 `sanlun` コマンドは、ホストにマッピングされているLUNに関する情報、マルチパス、およびイニシエータグループの作成に必要な情報を返します。

.例
次の例では 'lun lun lun show コマンドは LUN 情報を返します

[listing]
----
# sanlun lun show all

controller(7mode)/ device host lun
vserver(Cmode)           lun-pathname                   filename          adapter    protocol   size   mode
------------------------------------------------------------------------------------------------------------
sanboot_unix         /vol/hpux_boot/boot_hpux_lun      /dev/rdsk/c34t0d0  fclp1      FCP        150g    C
sanboot_unix         /vol/hpux_boot/boot_hpux_lun      /dev/rdsk/c23t0d0  fclp1      FCP        150g    C
sanboot_unix         /vol/hpux_boot/boot_hpux_lun      /dev/rdsk/c12t0d0  fclp0      FCP        150g    C
sanboot_unix         /vol/hpux_boot/boot_hpux_lun      /dev/rdsk/c81t0d0  fclp0      FCP        150g    C

----

NOTE: このツールキットは、Host Utilitiesのすべての構成とプロトコルに共通です。その結果、一部の内容は 1 つの構成に適用されますが、別の構成には適用されません。未使用のコンポーネントを使用しても、システムのパフォーマンスに影響はありません。
