---
sidebar: sidebar 
permalink: hu_hpux_60_rn.html 
keywords: host utilities, hpux, 6.0, netapp, ontap, release, notes 
summary: HPUX Host Utilities 6.0リリースノート 
---
= HP-UX Host Utilities 6.0リリースノート
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


本リリースノートには、HP-UX Host Utilities 6.0リリースの最新情報に加え、既知の問題、制限事項、ONTAP ストレージシステムの構成と管理に関する最新情報が記載されています。『リリースノート』ドキュメントは、HP-UX Host Utilitiesの使用に関する新しい情報が入手できるようになると更新されます。



== HP-UX Host Utilities 6.0リリースの概要

HP-UX Host Utilitiesは、いくつかのHP-UX環境と複数のプロトコルをサポートします。HP-UX Host Utilitiesは、次の環境をサポートします。

* ネイティブMPIO
* Veritas Dynamic Multipathing（DMP；動的マルチパス）



NOTE: 使用されている環境をすぐに明確にするために、本書ではVeritas DMP環境の場合は「DMP」、HP-UXネイティブ環境の場合は「MPIO」を指定します。使用するコマンドは、使用するドライバによって異なる場合があります。このような場合は、環境とドライバの両方のタイプを指定します。



== HP-UX Host Utilities 6.0の機能拡張

リリースノートは、新しい情報が提供されるたびに製品リリースごとに更新されます。HP-UX Host Utilities 6.0は、引き続き次のバージョンをサポートしています。

* HP-UX 11iv2
* HP-UX 11iv3




== 既知の問題および制限

HP-UX 6.0リリースでは既知の問題はありません。



== SANホスト構成のドキュメントについて

には、SAN Host Utilitiesのマニュアルが含まれています link:https://docs.netapp.com/us-en/ontap-sanhost/index.html["ONTAP SANホスト構成のドキュメント"] ONTAP SANホストの構成に関するドキュメントは、SANホストの現在のすべてのリリースをカバーしているため、累積的なものです。リリース間の機能の違いは、コンテキストに基づいて示されます。



== 製品マニュアルとその他の情報の参照先

ネットアップのすべての製品のマニュアルにアクセスし、ネットアップ社内サイトの製品ドキュメントページで、テクニカルレポートやホワイトペーパーなど、製品に関するその他の情報を参照できます。

* ONTAP ストレージ・システムの構成と管理*

* 。 link:https://docs.netapp.com/us-en/ontap/setup-upgrade/index.html["使用しているONTAP バージョンに対応した『ONTAP ソフトウェアセットアップガイド』"^]
* 。 link:https://docs.netapp.com/us-en/ontap/san-management/index.html["使用しているONTAP バージョンに対応した『ONTAP SANアドミニストレーションガイド』"^]
* 。 link:https://library.netapp.com/ecm/ecm_download_file/ECMLP2492508["使用しているONTAP のバージョンに対応したONTAP リリースノート"^]
* link:https://imt.netapp.com/matrix/#welcome["NetApp Interoperability Matrix を参照してください"^]
* link:https://hwu.netapp.com/["Hardware Universe"^] （旧称は『システム構成ガイド』）
* link:https://docs.netapp.com/us-en/ontap-sanhost/index.html["サポートされているファイバチャネルSANトポロジ"]
* link:https://mysupport.netapp.com/documentation/productlibrary/index.html?productID=61343["Host Utilitiesを使用するためのホストの設定"^]

