---
sidebar: sidebar 
permalink: hu_luhu_71_rn.html 
keywords: host utilities, linux, 7.1, netapp, ontap, release, notes 
summary: Linux Unified Host Utilities 7.1のリリースノート 
---
= 『Linux Unified Host Utilities 7.1 Release Notes』
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
このリリースノートのドキュメントには、Linux Unified Host Utilities 7.1リリースの最新情報が記載されています。既知の問題と制限事項、重要な注意事項、新機能、および拡張機能に関する情報も含まれています。また、Host Utilitiesのリリース以降に検出された問題についても説明します。



== Linux Unified Host Utilities 7.1リリースの概要

Linux Unified Host Utilitiesは、いくつかのLinuxオペレーティングシステムをサポートしています。Host Utilitiesを使用すると、Linuxホストをネットアップストレージシステムに接続できます。

Linux Unified Host Utilities 7.1では、引き続き次のバージョンのLinuxがサポートされます。

* Red Hat Enterprise Linux の場合
* SUSE Linux Enterprise Server
* Oracle Linux の場合
* Oracle VM
* Citrix XenServer
* Veritas の略



NOTE: オペレーティングシステムのバージョンおよびHost Utilitiesがサポートする更新については、を参照してください link:https://mysupport.netapp.com/matrix/imt.jsp?components=65623;64703;&solution=1&isHWU&src=IMT["NetApp Interoperability Matrix Tool で確認できます"^]。

Host Utilitiesソフトウェアは、32ビットと64ビットの両方のrpmファイルとして提供されています。使用するホストアーキテクチャとドキュメントに対応する正しい.rpmファイルは、からダウンロードできます link:https://mysupport.netapp.com/site/["ネットアップサポートサイト"^]。

のインストールとセットアップの手順については、を参照してください link:https://docs.netapp.com/us-en/ontap-sanhost/hu_luhu_71.html["『 Linux Unified Host Utilities 7.1 Installation Guide 』"]。



== 7.1リリースの新機能

SANtricity ONTAP を実行するNetApp Eシリーズストレージシステム、およびAFF を実行するシステムとFAS システムをサポートするため、Linux Host Utilitiesは_ Linux Unified Host Utilitiesと呼ばれるようになりました。


NOTE: 本ドキュメントに記載されているHost UtilitiesまたはLinux Host Utilitiesに関する記述は、Linux Unified Host Utilitiesを指しています。

* このリリースのLinux Unified Host Utilitiesは、サーバプロファイルの設定とRed Hat Enterprise Linux 6および7ホストでのI/Oパフォーマンスの向上を目的とした調整されたパッケージをサポートしています。
* Linux Unified Host Utilities 7.1では、引き続き次のバージョンがサポートされます。
+
** Red Hat Enterprise Linux の場合
** SUSE Linux Enterprise Server
** Oracle Linux の場合
** Oracle VM
** Citrix XenServer
** Veritas の略


* Red Hat Enterprise Linux 6および7には'環境に応じてホスト上に異なるサーバプロファイルを設定するために'tuned-adm'コマンドを使用した調整済みパッケージが用意されています
+
** これには、エンタープライズストレージアレイのLUNを使用する構成向けのエンタープライズストレージプロファイルも含まれます。Red Hat Enterprise Linuxの仮想ゲストプロファイルをゲスト仮想マシンとして使用することもできます。これらの調整済みパッケージを使用することで、ONTAP のスループットとレイテンシが大幅に向上します。





NOTE: ネットアップは、最初のリリース後も引き続きHost Utilitiesを使用して機能のサポートを追加します。サポートされている機能および追加された新機能の最新情報については、を参照してください link:https://mysupport.netapp.com/matrix/imt.jsp?components=65623;64703;&solution=1&isHWU&src=IMT["NetApp Interoperability Matrix Tool で確認できます"^]。



== 新機能と拡張された機能

リリースノートは、新しい情報が提供されるたびに製品リリースごとに更新されます。



=== 7.1の機能強化

* このリリースでは、次の機能がサポートされます。
+
** SUSE Linux Enterprise Server 15シリーズ
** Oracle VM 3.2シリーズ
** Oracle Linux 6および7シリーズ
** Red Hat Enterprise Linux 6および7シリーズ
** SUSE Linux Enterprise Server 11 SP4
** KVMおよびXen、RHEV 6.4および6.5
** Citrix XenServerのパラメータ


* EmulexおよびQlogic製の32GBファイバチャネルアダプタのサポートが追加されました。
* SLES12SP1、OL7.2、RHEL7.2、およびRHEL 6.8での「sanlun lun show -p geting] SIGABRT」を修正します。
* Red Hat Linux 6.8、Oracle Linux 6.8、XenServer 7.0、Oracle VM 3.3シリーズ、Oracle VM 3.4シリーズのオペレーティングシステムのサポートを拡張しました。




== 既知の問題および制限

[cols="10, 30"]
|===
| NetApp バグ ID | 説明 


| 1457017 | 「sanlun」インストールでは、「libdevmapper-so」および「libnl.so」ライブラリに関連する警告メッセージが表示されます。これらの警告は、「sanlun」キットの機能には影響しません。 
|===
link:https://mysupport.netapp.com/site/bugs-online/product["NetApp Bugs Online では"] 既知の問題の詳細情報を提供します。可能な場合は、推奨される対処方法も示します。

使用するキーワードの組み合わせとバグの種類には、次のものがあります。

* FCP - Linux
* iSCSI–Linux


を参照してください link:https://docs.netapp.com/us-en/ontap-sanhost/index.html["ONTAP SANホスト構成のドキュメント"] ホストOSの設定と構成の詳細については、を参照してください。



== SANホスト構成のドキュメントについて

には、SAN Host Utilitiesのマニュアルが含まれています link:https://docs.netapp.com/us-en/ontap-sanhost/index.html["ONTAP SANホスト構成のドキュメント"]。ONTAP SANホストの構成に関するドキュメントは、SANホストの現在のすべてのリリースをカバーしており、これまでのものは累積的ですリリース間の機能の違いは、コンテキストに基づいて示されます。



=== 追加情報



==== Linuxカーネルにバンドルされているドライバを使用する場合に推奨されるデフォルト値

Linuxカーネルにバンドルされているネイティブの受信トレイドライバを使用するFC環境をセットアップするときは、ドライバのデフォルト値を使用できます。iSCSI解決策 ソフトウェアを使用するiSCSI環境では、使用するOSのバージョンに応じて、推奨される特定の値を手動で設定する必要があります。



== 製品マニュアルとその他の情報の参照先

ネットアップのすべての製品のマニュアルにアクセスし、ネットアップ社内サイトの製品ドキュメントページで、テクニカルレポートやホワイトペーパーなど、製品に関するその他の情報を参照できます。

* ONTAP ストレージ・システムの構成と管理*

* 。 link:https://docs.netapp.com/us-en/ontap/setup-upgrade/index.html["『ONTAP ソフトウェアセットアップガイド』"^] ONTAP のバージョンに応じて更新します
* 。 link:https://docs.netapp.com/us-en/ontap/san-management/index.html["『ONTAP SANアドミニストレーションガイド』"^] ONTAP のバージョンに応じて更新します
* 。 link:https://library.netapp.com/ecm/ecm_download_file/ECMLP2492508["ONTAP リリースノート"^] ONTAP のバージョンに応じて更新します


* Eシリーズストレージシステムの構成と管理*

* 使用するプロトコルに適した『SANtricity Storage Manager Configuration and Provisioning for Windows Express Guide』を参照してください
* 使用しているオペレーティングシステム、プロトコル、およびバージョンのSANtricity に対応した『SANtricity Storage Manager構成およびプロビジョニングエクスプレスガイド』
* 使用しているSANtricity のバージョンに固有のSANtricity Storage Managerソフトウェアインストールリファレンス。
* 使用しているSANtricity バージョンに対応した『SANtricity ストレージマネージャマルチパスドライバガイド』。
* 使用しているSANtricity のバージョンに対応した『SANtricity ストレージマネージャリリースノート』。


にアクセスします link:https://docs.netapp.com/us-en/e-series/getting-started/index.html["E シリーズのドキュメント"] をクリックして、SANtricity 関連ドキュメントを参照してください
