---
sidebar: sidebar 
permalink: hu_luhu_71.html 
keywords: host utilities, unified, oracle, linux, 7.1, netapp, ontap 
summary: Linux Host Utilities 7.1とONTAPの使用方法について説明します。 
---
= Linux Host Utilities 7.1のインストール
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Linux Host Utilitiesは、Linuxホストに接続されているONTAPストレージの管理に役立ちます。NetAppでは、Linux Host Utilitiesのインストールを強く推奨していますが、必須ではありません。ユーティリティを使用しても、 Linux ホストの設定は変更されません。管理機能が向上し、ネットアップのカスタマーサポートが設定に関する情報を収集できるようになります。

次のLinuxディストリビューションがサポートされています。

* Red Hat Enterprise Linux の場合
* SUSE Linux Enterprise Server
* Oracle Linux の場合
* Oracle VM
* Citrix XenServer


.開始する前に
NetApp Linux Host Utilitiesソフトウェアパッケージは、に32ビットまたは64ビットの.rpmファイル形式で提供されていlink:https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/7.1/downloads["ネットアップサポートサイト"^]ます。

* 安定した運用を実現するために、 iSCSI 、 FC 、または FCoE の構成全体がサポートされることを確認する必要があります。
+
を使用して構成を確認できますlink:https://imt.netapp.com/matrix/#welcome["Interoperability Matrix Tool"^]。

* ベンダーのサポートサイトで入手可能なホストバスアダプタ（HBA）管理パッケージをインストールする必要があります。
+
管理ソフトウェアを使用すると、SAN ToolkitコマンドでFC HBAに関する情報（WWPNなど）を収集できます。コマンドが機能するためには `sanlun fcp show adapter`、次のパッケージが正しくインストールされていることを確認します。

+
** Marvell QLogic HBA–QConvergeConsole CLI
** Broadcom Emulex HBA - OneCommand ManagerコアアプリケーションCLI
** Marvell Brocade HBA–BrocadeコマンドユーティリティCLI


* 各Linuxディストリビューションで利用可能なRPMパッケージ「libhbaapi」と「libhbalinux」は、ホストOSにインストールする必要があります。



NOTE: Linux Host Utilitiesソフトウェアは、NVMe over Fibre Channel（NVMe/FC）およびNVMe over TCP（NVMe/TCP）のホストプロトコルをサポートしていません。

.手順
. Linux Host Utilitiesのバージョンが現在インストールされている場合は、次のコマンドを使用して削除します。
+
[source, cli]
----
rpm -e netapp_linux_unified_host_utilities-7-1
----
+
以前のバージョンのLinux Host Utilitiesの場合は、ホストユーティリティソフトウェアがインストールされているディレクトリに移動し、uninstallコマンドを入力してインストールされているパッケージを削除します。

. からホストに32ビットまたは64ビットのLinux Host Utilitiesソフトウェアパッケージをダウンロードしますlink:https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/7.1/downloads["ネットアップサポートサイト"^]。
. ソフトウェアパッケージをダウンロードしたディレクトリに移動し、次のコマンドを使用してインストールします。
+
[source, cli]
----
rpm -ivh netapp_linux_unified_host_utilities-7-1.x86_xx.rpm
----
+
[listing]
----
Verifying...                          ################################# [100%]
Preparing...                          ################################# [100%]
Updating / installing...
   1:netapp_linux_unified_host_utiliti################################# [100%]
----
. インストールを確認します。
+
[source, cli]
----
sanlun version
----
+
[listing]
----
sanlun version 7.1.386.1644
----




== Linuxカーネルでの推奨ドライバ設定

Linuxカーネルにバンドルされている標準の受信トレイドライバを使用するFC環境を設定する場合は、ドライバのデフォルト値を使用できます。



== SAN ツールキット

Linux Host Utilitiesは、Linuxホストにコマンドラインツールキットを提供するNetAppホストソフトウェアです。

このツールキットは、 NetApp Host Utilities パッケージをインストールすると自動的にインストールされます。このキットには 'lun ユーティリティが含まれており 'LUN と HBA の管理に役立ちます「 anlun 」コマンドは、ホストにマッピングされた LUN 、マルチパス、およびイニシエータグループの作成に必要な情報を返します。

.例
次の例では 'lun lun lun show コマンドは LUN 情報を返します

[source, cli]
----
# sanlun lun show all
----
出力例：

[listing]
----
controller(7mode/E-Series)/            device     host               lun
vserver(cDOT/FlashRay)   lun-pathname  filename   adapter  protocol  size    Product
------------------------------------------------------------------------------------
data_vserver          /vol/vol1/lun1   /dev/sdb   host16   FCP       120.0g  cDOT
data_vserver          /vol/vol1/lun1   /dev/sdc   host15   FCP       120.0g  cDOT
data_vserver          /vol/vol2/lun2   /dev/sdd   host16   FCP       120.0g  cDOT
data_vserver          /vol/vol2/lun2   /dev/sde   host15   FCP       120.0g  cDOT
----
[NOTE]
====
* このツールキットは、 Host Utilities のすべての構成とプロトコルで共通です。その結果、一部の内容は 1 つの構成に適用されますが、別の構成には適用されません。未使用のコンポーネントを使用しても、システムのパフォーマンスに影響はありません。
* SAN Toolkitは、Citrix XenServer、Oracle VM、およびRed Hat Enterprise Virtualization Hypervisorではサポートされていません。


====