---
sidebar: sidebar 
permalink: hu_luhu_71_rn.html 
keywords: host utilities, linux, 7.1, netapp, ontap, release, notes, linux 
summary: リリースノート（Linux Host Utilities 7.1） 
---
= Linux Host Utilities 7.1リリースノート
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
このリリースノートでは、ONTAPストレージシステムを使用する特定のホストの設定と管理に関する新機能と拡張機能、既知の問題と制限事項、および重要な注意事項について説明します。

Host Utilitiesでサポートされるオペレーティングシステムのバージョンと更新の具体的な情報については、を参照してlink:https://imt.netapp.com/matrix/#welcome["Interoperability Matrix Tool"^]ください。



== 新機能

Linux Host Utilities 7.1リリースには、次の新機能と機能拡張が含まれています。

* Linux Host Utilitiesは、SANtricityを実行するNetApp Eシリーズストレージシステム、およびONTAPを実行するAFF、FAS、ASAシステムをサポートするため、_Linux Unified Host Utilities_という名前になりました。
+

NOTE: 本ドキュメントに記載されているHost UtilitiesまたはLinux Host Utilitiesに関する記述は、Linux Unified Host Utilitiesを指しています。

* 現在、次のオペレーティングシステムがサポートされています。
+
** SUSE Linux Enterprise Server 15シリーズ
** Oracle VM 3.2シリーズ
** Oracle Linux 6および7シリーズ
** Red Hat Enterprise Linux 6および7シリーズ
** SUSE Linux Enterprise Server 11 SP4
** KVMおよびXen、RHEV 6.4および6.5
** Citrix XenServer


* Red Hat Enterprise Linux（RHEL）6およびRHEL 7ホストでは、サーバプロファイルを設定するためのチューニング済みパッケージがサポートされるようになりました。を使用できます `tuned-adm` 環境に応じて異なるプロファイルを設定するコマンド。たとえば、仮想ゲストプロファイルをゲスト仮想マシンとして使用したり、エンタープライズストレージプロファイルを使用して、エンタープライズストレージアレイのLUNを使用する構成を行うこともできます。これらの調整済みパッケージを使用すると、ONTAPのスループットとレイテンシが向上します。
* Broadcom EmulexおよびMarvell Qlogicから32Gb FCアダプタのサポートが追加されました。



NOTE: ネットアップは、最初のリリース後も引き続きHost Utilitiesを使用して機能のサポートを追加します。サポートされる機能と追加された新機能の最新情報については、を参照してくださいlink:https://imt.netapp.com/matrix/#welcome["Interoperability Matrix Tool"^]。



== コノリリースデカイケツ

SUSE Linux Enterprise Server 12 SP1、OL 7.2、RHEL 7.2、およびRHEL 6.8でコマンドを実行すると一時的に発生するホストOSエラーの問題 `sanlun lun show -p`は、このリリースで修正されています。



== 既知の問題および制限

Linux Host Utilities 7.1リリースには、次の既知の問題および制限事項があります。

[cols="10, 30, 30"]
|===
| NetApp バグ ID | タイトル | 説明 


| 1457017 | 「sanlun」インストールでは、「libdevmapper-so」および「libnl.so」ライブラリに関連する警告メッセージが表示されます。これらの警告は、「sanlun」キットの機能には影響しません。 | SANホストでLinux Host Utilities CLIコマンド「sanlun fcp show adapter -v」を実行すると、コマンドが失敗し、ホストバスアダプタ（HBA）検出に必要なライブラリの依存関係が見つからないことを示すエラーメッセージが表示されます。Refer to NetApp Bugs Online -。
`[root@hostname ~]# sanlun fcp show adapter -v
Unable to locate /usr/lib64/libHBAAPI.so library
Make sure the package installing the library is installed & loaded`link:https://mysupport.netapp.com/site/bugs-online/product/HOSTUTILITIES/1508554["1508554."^] 
|===
link:https://mysupport.netapp.com/site/bugs-online/product["NetApp Bugs Online では"^] 既知の問題の詳細情報を提供します。可能な場合は、推奨される対処方法も示します。
