---
sidebar: sidebar 
permalink: hu_ol_94.html 
keywords: host utilities, oracle, linux, 9.4, netapp, ontap 
summary: ONTAPでOracle Linux 9.4を使用する方法について説明します。 
---
= ONTAPでOracle Linux 9.4を使用
:hardbreaks:
:toclevels: 1P
:allow-uri-read: 
:toclevels: 1P
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ONTAP SANホストの設定を使用して、ONTAPをターゲットとしてOracle Linux 9.4を設定できます。



== Linux Unified Host Utilities をインストールします

NetApp Linux Unified Host Utilitiesソフトウェアパッケージは、から64-bit.rpmファイルとしてダウンロードできますlink:https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/7.1/downloads["ネットアップサポートサイト"^]。

NetAppでは、Linux Unified Host Utilitiesのインストールを強く推奨していますが、必須ではありません。ユーティリティを使用しても、 Linux ホストの設定は変更されません。管理機能が向上し、ネットアップのカスタマーサポートが設定に関する情報を収集できるようになります。

.手順
. から 64 ビットの Linux Unified Host Utilities ソフトウェアパッケージをダウンロードします https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/7.1/downloads["ネットアップサポートサイト"^] ホストに接続します。
. ソフトウェアパッケージをインストールします。
+
「 rpm -ivh 」 NetApp_linux_unified-connect host_utilities-7-1.x86_64 」を参照してください





== SAN Toolkitの使用

NetApp Host Utilitiesパッケージをインストールすると、ツールキットが自動的にインストールされます。このキットには、LUNおよびHost Bus Adapter（HBA；ホストバスアダプタ）の管理に役立つユーティリティが用意されて `sanlun`います。 `sanlun`show volumeGroupコマンドは、ホストにマッピングされているLUNに関する情報、マルチパス、およびイニシエータグループの作成に必要な情報を返します。

次の例では 'lun lun lun show コマンドは LUN 情報を返します

[listing]
----
sanlun lun show all
----
.例を示します
[%collapsible]
====
[listing]
----
controller(7mode/E-Series)/                                  device          host                  lun
vserver(cDOT/FlashRay)        lun-pathname                   filename        adapter    protocol   size    product
--------------------------------------------------------------------------------------------------------
vs_coexistence_147            /vol/fc_vol_2_9/dynamic_lun    /dev/sdcm       host12     FCP        10g     cDOT
vs_coexistence_147            /vol/fc_vol_2_8/dynamic_lun    /dev/sdcl       host12     FCP        10g     cDOT
vs_coexistence_147            /vol/fc_vol_2_7/dynamic_lun    /dev/sdck       host12     FCP        10g     cDOT
vs_coexistence_147            /vol/fc_vol_2_6/dynamic_lun    /dev/sdcj       host12     FCP        10g     cDO

----
====


== SANブートを有効にする

SAN ブートを使用する場合は、構成でサポートされている必要があります。

.開始する前に
を使用しlink:https://mysupport.netapp.com/matrix/imt.jsp?components=91241;&solution=236&isHWU&src=IMT["NetApp Interoperability Matrix Tool で確認できます"^]て、OS、HBA、HBAファームウェア、HBAブートBIOS、およびONTAPのバージョンがサポートされていることを確認します。

.手順
. SAN ブート LUN をホストにマッピングします。
. 複数のパスが使用可能であることを確認します。
+

NOTE: ホストオペレーティングシステムが起動し、パスで実行されると、複数のパスが使用可能になります。

. SAN ブート LUN がマッピングされているポートに対して、サーバ BIOS で SAN ブートを有効にします。
+
HBA BIOS を有効にする方法については、ベンダー固有のマニュアルを参照してください。

. ホストをリブートして、ブートが正常に完了したことを確認します。




== マルチパスを有効にする

Oracle Linux 9.4でマルチパスを使用してONTAP LUNを管理できます。マルチパスを使用するには、 `/etc/multipath.conf`ファイルが存在している必要があります。ファイルが存在しない場合は `/etc/multipath.conf`、touchコマンドを使用して空のゼロバイトファイルを作成できます `/etc/multipath.conf`。Oracle Linux 9.4はONTAP LUNを認識して正しく管理するために必要なすべての設定でコンパイルされているため、ファイルを変更する必要はありません `/etc/multipath.conf`。


NOTE: 1つのLUNに必要なパスは4つまでです。パスが4つ以上あると、ストレージ障害時にパスの問題が発生する可能性があります。



=== オールSANアレイ構成

オールSANアレイ（ASA）構成では、特定のLUNへのすべてのパスが最適化され、アクティブな状態が維持されます。これにより、すべてのパスを同時に経由するI/O処理が行われるため、パフォーマンスが向上します。

.例
次の例は、ONTAP LUNの正しい出力を示しています。

.例を示します
[%collapsible]
====
[listing]
----
multipath -ll
3600a098038303634722b4d59646c4436 dm-28 NETAPP,LUN C-Mode
size=10G features='3 queue_if_no_path pg_init_retries 50' hwhandler='1 alua' wp=rw
|-+- policy='service-time 0' prio=50 status=active
  |- 11:0:7:6   sdbz 68:208  active ready running
  |- 11:0:11:6  sddn 71:80   active ready running
  |- 11:0:15:6  sdfb 129:208 active ready running
  |- 12:0:1:6   sdgp 132:80  active ready running
----
====


=== ASAイカイノコウセイ

ASA以外の構成では、優先度が異なる2つのパスグループが必要です。優先度が高いパスはアクティブ/最適化されます。つまり、アグリゲートが配置されているコントローラによって処理されます。優先度の低いパスはアクティブですが、別のコントローラから提供されるため最適化されていません。最適化されていないパスは、最適化されたパスを使用できない場合にのみ使用されます。

.例
次の例は、 2 つのアクティブ / 最適化パスと 2 つのアクティブ / 非最適化パスを使用する ONTAP LUN に対する正しい出力を表示します。

.例を示します
[%collapsible]
====
[listing]
----
multipath -ll
3600a0980383036347ffb4d59646c4436 dm-28 NETAPP,LUN C-Mode
size=10G features='3 queue_if_no_path pg_init_retries 50' hwhandler='1 alua' wp=rw
|-+- policy='service-time 0' prio=50 status=active
| |- 16:0:6:35 sdwb  69:624  active ready running
| |- 16:0:5:35 sdun  66:752  active ready running
`-+- policy='service-time 0' prio=10 status=enabled
  |- 15:0:0:35 sdaj  66:48   active ready running
  |- 15:0:1:35 sdbx  68:176  active ready running
----
====


== 推奨設定

Oracle Linux 9.4 OSでは、ONTAP LUNが認識され、ASA構成とASA以外の構成の両方について、すべての設定パラメータが自動的に正しく設定されます。次の推奨設定を使用して、ホスト構成のパフォーマンスをさらに最適化できます。

 `multipath.conf`マルチパスデーモンを起動するには、ファイルが存在している必要があります。このファイルが存在しない場合は、コマンドを使用して空のゼロバイトファイルを作成できます `touch /etc/multipath.conf`。

 `multipath.conf`ファイルを初めて作成するときは、次のコマンドを使用してマルチパスサービスを有効にして開始しなければならない場合があります。

[listing]
----
# systemctl enable multipathd
# systemctl start multipathd
----
マルチパスで管理したくないデバイスがある場合や、既存の設定がデフォルトよりも優先される場合を除き、デバイスをファイルに直接追加する必要はあり `multipath.conf`ません。不要なデバイスを除外するには、次の構文をファイルに追加し `multipath.conf`、<DevId>を除外するデバイスのWWID文字列に置き換えます。

[listing]
----
blacklist {
        wwid <DevId>
        devnode "^(ram|raw|loop|fd|md|dm-|sr|scd|st)[0-9]*"
        devnode "^hd[a-z]"
        devnode "^cciss.*"
}
----
次の例では、デバイスのWWIDを特定し、そのデバイスをファイルに追加し `multipath.conf`ます。

.手順
. WWIDを確認します。
+
[listing]
----
/lib/udev/scsi_id -gud /dev/sda
----
+
[listing]
----
360030057024d0730239134810c0cb833
----
+
`sda`は、ブラックリストに追加するローカルSCSIディスクです。

. を追加します `WWID` ブラックリストのスタンザに `/etc/multipath.conf`：
+
[listing]
----
blacklist {
     wwid   360030057024d0730239134810c0cb833
     devnode "^(ram|raw|loop|fd|md|dm-|sr|scd|st)[0-9]*"
     devnode "^hd[a-z]"
     devnode "^cciss.*"
}
----


デフォルト設定を上書きする可能性のあるレガシー設定については、特にdefaultsセクションでファイルを常にチェックする必要があります `/etc/multipath.conf`。

次の表に、 `multipathd`ONTAP LUNの重要なパラメータと必要な値を示します。ホストが他のベンダーのLUNに接続されていて、これらのパラメータのいずれかが無視された場合は `multipath.conf`、ONTAP LUNに特化して適用されるファイルの以降のスタンザで修正する必要があります。そうしないと、 ONTAP LUN が想定どおりに機能しない可能性があります。これらのデフォルト設定を無効にする場合は、影響を十分に理解してから、NetAppやOSベンダーに相談してください。

[cols="2*"]
|===
| パラメータ | 設定 


| detect_prio | はい。 


| DEV_DETION_TMO | 無限大 


| フェイルバック | 即時 


| fast_io_fail_TMO | 5. 


| の機能 | 2 pg_init_retries 50 


| flush_on_last_del | はい。 


| hardware_handler | 0 


| パスの再試行なし | キュー 


| path_checker です | ツール 


| path_grouping_policy | group_by_prio 


| path_selector | サービス時間 0 


| polling _interval （ポーリング間隔） | 5. 


| Prio | ONTAP 


| プロダクト | LUN 


| retain_attached _hw_handler | はい。 


| RR_weight を指定します | 均一（ Uniform ） 


| ユーザーフレンドリ名 | いいえ 


| ベンダー | ネットアップ 
|===
.例
次の例は、上書きされたデフォルトを修正する方法を示しています。この場合は、を参照してください `multipath.conf` ファイルはの値を定義します `path_checker` および `no_path_retry` ONTAP LUNと互換性がありません。他のSANアレイがまだホストに接続されているためにこれらのパラメータを削除できない場合は、デバイススタンザを使用してONTAP LUN専用にこれらのパラメータを修正できます。

.例を示します
[%collapsible]
====
[listing]
----
defaults {
 path_checker readsector0
 no_path_retry fail
 }
devices {
 device {
 vendor "NETAPP"
 product "LUN"
 no_path_retry queue
 path_checker tur
 }
}
----
====

NOTE: Oracle Linux 9.4 Red Hat Compatible Kernel（RHCK）を設定するには、for Red Hat Enterprise Linux（RHEL）9.4を使用しますlink:hu_rhel_94.html#recommended-settings["推奨設定"]。



== KVMの設定

LUNはハイパーバイザーにマッピングされるため、カーネルベースの仮想マシンの設定は必要ありません。



== 既知の問題

ONTAPリリースを使用するOL 9.4のFCホスト構成に関する既知の問題はありません。
