---
sidebar: sidebar 
permalink: hu_ol_64.html 
keywords: host utilities, oracle, linux, 6.4, netapp, ontap 
summary: ONTAP で Oracle Linux 6.4 を使用する方法について説明します 
---
= Oracle Linux 6.4とONTAPの併用
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content




== Linux Unified Host Utilities をインストールします

NetApp Linux Unified Host Utilities ソフトウェアパッケージは、にあります link:https://mysupport.netapp.com/NOW/cgi-bin/software/?product=Host+Utilities+-+SAN&platform=Linux["ネットアップサポートサイト"^] 32 ビットおよび 64 ビットの .rpm ファイル。構成に適したファイルがわからない場合は、を使用してください link:https://mysupport.netapp.com/matrix/#welcome["NetApp Interoperability Matrix Tool で確認できます"^] 必要なものを確認します。

NetAppでは、Linux Unified Host Utilitiesのインストールを強く推奨していますが、必須ではありません。ユーティリティを使用しても、 Linux ホストの設定は変更されません。管理機能が向上し、ネットアップのカスタマーサポートが設定に関する情報を収集できるようになります。

.必要なもの
現在インストールされているバージョンの Linux Unified Host Utilities を使用している場合、このユーティリティをアップグレードするか、削除してから次の手順に従って最新バージョンをインストールしてください。

. から、 32 ビットまたは 64 ビットの Linux Unified Host Utilities ソフトウェアパッケージをダウンロードします link:https://mysupport.netapp.com/NOW/cgi-bin/software/?product=Host+Utilities+-+SAN&platform=Linux["ネットアップサポートサイト"^] サイトからホスト。
. 次のコマンドを使用して、ソフトウェアパッケージをインストールします。
+
「 rpm -ivh 」 NetApp_linux_unified-connect host_utilities-7-1.x86_64 」を参照してください




NOTE: このドキュメントの設定を使用して、に接続するクラウドクライアントを設定できます link:https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/index.html["Cloud Volumes ONTAP"^] および link:https://docs.netapp.com/us-en/cloud-manager-fsx-ontap/index.html["ONTAP 対応の Amazon FSX"^]。



== SAN ツールキット

このツールキットは、 NetApp Host Utilities パッケージをインストールすると自動的にインストールされます。このキットには 'lun ユーティリティが含まれており 'LUN と HBA の管理に役立ちます「 anlun 」コマンドは、ホストにマッピングされた LUN 、マルチパス、およびイニシエータグループの作成に必要な情報を返します。

.例
次の例では 'lun lun lun show コマンドは LUN 情報を返します

[listing]
----
# sanlun lun show all
----
出力例：

[listing]
----
controller(7mode/E-Series)/            device     host               lun
vserver(cDOT/FlashRay)   lun-pathname  filename   adapter  protocol  size    Product
-------------------------------------------------------------------------
data_vserver          /vol/vol1/lun1   /dev/sdb   host16   FCP       120.0g  cDOT
data_vserver          /vol/vol1/lun1   /dev/sdc   host15   FCP       120.0g  cDOT
data_vserver          /vol/vol2/lun2   /dev/sdd   host16   FCP       120.0g  cDOT
data_vserver          /vol/vol2/lun2   /dev/sde   host15   FCP       120.0g  cDOT
----


== SAN ブート中です

.必要なもの
SAN ブートを使用する場合は、構成でサポートされている必要があります。を使用できます https://mysupport.netapp.com/matrix/imt.jsp?components=65623;64703;&solution=1&isHWU&src=IMT["NetApp Interoperability Matrix Tool で確認できます"^] 使用している OS 、 HBA 、 HBA ファームウェア、 HBA ブート BIOS 、および ONTAP のバージョンがサポートされていることを確認します。

.手順
. SAN ブート LUN をホストにマッピングします。
. 複数のパスが使用可能であることを確認します。
+

NOTE: ホストOSが起動してパスで実行されると、複数のパスが使用可能になります。

. SAN ブート LUN がマッピングされているポートに対して、サーバ BIOS で SAN ブートを有効にします。
+
HBA BIOS を有効にする方法については、ベンダー固有のマニュアルを参照してください。

. ホストをリブートしてブートが成功したことを確認します。




== マルチパス

Oracle Linux 6.4 の場合は、 /etc/multipath.conf ファイルが存在している必要がありますが、ファイルに特定の変更を加える必要はありません。Oracle Linux 6.4 は、 ONTAP LUN を認識して正しく管理するために必要なすべての設定でコンパイルされています。ALUA ハンドラを有効にするには、次の手順を実行します。

.手順
. initrd-image のバックアップを作成します。
. ALUA および非 ALUA が機能するようにカーネルに次のパラメータ値を追加します。 `rdloaddriver=scsi_dh_alua`
+
....
kernel /vmlinuz-3.8.13-68.1.2.el6uek.x86_64 ro root=/dev/mapper/vg_ibmx3550m421096-lv_root rd_NO_LUKSrd_LVM_LV=vg_ibmx3550m421096/lv_root LANG=en_US.UTF-8 rd_NO_MDSYSFONT=latarcyrheb-sun16 crashkernel=256M KEYBOARDTYPE=pc KEYTABLE=us rd_LVM_LV=vg_ibmx3550m421096/lv_swap rd_NO_DM rhgb quiet rdloaddriver=scsi_dh_alua
....
. initrd-image を再作成するには、「 m kinitrd` 」コマンドを使用します。Oracle 6x 以降のバージョンでは、次のいずれかを使用します。「 m kinitrd -f /boot/initrd - "uname -r 」 .img uname -r 」またはコマンド「 `d racut -f 」
. ホストをリブートします。
. の出力を確認します `cat /proc/cmdline` 設定が完了したことを確認するためのコマンドです。を使用できます `multipath -ll` コマンドを使用して、ONTAP LUNの設定を確認します。優先順位が異なる 2 つのパスグループが必要です。優先度が高いパスは「アクティブ/最適化」です。つまり、アグリゲートが配置されているコントローラによって処理されます。優先度が低いパスはアクティブですが、別のコントローラから提供されるため最適化されません。最適化されていないパスは、使用可能な最適化されたパスがない場合にのみ使用されます。


.例
次の例は、 2 つのアクティブ / 最適化パスと 2 つのアクティブ / 非最適化パスを使用する ONTAP LUN に対する正しい出力を表示します。

[listing]
----
# multipath -ll
3600a09803831347657244e527766394e dm-5 NETAPP,LUN C-Mode
size=80G features='4 queue_if_no_path pg_init_retries 50 retain_attached_hw_handle' hwhandler='1 alua' wp=rw
|-+- policy='round-robin 0' prio=50 status=active
| |- 0:0:26:37 sdje 8:384   active ready running
| |- 0:0:25:37 sdik 135:64  active ready running
|-+- policy='round-robin 0' prio=10 status=enabled
  |- 0:0:18:37 sdda 70:128  active ready running
  |- 0:0:19:37 sddu 71:192  active ready running
----

NOTE: 1 つの LUN へのパスを余分に使用しないでください。必要なパスは最大 4 つです。8 個を超えるパスがストレージ障害時に原因パスの問題になる可能性があります。



== 推奨設定

Oracle Linux 6.4 OS は、 ONTAP LUN を認識し、すべての構成パラメータを自動的に正しく設定するようにコンパイルされています。

。 `multipath.conf` マルチパスデーモンを起動するにはファイルが存在している必要がありますが、次のコマンドを使用して空のゼロバイトファイルを作成できます。

`touch /etc/multipath.conf`。

このファイルを初めて作成するときに、マルチパスサービスの有効化と開始が必要になる場合があります。

[listing]
----
# chkconfig multipathd on
# /etc/init.d/multipathd start
----
* に直接何も追加する必要はありません `multipath.conf` ファイル。ただし、マルチパスで管理しないデバイスがある場合や、デフォルトよりも優先される既存の設定がある場合を除きます。
* には、次の構文を追加できます `multipath.conf` 不要なデバイスを除外するファイル：
+
** <DevId>を、除外するデバイスのWWID文字列に置き換えます。
+
[listing]
----
blacklist {
        wwid <DevId>
        devnode "^(ram|raw|loop|fd|md|dm-|sr|scd|st)[0-9]*"
        devnode "^hd[a-z]"
        devnode "^cciss.*"
}
----




.例
この例では、 `sda` は、ブラックリストに追加する必要があるローカルSCSIディスクです。

.手順
. 次のコマンドを実行して WWID を特定します。
+
[listing]
----
# /lib/udev/scsi_id -gud /dev/sda
360030057024d0730239134810c0cb833
----
. このWWIDをの「blacklist」スタンザに追加します `/etc/multipath.conf`：
+
[listing]
----
blacklist {
     wwid   360030057024d0730239134810c0cb833
     devnode "^(ram|raw|loop|fd|md|dm-|sr|scd|st)[0-9]*"
     devnode "^hd[a-z]"
     devnode "^cciss.*"
}
----


常にを確認する必要があります `/etc/multipath.conf` レガシー設定用のファイル（特にデフォルトセクション）。デフォルト設定が上書きされる可能性があります。

次の表は、重要なを示しています `multipathd` ONTAP LUNのパラメータと必要な値。ホストが他のベンダーのLUNに接続されていて、これらのパラメータのいずれかが上書きされた場合は、の以降のスタンザで修正する必要があります `multipath.conf` ONTAP LUNに適用されるファイル。そうしないと、 ONTAP LUN が想定どおりに機能しない可能性があります。これらのデフォルト値を無効にする場合は、影響を十分に理解してから、NetAppやOSベンダーに相談してください。

[cols="2*"]
|===
| パラメータ | 設定 


| detect_prio | はい。 


| DEV_DETION_TMO | " 無限 " 


| フェイルバック | 即時 


| fast_io_fail_TMO | 5. 


| の機能 | "3 queue_if_no_path pg_init_retries 50" 


| flush_on_last_del | はい。 


| hardware_handler | 0 


| パスの再試行なし | キュー 


| path_checker です | " tur " 


| path_grouping_policy | 「 group_by_prio 」 


| path_selector | " ラウンドロビン 0" 


| polling _interval （ポーリング間隔） | 5. 


| Prio | ONTAP 


| プロダクト | LUN. * 


| retain_attached _hw_handler | はい。 


| RR_weight を指定します | " 均一 " 


| ユーザーフレンドリ名 | いいえ 


| ベンダー | ネットアップ 
|===
.例
次の例は、オーバーライドされたデフォルトを修正する方法を示しています。この場合、「 multipath.conf 」ファイルは「 path_checker 」および「 detect_prio 」の値を定義しますが、 ONTAP LUN と互換性はありません。ホストに接続された他の SAN アレイが原因でアレイを削除できない場合は、デバイススタンザを使用して ONTAP LUN 専用にパラメータを修正できます。

[listing]
----
defaults {
 path_checker readsector0
 detect_prio no
 }
devices {
 device {
 vendor "NETAPP "
 product "LUN.*"
 path_checker tur
 detect_prio yes
 }
}
----

NOTE: Oracle Linux 6.4 Red Hat Enterprise Kernel （ RHCK ）を設定するには、を使用します link:hu_rhel_64.html#recommended-settings["推奨設定"] Red Hat Enterprise Linux （ RHEL ） 6.4 の場合：



== 既知の問題および制限

[cols="4*"]
|===
| NetApp バグ ID | タイトル | 説明 | Bugzilla ID 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=713555["713555"^] | QLogic アダプタのリセットは、 UEK2/Giveback や reboot などのコントローラ障害時に OL6.4 および OL5.9 で発生します | コントローラの障害（テイクオーバー、ギブバック、リブートなど）が発生すると、 UEK2 （ kernel-uek-2.6.39-400.17.1.el6uek ）または UEK2 （ kernel-uek-2.6.39 400.17.1.el5uek ）を持つ OL6.4 ホストで QLogic アダプタのリセットが発生します。これらのリセットは断続的です。アダプタがリセットされた場合、アダプタがリセットされて dm-multipath でパスのステータスが更新されるまでに I/O 停止が長引いた（ 10 分を超える）可能性があります。/var/log/messages に、このバグがヒットしたときに次のようなメッセージが表示されます。 kernel ： qla2xxx [0000 ： 11 ： 000.0] -8018 ： 0 ： adapter reset issued Nexus=0 ： 2 ： 13 。これはカーネルバージョンで確認されます。 OL6.4 ： kernel-uek-2.6.39-400.17.1.el6uek on OL5.9 ： kernel-uek-2.6.39-400.17.1.el5uek | link:https://bugzilla.oracle.com/bugzilla/show_bug.cgi?id=13999["13999"^] 


| link:htthttps://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=715217["715217"^] | OL6.4 または UEK2 を搭載した OL5.9 ホストでパスリカバリが遅延すると、コントローラまたはファブリックの障害時に I/O の再開が遅延する可能性があります | UEK2 カーネルを搭載した Oracle Linux 6.4 または Oracle Linux 5.9 ホストでコントローラ障害（ストレージフェイルオーバーまたはギブバック、リブートなど）またはファブリック障害（ FC ポートの無効化または有効化）が発生した場合、 DM-Multipath によるパスリカバリには長い時間がかかります（ 4 分）。から 10 分）。パスがアクティブな状態に回復している間に、カーネル： SD 0 ： 0 ： 8 ： 3 ： [SDLT] 結果： hostbyte=dd_error driverbyte=driver_ok 障害イベント中のパス回復に遅延が生じたため、 I/O の再開にも遅延が発生することがあります。OL 6.4 バージョン : device-mapper-1.02.77-9.el6 device-mapper-multipath-0.4.9.9-64.1.el6 kernel-uek-2.6.39-400-17.el6uek OL 5.9 バージョン : device-mapper-1.02.77-9.EL5 device-mapper-multipath-0.4.9.9-6uel1.95uel1.ek カーネル 7.1.ek | link:https://bugzilla.oracle.com/bugzilla/show_bug.cgi?id=14001["14001"^] 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=709911["709911"^] | UEK2 カーネルでの OL6.4 および OL5.9 iSCSI の DM マルチパスは、ストレージ障害後に LUN パスのステータスを更新するのに時間がかかります | Oracle Linux 6 Update4 および Oracle Linux 5 Update9 iSCSI と Unbreakable Enterprise Kernel Release 2 （ UEK2 ）を実行しているシステムでは、ストレージ障害イベント中に DM Multipath （ DMMP ）が Device Mapper （ DM ）デバイス（ LUN ）のパスステータスの更新に約 15 分かかる問題が発生しています。この間隔で「 multipath -ll 」コマンドを実行すると、その DM デバイス（ LUN ）のパスステータスは「 failed ready running 」と表示されます。パスのステータスは、最終的には「 active ready running 」と更新されます。 この問題が認識されるのは、次のバージョンです。 Oracle Linux 6 Update 4 ： UEK2 カーネル： 2.6.39-400.17.1.el6uek.x86_64 マルチパス： device-mapper-multipath-0.4.9.9-64.x86_64 iSCSI ： iscsi-initiator-utils-6.2.0.873-2.0.1.el1.el6.0-1.el6.0-10.x86_64 ： Oracle.862.860.9.61.el5.el7.6.0-multipath 0.7.6.0-10.6.0-10.860.7.63.el6.2.860.6.0-10.860.6.0-10.860.7.9- マルチパス 0.6.0-10.6.2.6-multipath 0.7.9- カーネル 5.el5.el6.2.860.7.9- カーネル 5.el6.2.860.6.2.860.6.2.860.6.2.860.7.9- マルチパス 0.7.9- Linux 1.el7. | link:http://bugzilla.oracle.com/bugzilla/show_bug.cgi?id=13984["13984"^] 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=739909["739909"^] | OL6.x で FC 障害が発生し、 UEK2 を使用している OL5.x ホストでは OL5.x ホストで SG_IO ioctl システムコールが失敗します | UEK2 カーネルを持つ Oracle Linux 6.x ホストと UEK2 カーネルを搭載した Oracle Linux 5.x ホストでは、問題が発生します。マルチパスデバイスの sg_ * コマンドは、アクティブなパスグループ内のすべてのパスをダウンにするファブリック障害の後、 EAGAIN エラーコード（ errno ）で失敗します。この問題は、マルチパスデバイスで I/O が発生していない場合にのみ発生します。以下の例は以下のとおりです。 #sg_inq -v /dev/mapper/3600a098041764937303f436c75324370 inquiry cdb ： 12 00 24 00 ioctl （ SG_IO v3 ） failed with OS_err （ errno ） = 11 inquiry ： Resource temporarily unavailable HDIO_GET ： リソースを一時的に使用できない [11] /dev/mapper/3600a098041764937303f436c75324370# で SCSI 情報の取得に失敗しました。この問題は、 DM-Multipath デバイスで I/O が発生していないときに、他のアクティブなグループへのパスグループのスイッチオーバーがアクティブにならないために発生します。この問題は、 kernel-uek パッケージと device-mapper-multipath パッケージの次のバージョンで確認されています。 OL6.4 バージョン： kernel-uek-2.6.39-400.17.1.el6uek device-mapper-multipath-0.4.9.9-64.0.1.el6 OL5.9 バージョン： kernel-uek-2.6.39-400.1el7.1.el1.el5.0.7.1-device-1.el6.5.7.4-device- | link:https://bugzilla.oracle.com/bugzilla/show_bug.cgi?id=14082["14082"^] 
|===

NOTE: Oracle Linux （ Red Hat 互換カーネル）の既知の問題については、を参照してください link:hu_rhel_64.html#known-problems-and-limitations["既知の問題"] Red Hat Enterprise Linux （ RHEL ） 6.4 の場合：
