---
sidebar: sidebar 
permalink: hu_ol_72.html 
keywords: host utilities, oracle, linux, 7.2, netapp, ontap 
summary: ONTAP で Oracle Linux 7.2 を使用する方法について説明します 
---
= ONTAPでOracle Linux 7.2を使用する
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content




== Linux Unified Host Utilities をインストールします

NetApp Linux Unified Host Utilities ソフトウェアパッケージは、にあります link:https://mysupport.netapp.com/NOW/cgi-bin/software/?product=Host+Utilities+-+SAN&platform=Linux["ネットアップサポートサイト"^] 32 ビットおよび 64 ビットの .rpm ファイル。構成に適したファイルがわからない場合は、を使用してください link:https://mysupport.netapp.com/matrix/#welcome["NetApp Interoperability Matrix Tool で確認できます"^] 必要なものを確認します。

NetAppでは、Linux Unified Host Utilitiesのインストールを強く推奨していますが、必須ではありません。ユーティリティを使用しても、 Linux ホストの設定は変更されません。管理機能が向上し、ネットアップのカスタマーサポートが設定に関する情報を収集できるようになります。

.必要なもの
現在インストールされているバージョンの Linux Unified Host Utilities を使用している場合、このユーティリティをアップグレードするか、削除してから次の手順に従って最新バージョンをインストールしてください。

. から、 32 ビットまたは 64 ビットの Linux Unified Host Utilities ソフトウェアパッケージをダウンロードします link:https://mysupport.netapp.com/NOW/cgi-bin/software/?product=Host+Utilities+-+SAN&platform=Linux["ネットアップサポートサイト"^] サイトからホスト。
. 次のコマンドを使用して、ソフトウェアパッケージをインストールします。
+
「 rpm -ivh 」 NetApp_linux_unified-connect host_utilities-7-1.x86_64 」を参照してください




NOTE: このドキュメントの設定を使用して、に接続するクラウドクライアントを設定できます link:https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/index.html["Cloud Volumes ONTAP"^] および link:https://docs.netapp.com/us-en/cloud-manager-fsx-ontap/index.html["ONTAP 対応の Amazon FSX"^]。



== SAN ツールキット

このツールキットは、 NetApp Host Utilities パッケージをインストールすると自動的にインストールされます。このキットには 'lun ユーティリティが含まれており 'LUN と HBA の管理に役立ちます「 anlun 」コマンドは、ホストにマッピングされた LUN 、マルチパス、およびイニシエータグループの作成に必要な情報を返します。

.例
次の例では 'lun lun lun show コマンドは LUN 情報を返します

[source, cli]
----
# sanlun lun show all
----
出力例：

[listing]
----
controller(7mode/E-Series)/            device     host               lun
vserver(cDOT/FlashRay)   lun-pathname  filename   adapter  protocol  size    Product
-------------------------------------------------------------------------
data_vserver          /vol/vol1/lun1   /dev/sdb   host16   FCP       120.0g  cDOT
data_vserver          /vol/vol1/lun1   /dev/sdc   host15   FCP       120.0g  cDOT
data_vserver          /vol/vol2/lun2   /dev/sdd   host16   FCP       120.0g  cDOT
data_vserver          /vol/vol2/lun2   /dev/sde   host15   FCP       120.0g  cDOT
----


== SAN ブート中です

.必要なもの
SAN ブートを使用する場合は、構成でサポートされている必要があります。を使用できます https://mysupport.netapp.com/matrix/imt.jsp?components=72764;72763;&solution=1&isHWU&src=IMT["NetApp Interoperability Matrix Tool で確認できます"^] 使用している OS 、 HBA 、 HBA ファームウェア、 HBA ブート BIOS 、および ONTAP のバージョンがサポートされていることを確認します。

.手順
. SAN ブート LUN をホストにマッピングします。
. 複数のパスが使用可能であることを確認します。
+

NOTE: ホストOSが起動してパスで実行されると、複数のパスが使用可能になります。

. SAN ブート LUN がマッピングされているポートに対して、サーバ BIOS で SAN ブートを有効にします。
+
HBA BIOS を有効にする方法については、ベンダー固有のマニュアルを参照してください。

. ホストをリブートしてブートが成功したことを確認します。




== マルチパス

Oracle Linux 7.2 は、 Unbreakable Enterprise Kernel （ UEK ） R3 および UEK R4 をサポートしています。OS はデフォルトで UEK R3 カーネルで起動します。

.Oracle Linux 7.2 UEK R3構成
Oracle Linux 7.2 UEK R3 では、空の multipath.conf ファイルを作成します。ALUA の更新が有効な場合と無効な場合、 Oracle Linux 7.2 UEK の設定はデフォルトで自動的に更新されます。ALUA ハンドラを有効にするには、次の手順を実行します。

. initrd-image のバックアップを作成します。
. ALUA および非 ALUA が機能するようにカーネルに次のパラメータ値を追加します。 `rdloaddriver=scsi_dh_alua`
+
....
kernel /vmlinuz-3.8.13-68.1.2.el6uek.x86_64 ro root=/dev/mapper/vg_ibmx3550m421096-lv_root rd_NO_LUKSrd_LVM_LV=vg_ibmx3550m421096/lv_root LANG=en_US.UTF-8 rd_NO_MDSYSFONT=latarcyrheb-sun16 crashkernel=256M KEYBOARDTYPE=pc KEYTABLE=us rd_LVM_LV=vg_ibmx3550m421096/lv_swap rd_NO_DM rhgb quiet rdloaddriver=scsi_dh_alua
....
. 「 dracut-f 」コマンドを使用して initrd-image を再作成します。
. ホストをリブートします。
. 設定が完了したことを確認するために 'cat /proc/cmdline コマンドの出力を確認します


.Oracle Linux 7.2 UEK R4の構成
Oracle Linux 7.2 UEK R4 の場合は /etc/multipath.conf ファイルが存在している必要がありますが、ファイルに特定の変更を加える必要はありません。Oracle Linux 7.2 には、 ONTAP LUN を認識して正しく管理するために必要な設定がすべて含まれています。

を使用できます `multipath -ll` コマンドを使用して、ONTAP LUNの設定を確認します。優先順位が異なる 2 つのパスグループが必要です。優先度が高いパスは「アクティブ/最適化」です。つまり、アグリゲートが配置されているコントローラによって処理されます。優先度が低いパスはアクティブですが、別のコントローラから提供されるため最適化されません。最適化されていないパスは、使用可能な最適化されたパスがない場合にのみ使用されます。

.例
次の例は、 2 つのアクティブ / 最適化パスと 2 つのアクティブ / 非最適化パスを使用する ONTAP LUN に対する正しい出力を表示します。

[listing]
----
# multipath -ll
3600a09803831347657244e527766394e dm-5 NETAPP,LUN C-Mode
size=80G features='4 queue_if_no_path pg_init_retries 50 retain_attached_hw_handle' hwhandler='1 alua' wp=rw
|-+- policy='service-time 0' prio=50 status=active
| |- 11:0:1:0 sdj 8:144 active ready running
| |- 11:0:2:0 sdr 65:16 active ready running
|-+- policy='service-time 0' prio=10 status=enabled
|- 11:0:0:0 sdb 8:i6 active ready running
|- 12:0:0:0 sdz 65:144 active ready running
----

NOTE: 1 つの LUN へのパスを余分に使用しないでください。必要なパスは最大 4 つです。8 個を超えるパスがストレージ障害時に原因パスの問題になる可能性があります。



== 推奨設定

Oracle Linux 7.2 OS は、 ONTAP LUN を認識し、すべての設定パラメータを自動的に正しく設定するようにコンパイルされています。
。 `multipath.conf` マルチパスデーモンを起動するにはファイルが存在している必要がありますが、次のコマンドを使用して空のゼロバイトファイルを作成できます。

`touch /etc/multipath.conf`

このファイルを初めて作成するときは、マルチパスサービスを有効にして開始しなければならない場合があります。

[listing]
----
# systemctl enable multipathd
# systemctl start multipathd
----
* に直接何も追加する必要はありません `multipath.conf` ファイル。マルチパスで管理しないデバイスがある場合、またはデフォルトよりも優先される既存の設定がある場合を除きます。
* 不要なデバイスを除外するには、に次の構文を追加します `multipath.conf` ファイル。
+
[listing]
----
blacklist {
        wwid <DevId>
        devnode "^(ram|raw|loop|fd|md|dm-|sr|scd|st)[0-9]*"
        devnode "^hd[a-z]"
        devnode "^cciss.*"
}
----
+
を交換します `<DevId>` を使用 `WWID` 除外するデバイスの文字列。



.例
この例では、 `sda` は、ブラックリストに追加する必要があるローカルSCSIディスクです。

.手順
. 次のコマンドを実行して WWID を特定します。
+
[listing]
----
# /lib/udev/scsi_id -gud /dev/sda
360030057024d0730239134810c0cb833
----
. を追加します `WWID` ブラックリストのスタンザに `/etc/multipath.conf`：
+
[listing]
----
blacklist {
     wwid   360030057024d0730239134810c0cb833
     devnode "^(ram|raw|loop|fd|md|dm-|sr|scd|st)[0-9]*"
     devnode "^hd[a-z]"
     devnode "^cciss.*"
}
----


常にを確認する必要があります `/etc/multipath.conf` レガシー設定用のファイル（特にデフォルトセクション）。デフォルト設定が上書きされる可能性があります。

次の表は、重要なを示しています `multipathd` ONTAP LUNのパラメータと必要な値。ホストが他のベンダーのLUNに接続されていて、これらのパラメータのいずれかが無効になっている場合は、で後述するstanzasで修正する必要があります `multipath.conf` ONTAP LUNに適用されるファイル。そうしないと、 ONTAP LUN が想定どおりに機能しない可能性があります。これらのデフォルト設定は、影響を完全に理解した場合にのみ、NetAppやOSベンダーに相談して無効にする必要があります。

[cols="2*"]
|===
| パラメータ | 設定 


| detect_prio | はい。 


| DEV_DETION_TMO | " 無限 " 


| フェイルバック | 即時 


| fast_io_fail_TMO | 5. 


| の機能 | "3 queue_if_no_path pg_init_retries 50" 


| flush_on_last_del | はい。 


| hardware_handler | 0 


| path_checker です | " tur " 


| path_grouping_policy | 「 group_by_prio 」 


| path_selector | "service-time 0" 


| polling _interval （ポーリング間隔） | 5. 


| Prio | ONTAP 


| プロダクト | LUN. * 


| retain_attached _hw_handler | はい。 


| RR_weight を指定します | " 均一 " 


| ユーザーフレンドリ名 | いいえ 


| ベンダー | ネットアップ 
|===
.例
次の例は、オーバーライドされたデフォルトを修正する方法を示しています。この場合、「 multipath.conf 」ファイルは「 path_checker 」および「 detect_prio 」の値を定義しますが、 ONTAP LUN と互換性はありません。ホストに接続された他の SAN アレイが原因でアレイを削除できない場合は、デバイススタンザを使用して ONTAP LUN 専用にパラメータを修正できます。

[listing]
----
defaults {
 path_checker readsector0
 detect_prio no
 }
devices {
 device {
 vendor "NETAPP "
 product "LUN.*"
 path_checker tur
 detect_prio yes
 }
}
----

NOTE: Oracle Linux 7.2 Red Hat Enterprise Kernel （ RHCK ）を設定するには、を使用してください link:hu_rhel_72.html#recommended-settings["推奨設定"] Red Hat Enterprise Linux （ RHEL ） 7.2 の場合：



== 既知の問題および制限

Oracle Linux 7.2 では既知の問題はありません。
