---
sidebar: sidebar 
permalink: hu_solaris_62_rn.html 
keywords: host utilities, solaris, 6.2 netapp, ontap 
summary: Solaris Host Utilities 6.2リリースノート 
---
= Solaris Host Utilities 6.2リリースノート
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
このリリースノートでは、新機能と拡張機能、現在のリリースで解決されている問題、既知の問題と制限事項、およびONTAPストレージシステムでの特定のSolarisホストの設定と管理に関する重要な注意事項について説明します。

オペレーティングシステムのバージョンおよびHost Utilitiesがサポートする更新については、を参照してください link:https://mysupport.netapp.com/matrix/imt.jsp?components=85803;&solution=1&isHWU&src=IMT["NetApp Interoperability Matrix Tool で確認できます"^]。



== 既知の問題および制限

特定のホストのパフォーマンスに影響する可能性がある次の既知の問題および制限事項に注意してください。

[cols="3"]
|===
| バグ ID | タイトル | 説明 


| link:https://mysupport.netapp.com/site/bugs-online/product/HOSTUTILITIES/BURT/1385189["1385189"^] | Solaris 11.4 HUK 6.2では、FCドライババインディングの変更が必要です | Solaris 11.4およびHUKの推奨事項：
FCドライバのバインドが `ssd(4D)` 終了： `sd(4D)`。の構成を移動します `ssd.conf` 終了： `sd.conf` Oracle（ドキュメントID 2595926.1）で説明しています。この動作は'新しくインストールされたSolaris 11.4システムと'11.3以前のバージョンからアップグレードされたシステムによって異なります 
|===
link:https://mysupport.netapp.com/site/["NetApp Bugs Online では"^] 既知の問題の詳細情報を提供します。可能な場合は、推奨される対処方法も示します。使用するキーワードの組み合わせとバグの種類には、次のものがあります。

* fcp General：特定のホストに関連付けられていないFCおよびHost Bus Adapter（HBA；ホストバスアダプタ）のバグを表示します。
* FCP - Solarisの場合

