---
sidebar: sidebar 
permalink: hu_solaris_114.html 
keywords: host utilities, solaris, 114, netapp, ontap 
summary: ONTAP で IBM AIX 7.2 または PowerVM VIOS 3.1 を使用する方法について説明します 
---
= Solaris 11.4とONTAPの併用
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ONTAP SANホストの設定を使用して、ONTAPをターゲットとしてSolaris 11.4を設定できます。



== Solaris Host Utilitiesのインストール

Host Utilities ソフトウェアパッケージが格納された圧縮ファイルは、からダウンロードできます https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/6.2/downloads["ネットアップサポートサイト"^]。ファイルをダウンロードしたら、zipファイルを展開して、Host Utilitiesのインストールに必要なソフトウェアパッケージを入手する必要があります。

.手順
. から Host Utilities が含まれている圧縮ファイルのコピーをダウンロードします https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/6.2/downloads["ネットアップサポートサイト"^] をホスト上のディレクトリに移動します。
. ダウンロードを格納しているディレクトリに移動します。
. ファイルを解凍します。
+
次の例は 'SPARC システムのファイルを解凍しますx86-64プラットフォームの場合は、を使用します `x86/x64` パッケージ。

+
「 gunzip NetApp_solaris_host_utilities_6_2N20170913_0304_sparc.tar.gz

. を使用します `tar xvf` コマンドを使用してファイルを展開します。
+
tar xvf NetApp_solaris_host_utilities_6_2N20170913_0304_sparc.tar

. .tarファイルから展開したパッケージをホストに追加します。
+
pkgadd -d NTAPSANTool.pkg

+
パッケージは '/opt/NT2/SANToolkit/bin' ディレクトリに追加されます

+
インストールを完了するには、を使用して環境のホストパラメータ（この場合はOracle Solaris I/OマルチパスまたはMPxIO）を設定する必要があります。 `host_config` コマンドを実行します

+
「 host_config 」コマンドの形式は次のとおりです。

+
/opt/NTAP-SANToolkit/bin/host_config <-setup ><-protocol fcp|iscsi|mixed><-multipath MPxIO | DMP | non>[-noalua] [-MCC 60|90|120]

+
「 host_config 」コマンドでは、次の処理が行われます。

+
** x86およびSPARCシステムのFCおよびSCSIドライバ設定を変更します。
** 両方のMPxIO構成でSCSIタイムアウトを設定
** VID / PID 情報を設定します
** ALUA を有効または無効にします
** MPxIOおよびSCSIドライバで使用されるALUAをx86システムとSPARCシステムの両方で設定します。


. ホストをリブートします。




== SAN ツールキット

NetApp Host Utilitiesパッケージをインストールすると、ツールキットが自動的にインストールされます。このキットには、LUNおよびHost Bus Adapter（HBA；ホストバスアダプタ）の管理に役立つユーティリティが用意されて `sanlun`います。 `sanlun`show volumeGroupコマンドは、ホストにマッピングされているLUNに関する情報、マルチパス、およびイニシエータグループの作成に必要な情報を返します。

.例
次の例では 'lun lun lun show コマンドは LUN 情報を返します

[listing]
----
#sanlun lun show

controller(7mode)/                 device                                            host             lun
vserver(Cmode)     lun-pathname    filename                                         adapter protocol  size  mode
------------------------------------------------------------------------------------------------------
data_vserver       /vol/vol1/lun1  /dev/rdsk/c0t600A098038314362692451465A2F4F39d0s2  qlc1  FCP       60g   C
data_vserver       /vol/vol2/lun2  /dev/rdsk/c0t600A098038314362705D51465A626475d0s2  qlc1  FCP       20g   C
----


== SAN ブート中です

.開始する前に
SAN ブートを使用する場合は、構成でサポートされている必要があります。を使用して、OS、HBA、HBAファームウェアとHBAブートBIOS、およびONTAPのバージョンがサポートされていることを確認できますlink:https://imt.netapp.com/matrix/#welcome["Interoperability Matrix Tool"^]。

SAN ブートとは、 Solaris ホストのブートデバイスとして SAN 接続ディスク（ LUN ）をセットアップするプロセスです。

Solaris MPxIO環境で動作するようにSANブートLUNをセットアップするには、FCプロトコルを使用し、Solaris Host Utilitiesを実行します。SAN ブート LUN のセットアップ方法は、ボリュームマネージャとファイルシステムによって異なります。Solaris MPIO（MicrosoftマルチパスI/O）環境でのSANブートLUNの詳細については、を参照してくださいlink:hu_solaris_62.html["Solaris Host Utilitiesをインストールします"]。



== マルチパス

マルチパスを使用すると、ホストとストレージシステムの間に複数のネットワークパスを設定できます。1 つのパスで障害が発生すると、トラフィックは残りのパスで継続されます。Solaris 11.4では、Oracle Solaris I/OマルチパスまたはMPxIOがデフォルトで有効になっています。テフオルトセツテイ `/kernel/drv/fp.conf` mpxio-disable="no"を変更します。



=== ASAイカイノコウセイ

ASA以外の構成では、優先度が異なる2つのパスグループが必要です。優先度の高いパスは[Active]または[Optimized]になります。つまり、アグリゲートが配置されているコントローラによって処理されます。優先度の低いパスはアクティブですが、別のコントローラから提供されるため最適化されていません。最適化されていないパスは、最適化されたパスを使用できない場合にのみ使用されます。

.例
次の例は、 2 つのアクティブ / 最適化パスと 2 つのアクティブ / 非最適化パスを使用する ONTAP LUN に対する正しい出力を表示します。

パスの優先度は、 OS のネイティブの「 m pathadm show lu <lun>` 」コマンドの各 LUN の「 * Access State * 」セクションに対して表示されます。



=== オールSANアレイ構成

オールSANアレイ（ASA）構成では、特定のLUNへのすべてのパスが最適化され、アクティブな状態が維持されます。これにより、すべてのパスを同時に経由するI/O処理が行われるため、パフォーマンスが向上します。

.例
次の例は、ONTAP LUNの正しい出力を示しています。

「 anlun 」コマンドの出力は、 ASA 構成と非 ASA 構成で同じです。

パスの優先度は、 OS のネイティブの「 m pathadm show lu <lun>` 」コマンドの各 LUN の「 * Access State * 」セクションに対して表示されます。

[listing]
----
#sanlun lun show -pv sparc-s7-16-49:/vol/solaris_vol_1_0/solaris_lun

                    ONTAP Path: sparc-s7-16-49:/vol/solaris_vol_1_0/solaris_lun
                           LUN: 0
                      LUN Size: 30g
                   Host Device: /dev/rdsk/c0t600A098038314362692451465A2F4F39d0s2
                          Mode: C
            Multipath Provider: Sun Microsystems
              Multipath Policy: Native
----

NOTE: オールSANアレイ（ASA）構成は、SolarisホストでONTAP 9.8以降でサポートされます。



== 推奨設定

NetAppでは、ONTAP LUNを使用するSolaris 11.4 SPARCおよびx86_64では、次のパラメータ設定を使用することを推奨しています。これらのパラメータの値は Host Utilities で設定します。Solaris 11.4のその他のシステム設定については、OracleのDOC ID：2595926.1を参照してください。

[cols="2*"]
|===
| パラメータ | 価値 


| throttle_max | 8. 


| not_ready 再試行 | 300 


| busy_retries です | 30 


| reset_retries です | 30 


| throttle_min | 2. 


| timeout_retries です | 10. 


| physical_block_size です | 4096 
|===
Solaris OSのすべてのバージョン(Solaris 10.xおよびSolaris 11.xを含む)は'Solaris HUK 6.2をサポートします

* Solaris 11.4では、FCドライバのバインドが `ssd` 終了： `sd`。次の構成ファイルは、HUK 6.2のインストールプロセス中に部分的に更新されます。
+
** `/kernel/drv/sd.conf`
** `/etc/driver/drv/scsi_vhci.conf`


* Solaris 11.3の場合、FCドライババインドでは次のように使用されます。 `ssd`。次の構成ファイルは、HUK 6.2のインストールプロセス中に部分的に更新されます。
+
** `/kernel/drv/ssd.conf`
** `/etc/driver/drv/scsi_vhci.conf`


* Solaris 10.xの場合、次の構成ファイルはHUK 6.2のインストールプロセスで完全に更新されます。
+
** `/kernel/drv/sd.conf`
** `/kernel/drv/ssd.conf`
** `/kernel/drv/scsi_vhci.conf`




設定の問題を解決するには、ナレッジベースの記事を参照してください。 link:https://kb.netapp.com/onprem/ontap/da/SAN/What_are_the_Solaris_Host_recommendations_for_Supporting_HUK_6.2["HUK 6.2をサポートするためのSolarisホストの推奨事項"^]。

NetAppでは、NetApp LUNを使用してzpoolで4KBのアライメントされたI/Oを成功させるために、次のことを推奨しています。

* 最新のSolaris OSを実行していることを確認し、4KBのI/OサイズのアライメントをサポートするすべてのSolaris機能が利用可能であることを確認します。
* Solaris 10 Update 11に最新のカーネルパッチがインストールされ、Solaris 11.4に最新のSupport Repository Update (SRU)がインストールされていることを確認します。
* NetApp論理ユニットには、次のものが必要です。 `lun/host-type` として `Solaris` LUNのサイズに関係なく。




=== MetroCluster の推奨設定

デフォルトでは、LUNへのすべてのパスが失われると、Solaris OSは* 20s *以降でI/O処理を実行できません。これはによって制御されます `fcp_offline_delay` パラメータのデフォルト値 `fcp_offline_delay` は、標準のONTAP クラスタに適しています。ただし、MetroCluster 構成ではの値です `fcp_offline_delay` 計画外のフェイルオーバーを含む処理中にI/Oがタイムアウトしないように、* 120S *に増やす必要があります。追加情報 およびデフォルト設定の推奨される変更については、ナレッジベースの記事を参照してください https://kb.netapp.com/onprem/ontap/metrocluster/Solaris_host_support_considerations_in_a_MetroCluster_configuration["MetroCluster 構成での Solaris ホストのサポートに関する考慮事項"^]。



== Oracle Solarisの仮想化

* Solaris の仮想化オプションには 'Solaris 論理ドメイン (LDoms または Oracle VM Server for SPARC) 'Solaris 動的ドメイン 'Solaris ゾーン 'Solaris コンテナなどがありますこれらのテクノロジは、さまざまなアーキテクチャをベースにしているにもかかわらず、一般的に「Oracle仮想マシン」というブランド名に変更されています。
* 場合によっては ' 特定の Solaris 論理ドメイン内の Solaris コンテナなど ' 複数のオプションを同時に使用できます
* NetAppでは通常、これらの仮想化テクノロジの使用がサポートされます。この場合、構成全体がOracleでサポートされ、LUNに直接アクセスできるパーティションがサポートされる構成のに記載されています。link:https://imt.netapp.com/matrix/#welcome["Interoperability Matrix Tool"^]これには、ルートコンテナ、LDOM I/Oドメイン、NPIVを使用してLUNにアクセスするLDOMが含まれます。
* などの仮想ストレージリソースのみを使用するパーティションまたは仮想マシンに `vdsk`は、NetApp LUNに直接アクセスできないため、特定の条件は必要ありません。基盤となるLUN（LDOM I/Oドメインなど）に直接アクセスできるパーティションまたは仮想マシンだけをに配置する必要がありますlink:https://imt.netapp.com/matrix/#welcome["Interoperability Matrix Tool"^]。




=== 仮想化の推奨設定

LDOM 内で LUN が仮想ディスクデバイスとして使用されている場合、 LUN のソースは仮想化によってマスクされ、 LDOM はブロックサイズを適切に検出しません。この問題を回避するには、_oracleバグ15824910_および `vdc.conf` 仮想ディスクのブロックサイズをに設定するファイルを作成する必要があります。 `4096`。詳細については、Oracle DOC:2157669.1を参照してください。

パッチを確認するには、次の手順を実行します。

.手順
. zpool を作成します。
. を実行します `zdb -C` zpoolに対して実行し、* ashift *の値が `12`。
+
* ashift *の値が次の値でない場合 `12`正しいパッチがインストールされていることを確認し、 `vdc.conf`。

+
「* ashift *」に値が表示されるまで先に進まないでください。 `12`。




NOTE: Oracle バグ 15824910 の各種バージョンの Solaris に対するパッチが用意されています。最適なカーネル・パッチを決定するためにサポートが必要な場合は、 Oracle にお問い合わせください。



== SnapMirrorアクティブな同期の推奨設定

SnapMirrorアクティブ同期環境で計画外サイトフェイルオーバースイッチオーバーが発生した場合にSolarisクライアントアプリケーションが無停止であることを確認するには、Solaris 11.4ホストで次の設定を行う必要があります。この設定は、フェールオーバーモジュールよりも優先されます `f_tpgs` 矛盾を検出するコードパスが実行されないようにします。


NOTE: ONTAP 9.9.1以降では、Solaris 11.4ホストでSnapMirrorのアクティブな同期設定がサポートされます。

指示に従って、オーバーライドパラメータを設定します。

.手順
. 構成ファイルを作成します `/etc/driver/drv/scsi_vhci.conf` ネットアップストレージタイプがホストに接続されている場合は、次のようなエントリが表示されます。
+
[listing]
----
scsi-vhci-failover-override =
"NETAPP  LUN","f_tpgs"
----
. を使用します `devprop` および `mdb` 上書きパラメータが正常に適用されたことを確認するコマンド。
+
`root@host-a:~# devprop-v-n /scsi_vhci -failover-override scsi-vhci -failover-override= NetApp LUN + f_tpgs root@host -a :~# echo "* scsi_vhci_dibling :print-x struct dev_info deive_vdive_vacuct | vdc_info vibl_sig_ info vstruct

+
[listing]
----
svl_lun_wwn = 0xa002a1c8960 "600a098038313477543f524539787938"
svl_fops_name = 0xa00298d69e0 "conf f_tpgs"
----



NOTE: 実行後 `scsi-vhci-failover-override` が適用されました。 `conf` がに追加されました `svl_fops_name`。追加情報およびデフォルト設定の推奨変更については、NetAppナレッジベースの記事を参照してください。 https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/SnapMirror/Solaris_Host_support_recommended_settings_in_SnapMirror_Business_Continuity_(SM-BC)_configuration["SnapMirrorアクティブ同期構成でのSolarisホストサポートの推奨設定"^]。



== 既知の問題

Solaris 11.4 with ONTAPリリースには、次の既知の問題があります。

[cols="4*"]
|===
| NetApp バグ ID | タイトル | 説明 | Oracle ID 


| link:https://mysupport.netapp.com/site/bugs-online/product/HOSTUTILITIES/1362435["1362435"^] | HUK 6.2 および Solaris_11.4 FC ドライババインディングの変更 | Solaris 11.4およびHUKの推奨事項を参照してください。FCドライバのバインドが `ssd (4D)` 終了： `sd (4D)`。既存の構成を `ssd.conf` 終了： `sd.conf` Oracle DOC:2595926.1に記載されています）。この動作は'新しくインストールされたSolaris 11.4システムと'Solaris 11.3以前のバージョンからアップグレードされたシステムによって異なります | （ドキュメント ID 2595926.1 ） 


| link:https://mysupport.netapp.com/site/bugs-online/product/HOSTUTILITIES/1366780["1366780"^] | x86 ArchでEmulex 32G Host Bus Adapter（HBA；ホストバスアダプタ）を使用している場合、Storage Failover（SFO；ストレージフェイルオーバー）ギブバック処理中にSolaris LIF問題が検出されました | x86_64プラットフォームでは、Emulexファームウェアバージョン12.6.x以降でSolaris LIF問題が検出されました。 | SR 3-24746803021 


| link:https://mysupport.netapp.com/site/bugs-online/product/HOSTUTILITIES/1368957["1368957"^] | Solaris 11.x `cfgadm -c configure` エンドツーエンドのEmulex構成でI/Oエラーが発生する | 実行中です `cfgadm -c configure` Emulexのエンドツーエンド構成でI/Oエラーが発生する。これは、ONTAP 9.5P17、9.6P14、9.7P13、および9.8P2で修正されています。 | 該当なし 


| link:https://mysupport.netapp.com/site/bugs-online/product/HOSTUTILITIES/1345622["1345622"^] | OSネイティブコマンドを使用したASA / pportを使用したSolarisホストでの異常パスレポート | オールSANアレイ（ASA）を搭載したSolaris 11.4では、パスが断続的に報告される問題が発生することがあります。 | 該当なし 
|===