---
sidebar: sidebar 
permalink: hu_solaris_62.html 
keywords: host utilities, unified, oracle, linux, 7.1, netapp, ontap 
summary: Solaris Host Utilities 6.2とONTAPの使用方法について説明します。 
---
= ONTAPストレージ用のSolaris Host Utilities 6.2のインストール
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Solaris ホスト ユーティリティは、Solaris ホストに接続されたONTAPストレージの管理と、構成データの収集に関するテクニカル サポートに役立ちます。

Solaris ホスト ユーティリティは、複数の Solaris 環境と複数のトランスポート プロトコルをサポートします。主な Solaris ホスト ユーティリティ環境は次のとおりです。

* SPARC プロセッサまたは x86/64 プロセッサを使用するシステム上の MPxIO とファイバ チャネル (FC) または iSCSI プロトコルを備えたネイティブ OS。
* SPARCプロセッサを使用するシステムではFCプロトコルまたはiSCSIプロトコルを使用するVeritas Dynamic Multipathing（DMP）、x86/64プロセッサを使用するシステムではiSCSIプロトコルを使用します。


Solaris Host Utilities 6.2 は、次の Solaris シリーズをサポートします。

* Solaris 11.x
* Solaris 10.x


.開始する前に
iSCSI、FC、または FCoE 構成がサポートされていることを確認します。使用することができますlink:https://imt.netapp.com/matrix/#welcome["Interoperability Matrix Tool"^]設定を確認します。

.手順
. ホストに root としてログインします。
. ホストユーティリティを含む圧縮ファイルのコピーを以下からダウンロードします。link:https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/6.2/downloads["ネットアップサポートサイト"^] Solaris ホスト上のディレクトリに:
+
[role="tabbed-block"]
====
.SPARC CPU
--
[source, cli]
----
netapp_solaris_host_utilities_6_2_sparc.tar.gz
----
--
.x86/x64 CPU
--
[source, cli]
----
netapp_solaris_host_utilities_6_2_amd.tar.gz
----
--
====
. ダウンロードが含まれる Solaris ホストのディレクトリに移動します。
. を使用してファイルを解凍します。 `gunzip` コマンドを実行します
+
[source, cli]
----
gunzip netapp_solaris_host_utilities_6_2_sparc.tar.gz
----
. ファイルを解凍するには、 `tar xvf`指示：
+
[source, cli]
----
tar xvf netapp_solaris_host_utilities_6_2_sparc.tar
----
. tarファイルから抽出したパッケージをホストに追加します
+
[source, cli]
----
pkgadd
----
+
パッケージは '/opt/NT2/SANToolkit/bin' ディレクトリに追加されます

+
次の例では、コマンドを使用し `pkgadd`てSolarisインストールパッケージをインストールします。

+
[source, cli]
----
pkgadd -d ./NTAPSANTool.pkg
----
. 次のいずれかのコマンドを使用して、ツールキットが正常にインストールされたことを確認します。
+
[source, cli]
----
pkginfo
----
+
[source, cli]
----
ls - al
----
+
.出力例を表示
[%collapsible]
====
[listing]
----
# ls -alR /opt/NTAP/SANToolkit
/opt/NTAP/SANToolkit:
total 1038
drwxr-xr-x   3 root     sys            4 Jul 22  2019 .
drwxr-xr-x   3 root     sys            3 Jul 22  2019 ..
drwxr-xr-x   2 root     sys            6 Jul 22  2019 bin
-r-xr-xr-x   1 root     sys       432666 Sep 13  2017 NOTICES.PDF

/opt/NTAP/SANToolkit/bin:
total 7962
drwxr-xr-x   2 root     sys            6 Jul 22  2019 .
drwxr-xr-x   3 root     sys            4 Jul 22  2019 ..
-r-xr-xr-x   1 root     sys      2308252 Sep 13  2017 host_config
-r-xr-xr-x   1 root     sys          995 Sep 13  2017 san_version
-r-xr-xr-x   1 root     sys      1669204 Sep 13  2017 sanlun
-r-xr-xr-x   1 root     sys          677 Sep 13  2017 vidpid.dat

# (cd /usr/share/man/man1; ls -al host_config.1 sanlun.1)
-r-xr-xr-x   1 root     sys        12266 Sep 13  2017 host_config.1
-r-xr-xr-x   1 root     sys         9044 Sep 13  2017 sanlun.1
----
====
. MPxIO または Veritas DMP 環境のホスト パラメータを構成します。
+
[source, cli]
----
/opt/NTAP/SANToolkit/bin/host_config
----
. インストールを確認します。
+
[source, cli]
----
sanlun version
----




== 次の手順

link:hu-solaris-san-toolkit.html["SANツールキットについて学ぶ"] 。
