---
sidebar: sidebar 
permalink: hu_sanhost_index.html 
keywords: san, host, utility, software, netapp 
summary: SAN Host Utilityのリリースに関する最新情報と、ホスト構成に対応したインストール手順について説明します。 
---
= SAN Host Utilitiesの詳細
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
SAN Host Utilityのリリースに関する最新情報と、ホスト構成に対応したインストール手順について説明します。

NetAppサポートサイトでは、複数のSAN Host Utilitiesソフトウェアパッケージを提供しています。NetAppでは、SANホストにSAN Host Utilitiesソフトウェアがある場合、そのソフトウェアを使用することを推奨しています。

AIX、HP-UX、Linux、およびSolaris Host Utilitiesソフトウェアには、コマンドラインツールキットが用意されています。このツールキットは、ONTAP LUNとHost Bus Adapter（HBA；ホストバスアダプタ）の管理に役立ちます。サポートが必要な問題が発生した場合は、NetAppカスタマーサポートでSAN Host Utilitiesを使用して構成に関する情報を収集することもできます。このツールキットは、Host Utilitiesソフトウェアパッケージをインストールすると自動的にインストールされます。

Windows Host Utilitiesを使用すると、WindowsホストコンピュータをNetAppストレージシステムに接続できます。ソフトウェアには、必要なWindowsレジストリとHBAパラメータを設定するインストールプログラムが含まれています。これにより、WindowsホストがONTAPおよびEシリーズプラットフォームに対するストレージシステムの動作を正しく処理できるようになります。


NOTE: インストール後の安定した運用を実現するために、を使用してlink:https://imt.netapp.com/matrix/#welcome["Interoperability Matrix Tool"^]、NVMe over Fabrics（NVMe over TCPおよびNVMe over Fibre Channelを含む）、iSCSI、FC、またはFCoEの構成がホストで完全にサポートされていることを確認します。
