---
sidebar: sidebar 
permalink: hu_veritas_6x.html 
keywords: host utilities, veritas, infoscale, 6.x, netapp, ontap, san, lun, multipathing, iscsi 
summary: VERITAS ONTAP Infosscale 6 シリーズ・リリースの SAN ホスト構成設定に関するガイダンスを提供します 
---
= ONTAPでVeritas Storage Foundation 6 for Linuxを使用
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
FC、FCoE、およびiSCSIプロトコルを使用するRed Hat Enterprise LinuxおよびOracle Linux（Red Hat互換カーネルベース）プラットフォーム用のVeritas Storage Foundation 6シリーズリリースでは、ONTAP SANホスト設定を使用できます。



== Linux Host Utilitiesのインストール

NetApp Linux Host Utilitiesソフトウェアパッケージは、から64-bit.rpmファイルとしてダウンロードできますlink:https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/7.1/downloads["ネットアップサポートサイト"^]。

NetAppでは、Linux Host Utilitiesのインストールを強く推奨していますが、必須ではありません。ユーティリティを使用しても、 Linux ホストの設定は変更されません。管理機能が向上し、ネットアップのカスタマーサポートが設定に関する情報を収集できるようになります。

.手順
. からホストに64ビットLinux Host Utilitiesソフトウェアパッケージをダウンロードします https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/7.1/downloads["ネットアップサポートサイト"^]。
. ソフトウェアパッケージをインストールします。
+
「 rpm -ivh 」 NetApp_linux_unified-connect host_utilities-7-1.x86_64 」を参照してください





== SAN ツールキット

NetApp Host Utilitiesパッケージをインストールすると、ツールキットが自動的にインストールされます。このキットには、LUNおよびHost Bus Adapter（HBA；ホストバスアダプタ）の管理に役立つユーティリティが用意されて `sanlun`います。 `sanlun`show volumeGroupコマンドは、ホストにマッピングされているLUNに関する情報、マルチパス、およびイニシエータグループの作成に必要な情報を返します。

.例
次の図では 'lun show コマンドは LUN 情報を返します

[listing]
----
# sanlun show -p -v SFRAC:/vol/fen1/lun1

              ONTAP Path: SFRAC:/vol/fen1/lun1
                     LUN: 0
                LUN Size: 10g
                 Product: cDOT
                DMP NODE: sfrac0_47
      Multipath Provider: Veritas
----------  ------  ---------  ------  -------------------------------------
Veritas     host    vserver    host:
path        path    path     /dev/   chan:     vserver           major:
state       state   type     node    id:lun    LIF                   minor
----------  ------  ---------  ------  -------------------------------------
enabled     up      active/non-optimized sdea   14:0:1:0   lif_10    128:32
enabled (a) up      active/optimized     sdcj   14:0:0:0   lif_2      69:112
enabled (a) up      active/optimized     sdb    13:0:0:0   lif_1       8:16
enabled     up      active/non-optimized sdas   13:0:1:0   lif_9      66:192
----


== SAN ブート中です

.開始する前に
SAN ブートを使用する場合は、構成でサポートされている必要があります。を使用して、OS、HBA、HBAファームウェアとHBAブートBIOS、およびONTAPのバージョンがサポートされていることを確認できますlink:https://imt.netapp.com/matrix/#welcome["Interoperability Matrix Tool"^]。

Veritas Support Portal （ Product Matrix 、 Platform Lookup 、 HCL Matrix ）を参照して、 SAN ブート構成がサポートされていること、および既知の警告を確認してください。

.手順
. SAN ブート LUN をホストにマッピングします。
. 複数のパスが使用可能であることを確認します。
+

NOTE: ホストOSが起動してパスで実行されると、複数のパスが使用可能になります。

. SAN ブート LUN がマッピングされているポートに対して、サーバ BIOS で SAN ブートを有効にします。
+
HBA BIOS を有効にする方法については、ベンダー固有のマニュアルを参照してください。

. ホストをリブートして、ブートが正常に完了したことを確認します。




== マルチパス

構成がシステム要件を満たしていることを確認する必要があります。詳細については、およびVeritas HCL Matrixを参照して https://imt.netapp.com/matrix/#welcome["Interoperability Matrix Tool"^]ください。

.例
次の例では `vxdmpadm`、コマンドを使用して、VxDMPマルチパスにONTAPターゲットアレイが接続されていることを確認します。

[listing]
----
# vxdmpadm listenclosure
ENCLR_NAME   ENCLR_TYPE  ENCLR_SNO     STATUS      ARRAY_TYPE    LUN_COUNT    FIRMWARE
=====================================================================================
sfrac0       SFRAC       804Xw$PqE52h  CONNECTED   ALUA          43           9800
----
[listing]
----
# vxdmpadm getdmpnode
NAME       STATE    ENCLR-TYPE  PATHS  ENBL  DSBL ENCLR-NAME
===================================================================
sfrac0_47  ENABLED  SFRAC       4      4     0    sfrac0
----
Veritas Dynamic Multipathing （ VxDMP ）を使用すると、ネットアップ LUN を Veritas Multipath Devices として要求するための設定タスクを実行する必要があります。Veritas からネットアップストレージシステムに提供される Array Support Library （ ASL ）と Array Policy Module （ APM ）パッケージをインストールしておく必要があります。Veritas Software Installation では、デフォルトの ASL APM パッケージが製品とともにロードされますが、 Veritas サポートポータルにリストされている最新のサポートされているパッケージを使用することをお勧めします。

.例
次の例は、 Veritas Support Library （ ASL ）および Array Policy Module （ APM ）の設定を表示します。

[listing]
----
# vxdmpadm list dmpnode dmpnodename=sfrac0_47 | grep asl
asl        = libvxnetapp.so
----
[listing]
----
# vxddladm listversion |grep libvxnetapp.so
libvxnetapp.so              vm-7.4-rev-1    6.1

# rpm -qa |grep VRTSaslapm
VRTSaslapm-x.x.x.0000-RHEL8.X86_64
----
[listing]
----
vxddladm listsupport libname=libvxnetapp.so
ATTR_NAME   ATTR_VALUE
=========================================
LIBNAME     libvxnetapp.so
VID         NETAPP
PID         All
ARRAY_TYPE  ALUA, A/A
----


=== ASAイカイノコウセイ

ASA以外の構成では、優先度が異なる2つのパスグループが必要です。優先度の高いパスは[Active]または[Optimized]になります。つまり、アグリゲートが配置されているコントローラによって処理されます。優先度の低いパスはアクティブですが、別のコントローラから提供されるため最適化されていません。最適化されていないパスは、最適化されたパスを使用できない場合にのみ使用されます。

.例
次の例は、 2 つのアクティブ / 最適化パスと 2 つのアクティブ / 非最適化パスを使用する ONTAP LUN に対する正しい出力を表示します。

[listing]
----
# vxdmpadm getsubpaths dmpnodename-sfrac0_47
NAME  STATE[A]   PATH-TYPE[M]   CTLR-NAME   ENCLR-TYPE  ENCLR-NAME  ATTRS  PRIORITY
===================================================================================
sdas  ENABLED     Active/Non-Optimized c13   SFRAC       sfrac0     -      -
sdb   ENABLED(A)  Active/Optimized     c14   SFRAC       sfrac0     -      -
sdcj  ENABLED(A)  Active/Optimized     c14   SFRAC       sfrac0     -      -
sdea  ENABLED     Active/Non-Optimized c14   SFRAC       sfrac0     -      -
----

NOTE: 1つのLUNに必要なパスは4つまでです。パスが4つ以上あると、ストレージ障害時にパスの問題が発生する可能性があります。



=== 推奨設定



==== Veritas Multipath の設定

NetAppでは、ストレージフェイルオーバー処理でシステム構成を最適化するために、次のVeritas VxDMP調整可能なオプションを推奨しています。

[cols="2*"]
|===
| パラメータ | 設定 


| dmp_lun_retry_timeout | 60 


| dmp_path_age | 120 


| dmp_restore_interval の値です | 60 
|===
DMP チューニング可能な値は 'vxdmpadm コマンドを使用して ' 次のようにオンラインで設定します

#vxdmpadm settune dmp_tadate=value

これらの調整可能な値は '#vxdmpadm gettune' を使用して動的に確認できます

.例
次の例は、 SAN ホストの実質的な VxDMP 調整可能な設定を示しています。

[listing]
----
# vxdmpadm gettune

Tunable                    Current Value    Default Value
dmp_cache_open                      on                on
dmp_daemon_count                    10                10
dmp_delayq_interval                 15                15
dmp_display_alua_states             on                on
dmp_fast_recovery                   on                on
dmp_health_time                     60                60
dmp_iostats_state              enabled           enabled
dmp_log_level                        1                 1
dmp_low_impact_probe                on                on
dmp_lun_retry_timeout               60                30
dmp_path_age                       120               300
dmp_pathswitch_blks_shift            9                 9
dmp_probe_idle_lun                  on                on
dmp_probe_threshold                  5                 5
dmp_restore_cycles                  10                10
dmp_restore_interval                60               300
dmp_restore_policy         check_disabled   check_disabled
dmp_restore_state              enabled           enabled
dmp_retry_count                      5                 5
dmp_scsi_timeout                    20                20
dmp_sfg_threshold                    1                 1
dmp_stat_interval                    1                 1
dmp_monitor_ownership               on                on
dmp_monitor_fabric                  on                on
dmp_native_support                 off               off
----


==== プロトコル別の設定

* FC / FCoE のみ：デフォルトのタイムアウト値を使用します。
* iSCSI の場合のみ： 'replacement_timeout' パラメータの値を 120 に設定します
+
iscsi 'replacement_timeout' パラメータは、タイムアウトしたパスまたはセッションが再確立されるまで iSCSI レイヤが待機してからコマンドをすべて失敗させるまでの時間を制御します。iSCSI 構成ファイルでは 'replacement_timeout' の値を 120 に設定することをお勧めします



.例
[listing]
----
# grep replacement_timeout /etc/iscsi/iscsid.conf
node.session.timeo.replacement_timeout = 120
----


==== OS プラットフォーム別の設定

Red Hat Enterprise Linux 7 および 8 シリーズでは ' ストレージ・フェイルオーバー・シナリオで Veritas Infosscale 環境をサポートするために 'udev rport' 値を設定する必要がありますファイル /etc/udev/rules.d/ 40-rport.rules` を次のファイル内容で作成します

[listing]
----
# cat /etc/udev/rules.d/40-rport.rules
KERNEL=="rport-*", SUBSYSTEM=="fc_remote_ports", ACTION=="add", RUN+=/bin/sh -c 'echo 20 > /sys/class/fc_remote_ports/%k/fast_io_fail_tmo;echo 864000 >/sys/class/fc_remote_ports/%k/dev_loss_tmo'"
----

NOTE: VERITAS 固有のその他の設定については ' 標準の VERITAS Infosscale 製品マニュアルを参照してください



== マルチパス共存

Veritas Infoscale、Linux Native Device Mapper、LVM Volume Managerなど、異機種混在のマルチパス環境を使用している場合の構成設定については、Veritas Product Administrationのドキュメントを参照してください。



== 既知の問題

Veritas Storage Foundation 6 for Linux with ONTAPリリースでは、既知の問題はありません。
