---
sidebar: sidebar 
permalink: hu_vsphere_8.html 
keywords: host utilities, veritas, infoscale, 8.x, netapp, ontap, vmware, vspehere 
summary: FC、FCoE、およびiSCSIの各プロトコルを使用するVMware vSphere 8.xリリース用のONTAP SANホスト設定を行うことができます。 
---
= VMware vSphere 8.xとONTAPの併用
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
FC、FCoE、およびiSCSIの各プロトコルを使用するVMware vSphere 8.xリリース用のONTAP SANホスト設定を行うことができます。



== ハイパーバイザーSANブート

.必要なもの
SAN ブートを使用する場合は、構成でサポートされている必要があります。を使用できます https://mysupport.netapp.com/matrix/imt.jsp?components=65623;64703;&solution=1&isHWU&src=IMT["NetApp Interoperability Matrix Tool で確認できます"^] 使用している OS 、 HBA 、 HBA ファームウェア、 HBA ブート BIOS 、および ONTAP のバージョンがサポートされていることを確認します。

.手順
. SAN ブート LUN をホストにマッピングします。
. 複数のパスが使用可能であることを確認します。
+

NOTE: ホストオペレーティングシステムが起動し、パスで実行されると、複数のパスが使用可能になります。

. SAN ブート LUN がマッピングされているポートに対して、サーバ BIOS で SAN ブートを有効にします。
+
HBA BIOS を有効にする方法については、ベンダー固有のマニュアルを参照してください。

. ホストをリブートして、ブートが正常に完了したことを確認します。




== マルチパス

ESXiには、Native Multipathing Plug-in（NMP）と呼ばれる拡張可能なマルチパスモジュールが用意されており、サブプラグイン、ストレージアレイタイププラグイン（SATP）、パス選択プラグイン（PSP）を管理します。デフォルトでは、これらのSATPルールはESXiで使用できます。

NetApp ONTAP ストレージについては、 `VMW_SATP_ALUA` プラグインは、でデフォルトで使用されます `VMW_PSP_RR` パス選択ポリシー（PSP）として使用します。確認するには、次のコマンドを使用します。

[listing]
----
`esxcli storage nmp satp rule list -s VMW_SATP_ALUA`
----
出力例：

[listing]
----
Name           Device  Vendor    Model         Driver  Transport  Options
---------------------------------------------------------------------------------
VMW_SATP_ALUA          LSI       INF-01-00                        reset_on_attempted_reserve  system
VMW_SATP_ALUA          NETAPP                                     reset_on_attempted_reserve  system

Rule Group  Claim Options  Default PSP  PSP Options     Description
------------------------------------------------------------------
tpgs_on        VMW_PSP_MRU                  NetApp E-Series arrays with ALUA support
tpgs_on        VMW_PSP_RR                   NetApp arrays with ALUA support
----


=== ASAイカイノコウセイ

ASA以外の構成では、優先度が異なる2つのパスグループが必要です。優先度が高いパスはアクティブ/最適化されます。つまり、アグリゲートが配置されているコントローラによって処理されます。優先度の低いパスはアクティブですが、別のコントローラから提供されるため最適化されていません。最適化されていないパスは、最適化されたパスを使用できない場合にのみ使用されます。

.例
次の例は、 2 つのアクティブ / 最適化パスと 2 つのアクティブ / 非最適化パスを使用する ONTAP LUN に対する正しい出力を表示します。

[listing]
----
# esxcli storage nmp device list -d naa.600a0980383148693724545244395855
----
出力例：

[listing]
----
naa.600a0980383148693724545244395855
   Device Display Name: NETAPP Fibre Channel Disk (naa.600a0980383148693724545244395855)
   Storage Array Type: VMW_SATP_ALUA
   Storage Array Type Device Config: {implicit_support=on; explicit_support=off; explicit_allow=on; alua_followover=on; action_OnRetryErrors=off; {TPG_id=1000,TPG_state=ANO}{TPG_id=1001,TPG_state=AO}}
   Path Selection Policy: VMW_PSP_RR
   Path Selection Policy Device Config: {policy=rr,iops=1000,bytes=10485760,useANO=0; lastPathIndex=1: NumIOsPending=0,numBytesPending=0}
   Path Selection Policy Device Custom Config:
   Working Paths: vmhba4:C0:T0:L11, vmhba3:C0:T0:L11
   Is USB: false
----
[listing]
----
# esxcli storage nmp path list -d naa.600a0980383148693724545244395855
----
出力例：

[listing, subs="+quotes"]
----
fc.20000024ff7f4a51:21000024ff7f4a51-fc.2009d039ea3ab21f:2003d039ea3ab21f-naa.600a0980383148693724545244395855
   Runtime Name: vmhba4:C0:T0:L11
   Device: naa.600a0980383148693724545244395855
   Device Display Name: NETAPP Fibre Channel Disk (naa.600a0980383148693724545244395855)
   Group State: active
   Array Priority: 0
   Storage Array Type Path Config: {TPG_id=1001,*TPG_state=AO*,RTP_id=4,RTP_health=UP}
   Path Selection Policy Path Config: PSP VMW_PSP_RR does not support path configuration.

fc.20000024ff7f4a50:21000024ff7f4a50-fc.2009d039ea3ab21f:2002d039ea3ab21f-naa.600a0980383148693724545244395855
   Runtime Name: vmhba3:C0:T0:L11
   Device: naa.600a0980383148693724545244395855
   Device Display Name: NETAPP Fibre Channel Disk (naa.600a0980383148693724545244395855)
   Group State: active
   Array Priority: 0
   Storage Array Type Path Config: {TPG_id=1001,*TPG_state=AO*,RTP_id=3,RTP_health=UP}
   Path Selection Policy Path Config: PSP VMW_PSP_RR does not support path configuration.

fc.20000024ff7f4a51:21000024ff7f4a51-fc.2009d039ea3ab21f:2001d039ea3ab21f-naa.600a0980383148693724545244395855
   Runtime Name: vmhba4:C0:T3:L11
   Device: naa.600a0980383148693724545244395855
   Device Display Name: NETAPP Fibre Channel Disk (naa.600a0980383148693724545244395855)
   Group State: active unoptimized
   Array Priority: 0
   Storage Array Type Path Config: {TPG_id=1000,*TPG_state=ANO*,RTP_id=2,RTP_health=UP}
   Path Selection Policy Path Config: PSP VMW_PSP_RR does not support path configuration.

fc.20000024ff7f4a50:21000024ff7f4a50-fc.2009d039ea3ab21f:2000d039ea3ab21f-naa.600a0980383148693724545244395855
   Runtime Name: vmhba3:C0:T3:L11
   Device: naa.600a0980383148693724545244395855
   Device Display Name: NETAPP Fibre Channel Disk (naa.600a0980383148693724545244395855)
   Group State: active unoptimized
   Array Priority: 0
   Storage Array Type Path Config: {TPG_id=1000,*TPG_state=ANO*,RTP_id=1,RTP_health=UP}
   Path Selection Policy Path Config: PSP VMW_PSP_RR does not support path configuration.
----


=== オールSANアレイ構成

オールSANアレイ（ASA）構成では、特定のLUNへのすべてのパスが最適化され、アクティブな状態が維持されます。これにより、すべてのパスを同時に経由するI/O処理が行われるため、パフォーマンスが向上します。

.例
次の例は、ONTAP LUNの正しい出力を示しています。

[listing]
----
esxcli storage nmp device list -d naa.600a098038304759563f4e7837574453
----
出力例：

[listing]
----
naa.600a098038314962485d543078486c7a
   Device Display Name: NETAPP Fibre Channel Disk (naa.600a098038314962485d543078486c7a)
   Storage Array Type: VMW_SATP_ALUA
   Storage Array Type Device Config: {implicit_support=on; explicit_support=off; explicit_allow=on; alua_followover=on; action_OnRetryErrors=off; {TPG_id=1001,TPG_state=AO}{TPG_id=1000,TPG_state=AO}}
   Path Selection Policy: VMW_PSP_RR
   Path Selection Policy Device Config: {policy=rr,iops=1000,bytes=10485760,useANO=0; lastPathIndex=3: NumIOsPending=0,numBytesPending=0}
   Path Selection Policy Device Custom Config:
   Working Paths: vmhba4:C0:T0:L14, vmhba4:C0:T1:L14, vmhba3:C0:T0:L14, vmhba3:C0:T1:L14
   Is USB: false

----
[listing]
----
# esxcli storage nmp path list -d naa.600a098038314962485d543078486c7a
----
出力例：

[listing, subs="+quotes"]
----
fc.200034800d756a75:210034800d756a75-fc.2018d039ea936319:2015d039ea936319-naa.600a098038314962485d543078486c7a
   Runtime Name: vmhba4:C0:T0:L14
   Device: naa.600a098038314962485d543078486c7a
   Device Display Name: NETAPP Fibre Channel Disk (naa.600a098038314962485d543078486c7a)
   Group State: active
   Array Priority: 0
   Storage Array Type Path Config: {TPG_id=1000,*TPG_state=AO*,RTP_id=2,RTP_health=UP}
   Path Selection Policy Path Config: PSP VMW_PSP_RR does not support path configuration.

fc.200034800d756a75:210034800d756a75-fc.2018d039ea936319:2017d039ea936319-naa.600a098038314962485d543078486c7a
   Runtime Name: vmhba4:C0:T1:L14
   Device: naa.600a098038314962485d543078486c7a
   Device Display Name: NETAPP Fibre Channel Disk (naa.600a098038314962485d543078486c7a)
   Group State: active
   Array Priority: 0
   Storage Array Type Path Config: {TPG_id=1001,*TPG_state=AO*,RTP_id=4,RTP_health=UP}
   Path Selection Policy Path Config: PSP VMW_PSP_RR does not support path configuration.

fc.200034800d756a74:210034800d756a74-fc.2018d039ea936319:2014d039ea936319-naa.600a098038314962485d543078486c7a
   Runtime Name: vmhba3:C0:T0:L14
   Device: naa.600a098038314962485d543078486c7a
   Device Display Name: NETAPP Fibre Channel Disk (naa.600a098038314962485d543078486c7a)
   Group State: active
   Array Priority: 0
   Storage Array Type Path Config: {TPG_id=1000,*TPG_state=AO*,RTP_id=1,RTP_health=UP}
   Path Selection Policy Path Config: PSP VMW_PSP_RR does not support path configuration.

fc.200034800d756a74:210034800d756a74-fc.2018d039ea936319:2016d039ea936319-naa.600a098038314962485d543078486c7a
   Runtime Name: vmhba3:C0:T1:L14
   Device: naa.600a098038314962485d543078486c7a
   Device Display Name: NETAPP Fibre Channel Disk (naa.600a098038314962485d543078486c7a)
   Group State: active
   Array Priority: 0
   Storage Array Type Path Config: {TPG_id=1001,*TPG_state=AO*,RTP_id=3,RTP_health=UP}
   Path Selection Policy Path Config: PSP VMW_PSP_RR does not support path configuration.
----


== VVol

仮想ボリューム（VVOL）は、仮想マシン（VM）ディスク、そのSnapshot、および高速クローンに対応するVMwareオブジェクトタイプです。

VMware vSphere 用の ONTAP ツールには VASA Provider for ONTAP が含まれており、 VMware vCenter は VVol ベースのストレージを利用するための統合ポイントを提供します。ONTAP tools Open Virtualization Appliance（OVA）を導入すると、vCenterサーバに自動的に登録され、VASA Providerが有効になります。

vCenter のユーザインターフェイスを使用して VVOL データストアを作成する場合は、 FlexVol をデータストアのバックアップストレージとして作成するように指示されます。vVolデータストア内のVVOLには、ESXiホストがプロトコルエンドポイント（PE）を使用してアクセスします。SAN 環境では、 PE として使用するために、データストア内の各 FlexVol に 4MB の LUN が 1 つ作成されます。SAN PE は管理論理ユニット（ ALU ）です。vVol は、関連する論理ユニット（ SLU ）です。

VVOL を使用する際には、以下をはじめとする、 SAN 環境の標準的な要件とベストプラクティスが適用されます（ただし、これらに限定されません）。

* 使用する SVM ごとに、各ノードに少なくとも 1 つの SAN LIF を作成します。ベストプラクティスとして、ノードごとに 2 つ以上を作成し、必要以上に作成しないことを推奨します。
* あらゆる単一点障害を排除します。複数の仮想スイッチを使用する場合はNICチーミングを使用する異なるネットワークサブネット上の複数のVMkernelネットワークインターフェイスを使用するか、複数の物理スイッチに接続された複数の物理NICを使用してHAとスループットを向上させます。
* ホスト接続に必要に応じて、ゾーニング、VLAN、またはその両方を設定します。
* 必要なすべてのイニシエータが目的のSVMのターゲットLIFにログインしていることを確認します。



NOTE: VASA Provider を有効にするには、 VMware vSphere 用の ONTAP ツールを導入する必要があります。すべてのigroup設定はVASA Providerで管理されるため、VVOL環境でigroupを作成または管理する必要はありません。

現時点で VVOL の設定をデフォルトから変更することは推奨されません。

を参照してください https://mysupport.netapp.com/matrix/imt.jsp?components=65623;64703;&solution=1&isHWU&src=IMT["NetApp Interoperability Matrix Tool で確認できます"^] 特定のバージョンの ONTAP ツール、または使用している vSphere と ONTAP の特定のバージョンの VASA Provider

VVOLのプロビジョニングと管理の詳細については、ONTAP tools for VMware vSphereのドキュメントを参照してください。 link:https://docs.netapp.com/us-en/netapp-solutions/hybrid-cloud/vsphere_ontap_ontap_for_vsphere.html["TR-4597"^]および link:https://www.netapp.com/pdf.html?item=/media/13555-tr4400pdf.pdf["TR-4400"^]。



== 推奨設定



=== ATSロック

VAAI 対応のストレージやアップグレードされた VMFS5 には ATS ロックが必須 * であり、 ONTAP LUN との適切な相互運用性と最適な VMFS 共有ストレージ I/O パフォーマンスを実現するために必要です。ATS ロックの有効化の詳細については、 VMware のドキュメントを参照してください。

[cols="4*"]
|===
| 設定 | デフォルト | ONTAP を推奨します | 説明 


| HardwareAcceleratedLocking | 1. | 1. | Atomic Test and Set （ ATS ）ロックの使用を有効にします 


| ディスク IOPS | 1000 | 1. | IOPS 制限：ラウンドロビン PSP は、デフォルトで 1000 IOPS 制限に設定されます。このデフォルトの場合、 1000 個の I/O 処理が実行されたあとに新しいパスが使用されます。 


| Disk.QFullSampleSize | 0 | 32 | ESXi のスロットリングが開始されるまでの、キューがフルまたはビジーの状態の数。 
|===

NOTE: -- 有効にします `Space-alloc` のVMware vSphereにマッピングされたすべてのLUNに対して設定します `UNMAP` 仕事のために。詳細については、ONTAP のドキュメントを参照してください。



=== ゲスト OS のタイムアウト

推奨されるゲスト OS の調整を使用して、仮想マシンを手動で設定できます。アップデートを調整したら、アップデートを有効にするためにゲストを再起動する必要があります。

* GOS タイムアウト値： *

[cols="2*"]
|===
| ゲスト OS タイプ | タイムアウト 


| Linux のバリエーション | ディスクタイムアウト = 60 


| Windows の場合 | ディスクタイムアウト = 60 


| Solaris の場合 | ディスクタイムアウト = 60 busy retry = 300 not ready retry = 300 reset retry = 30 max throttle = 32 min throttle = 8 
|===


=== vSphereで調整可能なことを検証します

を確認するには、次のコマンドを使用します `HardwareAcceleratedLocking` 設定：

`esxcli system settings  advanced list --option /VMFS3/HardwareAcceleratedLocking`

[listing, subs="+quotes"]
----
   Path: /VMFS3/HardwareAcceleratedLocking
   Type: integer
   Int Value: *1*
   Default Int Value: 1
   Min Value: 0
   Max Value: 1
   String Value:
   Default String Value:
   Valid Characters:
   Description: Enable hardware accelerated VMFS locking (requires compliant hardware). Please see http://kb.vmware.com/kb/2094604 before disabling this option.
----


=== ディスクIOPSの設定を検証します

IOPSの設定を確認するには、次のコマンドを使用します。

`esxcli storage nmp device list -d naa.600a098038304731783f506670553355`

[listing, subs="+quotes"]
----
naa.600a098038304731783f506670553355
   Device Display Name: NETAPP Fibre Channel Disk (naa.600a098038304731783f506670553355)
   Storage Array Type: VMW_SATP_ALUA
   Storage Array Type Device Config: {implicit_support=on; explicit_support=off; explicit_allow=on; alua_followover=on; action_OnRetryErrors=off; {TPG_id=1000,TPG_state=ANO}{TPG_id=1001,TPG_state=AO}}
   Path Selection Policy: VMW_PSP_RR
   Path Selection Policy Device Config: {policy=rr,*iops=1*,bytes=10485760,useANO=0; lastPathIndex=0: NumIOsPending=0,numBytesPending=0}
   Path Selection Policy Device Custom Config:
   Working Paths: vmhba4:C0:T0:L82, vmhba3:C0:T0:L82
   Is USB: false
----


=== QFullSampleSizeを検証します

QFullSampleSizeを確認するには、次のコマンドを使用します。

`esxcli system settings  advanced list --option /Disk/QFullSampleSize`

[listing, subs="+quotes"]
----
   Path: /Disk/QFullSampleSize
   Type: integer
   Int Value: *32*
   Default Int Value: 0
   Min Value: 0
   Max Value: 64
   String Value:
   Default String Value:
   Valid Characters:
   Description: Default I/O samples to monitor for detecting non-transient queue full condition. Should be nonzero to enable queue depth throttling. Device specific QFull options will take precedence over this value if set.
----


== 既知の問題

VMware vSphere 8.x with ONTAPリリースには、次の既知の問題があります。

[cols="10,30,30"]
|===
| NetApp バグ ID | タイトル | 説明 


| link:https://mysupport.netapp.com/site/bugs-online/product/HOSTUTILITIES/1543660["1543660"^] | vNVMeアダプタを使用するLinux VMで[All Paths Down（APD；すべてのパスが停止）]ウィンドウが長くなると、I/Oエラーが発生します  a| 
vSphere 8.x以降を実行していて、仮想NVMe（vNVME）アダプタを使用しているLinux VMでは、vNVMeの再試行処理がデフォルトで無効になっているため、I/Oエラーが発生します。オールパスダウン（APD）時や大量のI/O負荷時に古いカーネルを実行しているLinux VMでの停止を回避するために、VMwareでは、vNVMeの再試行処理を無効にするための調整可能な「VSCSIDisableNvmeRetry」を導入しました。

|===
.関連情報
* link:https://docs.netapp.com/us-en/netapp-solutions/virtualization/vsphere_ontap_ontap_for_vsphere.html["TR-4597 ：『 VMware vSphere with ONTAP 』"^]
* link:https://kb.vmware.com/s/article/2031038["NetApp MetroCluster での VMware vSphere 5.x 、 6.x 、および 7.x のサポート（ 2031038 ）"^]
* link:https://kb.vmware.com/s/article/83370["NetApp ONTAPとNetApp SnapMirrorのアクティブな同期とVMware vSphere Metro Storage Cluster（vMSC）"^]

