---
sidebar: sidebar 
permalink: hu_wuhu_72.html 
keywords: windows, 7.2, host utilities, SAN, windows 
summary: Windows Host Utilitiesには、WindowsホストがONTAPおよびEシリーズプラットフォームのストレージシステムの動作を正しく処理できるように、必要なWindowsレジストリとHBAパラメータを設定するインストールプログラムが含まれています。 
---
= Windows Host Utilities 7.2をインストールする
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Windows Host Utilitiesを使用すると、WindowsホストコンピュータをNetAppストレージシステムに接続できます。

Windows Host Utilitiesは、次のバージョンのWindowsをサポートします。

* Windows 2022
* Windows 2019
* Windows * 2016
* Windows Server 2012 R2の場合
* Windows Server 2012


Windows Host Utilitiesには、WindowsホストがONTAPおよびEシリーズプラットフォームのストレージシステムの動作を正しく処理できるように、必要なWindowsレジストリとHost Bus Adapter（HBA；ホストバスアダプタ）パラメータを設定するインストールプログラムが含まれています。

Host Utilitiesソフトウェアをインストールすると、必要なWindowsレジストリとHBAパラメータがインストーラによって設定されます。

Windows ホストコンピュータには、次のプログラムとファイルがインストールされています。デフォルト・ディレクトリは C ： \Program Files\NetApp\SnapManager \Windows Host Utilities' です。

|===
| プログラム | 目的 


| emulexhba.reg` | トラブルシューティングプログラム。このプログラムは、テクニカルサポート担当者から指示があった場合にのみ実行してください。 


| `\NetAppQCLI\fcconfig.exe` | インストールプログラムがHBAパラメータを設定するために使用します。 


| `\NetAppQCLI\fcconfig.ini` | インストールプログラムがHBAパラメータを設定するために使用します。 


| `\NetAppQCLI\*.*` | インストールプログラムがQLogic FC HBAパラメータを設定するために使用します。 


| 'a_version.exe' | Host UtilitiesとFC HBAのバージョンが表示されます。 
|===
Host Utilitiesは、さまざまなWindowsホスト構成、プロトコル、マルチパスオプションをサポートします。詳細については、を参照して https://mysupport.netapp.com/matrix/["Interoperability Matrix Tool"^]ください。



== ホストとストレージシステムの構成を確認します

Host Utilities をインストールする前に、 Host Utilities のバージョンがホストおよびストレージシステムの構成に対応していることを確認し、ソフトウェアが正しくインストールされるようにする必要があります。

.手順
. でサポートされる構成を確認します http://mysupport.netapp.com/matrix["Interoperability Matrix Tool"^]。
. で、該当するホストに必要なホットフィックスを確認します link:https://docs.netapp.com/us-en/ontap-sanhost/index.html["SANホストのWindowsに関するドキュメント"]。
+

NOTE: 。 link:https://docs.netapp.com/us-en/ontap-sanhost/hu_windows_2022.html["ONTAP で2022にWindowsサーバを使用する"] ドキュメントでは、 link:https://docs.netapp.com/us-en/ontap-sanhost/hu_windows_2022.html#installing-windows-hotfixes["Windowsホットフィックスのインストール"] Windowsサーバ2022の場合：以前のバージョンのWindowsサーバに関連する修正プログラムの情報については、ホスト構成カテゴリのWindowsドキュメントを参照してください。

. iSCSI、FCP、またはNVMe-oFライセンスを追加し、ターゲットサービスを開始します。
+

NOTE: SANtricityストレージマネージャを使用するEシリーズストレージシステムでは、FCプロトコルとiSCSIプロトコルのライセンスは必要ありません。

. ケーブル接続を確認します。
+
を参照してください https://docs.netapp.com/us-en/ontap/san-config/index.html["SAN 構成リファレンス"^] 使用しているバージョンのONTAPまたは https://docs.netapp.com/us-en/e-series/install-hw-cabling/index.html["Eシリーズハードウェアケーブル接続"^] ケーブル接続と構成の詳細については、を参照してください。





== FC HBA およびスイッチを設定します

ストレージシステムへのFC接続用にサポートされる1つ以上のFC Host Bus Adapter（HBA；ホストバスアダプタ）をインストールして設定します。

Windows Host Utilitiesのインストーラでは、必要なFC HBAを設定できます。


CAUTION: HBA設定を手動で変更しないでください。

.手順
. HBAベンダーの指示に従って、サポートされているFC HBAを1つ以上取り付けます。
. サポートされている HBA ドライバと管理ユーティリティを入手し、 HBA ベンダーの指示に従ってインストールします。
. HBAをFCスイッチに接続するか、またはストレージシステムに直接接続します。
. FCスイッチのドキュメントに従って、FCスイッチにゾーンを作成します。
. ONTAP の場合は、WWPNでスイッチをゾーニングします。必ず、ストレージコントローラの物理ポートのWWPNではなく、論理インターフェイス（LIF）のWWPNを使用してください。を参照してください https://docs.netapp.com/us-en/ontap/san-config/index.html["SAN 構成リファレンス"^] 詳細については、ドキュメントを参照してください。




== Host Utilities をインストールする

インストールプログラムを実行すると、 Host Utilities パッケージがインストールされ、 Windows のレジストリと HBA が設定されます。

Windows Host Utilitiesソフトウェアパッケージをインストールするときに、マルチパスのサポートを含めるかどうかを指定する必要があります。次のオプションの入力を求められます。Windows のコマンドプロンプトからサイレントインストール（無人インストール）を実行することもできます。

.マルチパスのサポート
* を選択します `MPIO` Windowsホストまたは仮想マシンからストレージシステムへのパスが複数ある場合。
* を選択します `no MPIO` ストレージシステムへの単一のパスを使用している場合のみ。


Microsoft Multipath I/O（MPIO）は、Windows XPおよびWindows Vistaシステムでは選択できません。これらのゲストオペレーティングシステムではマルチパスI/Oはサポートされていません。Hyper-Vゲストでマルチパスのサポートを選択した場合、raw（パススルー）ディスクはゲストOSに表示されません。ゲストOSではrawディスクまたはMPIOのどちらかを使用できますが、両方を使用することはできません。

Host Utilitiesは対話的にインストールすることも、コマンドラインを使用してインストールすることもできます。新しい Host Utilities インストールパッケージが、 Windows ホストからアクセスできるパスに含まれている必要があります。Host Utilitiesを対話的にインストールするか、Windowsコマンドラインからインストールする手順に従います。

[role="tabbed-block"]
====
.対話型インストール
--
Host Utilities ソフトウェアパッケージを対話的にインストールするには、 Host Utilities のインストールプログラムを実行し、プロンプトに従ってインストールする必要があります。

.手順
. から実行可能ファイルをダウンロードします https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/7.2/downloads["ネットアップサポートサイト"^]。
. 実行ファイルをダウンロードしたディレクトリに移動します。
. を実行します `netapp_windows_host_utilities_7.2_x64` ファイルを作成し、画面の指示に従います。
. プロンプトが表示されたら、 Windows ホストをリブートします。


--
.コマンドラインからのインストール
--
Windowsコマンドプロンプトで該当するコマンドを入力すると、Host Utilitiesのサイレント（無人）インストールを実行できます。インストールが完了すると、システムが自動的にリブートします。

.手順
. Windowsコマンドプロンプトで、次のコマンドを入力します。
+
`m siexec/i installer.msi /quiet multipath={0}[INSTALLDIR=inst_path ]`

+
** `installer` は、の名前です `.msi` 使用しているCPUアーキテクチャ用のファイル。
** マルチパスでは、 MPIO サポートがインストールされているかどうかが指定指定できる値は、noの場合は「0」、yesの場合は「1」です。
** 「 inst_path 」は、 Host Utilities ファイルがインストールされているパスです。デフォルトパスは「 C ： \Program Files\NetApp\Virtual Host Utilities\` 」です。





NOTE: ロギングやその他の機能に関する標準のMicrosoft Installer（MSI）オプションを表示するには、と入力します `msiexec /help` をクリックします。たとえば、などです `msiexec /i install.msi /quiet /l*v <install.log> LOGVERBOSE=1` コマンドはロギング情報を表示します。

--
====