---
sidebar: sidebar 
permalink: hu_wuhu_troubleshoot.html 
keywords: windows, host, utilities, 7.1, hba, fibre, channel, SANtricity, netapp, san, host, e-series, platform 
summary: Windows Host Utilitiesには、WindowsホストがONTAPおよびEシリーズプラットフォームのストレージシステムの動作を正しく処理できるように、必要なWindowsレジストリとHBAパラメータを設定するインストールプログラムが含まれています。 
---
= トラブルシューティングを行う
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
Windows Host Utilitiesの一般的なトラブルシューティングテクニックを使用できます。既知の問題と解決策については、最新のリリースノートを確認してください。

相互運用性の潜在的な問題について調査できるさまざまな領域を次に示します。

* 潜在的な相互運用性の問題を特定するには、ホストオペレーティングシステムソフトウェア、ホストハードウェア、ONTAPソフトウェア、ストレージシステムハードウェアの組み合わせがHost Utilitiesでサポートされていることを確認します。詳細については、を参照してください http://mysupport.netapp.com/matrix["Interoperability Matrix Tool"^]。
* iSCSI構成が正しいことを確認します。
* 再起動後にiSCSI LUNを使用できない場合は、Microsoft iSCSIイニシエータGUIの* Persistent Targets *タブで、ターゲットがpersistentと表示されていることを確認します。
* LUNを使用するアプリケーションの起動時にエラーが表示される場合は、アプリケーションがiSCSIサービスに依存するように設定されていることを確認します。
* ONTAPを実行するストレージコントローラへのFCパスでは、ノードの物理ポートのWWPNではなく、ターゲットLIFのWWPNを使用してFCスイッチがゾーニングされていることを確認します。
* を確認します link:hu_wuhu_71_rn.html["リリースノート"] Windows Host Utilitiesを使用して既知の問題を確認します。このリリースノートには、既知の問題と制限事項が記載されています。
* ドキュメントのトラブルシューティング情報を確認します https://docs.netapp.com/us-en/ontap/san-admin/index.html["ONTAP SANの管理"^]。
* 検索 https://mysupport.netapp.com/site/bugs-online/product["NetApp Bugs Online では"^] を参照してください。
+
** [Advanced Search]の[Bug Type]フィールドで、* iSCSI - Windows *を選択し、* Go *を選択します。Bug Type * FCP-Windows *の検索を再度実行する必要があります。


* システムに関する情報を収集します。
* ホストまたはストレージシステムのコンソールに表示されるエラーメッセージをすべて記録します。
* ホストとストレージシステムのログファイルを収集
* 問題の兆候や、問題が発生する直前にホストまたはストレージシステムに加えた変更を記録します。
* 問題を解決できない場合は、ネットアップのテクニカルサポートにお問い合わせください。

