---
sidebar: sidebar 
permalink: hu_wuhu_71_rn.html 
keywords: host utilities, linux, 7.1, netapp, ontap, release, notes 
summary: Windows Unified Host Utilities 7.1のリリースノート 
---
= 『Windows Unified Host Utilities 7.1 Release Notes』
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


このリリースノートドキュメントには、Windows Unified Host Utilities 7.1リリースの最新情報として、新機能、拡張機能、および既知の問題に関する更新情報が記載されています。このドキュメントは、Windows Host Utilitiesの使用に関する新しい情報が入手可能になると更新されます。



== Windows Unified Host Utilities 7.1リリースの概要

Windows Unified Host Utilitiesを使用すると、Windowsホストコンピュータをネットアップストレージシステムに接続できます。Windows Unified Host Utilitiesには、必要なWindowsレジストリとHBA値を設定するインストールプログラムが含まれています。

Windows Unified Host Utilities 7.1では、引き続き次のバージョンのWindowsがサポートされます。

* Windows Server 2012
* Windows Server 2012 R2の場合
* Windows * 2016
* Windows Server 2019
* Windows 2022



NOTE: ネットアップでは、Host Utilitiesソフトウェアのリリース間で追加コンポーネントを認定しています。システム要件の最新情報については、を参照してください link:https://mysupport.netapp.com/matrix/imt.jsp?components=65623;64703;&solution=1&isHWU&src=IMT["NetApp Interoperability Matrix Tool で確認できます"^]。



== このHost Utilitiesリリースの機能

Windows Unified Host Utilities 7.1では、Eシリーズストレージシステム、ONTAP 9以降のバージョンのサポート、およびiSCSIタイムアウトの強化により、フェイルオーバーの高速化がサポートされます。



== 重要な注意事項

最新リリースのWindows Host Utilitiesを導入する前に、システムの運用に影響する可能性がある問題を特定して解決するのに役立つ情報を確認しておく必要があります。

個々のバグの詳細およびその他のバグ関連ツールについては、を参照してください link:https://mysupport.netapp.com/site/bugs-online/product["NetApp Bugs Online では"^]。



=== 必要な修正プログラムをインストールします

Windows Unified Host Utilitiesのインストールまたはアップグレードを正常に行うために、特定のWindowsホットフィックスをインストールする必要があります。一部のホットフィックスは、Windowsの更新プログラムのコンポーネントです。

を参照してください link:https://docs.netapp.com/us-en/ontap-sanhost/hu_wuhu_71.html["Windows Host Utilitiesのマニュアル"] をクリックしてください。



== 既知の問題

このリリースでは、いくつかの予期しない動作や望ましくない動作の可能性がある動作、およびこれらの動作を回避するための回避策が確認されています。

[cols="30, 30, 20"]
|===
| タイトル | 説明 | 回避策 


| を実行します `linux_gos_timeout-install.sh` スクリプトは、Red Hat Enterprise LinuxまたはSUSE Linux Enterprise Serverを実行するHyper-Vゲストには必要ありません | を実行する必要はなくなりました `linux_gos_timeout-install.sh` デフォルトのタイムアウト設定が使用されているため、Red Hat Enterprise Linux 5、Red Hat Enterprise Linux 6、またはSUSE Linux Enterprise Server 11 Hyper-Vゲストでディスクタイムアウトを変更するスクリプト。。 `linux_gos_timeout-install.sh` 以前のバージョンのHost Utilitiesに含まれていたスクリプトは、Windows Unified Host Utilitiesに含まれなくなりました。Windows Unified Host Utilities 7.1では、デフォルトのディスクタイムアウト設定が使用されています。 | 該当なし 


| IPv4とIPv6が混在したiSCSIセッションは、リブート後に再接続されません | マルチパスI/O（MPIO）構成、またはIPv4とIPv6の両方のエンドポイントを含むセッション（MCS）ごとに複数の接続を設定すると、Windowsホストのリブート後に一部のiSCSIセッションが再接続に失敗することがあります。 | リブート後にすべてのiSCSIパスが戻るようにするには、すべてのIPv4エンドポイントまたはすべてのIPv6を使用します。IPv4とIPv6を混在させないでください。 


| MCSは、iSCSIソフトウェアブートではサポートされません | iSCSIソフトウェアブートを使用して、iSCSI Multiple connections per session（MCS；セッションごとのiSCSI複数接続）を使用している場合、iSCSIブートをリードする接続は保護できません。これにより、ブートLUNとの接続が切断されて、ホストがクラッシュする可能性があります。 | Microsoftでは、iSCSIソフトウェアブートホストのMCSはサポートしていません。MPIOを高可用性解決策 として使用してください。MPIOとMCSの混在はサポートされていません。 
|===
link:https://mysupport.netapp.com/site/bugs-online/product["NetApp Bugs Online では"^] 既知の問題の詳細情報を提供します。可能な場合は、推奨される対処方法も示します。



== SANホスト構成のドキュメントについて

には、SAN Host Utilitiesのマニュアルが含まれています link:https://docs.netapp.com/us-en/ontap-sanhost/index.html["ONTAP SANホスト構成のドキュメント"]。ONTAP SANホストの構成に関するドキュメントは、SANホストの現在のすべてのリリースをカバーしており、これまでのものは累積的ですリリース間の機能の違いは、コンテキストに基づいて示されます。



== 製品マニュアルとその他の情報の参照先

ネットアップのすべての製品のマニュアルにアクセスし、ネットアップ社内サイトの製品ドキュメントページで、テクニカルレポートやホワイトペーパーなど、製品に関するその他の情報を参照できます。

.関連情報
* ONTAP ストレージ・システムの構成と管理*

* 。 link:https://docs.netapp.com/us-en/ontap/setup-upgrade/index.html["『ONTAP ソフトウェアセットアップガイド』"^] ONTAP のバージョンに応じて更新します
* 。 link:https://docs.netapp.com/us-en/ontap/san-management/index.html["『ONTAP SANアドミニストレーションガイド』"^] ONTAP のバージョンに応じて更新します
* 。 link:https://library.netapp.com/ecm/ecm_download_file/ECMLP2492508["ONTAP リリースノート"^] ONTAP のバージョンに応じて更新します


* Eシリーズストレージシステムの構成と管理*

* 使用するプロトコルに適した『SANtricity Storage Manager Configuration and Provisioning for Windows Express Guide』を参照してください
* 使用しているオペレーティングシステム、プロトコル、およびバージョンのSANtricity に対応した『SANtricity Storage Manager構成およびプロビジョニングエクスプレスガイド』
* 使用しているSANtricity のバージョンに固有のSANtricity Storage Managerソフトウェアインストールリファレンス。
* 使用しているSANtricity バージョンに対応した『SANtricity ストレージマネージャマルチパスドライバガイド』。
* 使用しているSANtricity のバージョンに対応した『SANtricity ストレージマネージャリリースノート』。


を参照してください link:https://docs.netapp.com/us-en/e-series/getting-started/index.html["E シリーズのドキュメント"^] をクリックして、SANtricity 関連ドキュメントを参照してください
