---
sidebar: sidebar 
permalink: hu_wuhu_upgrade.html 
keywords: windows, host, utilities, 7.1, hba, fibre, channel, SANtricity, netapp, san, host, e-series, platform 
summary: Windows Host Utilitiesには、WindowsホストがONTAPおよびEシリーズプラットフォームのストレージシステムの動作を正しく処理できるように、必要なWindowsレジストリとHBAパラメータを設定するインストールプログラムが含まれています。 
---
= ONTAPストレージ用のWindowsホストユーティリティのアップグレード
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
インストール手順に従って対話形式で実行するか、Windows コマンドラインを使用して、 ONTAPストレージ構成内の Windows Host Utilities ソフトウェアをアップグレードできます。  Windows ホストがアクセスできるパスに新しい Windows ホスト ユーティリティ インストール ソフトウェアをインストールする必要があります。

[role="tabbed-block"]
====
.対話型アップグレード
--
Host Utilities インストール プログラムを実行し、プロンプトに従って、Windows Host Utilities ソフトウェアを対話型でアップグレードします。

.手順
. 実行ファイルをダウンロードしたディレクトリに移動します。
. 実行ファイルを実行し、画面の指示に従います。
. プロンプトが表示されたら、 Windows ホストをリブートします。
. リブートが完了したら、ホストユーティリティのバージョンを確認します。
+
.. コントロールパネル * を開きます。
.. 「 * Program and features* 」に移動して、ホストユーティリティのバージョンを確認します。




--
.非対話型アップグレード
--
Windows コマンド ラインを使用して、非対話型の Windows Host Utilities ソフトウェア アップグレードを実行します。

.手順
. Windowsコマンドプロンプトで、次のコマンドを入力します。
+
[source, cli]
----
msiexec /i installer.msi /quiet MULTIPATHING= {0 | 1} [INSTALLDIR=inst_path]
----
+
** `installer` は、の名前です `.msi` 使用しているCPUアーキテクチャ用のファイル。
** マルチパスは、MicrosoftマルチパスI/O（MPIO）サポートがインストールされているかどうかを示します。指定できる値は、noの場合は「0」、yesの場合は「1」です。
** 「 inst_path 」は、 Host Utilities ファイルがインストールされているパスです。デフォルトパスは「 C ： \Program Files\NetApp\Virtual Host Utilities\` 」です。





NOTE: ロギングやその他の機能に関する標準のMicrosoft Installer（MSI）オプションを表示するには、と入力します `msiexec /help` をクリックします。たとえば、などです `msiexec /i install.msi /quiet /l*v <install.log> LOGVERBOSE=1` コマンドはロギング情報を表示します。

インストールが完了すると、システムが自動的にリブートします。

--
====