---
sidebar: sidebar 
permalink: nvme-aix.html 
keywords: nvme, linux, rhel, red hat, enterprise, aix, ontap 
summary: ONTAPを使用するAIX用のNVMe/FCホストの設定方法 
---
= ONTAPストレージ用にNVMe-oFを使用してAIXを構成する
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
IBM AIX および Virtual I/O Server (VIOS)/PowerVM ホストは、非対称名前空間アクセス (ANA) を備えた NVMe/FC プロトコルをサポートしています。  ANA は、iSCSI および FCP 環境における非対称論理ユニット アクセス (ALUA) マルチパスに相当します。

サポートされている構成の詳細については、link:https://mysupport.netapp.com/matrix/["Interoperability Matrix Tool（IMT）"^] 。

.このタスクについて
AIX ホストの NVMe-oF ホスト構成では、次のサポートと機能を使用できます。構成プロセスを開始する前に、既知の制限事項も確認する必要があります。

* 利用可能なサポート：
+
** ONTAP 9.13.1 以降では、物理スタックと仮想スタックの両方で SAN ブートをサポートする IBM AIX 7.2 TL5 SP6、AIX 7.3 TL1 SP2、および VIOS 3.1.4.21 に NVMe/FC サポートが追加されました。  SAN ブート サポートの設定の詳細については、IBM のドキュメントを参照してください。
** NVMe/FCは、POWER9およびPower10 IBMサーバでサポートされます。
** NVMe デバイスには、AIX SCSI マルチパス I/O (MPIO) サポート用のホスト ユーティリティなどの個別の PCM (パス コントロール モジュール) は必要ありません。
** VIOS 3.1.4.21では、NetApp（VIOS/PowerVM）による仮想化のサポートが導入されました。これは、Power10 IBMサーバを使用したNPIV（N_PortID Virtualization）ストレージ仮想化モードでのみサポートされます。


* 既知の制限事項：
+
** AIX ホスト上の Qlogic/Marvel 32G FC HBA は NVMe/FC をサポートしていません。
** Power9 IBM サーバーを使用する NVMe/FC デバイスでは、SAN ブートはサポートされません。




.開始する前に
* アダプタファームウェア12.4.257.30以降のバージョンの32Gb FC Emulexアダプタ（EN1A、EN1B、EN1L、EN1M）または64Gb FCアダプタ（EN1N、EN1P）があることを確認します。
* MetroCluster構成を使用している場合はNetApp、AIXオペレーティングシステムによるI/Oタイムアウトの短縮を回避するために、MetroCluster計画外スイッチオーバーイベントをサポートするために、AIX NVMe/FCのデフォルトAPD（All Path Down）時間を変更することを推奨します。追加情報およびデフォルト設定の推奨される変更については、『NetApp Bugs Online - link:https://mysupport.netapp.com/site/bugs-online/product/HOSTUTILITIES/1553249["1553249"^]。
* AIX のバージョンに応じて、AIX ホスト OS の非対称名前空間アクセス遷移タイムアウト (ANATT) はデフォルトで 30 秒または 60 秒になります。ホストの ANATT のデフォルトが 30 秒の場合、すべてのONTAPワークフローが中断されないよう、ANATT を 60 秒に設定する IBM Interim Fix (ifix) を IBM Web サイトからインストールする必要があります。
+
[NOTE]
====
NVMe/FC AIX をサポートするには、AIX OS の GA バージョンに ifix をインストールする必要があります。  VIOS/PowerVM OS では ifix は必要ありません。

関連するifixが以前にインストールされていないAIXバージョンにifixをインストールする必要があります。 `devices.pciex.pciexclass.010802.rte`システム上。以前にインストールされた ifix は、新しいインストールと競合する可能性があります。

====
+
[role="tabbed-block"]
====
.ANATTを60秒に設定する
--
AIX レベル 72-TL5-SP6-2320 および AIX レベル 73-TL1-SP2-2320 リリースのデフォルトの ANATT は 30 秒です。  IBM は、ANATT を 60 秒に設定する ifix を提供しています。  ifix は IBM ケース ID TS018079082 を通じて入手でき、次の AIX リリースにインストールできます。

** AIXレベル72-TL5-SP6-2320の場合は、をインストールします `IJ46710s6a.230509.epkg.Z` パッケージ。
** AIXレベル73-TL1-SP2-2320の場合は、をインストールします `IJ46711s2a.230509.epkg.Z` パッケージ。


--
.デフォルトのANATTは60秒です
--
次の AIX リリースでは、デフォルトの ANATT は 60 秒です。

** AIX レベル 73-TL2-SP3-2446
** AIX レベル 73-TL2-SP2-2420
** AIX レベル 72-TL5-SP8-2420


--
.オプションで、ANATTを120秒に設定します
--
IBM は、ANATT を 120 秒に設定する ifix を提供しています。  ANATT を 120 秒に設定すると、 ONTAPストレージ フェイルオーバー イベント中のパフォーマンスが向上します。  ifix は IBM ケース ID TS012877410 を通じて入手でき、次の AIX リリースにインストールできます。

** AIXレベル73-TL3-SP0-2446の場合は、 `IJ53487s0a.250130.epkg.Z`パッケージ。
** AIXレベル72-TL5-SP9-2446の場合は、 `IJ53445s9a.250130.epkg.Z`パッケージ。


--
====
+
[NOTE]
====
NVMe/FC をサポートする Power9 サーバーの最小サーバー ファームウェア バージョンは FW 950 です。

NVMe/FC をサポートする Power10 サーバーの最小サーバー ファームウェア バージョンは FW 1010 です。

====
+
ifixの管理の詳細については、を参照してください link:http://www-01.ibm.com/support/docview.wss?uid=isg3T1012104["AIXでの暫定修正の管理"^]。





== ステップ1: ホストのマルチパス構成を確認する

AIX OS をインストールすると、NVMe マルチパスに使用される IBM MPIO がデフォルトで有効になります。

.手順
. NVMe マルチパスが有効になっていることを確認します。
+
[source, cli]
----
lsmpio -l hdisk1
----
+
.例を示します
[%collapsible]
====
[listing]
----
name     path_id  status   path_status  parent  connection
hdisk1  8         Enabled  Sel,Opt       nvme12  fcnvme0, 9
hdisk1  9         Enabled  Sel,Non       nvme65  fcnvme1, 9
hdisk1  10        Enabled  Sel,Opt       nvme37  fcnvme1, 9
hdisk1  11        Enabled  Sel,Non       nvme60  fcnvme0, 9
----
====




== ステップ2: NVMe/FCを構成する

VIOS 上の仮想ファイバー チャネル (vFC) では NVMe/FC プロトコル サポートが無効になっているため、VIOS 上の Broadcom/Emulex アダプター用に NVMe/FC を構成する必要があります。  NVMe/FC プロトコル サポートは、物理 FC でデフォルトで有効になっています。

.手順
. link:https://mysupport.netapp.com/matrix/["サポートされているアダプタを使用していることを確認してください"^] 。
. 仮想アダプタのリストを取得します。
+
[source, cli]
----
lsmap -all -npiv
----
+
.例を示します
[%collapsible]
====
[listing]
----
Name          Physloc                            ClntID ClntName       ClntOS
------------- ---------------------------------- ------ -------------- -------
vfchost0      U9105.22A.785DB61-V2-C2                 4 s1022-iop-mcc- AIX
Status:LOGGED_IN
FC name:fcs4                    FC loc code:U78DA.ND0.WZS01UY-P0-C7-T0
Ports logged in:3
Flags:0xea<LOGGED_IN,STRIP_MERGE,SCSI_CLIENT,NVME_CLIENT>
VFC client name:fcs0            VFC client DRC:U9105.22A.785DB61-V4-C2
----
====
. を実行して、アダプタでNVMe/FCプロトコルのサポートを有効にします `ioscli vfcctrl` VIOSでのコマンド：
+
[source, cli]
----
vfcctrl -enable -protocol nvme -vadapter vfchost0
----
+
.出力例
[listing]
----
The "nvme" protocol for "vfchost0" is enabled.
----
. アダプタでサポートが有効になっていることを確認します。
+
[source, cli]
----
lsattr -El vfchost0
----
+
.例を示します
[%collapsible]
====
[listing]
----
alt_site_wwpn       WWPN to use - Only set after migration   False
current_wwpn  0     WWPN to use - Only set after migration   False
enable_nvme   yes   Enable or disable NVME protocol for NPIV True
label               User defined label                       True
limit_intr    false Limit NPIV Interrupt Sources             True
map_port      fcs4  Physical FC Port                         False
num_per_nvme  0     Number of NPIV NVME queues per range     True
num_per_range 0     Number of NPIV SCSI queues per range     True
----
====
. すべてのアダプタに対してNVMe/FCプロトコルを有効にします。
+
.. を変更します `dflt_enabl_nvme` の属性値 `viosnpiv0` 疑似デバイスをに送信します `yes`。
.. を設定します `enable_nvme` 属性値をに設定します `yes` すべてのVFCホストデバイスに対して。
+
[source, cli]
----
chdev -l viosnpiv0 -a dflt_enabl_nvme=yes
----
+
[source, cli]
----
lsattr -El viosnpiv0
----
+
.例を示します
[%collapsible]
====
[listing]
----
bufs_per_cmd    10  NPIV Number of local bufs per cmd                    True
dflt_enabl_nvme yes Default NVME Protocol setting for a new NPIV adapter True
num_local_cmds  5   NPIV Number of local cmds per channel                True
num_per_nvme    8   NPIV Number of NVME queues per range                 True
num_per_range   8   NPIV Number of SCSI queues per range                 True
secure_va_info  no  NPIV Secure Virtual Adapter Information              True
----
====


. を変更して、選択したアダプタのNVMe/FCプロトコルを有効にします `enable_nvme` へのVFCホストデバイス属性の値 `yes`。
. 確認します `FC-NVMe Protocol Device` がサーバに作成されました：
+
[source, cli]
----
lsdev |grep fcnvme
----
+
.出力例
[listing]
----
fcnvme0       Available 00-00-02    FC-NVMe Protocol Device
fcnvme1       Available 00-01-02    FC-NVMe Protocol Device
----
. サーバからホストのNQNを記録します。
+
[source, cli]
----
lsattr -El fcnvme0
----
+
.例を示します
[%collapsible]
====
[listing]
----
attach     switch                                                               How this adapter is connected  False
autoconfig available                                                            Configuration State            True
host_nqn   nqn.2014-08.org.nvmexpress:uuid:64e039bd-27d2-421c-858d-8a378dec31e8 Host NQN (NVMe Qualified Name) True
----
====
+
[source, cli]
----
lsattr -El fcnvme1
----
+
.例を示します
[%collapsible]
====
[listing]
----
attach     switch                                                               How this adapter is connected  False
autoconfig available                                                            Configuration State            True
host_nqn   nqn.2014-08.org.nvmexpress:uuid:64e039bd-27d2-421c-858d-8a378dec31e8 Host NQN (NVMe Qualified Name) True
----
====
. ホストのNQNをチェックし、ONTAPアレイの対応するサブシステムのホストのNQN文字列と一致することを確認します。
+
[source, cli]
----
vserver nvme subsystem host show -vserver vs_s922-55-lpar2
----
+
.出力例
[listing]
----
Vserver         Subsystem                Host NQN
------- --------- ----------------------------------------------------------
vs_s922-55-lpar2 subsystem_s922-55-lpar2 nqn.2014-08.org.nvmexpress:uuid:64e039bd-27d2-421c-858d-8a378dec31e8
----
. イニシエータポートが動作しており、ターゲットLIFが表示されていることを確認します。




== ステップ3: NVMe/FCを検証する

ONTAP名前空間が NVMe/FC 構成に対して正しいことを確認します。

.手順
. ONTAPネームスペースがホストに正しく反映されていることを確認します。
+
[source, cli]
----
lsdev -Cc disk |grep NVMe
----
+
.出力例
[listing]
----
hdisk1  Available 00-00-02 NVMe 4K Disk
----
. 必要に応じて、マルチパスのステータスを確認します。
+
[source, cli]
----
lsmpio -l hdisk1
----
+
.例を示します
[%collapsible]
====
[listing]
----
name     path_id  status   path_status  parent  connection
hdisk1  8        Enabled  Sel,Opt      nvme12  fcnvme0, 9
hdisk1  9        Enabled  Sel,Non      nvme65  fcnvme1, 9
hdisk1  10       Enabled  Sel,Opt      nvme37  fcnvme1, 9
hdisk1  11       Enabled  Sel,Non      nvme60  fcnvme0, 9
----
====




== ステップ4: 既知の問題を確認する

ONTAPストレージを搭載した AIX の NVMe/FC ホスト構成には、次の既知の問題があります。

[cols="10,30,30"]
|===
| BURT ID | タイトル | 説明 


| link:https://mysupport.netapp.com/site/bugs-online/product/HOSTUTILITIES/BURT/1553249["1553249"^] | MCC計画外スイッチオーバーイベントをサポートするために変更されるAIX NVMe/FCのデフォルトAPD時間 | AIXオペレーティングシステムでは、NVMe/FCにデフォルトで20秒のオールパスダウン（APD）タイムアウト値が使用されます。  ただし、ONTAP MetroClusterの自動計画外スイッチオーバー（AUSO）とTiebreakerで開始されるスイッチオーバーのワークフローには、APDのタイムアウト時間よりも少し時間がかかり、I/Oエラーが発生することがあります。 


| link:https://mysupport.netapp.com/site/bugs-online/product/HOSTUTILITIES/BURT/1546017["1546017だ"^] | AIX NVMe/FCではANATTの上限が60秒に設定されていますが、ONTAPでは120秒に設定されています | ONTAPは、120秒のコントローラ識別でANA（非対称ネームスペースアクセス）移行タイムアウトをアドバタイズします。現在、IFIXでは、AIXはコントローラ識別からANA移行タイムアウトを読み取りますが、その制限を超えている場合は実質的に60秒にクランプします。 


| link:https://mysupport.netapp.com/site/bugs-online/product/HOSTUTILITIES/BURT/1541386["1541386年"^] | AIX NVMe/FCがANATTの有効期限後にEIOにヒットしました | Storage Failover（SFO；ストレージフェイルオーバー）イベントが発生した場合、特定のパスでANA（非対称ネームスペースアクセス）移行がタイムアウトの上限を超えると、ネームスペースへの正常な代替パスがあるにもかかわらず、AIX NVMe/FCホストがI/Oエラーで失敗します。 


| link:https://mysupport.netapp.com/site/bugs-online/product/HOSTUTILITIES/BURT/1541380["1541380"^] | AIX NVMe/FCは、ANATTのハーフ/フルの有効期限が切れるまで待機してから、ANA AENのあとにI/Oを再開します | IBM AIX NVMe/FCでは、ONTAPで公開されるAsynchronous Notification（AEN；非同期通知）の一部がサポートされません。このように最適化されていないANA処理は、SFO処理中に最適化されていません。 
|===


== ステップ5: トラブルシューティング

NVMe/FC障害のトラブルシューティングを行う前に、以下の規格に準拠した構成を実行していることを確認してください。link:https://mysupport.netapp.com/matrix/["IMT にログインします。"^]仕様。問題が解決しない場合は、link:https://mysupport.netapp.com["ネットアップサポート"^] 。
