---
sidebar: sidebar 
permalink: nvme_aix.html 
keywords: nvme, linux, rhel, red hat, enterprise, aix, ontap 
summary: ONTAPを使用するAIX用のNVMe/FCホストの設定方法 
---
= ONTAPを使用したAIXのNVMe/FCホスト構成
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
ONTAPストレージをターゲットとして使用するIBM AIXホストおよびVIOS/PowerVMホストで、NVMe over Fibre Channel（NVMe/FC）を有効にすることができます。サポートされる構成の詳細については、を参照してください link:https://mysupport.netapp.com/matrix/["NetApp Interoperability Matrix Tool で確認できます"^]。

ONTAPを備えたAIXホストでは、NVMe/FCホスト構成が次のようにサポートされます。

* ONTAP 9.13.1以降では、IBM AIX 7.2 TL5 SP6、AIX 7.3 TL1 SP2、およびVIOS 3.1.4.21リリースでNVMe/FCのサポートが追加され、物理スタックと仮想スタックの両方でSANブートがサポートされるようになりました。SANブートサポートの設定の詳細については、IBMのドキュメントを参照してください。
* NVMe/FCは、POWER9およびPower10 IBMサーバでサポートされます。
* NVMeデバイスには、Host Utilities for AIX SCSI Multipath I/O（MPIO）のサポートなど、個別のPCM（Path Control Module）は必要ありません。
* VIOS 3.1.4.21では、NetApp（VIOS/PowerVM）による仮想化のサポートが導入されました。これは、Power10 IBMサーバを使用したNPIV（N_PortID Virtualization）ストレージ仮想化モードでのみサポートされます。


.必要なもの
* アダプタファームウェア12.4.257.30以降のバージョンの32Gb FC Emulexアダプタ（EN1A、EN1B、EN1L、EN1M）または64Gb FCアダプタ（EN1N、EN1P）があることを確認します。
* MetroCluster構成を使用している場合は、AIXオペレーティングシステムによるI/Oタイムアウトの短縮を回避するために、MetroCluster計画外スイッチオーバーイベントがサポートされるように、AIX NVMe/FCのデフォルトのAPD（All Path Down）時間を変更することを推奨します。追加情報および推奨されるデフォルト設定の変更については、パブリックレポート1553249を参照してください。
* デフォルトでは、AIXホストOSのAsymmetric Namespace Access Transition Timeout（ANATT）の値は30秒です。IBMは、ANATT値を60秒に制限するInterim Fix（IFIX）を提供しています。すべてのONTAPワークフローが無停止であることを確認するには、IBMのWebサイトからIFIXをインストールする必要があります。
+

NOTE: NVMe/FC AIXをサポートするには、GAバージョンのAIX OSにIFIXをインストールする必要があります。これは、VIOS/PowerVM OSでは必要ありません。

+
IFIXの詳細は次のとおりです。

+
** AIXレベル72-TL5-SP6-2320の場合は、をインストールします `IJ46710s6a.230509.epkg.Z` パッケージ。
** AIXレベル73-TL1-SP2-2320の場合は、をインストールします `IJ46711s2a.230509.epkg.Z` パッケージ。
+
ifixの管理の詳細については、を参照してください link:http://www-01.ibm.com/support/docview.wss?uid=isg3T1012104["AIXでの暫定修正の管理"^]。

+

NOTE: に関連する以前にインストールされたifixがないAIXバージョンにifixをインストールする必要があります `devices.pciex.pciexclass.010802.rte` システム上。これらのifixが存在する場合、新しいインストールと競合します。

+
次の表に、AIX LPAR（AIX論理パーティション）または物理スタックに割り当てられたHBAを示します。

+
[cols="10,10,10,10,10"]
|===
| ホストOS | パワーアーチ | 電源FWバージョン | モード | コメント 


.2+| AIX 7.2 TL5 SP6 | POWER9 | Fw 950以降 | 物理スタック | IFIXはTS012877410から入手できます。 


| パワー10 | Fw 1010以降 | 物理スタック | SANブーティングがサポートされています。IFIXはTS012877410から入手できます。 


.2+| AIX 7.3 TL1 SP2 | POWER9 | Fw 950以降 | 物理スタック | IFIXはTS012877410から入手できます。 


| パワー10 | Fw 1010以降 | 物理スタックと仮想スタック | IFIXはTS012877410から入手できます。 
|===
+
次の表に、仮想化モードでNPIV対応サポートを使用するVIOSに割り当てられたHBAを示します。

+
[cols="10,10,10,10,10"]
|===
| ホストOS | パワーアーチ | 電源FWバージョン | モード | コメント 


| VIOS/PowerVM 3.1.4.21 | パワー10 | Fw 1010以降 | 仮想スタック | サポートはAIX 7.3 TL1 SP2 for VIOCから開始されます 
|===






== 既知の制限

ONTAPを使用したAIXでのNVMe/FCホスト構成には、次の既知の制限事項があります。

* AIXホスト上のQLogic / Marvel 32G FC HBAでは、NVMe/FCはサポートされません。
* POWER9 IBMサーバを使用するNVMe/FCデバイスでは、SANブートはサポートされません。




== マルチパス

NVMeマルチパスに使用されるIBM MPIO（マルチパスI/O）は、AIX OSのインストール時にデフォルトで提供されます。

を使用して、AIXホストでNVMeマルチパスが有効になっていることを確認できます `lsmpio` コマンドを実行します

[listing]
----
#[root@aix_server /]: lsmpio -l hdisk1
----
*出力例*

[listing]
----
name     path_id  status   path_status  parent  connection
hdisk1  8         Enabled  Sel,Opt       nvme12  fcnvme0, 9
hdisk1  9         Enabled  Sel,Non       nvme65  fcnvme1, 9
hdisk1  10        Enabled  Sel,Opt       nvme37  fcnvme1, 9
hdisk1  11        Enabled  Sel,Non       nvme60  fcnvme0, 9
----


== NVMe/FC を設定

次の手順を使用して、Broadcom/Emulexアダプタ用にNVMe/FCを設定できます。

.手順
. サポートされているアダプタを使用していることを確認します。サポートされているアダプタの最新のリストについては、を参照してください link:https://mysupport.netapp.com/matrix/["NetApp Interoperability Matrix Tool で確認できます"^]。
. NVMe/FCプロトコルのサポートは、物理FCではデフォルトで有効になっていますが、NVMe/FCプロトコルのサポートは、Virtual I/O Server（VIOS）のVirtual Fibre Channel（VFC；仮想ファイバチャネル）では無効になっています。
+
仮想アダプタのリストを取得します。

+
[listing]
----
$ lsmap -all -npiv
----
+
*出力例*

+
[listing]
----
Name          Physloc                            ClntID ClntName       ClntOS
------------- ---------------------------------- ------ -------------- -------
vfchost0      U9105.22A.785DB61-V2-C2                 4 s1022-iop-mcc- AIX
Status:LOGGED_IN
FC name:fcs4                    FC loc code:U78DA.ND0.WZS01UY-P0-C7-T0
Ports logged in:3
Flags:0xea<LOGGED_IN,STRIP_MERGE,SCSI_CLIENT,NVME_CLIENT>
VFC client name:fcs0            VFC client DRC:U9105.22A.785DB61-V4-C2
----
. を実行して、アダプタでNVMe/FCプロトコルのサポートを有効にします `ioscli vfcctrl` VIOSでのコマンド：
+
[listing]
----
$  vfcctrl -enable -protocol nvme -vadapter vfchost0
----
+
*出力例*

+
[listing]
----
The "nvme" protocol for "vfchost0" is enabled.
----
. アダプタでサポートが有効になっていることを確認します。
+
[listing]
----
# lsattr -El vfchost0
----
+
*出力例*

+
[listing]
----
alt_site_wwpn       WWPN to use - Only set after migration   False
current_wwpn  0     WWPN to use - Only set after migration   False
enable_nvme   yes   Enable or disable NVME protocol for NPIV True
label               User defined label                       True
limit_intr    false Limit NPIV Interrupt Sources             True
map_port      fcs4  Physical FC Port                         False
num_per_nvme  0     Number of NPIV NVME queues per range     True
num_per_range 0     Number of NPIV SCSI queues per range     True
----
. 現在のすべてのアダプタまたは選択したアダプタに対してNVMe/FCプロトコルを有効にします。
+
.. すべてのアダプタに対してNVMe/FCプロトコルを有効にします。
+
... を変更します `dflt_enabl_nvme` の属性値 `viosnpiv0` 疑似デバイスをに送信します `yes`。
... を設定します `enable_nvme` 属性値をに設定します `yes` すべてのVFCホストデバイスに対して。
+
[listing]
----
# chdev -l viosnpiv0 -a dflt_enabl_nvme=yes
----
+
[listing]
----
# lsattr -El viosnpiv0
----
+
*出力例*

+
[listing]
----
bufs_per_cmd    10  NPIV Number of local bufs per cmd                    True
dflt_enabl_nvme yes Default NVME Protocol setting for a new NPIV adapter True
num_local_cmds  5   NPIV Number of local cmds per channel                True
num_per_nvme    8   NPIV Number of NVME queues per range                 True
num_per_range   8   NPIV Number of SCSI queues per range                 True
secure_va_info  no  NPIV Secure Virtual Adapter Information              True
----


.. を変更して、選択したアダプタのNVMe/FCプロトコルを有効にします `enable_nvme` へのVFCホストデバイス属性の値 `yes`。


. 確認します `FC-NVMe Protocol Device` がサーバに作成されました：
+
[listing]
----
# [root@aix_server /]: lsdev |grep fcnvme
----
+
* exmaple output *

+
[listing]
----
fcnvme0       Available 00-00-02    FC-NVMe Protocol Device
fcnvme1       Available 00-01-02    FC-NVMe Protocol Device
----
. サーバからホストのNQNを記録します。
+
[listing]
----
# [root@aix_server /]: lsattr -El fcnvme0
----
+
*出力例*

+
[listing]
----
attach     switch                                                               How this adapter is connected  False
autoconfig available                                                            Configuration State            True
host_nqn   nqn.2014-08.org.nvmexpress:uuid:64e039bd-27d2-421c-858d-8a378dec31e8 Host NQN (NVMe Qualified Name) True
----
+
[listing]
----
[root@aix_server /]: lsattr -El fcnvme1
----
+
*出力例*

+
[listing]
----
attach     switch                                                               How this adapter is connected  False
autoconfig available                                                            Configuration State            True
host_nqn   nqn.2014-08.org.nvmexpress:uuid:64e039bd-27d2-421c-858d-8a378dec31e8 Host NQN (NVMe Qualified Name) True
----
. ホストのNQNをチェックし、ONTAPアレイの対応するサブシステムのホストのNQN文字列と一致することを確認します。
+
[listing]
----
::> vserver nvme subsystem host show -vserver vs_s922-55-lpar2
----
+
*出力例*

+
[listing]
----
Vserver         Subsystem                Host NQN
------- --------- ----------------------------------------------------------
vs_s922-55-lpar2 subsystem_s922-55-lpar2 nqn.2014-08.org.nvmexpress:uuid:64e039bd-27d2-421c-858d-8a378dec31e8
----
. イニシエータポートが動作しており、ターゲットLIFが表示されていることを確認します。




== NVMe/FC を検証

ONTAPネームスペースがホストに正しく反映されていることを確認する必要があります。これを行うには、次のコマンドを実行します。

[listing]
----
# [root@aix_server /]: lsdev -Cc disk |grep NVMe
----
*出力例*

[listing]
----
hdisk1  Available 00-00-02 NVMe 4K Disk
----
マルチパスのステータスを確認できます。

[listing]
----
#[root@aix_server /]: lsmpio -l hdisk1
----
*出力例*

[listing]
----
name     path_id  status   path_status  parent  connection
hdisk1  8        Enabled  Sel,Opt      nvme12  fcnvme0, 9
hdisk1  9        Enabled  Sel,Non      nvme65  fcnvme1, 9
hdisk1  10       Enabled  Sel,Opt      nvme37  fcnvme1, 9
hdisk1  11       Enabled  Sel,Non      nvme60  fcnvme0, 9
----


== 既知の問題

ONTAPリリースを使用するAIXのNVMe/FCホスト設定には、次の既知の問題があります。

[cols="10,30,30"]
|===
| BURT ID | タイトル | 説明 


| 1553249 | MCC計画外スイッチオーバーイベントをサポートするために変更されるAIX NVMe/FCのデフォルトAPD時間 | AIXオペレーティングシステムでは、NVMe/FCにデフォルトで20秒のオールパスダウン（APD）タイムアウト値が使用されます。  ただし、ONTAP MetroClusterの自動計画外スイッチオーバー（AUSO）とTiebreakerで開始されるスイッチオーバーのワークフローには、APDのタイムアウト時間よりも少し時間がかかり、I/Oエラーが発生することがあります。 


| 1546017だ | AIX NVMe/FCではANATTの上限が60秒に設定されていますが、ONTAPでは120秒に設定されています | ONTAPは、120秒のコントローラ識別でANA（非対称ネームスペースアクセス）移行タイムアウトをアドバタイズします。現在、IFIXでは、AIXはコントローラ識別からANA移行タイムアウトを読み取りますが、その制限を超えている場合は実質的に60秒にクランプします。 


| 1541386年 | AIX NVMe/FCがANATTの有効期限後にEIOにヒットしました | Storage Failover（SFO；ストレージフェイルオーバー）イベントが発生した場合、特定のパスでANA（非対称ネームスペースアクセス）移行がタイムアウトの上限を超えると、ネームスペースへの正常な代替パスがあるにもかかわらず、AIX NVMe/FCホストがI/Oエラーで失敗します。 


| 1541380 | AIX NVMe/FCは、ANATTのハーフ/フルの有効期限が切れるまで待機してから、ANA AENのあとにI/Oを再開します | IBM AIX NVMe/FCでは、ONTAPで公開されるAsynchronous Notification（AEN；非同期通知）の一部がサポートされません。このように最適化されていないANA処理は、SFO処理中に最適化されていません。 
|===


== トラブルシューティング

NVMe/FCの障害をトラブルシューティングする前に、実行している構成がInteroperability Matrix Tool（IMT）の仕様に準拠していることを確認してください。問題が解決しない場合は、 link:mysupport.netapp.com["ネットアップサポート"^] さらなるトリアージのために。
