---
sidebar: sidebar 
permalink: nvme_ol_85.html 
keywords: nvme, linux, oracle, 8.5 
summary: 例を使用した、ONTAP を使用したOracle Linux 8.5用のVME / FCホスト構成のセットアップ 
---
= ONTAP を使用したOracle Linux 8.5向けのNVMe / FCホスト構成
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content




== サポート性

ONTAP 9.6以降では、Oracle Linux 8.5でNVMe/FCがサポートされます。Oracle Linux 8.5ホストでは、同じFibre Channel（FC）イニシエータアダプタポートを介して、NVMe/FCとFCPの両方のトラフィックを実行できます。を参照してください link:https://hwu.netapp.com/["Hardware Universe"^] サポートされる FC アダプタおよびコントローラの一覧を表示するには、を参照してください。サポートされる構成の最新のリストについては、を参照してください link:https://mysupport.netapp.com/matrix/["NetApp Interoperability Matrix を参照してください"^]。


NOTE: このコンテンツで提供される設定を使用して、に接続するクラウドクライアントを設定できます link:https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/index.html["Cloud Volumes ONTAP"^] および link:https://docs.netapp.com/us-en/cloud-manager-fsx-ontap/index.html["ONTAP 対応の Amazon FSX"^]。



== の機能

* Oracle Linux 8.5では、NVMeネームスペースでインカーネルNVMeマルチパスがデフォルトで有効になっています。
* Oracle Linux 8.5では'nvme-fc auto-connect`スクリプトがネイティブの'nvme-cli'パッケージに含まれていますそのため、外部ベンダーが提供するoutbox自動接続スクリプトをインストールする代わりに、これらのネイティブ自動接続スクリプトを使用することもできます。
* Oracle Linux 8.5では、NVMeマルチパスのラウンドロビンロードバランシングを可能にする「nvme-cli」パッケージの一部としてネイティブの「udev」ルールがすでに提供されています。そのため、このルールを手動で作成する必要はありません（Oracle Linux 8.1の場合と同様）。
* Oracle Linux 8.5では、NVMeとSCSIの両方のトラフィックを、同じ新規のホストで実行できます。実際、これは一般的に導入されるホスト構成であると想定されています。SCSIの場合'dm-multipathをSCSI LUNで通常どおりに設定してから'mpathデバイスを生成できます一方'NVMeマルチパスを使用してNVMe-oFマルチパスデバイス（つまり'/dev/nvmeXnY')をホストで設定できます
* Oracle Linux 8.5では、ネイティブの「nvme-cli」に含まれるネットアッププラグインは、ONTAP ネームスペースと同様にONTAP の詳細を表示できます。




== 既知の制限

* NVMe/FCはテクノロジプレビュー機能であるため、IMT にはサポートは掲載されていません。
* NVMe/FC（ストレージフェイルオーバー）などのONTAP フェイルオーバーイベントを快適に潮流させるには、「ctrl_loute_tmo」タイマーを調整して30分程度の再試行期間を設定することをお勧めします。以下の詳細を参照してください。




== 設定要件

を参照してください link:https://mysupport.netapp.com/matrix/["NetApp Interoperability Matrix を参照してください"^] サポートされている構成の正確な情報については、を参照



== Oracle Linux 8.5でのNVMe/FCの有効化

.手順
. サーバにOracle Linux 8.5 General Availability（GA）をインストールします。インストールが完了したら、指定したOracle Linux 8.5 GAカーネルを実行していることを確認します。を参照してください link:https://mysupport.netapp.com/matrix/["NetApp Interoperability Matrix を参照してください"^] サポートされるバージョンの最新のリストについては、を参照してください。
+
[listing]
----
# uname -r
5.4.17-2136.309.4.el8uek.x86_64
----
. 「nvme-cli」パッケージをインストールします。
+
[listing]
----
# rpm -qa|grep nvme-cli
nvme-cli-1.14-3.el8.x86_64
----
. Oracle Linux 8.5ホストで、/etc/nvme/hostnqn'の「hostnqn」文字列を確認し、ONTAP アレイの対応するサブシステムの「hostnqn'」文字列に一致することを確認します。
+
[listing]
----
# cat /etc/nvme/hostnqn
nqn.2014-08.org.nvmexpress:uuid:9ed5b327-b9fc-4cf5-97b3-1b5d986345d1
::> vserver nvme subsystem host show -vserver vs_ol_nvme

Vserver    Subsystem      Host NQN
---------------------------------------------
vs_ol_nvme nvme_ss_ol_1   nqn.2014-08.org.nvmexpress:uuid:9ed5b327-b9fc-4cf5-97b3-1b5d986345d1
----
+

NOTE: hostnqn文字列が一致しない場合は、「vserver modify」コマンドを使用して、対応するONTAP アレイサブシステムの「hostnqn」文字列を、ホストの「/etc/nvme/hostnqn」からの「nqn」文字列に一致するように更新します。

. ホストをリブートします。
+
[NOTE]
====
同一のOracle Linux 8.5上でNVMeトラフィックとSCSIトラフィックの両方を同一のOracle Linux 8.5上で同時に実行する場合は、ONTAP ネームスペースにはカーネル内NVMeマルチパスを、ONTAP LUNにはそれぞれ「dm-multipath」を使用することを推奨します。また'dm-multipathでONTAP ネームスペースがこれらのネームスペースデバイスを要求しないようにブラックリストに登録される必要がありますこれを行うには'enable_foreign'設定を/etc/multipath.confに追加します

[listing]
----
# cat /etc/multipath.conf
defaults {
        enable_foreign     NONE
}
----
====
. 新しい設定を有効にするには'systemctl restart multipathdを実行して'multipathdデーモンを再起動します




=== Broadcom FC アダプタを NVMe/FC 用に設定します

.手順
. サポートされているアダプタを使用していることを確認します。サポートされているアダプタの最新のリストについては、を参照してください link:https://mysupport.netapp.com/matrix/["NetApp Interoperability Matrix を参照してください"^]。
+
[listing]
----
# cat /sys/class/scsi_host/host*/modelname
LPe32002-M2
LPe32002-M2
# cat /sys/class/scsi_host/host*/modeldesc
Emulex LightPulse LPe32002-M2 2-Port 32Gb Fibre Channel Adapter
Emulex LightPulse LPe32002-M2 2-Port 32Gb Fibre Channel Adapter
----
. 推奨される Broadcom lpfc ファームウェアとインボックスドライバを使用していることを確認します。サポートされているアダプタドライバとファームウェアのバージョンの最新リストについては、を参照してください link:https://mysupport.netapp.com/matrix/["NetApp Interoperability Matrix を参照してください"^]。
+
[listing]
----
# cat /sys/class/scsi_host/host*/fwrev
14.0.505.11, sli-4:2:c
14.0.505.11, sli-4:2:c

# cat /sys/module/lpfc/version
0:12.8.0.11
----
. lpfc_enable_fc4_typeが3に設定されていることを確認します
+
[listing]
----
# cat /sys/module/lpfc/parameters/lpfc_enable_fc4_type
3
----
. イニシエータポートが動作中で、ターゲットLIFを認識できることを確認します。
+
[listing]
----
# cat /sys/class/fc_host/host*/port_name
0x100000109b1c1204
0x100000109b1c1205
# cat /sys/class/fc_host/host*/port_state
Online
Online
# cat /sys/class/scsi_host/host*/nvme_info
NVME Initiator Enabled
XRI Dist lpfc0 Total 6144 IO 5894 ELS 250
NVME LPORT lpfc0 WWPN x100000109b1c1204 WWNN x200000109b1c1204 DID x011d00 ONLINE
NVME RPORT WWPN x203800a098dfdd91 WWNN x203700a098dfdd91 DID x010c07 TARGET DISCSRVC ONLINE
NVME RPORT WWPN x203900a098dfdd91 WWNN x203700a098dfdd91 DID x011507 TARGET DISCSRVC ONLINE
NVME Statistics
LS: Xmt 0000000f78 Cmpl 0000000f78 Abort 00000000
LS XMIT: Err 00000000 CMPL: xb 00000000 Err 00000000
Total FCP Cmpl 000000002fe29bba Issue 000000002fe29bc4 OutIO 000000000000000a
abort 00001bc7 noxri 00000000 nondlp 00000000 qdepth 00000000 wqerr 00000000 err 00000000
FCP CMPL: xb 00001e15 Err 0000d906
NVME Initiator Enabled
XRI Dist lpfc1 Total 6144 IO 5894 ELS 250
NVME LPORT lpfc1 WWPN x100000109b1c1205 WWNN x200000109b1c1205 DID x011900 ONLINE
NVME RPORT WWPN x203d00a098dfdd91 WWNN x203700a098dfdd91 DID x010007 TARGET DISCSRVC ONLINE
NVME RPORT WWPN x203a00a098dfdd91 WWNN x203700a098dfdd91 DID x012a07 TARGET DISCSRVC ONLINE
NVME Statistics
LS: Xmt 0000000fa8 Cmpl 0000000fa8 Abort 00000000
LS XMIT: Err 00000000 CMPL: xb 00000000 Err 00000000
Total FCP Cmpl 000000002e14f170 Issue 000000002e14f17a OutIO 000000000000000a
abort 000016bb noxri 00000000 nondlp 00000000 qdepth 00000000 wqerr 00000000 err 00000000
FCP CMPL: xb 00001f50 Err 0000d9f8
----




=== 1MBのI/Oサイズを有効にしています

.手順
. lpfcドライバから問題 I/Oへの要求を最大1MBにするには'lpfc_sg_seg_cnt'パラメータを256に設定する必要があります
+
[listing]
----
# cat /etc/modprobe.d/lpfc.conf
options lpfc lpfc_sg_seg_cnt=256
----
. 「 racut-f 」コマンドを実行してからホストを再起動します。ホストが起動したら'lpfc_sg_seg_cnt'が256に設定されていることを確認します
+
[listing]
----
# cat /sys/module/lpfc/parameters/lpfc_sg_seg_cnt
256
----




== Marvell / QLogic FCアダプタをNVMe/FC用に設定します

.手順
. OL 8.5 GAカーネルに含まれているネイティブインボックスqla2xxxドライバには、最新のアップストリーム修正が含まれており、ONTAP サポートに不可欠です。サポートされているアダプタドライバとファームウェアのバージョンが実行されていることを確認します。
+
[listing]
----
# cat /sys/class/fc_host/host*/symbolic_name
QLE2742 FW:v9.06.02 DVR:v10.02.00.106-k
QLE2742 FW:v9.06.02 DVR:v10.02.00.106-k
----
. Marvell アダプタが NVMe/FC イニシエータとして機能できるように、「 ql2xnvmeenable 」が設定されていることを確認します。
+
[listing]
----
# cat /sys/module/qla2xxx/parameters/ql2xnvmeenable
1
----




== NVMe/FCを設定しています

NVMe/FC とは異なり、 NVMe/FC は自動接続機能を備えていません。これは、Linux NVMe/FCホストには次の2つの大きな制限事項があることを反映しています。

* パスが復活した後に自動再接続が行われない-NVMe/TCPは、パスがダウンしてからデフォルトの「Ctrl-loss -TTMO」の10分を超えて復活したパスに自動的に再接続することはできません。
* ホストのブート時に自動接続が行われない- NVMe/FCはホストのブート時にも自動的に接続できません。


ONTAP フェイルオーバーイベント(SFOなど)を快適に潮流させるには'Ctrl_LONS_TMOタイマーを調整して'30分間などの長い再試行期間を設定することをお勧めします手順は次のとおりです。

.手順
. イニシエータポートが、サポートされているNVMe/FC LIF経由で検出ログページデータを読み込めたかどうかを確認します。
+
[listing]
----
# nvme discover -t tcp -w 192.168.1.8 -a 192.168.1.51
Discovery Log Number of Records 10, Generation counter 119
=====Discovery Log Entry 0======
trtype: tcp
adrfam: ipv4
subtype: nvme subsystem
treq: not specified
portid: 0
trsvcid: 4420
subnqn: nqn.1992-08.com.netapp:sn.56e362e9bb4f11ebbaded039ea165abc:subsystem.nvme_118_tcp_1
traddr: 192.168.2.56
sectype: none
=====Discovery Log Entry 1======
trtype: tcp
adrfam: ipv4
subtype: nvme subsystem
treq: not specified
portid: 1
trsvcid: 4420
subnqn: nqn.1992-08.com.netapp:sn.56e362e9bb4f11ebbaded039ea165abc:subsystem.nvme_118_tcp_1
traddr: 192.168.1.51
sectype: none
=====Discovery Log Entry 2======
trtype: tcp
adrfam: ipv4
subtype: nvme subsystem
treq: not specified
portid: 0
trsvcid: 4420
subnqn: nqn.1992-08.com.netapp:sn.56e362e9bb4f11ebbaded039ea165abc:subsystem.nvme_118_tcp_2
traddr: 192.168.2.56
sectype: none
...
----
. 同様に、もう一方のNVMe/FCイニシエータターゲットLIFのコンボファイルが検出ログページのデータを正常に取得できることを確認してください。例：
+
[listing]
----
# nvme discover -t tcp -w 192.168.1.8 -a 192.168.1.51
# nvme discover -t tcp -w 192.168.1.8 -a 192.168.1.52
# nvme discover -t tcp -w 192.168.2.9 -a 192.168.2.56
# nvme discover -t tcp -w 192.168.2.9 -a 192.168.2.57
----
. 次に、ノード全体で、サポートされているすべてのNVMe/FCイニシエータターゲットLIFに対して「nvme connect -all」を実行します。パスが失われた場合に再試行するように'connect-allの間に'ctrl_loss _tmo'期間を延長してください（たとえば'-30分は'-l 1800'で設定できます）例：
+
[listing]
----
# nvme connect-all -t tcp -w 192.168.1.8 -a 192.168.1.51 -l 1800
# nvme connect-all -t tcp -w 192.168.1.8 -a 192.168.1.52 -l 1800
# nvme connect-all -t tcp -w 192.168.2.9 -a 192.168.2.56 -l 1800
# nvme connect-all -t tcp -w 192.168.2.9 -a 192.168.2.57 -l 1800
----




== NVMe/FC を検証しています

.手順
. Oracle Linux 8.5ホストで、次のNVMe/FC設定を確認します。
+
[listing]
----
# cat /sys/module/nvme_core/parameters/multipath
Y
# cat /sys/class/nvme-subsystem/nvme-subsys*/model
NetApp ONTAP Controller
NetApp ONTAP Controller
# cat /sys/class/nvme-subsystem/nvme-subsys*/iopolicy
round-robin
round-robin
----
. ネームスペースが作成され、ホストで正しく検出されていることを確認します。
+
[listing]
----
# nvme list
Node         SN                    Model
---------------------------------------------------------------
/dev/nvme0n1 814vWBNRwf9HAAAAAAAB  NetApp ONTAP Controller
/dev/nvme0n2 814vWBNRwf9HAAAAAAAB  NetApp ONTAP Controller
/dev/nvme0n3 814vWBNRwf9HAAAAAAAB  NetApp ONTAP Controller

Namespace Usage  Format                  FW            Rev
--------------------------------------------------------------
1                85.90 GB / 85.90 GB     4 KiB + 0 B   FFFFFFFF
2                85.90 GB / 85.90 GB     4 KiB + 0 B   FFFFFFFF
3                85.90 GB / 85.90 GB     4 KiB + 0 B   FFFFFFFF
----
. 各パスのコントローラの状態がライブで、適切なANAステータスであることを確認します
+
[listing]
----
# nvme list-subsys /dev/nvme0n1
nvme-subsys0 - NQN=nqn.1992-08.com.netapp:sn.5f5f2c4aa73b11e9967e00a098df41bd:subsystem.nvme_ss_ol_1
\
+- nvme0 fc traddr=nn-0x203700a098dfdd91:pn-0x203800a098dfdd91 host_traddr=nn-0x200000109b1c1204:pn-0x100000109b1c1204 live inaccessible
+- nvme1 fc traddr=nn-0x203700a098dfdd91:pn-0x203900a098dfdd91 host_traddr=nn-0x200000109b1c1204:pn-0x100000109b1c1204 live inaccessible
+- nvme2 fc traddr=nn-0x203700a098dfdd91:pn-0x203a00a098dfdd91 host_traddr=nn-0x200000109b1c1205:pn-0x100000109b1c1205 live optimized
+- nvme3 fc traddr=nn-0x203700a098dfdd91:pn-0x203d00a098dfdd91 host_traddr=nn-0x200000109b1c1205:pn-0x100000109b1c1205 live optimized
----
. ネットアッププラグインにONTAP ネームスペースデバイスごとに適切な値が表示されていることを確認します
+
[listing]
----
# nvme netapp ontapdevices -o column
Device       Vserver  Namespace Path
-----------------------------------
/dev/nvme0n1  vs_ol_nvme  /vol/ol_nvme_vol_1_1_0/ol_nvme_ns
/dev/nvme0n2  vs_ol_nvme  /vol/ol_nvme_vol_1_0_0/ol_nvme_ns
/dev/nvme0n3  vs_ol_nvme  /vol/ol_nvme_vol_1_1_1/ol_nvme_ns

NSID    UUID                                   Size
-----------------------------------------------------
1       72b887b1-5fb6-47b8-be0b-33326e2542e2   85.90GB
2       04bf9f6e-9031-40ea-99c7-a1a61b2d7d08   85.90GB
3       264823b1-8e03-4155-80dd-e904237014a4   85.90GB

# nvme netapp ontapdevices -o json
{
"ONTAPdevices" : [
    {
        "Device" : "/dev/nvme0n1",
        "Vserver" : "vs_ol_nvme",
        "Namespace_Path" : "/vol/ol_nvme_vol_1_1_0/ol_nvme_ns",
        "NSID" : 1,
        "UUID" : "72b887b1-5fb6-47b8-be0b-33326e2542e2",
        "Size" : "85.90GB",
        "LBA_Data_Size" : 4096,
        "Namespace_Size" : 20971520
    },
    {
        "Device" : "/dev/nvme0n2",
        "Vserver" : "vs_ol_nvme",
        "Namespace_Path" : "/vol/ol_nvme_vol_1_0_0/ol_nvme_ns",
        "NSID" : 2,
        "UUID" : "04bf9f6e-9031-40ea-99c7-a1a61b2d7d08",
        "Size" : "85.90GB",
        "LBA_Data_Size" : 4096,
        "Namespace_Size" : 20971520
      },
      {
         "Device" : "/dev/nvme0n3",
         "Vserver" : "vs_ol_nvme",
         "Namespace_Path" : "/vol/ol_nvme_vol_1_1_1/ol_nvme_ns",
         "NSID" : 3,
         "UUID" : "264823b1-8e03-4155-80dd-e904237014a4",
         "Size" : "85.90GB",
         "LBA_Data_Size" : 4096,
         "Namespace_Size" : 20971520
       },
  ]
}
----




== トラブルシューティング

NVMe/FC障害のトラブルシューティングを開始する前に、必ずIMT の仕様に準拠した設定を実行していることを確認してください。ホスト側の問題をデバッグするには、次の手順に進みます。



=== lpfc詳細ログ

次に'drivers /scsi/lpfc/lpfc_logmsg.h'に示されている'NVMe/FCで使用可能なlpfcドライバ・ロギング・ビットマスクのリストを示します

[listing]
----
#define LOG_NVME 0x00100000 /* NVME general events. */
#define LOG_NVME_DISC 0x00200000 /* NVME Discovery/Connect events. */
#define LOG_NVME_ABTS 0x00400000 /* NVME ABTS events. */
#define LOG_NVME_IOERR 0x00800000 /* NVME IO Error events. */
----
したがって'lpfcドライバの観点からNVMe/FCイベントをロギングするには'lpfc_log_verbose'ドライバ設定（/etc/modprobe.d/lpfc.confのlpfc行に追加）を上記のいずれかの値に設定します次に'dracut-fを実行してinitiramfsを再作成し'ホストを再起動します再起動後、上記の「LOG_NVME_DISCビットマスク」の例を使用して、詳細ログが適用されていることを確認します。

[listing]
----
# cat /etc/modprobe.d/lpfc.conf
lpfc_enable_fc4_type=3 lpfc_log_verbose=0xf00083
# cat /sys/module/lpfc/parameters/lpfc_log_verbose
15728771
----


=== qla2xxx詳細ログ

lpfc ドライバの場合と同様の、 NVMe/FC 用の qla2xxx ログ機能はありません。したがって、次の手順を使用して一般的な qla2xxx ログレベルを設定できます。

.手順
. 対応するmodprobe qla2xxx confファイルに'ql2xextended_error_logging=0x1e400000`の値を追加します
. 「 d racut-f 」コマンドを実行して「 initramfs 」を再作成し、ホストを再起動します。
. リブート後、次のように詳細ログが適用されていることを確認します。
+
[listing]
----
# cat /etc/modprobe.d/qla2xxx.conf
options qla2xxx ql2xnvmeenable=1 ql2xextended_error_logging=0x1e400000
# cat /sys/module/qla2xxx/parameters/ql2xextended_error_logging
507510784
----




=== 一般的な nvme-CLI エラーとその回避策があります

NVMe検出、NVMe接続、またはNVMe接続の実行中に「nvme-cli」コマンドによって表示されるエラーとその回避策を次の表に示します。

[cols="20, 20, 50"]
|===
| nvme-CLIにエラーが表示されます | 原因と考えられます | 回避策 


| 'Failed to write to /dev/nvme-Fabrics：Invalid argument ' error displayed during NVMe discover、NVMe connect、or NVMe connect-all | 構文が正しくありません | 指定されたNVMeコマンドに正しい構文を使用していることを確認します。 


| '/dev/nvme-Fabricsへの書き込みに失敗しました：NVMe検出、NVMe接続、またはNVMe Connect-all実行中にNo such file or directory」エラーが表示されます | 複数の問題が原因でこのエラーが発生する可能性一般的なケースとしては、指定したNVMeコマンドに誤った引数を渡した場合などがあります。  a| 
* 指定されたコマンドに適切な引数（WWNN文字列、WWPN文字列など）を渡したことを確認してください。
* 引数が正しいにもかかわらず、このエラーがまだ表示される場合は、「/sys/class/scsi_host*/nvme_info」の出力が正しいかどうかを確認します。NVMeイニシエータの「enabled」と表示され、NVMe/FCターゲットLIFがリモートポートのセクションに正しく表示されていることを確認します。例：
+
[listing]
----
# cat /sys/class/scsi_host/host*/nvme_info
NVME Initiator Enabled
NVME LPORT lpfc0 WWPN x10000090fae0ec9d WWNN x20000090fae0ec9d DID x012000 ONLINE
NVME RPORT WWPN x200b00a098c80f09 WWNN x200a00a098c80f09 DID x010601 TARGET DISCSRVC ONLINE
NVME Statistics
LS: Xmt 0000000000000006 Cmpl 0000000000000006
FCP: Rd 0000000000000071 Wr 0000000000000005 IO 0000000000000031
Cmpl 00000000000000a6 Outstanding 0000000000000001
NVME Initiator Enabled
NVME LPORT lpfc1 WWPN x10000090fae0ec9e WWNN x20000090fae0ec9e DID x012400 ONLINE
NVME RPORT WWPN x200900a098c80f09 WWNN x200800a098c80f09 DID x010301 TARGET DISCSRVC ONLINE
NVME Statistics
LS: Xmt 0000000000000006 Cmpl 0000000000000006
FCP: Rd 0000000000000073 Wr 0000000000000005 IO 0000000000000031
Cmpl 00000000000000a8 Outstanding 0000000000000001
----
* 出力「nvme_info」に上記のようにターゲットLIFが表示されない場合は、「/var/log/messages」および「dmesg」出力で疑わしいNVMe/FCエラーがないかを確認し、それに応じてレポートまたは修正してください。




| NVMe検出'NVMe接続'NVMe Connect-Allの実行中に'No discovery log entries to fetch'エラーが表示される | このエラーメッセージは、通常、「/etc/nvme/hostnqn」文字列がネットアップアレイの対応するサブシステムに追加されていない場合に表示されます。または'不正なhostnqn'文字列がそれぞれのサブシステムに追加されています | 正確な「 /etc/nvme/hostnqn 」文字列がネットアップアレイの対応するサブシステムに追加されていることを確認します（「 vserver nvme subsystem host show 」コマンドで確認します）。 


| 'Failed to write to /dev/nvme-Fabrics：Operation already in progress' displayed during NVMe discover、NVMe connect、or NVMe connect-all（NVMe接続-すべてのNVMe検出中に、オペレーションはすでに進行中です | このエラーメッセージは、コントローラの関連付けまたは指定された処理がすでに作成されている場合や作成中の場合に表示されます。これは、上記にインストールされている自動接続スクリプトの一部として発生する可能性があります。 | なしNVMe 検出を実行するには、しばらくしてからこのコマンドを実行してください。また、NVMe connectとconnect-allの場合は、「nvme list」を実行して、ネームスペースデバイスがすでに作成され、ホストに表示されていることを確認します。 
|===


=== テクニカルサポートへの連絡のタイミング

問題が解決しない場合は、次のファイルとコマンドの出力を収集し、テクニカルサポートに問い合わせてトリアージを依頼してください。

[listing]
----
cat /sys/class/scsi_host/host*/nvme_info
/var/log/messages
dmesg
nvme discover output as in:
nvme discover --transport=fc --traddr=nn-0x200a00a098c80f09:pn-0x200b00a098c80f09 --host-traddr=nn-0x20000090fae0ec9d:pn-0x10000090fae0ec9d
nvme list
nvme list-subsys /dev/nvmeXnY
----


== 既知の問題および対処方法

なし
