---
sidebar: sidebar 
permalink: nvme_esxi_7.html 
keywords: nvme, esxi, ontap 
summary: ONTAP を使用して ESXi 7.0 用に NVMe/FC を設定する方法について説明します 
---
= ONTAP を使用した ESXi 7.0 用 NVMe-oF ホスト構成
:toc: macro
:hardbreaks:
:toclevels: 1
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content




== サポート性

ONTAP 9.7 以降では、 ESXi 7.0 で NVMe/FC がサポートされます。

ESXi イニシエータホストは、 NVMe/FC と FCP の両方のトラフィックを同じアダプタポートで実行できます。を参照してください link:https://hwu.netapp.com/Home/Index["Hardware Universe"] サポートされる FC アダプタおよびコントローラの一覧を表示するには、を参照してください。サポートされている構成およびバージョンの最新のリストについては、を参照してください 。



== 既知の制限

以下はサポートされていません。

* RDM マッピング
* できません




== ANA で NVMe / FC を有効化します

. ONTAP との相互運用性を向上させるには、 HppManageDegradedPaths パラメータを無効にします。
+
[listing]
----
# esxcfg-advcfg -s 0 /Misc/HppManageDegradedPaths
----
. ホストをリブートします。
. 再起動後、 HppManageDegradedPaths パラメータが無効になっていることを確認します。
+
[listing]
----
# esxcfg-advcfg -g /Misc/HppManageDegradedPaths
Value of HppManageDegradedPaths is 0
----
. ESXi ホストの NQN 文字列を確認して、 ONTAP アレイの対応するサブシステムのホスト NQN 文字列と一致していることを確認します。
+
.例
[listing]
----
# esxcli nvme info get
Host NQN: nqn.2014-08.com.vmware:nvme:chat-54-113

*> vserver nvme subsystem host show -vserver co_nv_fc_esx
Vserver Subsystem Host NQN
------- --------- ----------------------------------------------------------
co_nv_fc_esx
        subsys_chat_54_113_nvme
                  nqn.2014-08.com.vmware:nvme:chat-54-113
----




== Broadcom FC アダプタを NVMe/FC 用に設定します

. 推奨されている lpfc ドライバをインストールするには ' 一時フォルダにコピーし ' 次のコマンドを実行します
+
[listing]
----
# esxcli software vib install -d /tmp/t/Emulex-FCoE-FC-lpfc-12.4.224.0-offline-bundle-13621872.zip --no-sig-check
Installation Result
   Message: The update completed successfully, but the system needs to be rebooted for the changes to be effective.
   Reboot Required: true
   VIBs Installed: EMU_bootbank_lpfc_12.4.224.0-1OEM.688.0.0.13621872
   VIBs Removed: EMU_bootbank_lpfc_12.4.211.6-1OEM.688.0.0.13621872
   VIBs Skipped:
----
. 必要に応じて 'lpfc ドライバ・パラメータ lpfc_enable_fc4_type=3` を設定して 'lpfc ドライバで NVMe/FC サポートを有効にします
+

NOTE: このパラメータは、 LPe35000 シリーズアダプタのデフォルトで設定されています。LPe32000 シリーズおよび LPe31000 シリーズアダプタ用に手動で設定するには、次の手順を実行する必要があります。

+
[listing]
----
# esxcli system module parameters set -m lpfc -p lpfc_enable_fc4_type=3
----
. elxmgmt ユーティリティを使用して、 Broadcom FC アダプタのファームウェアを推奨バージョンにアップグレードします。
+
[listing]
----
# esxcli software vib install -d /tmp/t/Emulex-elxmgmt-6.8.7-12.4.211.7.zip --no-sig-check
Installation Result
   Message: The update completed successfully, but the system needs to be rebooted for the changes to be effective.
   Reboot Required: true
   VIBs Installed: EMU_bootbank_emu-esx-elxmgmt_12.4.211.7-01
   VIBs Removed:
   VIBs Skipped:
…
----
. ホストをリブートします。
. 再起動後、推奨される lpfc ドライバおよびアダプタファームウェアのバージョンが適用され、イニシエータポートがオンラインになっていることを確認します。
+
[listing]
----
# esxcli storage san fc list
 Adapter: vmhba3
   Port ID: 010600
   Node Name: 20:00:00:90:fa:e0:ec:8e
   Port Name: 10:00:00:90:fa:e0:ec:8e
   Speed: 32 Gbps
   Port Type: NPort
   Port State: ONLINE
   Model Description: Emulex LightPulse LPe32002-M2 2-Port 32Gb Fibre Channel Adapter
   Hardware Version: 0000000c
   OptionROM Version: 12.4.217.2
   Firmware Version: 12.4.217.2
   Driver Name: lpfc
   DriverVersion: 12.4.224.0

   Adapter: vmhba4
   Port ID: 010F00
   Node Name: 20:00:00:90:fa:e0:ec:8f
   Port Name: 10:00:00:90:fa:e0:ec:8f
   Speed: 32 Gbps
   Port Type: NPort
   Port State: ONLINE
   Model Description: Emulex LightPulse LPe32002-M2 2-Port 32Gb Fibre Channel Adapter
   Hardware Version: 0000000c
   OptionROM Version: 12.4.217.2
   Firmware Version: 12.4.217.2
   Driver Name: lpfc
   DriverVersion: 12.4.224.0
----




== NVMe/FC を検証しています

. ONTAP ターゲットの NVMe/FC コントローラが ESXi ホストで正しく検出されていることを確認します。
+
[listing]
----
# esxcli nvme controller list

Name                                                                                                                             Controller Number  Adapter  Transport Type  Is Online
-------------------------------------------------------------------------------------------------------------------------------  -----------------  -------  --------------  ---------
nqn.1992-08.com.netapp:sn.e7f89c2c245d11e9975300a098dfce55:subsystem.interop_57_vm_01#vmhba32#204900a098dfe3d1:204a00a098dfe3d1                259  vmhba32  FC                  false
nqn.1992-08.com.netapp:sn.e7f89c2c245d11e9975300a098dfce55:subsystem.interop_57_vm_09#vmhba32#204900a098dfe3d1:204a00a098dfe3d1                263  vmhba32  FC                  false
nqn.1992-08.com.netapp:sn.e7f89c2c245d11e9975300a098dfce55:subsystem.interop_57_vm_11#vmhba32#204900a098dfe3d1:204a00a098dfe3d1                267  vmhba32  FC                  false
nqn.1992-08.com.netapp:sn.e7f89c2c245d11e9975300a098dfce55:subsystem.interop_57_vm_10#vmhba32#204900a098dfe3d1:204a00a098dfe3d1                265  vmhba32  FC                  false
nqn.1992-08.com.netapp:sn.e7f89c2c245d11e9975300a098dfce55:subsystem.interop_57_vm_02#vmhba32#204900a098dfe3d1:204a00a098dfe3d1                261  vmhba32  FC                  false
----
. NVMe/FC ネームスペースが適切に作成されたことを確認します。
+
次の例の UUID は、 NVMe / FC ネームスペースデバイスを表しています。

+
[listing]
----
#esxcfg-mpath -b
uuid.0d12b7cd97344be8a53b7913f8f72f04 : NVMe Fibre Channel Disk (uuid.0d12b7cd97344be8a53b7913f8f72f04)
   vmhba65:C0:T9:L30 LUN:30 state:active fc Adapter: WWNN: 20:00:00:90:fa:e0:ec:8f WWPN: 10:00:00:90:fa:e0:ec:8f  Target: WWNN: 20:49:00:a0:98:df:e3:d1 WWPN: 20:4d:00:a0:98:df:e3:d1
   vmhba64:C0:T9:L30 LUN:30 state:active fc Adapter: WWNN: 20:00:00:90:fa:e0:ec:8e WWPN: 10:00:00:90:fa:e0:ec:8e  Target: WWNN: 20:49:00:a0:98:df:e3:d1 WWPN: 20:4c:00:a0:98:df:e3:d1
   vmhba64:C0:T5:L30 LUN:30 state:standby fc Adapter: WWNN: 20:00:00:90:fa:e0:ec:8e WWPN: 10:00:00:90:fa:e0:ec:8e  Target: WWNN: 20:49:00:a0:98:df:e3:d1 WWPN: 20:4a:00:a0:98:df:e3:d1
   vmhba65:C0:T0:L30 LUN:30 state:standby fc Adapter: WWNN: 20:00:00:90:fa:e0:ec:8f WWPN: 10:00:00:90:fa:e0:ec:8f  Target: WWNN: 20:49:00:a0:98:df:e3:d1 WWPN: 20:4b:00:a0:98:df:e3:d1

uuid.49de7683950d47c9898f51443d893910 : NVMe Fibre Channel Disk (uuid.49de7683950d47c9898f51443d893910)
   vmhba65:C0:T12:L39 LUN:39 state:active fc Adapter: WWNN: 20:00:00:90:fa:e0:ec:8f WWPN: 10:00:00:90:fa:e0:ec:8f  Target: WWNN: 20:3a:00:a0:98:df:e3:d1 WWPN: 20:27:00:a0:98:df:e3:d1
   vmhba65:C0:T13:L39 LUN:39 state:standby fc Adapter: WWNN: 20:00:00:90:fa:e0:ec:8f WWPN: 10:00:00:90:fa:e0:ec:8f  Target: WWNN: 20:3a:00:a0:98:df:e3:d1 WWPN: 20:29:00:a0:98:df:e3:d1
   vmhba64:C0:T12:L39 LUN:39 state:active fc Adapter: WWNN: 20:00:00:90:fa:e0:ec:8e WWPN: 10:00:00:90:fa:e0:ec:8e  Target: WWNN: 20:3a:00:a0:98:df:e3:d1 WWPN: 20:3b:00:a0:98:df:e3:d1
   vmhba64:C0:T13:L39 LUN:39 state:standby fc Adapter: WWNN: 20:00:00:90:fa:e0:ec:8e WWPN: 10:00:00:90:fa:e0:ec:8e  Target: WWNN: 20:3a:00:a0:98:df:e3:d1 WWPN: 20:28:00:a0:98:df:e3:d1
----
+

NOTE: ONTAP 9.7 では、 NVMe/FC ネームスペースのデフォルトのブロックサイズは 4K です。このデフォルトサイズは ESXi に対応していません。したがって、 ESXi のネームスペースを作成する場合は、ネームスペースブロックサイズを 512b に設定する必要があります。これを行うには、「 vserver nvme namespace create 」コマンドを使用します。

+
vserver nvme namespace create -vserver vs_1 -path /vol/namespace1-size 100g -ostype vmware-block-size 512B

+
を参照してください link:https://docs.netapp.com/ontap-9/index.jsp?topic=%2Fcom.netapp.doc.dot-cm-cmpr-970%2Fvserver__nvme__namespace__create.html["詳細については、 ONTAP 9 コマンドのマニュアルページを参照してください"]。

. それぞれの NVMe/FC ネームスペースデバイスの個々の ANA パスのステータスを確認します。
+
[listing]
----
# esxcli storage hpp path list
fc.20000090fae0ec8f:10000090fae0ec8f-fc.204900a098dfe3d1:204d00a098dfe3d1-uuid.1aa669c5376240a28ae47d8d549586ea
   Runtime Name: vmhba65:C0:T9:L33
   Device: uuid.1aa669c5376240a28ae47d8d549586ea
   Device Display Name: NVMe Fibre Channel Disk (uuid.1aa669c5376240a28ae47d8d549586ea)
   Path State: active

fc.20000090fae0ec8e:10000090fae0ec8e-fc.204900a098dfe3d1:204a00a098dfe3d1-uuid.1aa669c5376240a28ae47d8d549586ea
   Runtime Name: vmhba64:C0:T5:L33
   Device: uuid.1aa669c5376240a28ae47d8d549586ea
   Device Display Name: NVMe Fibre Channel Disk (uuid.1aa669c5376240a28ae47d8d549586ea)
   Path State: standby
----

