---
sidebar: sidebar 
permalink: nvme_aix.html 
keywords: nvme, linux, rhel, red hat, enterprise, aix, ontap 
summary: ONTAPを使用するAIX用のNVMe/FCホストの設定方法 
---
= ONTAPを使用したAIXのNVMe/FCホスト構成
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
NVMe/FCは、ONTAPストレージをターゲットとして使用して、IBM AIXホストおよびVIOS/PowerVMホストで有効にすることができます。サポートされる構成の詳細については、を参照してください link:https://mysupport.netapp.com/matrix/["NetApp Interoperability Matrix Tool で確認できます"^]。

ONTAPを備えたAIXホストでは、NVMe/FCホスト構成が次のようにサポートされます。

* ONTAP 9.13.1以降では、IBM AIX 7.2 TL5 SP6、AIX 7.3 TL1 SP2、およびVIOS 3.1.4.21リリースでNVMe over Fibre Channel（NVMe/FC）のサポートが追加され、物理スタックと仮想スタックの両方でSANブートがサポートされます。SANブートサポートの設定の詳細については、IBMのドキュメントを参照してください。
* NVMe/FCは、POWER9およびPower10 IBMサーバでのみサポートされます。
* NVMeデバイスには、AIX SCSI MPIOサポート用のHUKなど、個別のPCM（Path Control Module）は必要ありません。
* VIOS 3.1.4.21では、NetApp（VIOS/PowerVM）による仮想化のサポートが導入されました。これは、Power10 IBMサーバを使用したNPIV（N_PortID Virtualization）ストレージ仮想化モードでのみサポートされます。


.必要なもの
* アダプタファームウェア12.4.257.30以降のバージョンの32Gb FC Emulexアダプタ（EN1A、EN1B、EN1L、EN1M）または64Gb FCアダプタ（EN1N、EN1P）があることを確認します。
* MetroCluster構成を使用している場合は、AIXオペレーティングシステムによるI/Oタイムアウトの短縮を回避するために、MetroCluster計画外スイッチオーバーイベントがサポートされるように、AIX NVMe/FCのデフォルトのAPD（All Path Down）時間を変更することを推奨します。追加情報および推奨されるデフォルト設定の変更については、パブリックレポート1553249を参照してください。
* デフォルトでは、AIXホストOSのANATT値は30秒です。IBMは、ANATT値を60秒に制限するInterim Fix（IFIX）を提供しています。すべてのONTAPワークフローが無停止であることを確認するには、IBMのWebサイトからIFIXをインストールする必要があります。
+

NOTE: NVMe/FC AIXをサポートするには、GAバージョンのAIX OSにIFIXをインストールする必要があります。これは、VIOS/PowerVM OSでは必要ありません。

+
IFIXの詳細は次のとおりです。

+
** AIXレベル72-TL5-SP6-2320の場合は、をインストールします `IJ46710s6a.230509.epkg.Z` パッケージ。
** AIXレベル73-TL1-SP2-2320の場合は、をインストールします `IJ46711s2a.230509.epkg.Z` パッケージ。
+
ifixの管理の詳細については、を参照してください link:http://www-01.ibm.com/support/docview.wss?uid=isg3T1012104["AIXでの暫定修正の管理"^]。

+

NOTE: に関連する以前にインストールされたifixがないAIXバージョンにifixをインストールする必要があります `devices.pciex.pciexclass.010802.rte` システム上。これらのifixが存在する場合、新しいインストールと競合します。

+
次の表に、非仮想化モードでAIX LPAR（AIX論理パーティション）または物理/ネイティブスタックに割り当てられたHBAを示します。

+
[cols="10,10,10,10,10"]
|===
| ホストOS | パワーアーチ | 電源FWバージョン | モード | コメント 


.2+| AIX 7.2 TL5 SP6 | POWER9 | Fw 950以降 | 物理スタック | IFIXはTS012877410から入手できます。 


| パワー10 | Fw 1010以降 | 物理スタック | SANブーティングがサポートされています。IFIXはTS012877410から入手できます。 


.2+| AIX 7.3 TL1 SP2 | POWER9 | Fw 950以降 | 物理スタック | IFIXはTS012877410から入手できます。 


| パワー10 | Fw 1010以降 | 物理スタックと仮想スタック | IFIXはTS012877410から入手できます。 
|===
+
次の表に、仮想化モードでNPIV対応サポートを使用するVIOSに割り当てられたHBAを示します。

+
[cols="10,10,10,10,10"]
|===
| ホストOS | パワーアーチ | 電源FWバージョン | モード | コメント 


| VIOS/PowerVM 3.1.4.21 | パワー10 | Fw 1010以降 | 仮想スタック | サポートは、AIX 7.3 TL1 SP2 for VIOCcから開始されます 
|===






== 既知の制限

ONTAPを使用したAIXでのNVMe/FCホスト構成には、次の既知の制限事項があります。

* AIXホスト上のQLogic / Marvel 32G FC HBAでは、NVMe/FCはサポートされません。
* POWER9 IBMサーバを使用するNVMe/FCデバイスでは、SANブートはサポートされません。




== マルチパス

NVMeマルチパスに使用されるIBM MPIO（マルチパスI/O）は、AIX OSのインストール時にデフォルトで提供されます。

を使用して、AIXホストでNVMeマルチパスが有効になっていることを確認できます `lsmpio` コマンドを実行します

[listing]
----
#[root@aix_server /]: lsmpio -l hdisk1
----
*出力例*

[listing]
----
name     path_id  status   path_status  parent  connection
hdisk1  8         Enabled  Sel,Opt       nvme12  fcnvme0, 9
hdisk1  9         Enabled  Sel,Non       nvme65  fcnvme1, 9
hdisk1  10        Enabled  Sel,Opt       nvme37  fcnvme1, 9
hdisk1  11        Enabled  Sel,Non       nvme60  fcnvme0, 9
----


== NVMe/FC を設定

次の手順を使用して、Broadcom/Emulexアダプタ用にNVMe/FCを設定できます。

.手順
. サポートされているアダプタを使用していることを確認します。サポートされているアダプタの最新のリストについては、を参照してください link:https://mysupport.netapp.com/matrix/["NetApp Interoperability Matrix Tool で確認できます"^]。
. NVMe/FCプロトコルのサポートは、物理FCではデフォルトで有効になっていますが、NVMe/FCプロトコルのサポートは、Virtual I/O Server（VIOS）のVirtual Fibre Channel（VFC；仮想ファイバチャネル）では無効になっています。NVMe/FCのサポートが無効になっているアダプタのリストを取得します。
+
[listing]
----
$ lsmap -all -npiv
----
+
*出力例*

+
[listing]
----
Name          Physloc                            ClntID ClntName       ClntOS
------------- ---------------------------------- ------ -------------- -------
vfchost0      U9105.22A.785DB61-V2-C2                 4 s1022-iop-mcc- AIX
Status:LOGGED_IN
FC name:fcs4                    FC loc code:U78DA.ND0.WZS01UY-P0-C7-T0
Ports logged in:3
Flags:0xea<LOGGED_IN,STRIP_MERGE,SCSI_CLIENT,NVME_CLIENT>
VFC client name:fcs0            VFC client DRC:U9105.22A.785DB61-V4-C2
Name          Physloc                            ClntID ClntName       ClntOS
------------- ---------------------------------- ------ -------------- -------
vfchost1      U9105.22A.785DB61-V2-C3                 4
Status:NOT_LOGGED_IN
FC name:                        FC loc code:
Ports logged in:0
Flags:0x81<NOT_MAPPED,NOT_CONNECTED>
VFC client name:                VFC client DRC:
----
. を実行して、アダプタでNVMe/FCプロトコルのサポートを有効にします `ioscli vfcctrl` VIOSでのコマンド：
+
[listing]
----
$  vfcctrl -enable -protocol nvme -vadapter vfchost0
----
+
*出力例*

+
[listing]
----
The "nvme" protocol for "vfchost0" is enabled.
----
. アダプタでサポートが有効になっていることを確認します。
+
[listing]
----
# lsattr -El vfchost0
----
+
*出力例*

+
[listing]
----
alt_site_wwpn       WWPN to use - Only set after migration   False
current_wwpn  0     WWPN to use - Only set after migration   False
enable_nvme   yes   Enable or disable NVME protocol for NPIV True
label               User defined label                       True
limit_intr    false Limit NPIV Interrupt Sources             True
map_port      fcs4  Physical FC Port                         False
num_per_nvme  0     Number of NPIV NVME queues per range     True
num_per_range 0     Number of NPIV SCSI queues per range     True
----
. 現在のすべてのアダプタまたは選択したアダプタに対してNVMe/FCプロトコルを有効にします。
+
.. すべてのアダプタに対してNVMe/FCプロトコルを有効にします。
+
... を変更します `dflt_enabl_nvme` の属性値 `viosnpiv0` 疑似デバイスをに送信します `yes`。
... を設定します `enable_nvme` 属性値をに設定します `yes` すべてのVFCホストデバイスに対して。
+
[listing]
----
# chdev -l viosnpiv0 -a dflt_enabl_nvme=yes
----
+
[listing]
----
# lsattr -El viosnpiv0
----
+
*出力例*

+
[listing]
----
bufs_per_cmd    10  NPIV Number of local bufs per cmd                    True
dflt_enabl_nvme yes Default NVME Protocol setting for a new NPIV adapter True
num_local_cmds  5   NPIV Number of local cmds per channel                True
num_per_nvme    8   NPIV Number of NVME queues per range                 True
num_per_range   8   NPIV Number of SCSI queues per range                 True
secure_va_info  no  NPIV Secure Virtual Adapter Information              True
----


.. を変更して、選択したアダプタのNVMe/FCプロトコルを有効にします `enable_nvme` へのVFCホストデバイス属性の値 `yes`。


. 確認します `FC-NVMe Protocol Device` がサーバに作成されました：
+
[listing]
----
# [root@aix_server /]: lsdev |grep fcnvme
----
+
* exmaple output *

+
[listing]
----
fcnvme0       Available 00-00-02    FC-NVMe Protocol Device
fcnvme1       Available 00-01-02    FC-NVMe Protocol Device
----
. サーバからホストのNQNを記録します。
+
[listing]
----
# [root@aix_server /]: lsattr -El fcnvme0
----
+
*出力例*

+
[listing]
----
attach     switch                                                               How this adapter is connected  False
autoconfig available                                                            Configuration State            True
host_nqn   nqn.2014-08.org.nvmexpress:uuid:64e039bd-27d2-421c-858d-8a378dec31e8 Host NQN (NVMe Qualified Name) True
----
+
[listing]
----
[root@aix_server /]: lsattr -El fcnvme1
----
+
*出力例*

+
[listing]
----
attach     switch                                                               How this adapter is connected  False
autoconfig available                                                            Configuration State            True
host_nqn   nqn.2014-08.org.nvmexpress:uuid:64e039bd-27d2-421c-858d-8a378dec31e8 Host NQN (NVMe Qualified Name) True
----
+
.. パーティションUUIDを表示します。
+
[listing]
----
[root@aix_server /]: lsattr -El sys0 -a partition_uuid
----
+
*出力例*

+
[listing]
----
partition_uuid 64e039bd-27d2-421c-858d-8a378dec31e8 Partition UUID False
----


. ホストのNQNをチェックし、ONTAPアレイの対応するサブシステムのホストのNQN文字列と一致することを確認します。
+
[listing]
----
::> vserver nvme subsystem host show -vserver vs_s922-55-lpar2
----
+
*出力例*

+
[listing]
----
Vserver         Subsystem                Host NQN
------- --------- ----------------------------------------------------------
vs_s922-55-lpar2 subsystem_s922-55-lpar2 nqn.2014-08.org.nvmexpress:uuid:64e039bd-27d2-421c-858d-8a378dec31e8
----
. イニシエータポートが動作しており、ターゲットLIFが表示されていることを確認します。




== NVMe/FC を検証

ONTAPネームスペースがホストに正しく反映されていることを確認する必要があります。これを行うには、次のコマンドを実行します。

[listing]
----
# [root@aix_server /]: lsdev -Cc disk |grep NVMe
----
*出力例*

[listing]
----
hdisk1  Available 00-00-02 NVMe 4K Disk
----
マルチパスのステータスを確認できます。

[listing]
----
#[root@aix_server /]: lsmpio -l hdisk1
----
*出力例*

[listing]
----
name     path_id  status   path_status  parent  connection
hdisk1  8        Enabled  Sel,Opt      nvme12  fcnvme0, 9
hdisk1  9        Enabled  Sel,Non      nvme65  fcnvme1, 9
hdisk1  10       Enabled  Sel,Opt      nvme37  fcnvme1, 9
hdisk1  11       Enabled  Sel,Non      nvme60  fcnvme0, 9
----


== 既知の問題

ONTAPを備えたAIXでのNVMe/FCホストの設定には、次の既知の問題があります。

[cols="10,30,30"]
|===
| BURT ID | タイトル | 説明 


| 1553249 | MCC計画外スイッチオーバーイベントをサポートするために変更されるAIX NVMe/FCのデフォルトAPD時間 | AIXオペレーティングシステムでは、NVMe/FCにデフォルトでAll Path Down（APD）タイムアウト値の20秒が使用されます。  ただし、ONTAP MetroClusterの自動計画外スイッチオーバー（AUSO）とTiebreakerで開始されるスイッチオーバーのワークフローには、APDのタイムアウト時間よりも少し時間がかかり、I/Oエラーが発生することがあります。 


| 1546017だ | AIX NVMe/FCではANATTの上限が60秒に設定されていますが、ONTAPでは120秒に設定されています | ONTAPは、120秒のコントローラ識別でANA（非対称ネームスペースアクセス）移行タイムアウトをアドバタイズします。現在、IFIXでは、AIXはコントローラ識別からANA移行タイムアウトを読み取りますが、その制限を超えている場合は実質的に60秒にクランプします。 


| 1541386年 | AIX NVMe/FCがANATTの有効期限後にEIOにヒットしました | Storage Failover（SFO；ストレージフェイルオーバー）イベントが発生した場合、特定のパスでANA（非対称ネームスペースアクセス）移行がタイムアウトの上限を超えると、ネームスペースへの正常な代替パスがあるにもかかわらず、AIX NVMe/FCホストがI/Oエラーで失敗します。 


| 1541380 | AIX NVMe/FCは、ANATTのハーフ/フルの有効期限が切れるまで待機してから、ANA AENのあとにI/Oを再開します | IBM AIX NVMe/FCでは、ONTAPで公開されるAsynchronous Notification（AEN；非同期通知）の一部がサポートされません。このように最適化されていないANA処理は、SFO処理中に最適化されていません。 
|===


== トラブルシューティング

NVMe/FCの障害をトラブルシューティングする前に、実行している構成がIMT の仕様に準拠していることを確認してから、次の手順に進んでホスト側の問題をデバッグします。



=== 詳細ログを有効にします

構成に問題 が含まれている場合は、詳細なロギングを使用してトラブルシューティングに必要な情報を得ることができます。

.手順
Qlogicの詳細ロギングを設定する手順 （qla2xxx）は、lpfc詳細ロギングを設定する手順 とは異なります。

[role="tabbed-block"]
====
.LPFC
--
.手順
. を設定します `lpfc_log_verbose` NVMe/FCイベントをログに記録するためのドライバ設定は次のいずれかです。
+
[listing]
----
#define LOG_NVME 0x00100000 /* NVME general events. */
#define LOG_NVME_DISC 0x00200000 /* NVME Discovery/Connect events. */
#define LOG_NVME_ABTS 0x00400000 /* NVME ABTS events. */
#define LOG_NVME_IOERR 0x00800000 /* NVME IO Error events. */
----
. 値を設定したら、を実行します `dracut-f` コマンドを実行し、ホストをリブートします。
. 設定を確認します。
+
[listing]
----
# cat /etc/modprobe.d/lpfc.conf
options lpfc lpfc_log_verbose=0xf00083

# cat /sys/module/lpfc/parameters/lpfc_log_verbose
15728771
----


--
.qla2xxx
--
NVMe/FCについては、同様の固有のqla2xxxロギングはありません `lpfc` ドライバ。したがって、次の手順を使用して一般的なqla2xxxログレベルを設定できます。

.手順
. 対応する「 m odprobe qla2xxx conf 」ファイルに「 ql2xextended_error_logging=0x1e400000 」の値を追加します。
. 「 d racut-f 」コマンドを実行して「 initramfs 」を再作成し、ホストを再起動します。
. リブート後、次のように詳細ログが適用されていることを確認します。
+
[listing]
----
# cat /etc/modprobe.d/qla2xxx.conf
options qla2xxx ql2xnvmeenable=1 ql2xextended_error_logging=0x1e400000
# cat /sys/module/qla2xxx/parameters/ql2xextended_error_logging
507510784
----


--
====


=== 一般的なnvme-CLIエラーとその回避策があります

によって表示されるエラーです `nvme-cli` 実行中 `nvme discover`、 `nvme connect`または `nvme connect-all` 処理とその対処方法を次の表に示します。

[cols="20, 20, 50"]
|===
| エラーは 'nvme-cli' によって表示されます | 原因と考えられます | 回避策 


| '/dev/nvme-Fabrics への書き込みに失敗しました : 引数が無効です | 構文が正しくありません | の正しい構文を使用していることを確認します `nvme discover`、 `nvme connect`および `nvme connect-all` コマンド 


| '/dev/nvme-Fabrics への書き込みに失敗しました : このようなファイルまたはディレクトリはありません | NVMeコマンドに誤った引数を指定した場合など、複数の問題が原因でこのエラーがトリガーされることがあります。  a| 
* コマンドに正しい引数（正しいWWNN文字列、WWPN文字列など）が渡されたことを確認します。
* 引数が正しいにもかかわらず、このエラーが引き続き表示される場合は、を確認してください `/sys/class/scsi_host/host*/nvme_info` コマンドの出力は正しいですが、NVMeイニシエータはと表示されます `Enabled`、およびNVMe/FCターゲットLIFがリモートポートのセクションに正しく表示されます。例
+
[listing]
----

# cat /sys/class/scsi_host/host*/nvme_info
NVME Initiator Enabled
NVME LPORT lpfc0 WWPN x10000090fae0ec9d WWNN x20000090fae0ec9d DID x012000 ONLINE
NVME RPORT WWPN x200b00a098c80f09 WWNN x200a00a098c80f09 DID x010601 TARGET DISCSRVC ONLINE
NVME Statistics
LS: Xmt 0000000000000006 Cmpl 0000000000000006
FCP: Rd 0000000000000071 Wr 0000000000000005 IO 0000000000000031
Cmpl 00000000000000a6 Outstanding 0000000000000001
NVME Initiator Enabled
NVME LPORT lpfc1 WWPN x10000090fae0ec9e WWNN x20000090fae0ec9e DID x012400 ONLINE
NVME RPORT WWPN x200900a098c80f09 WWNN x200800a098c80f09 DID x010301 TARGET DISCSRVC ONLINE
NVME Statistics
LS: Xmt 0000000000000006 Cmpl 0000000000000006
FCP: Rd 0000000000000073 Wr 0000000000000005 IO 0000000000000031
Cmpl 00000000000000a8 Outstanding 0000000000000001
----
* ターゲットLIFがに表示されない場合は、で上記のように表示されます `nvme_info` コマンドの出力で、を確認します `/var/log/messages` および `dmesg` 疑わしいNVMe/FCエラーがないかどうかをコマンドで出力し、状況に応じて報告または修正




| ' 取得する検出ログエントリがありません  a| 
一般的には、が観察されます `/etc/nvme/hostnqn` 文字列がネットアップアレイの対応するサブシステムに追加されていないか、正しくありません `hostnqn` 文字列がそれぞれのサブシステムに追加されています。
 a| 
が正確であることを確認します `/etc/nvme/hostnqn` 文字列がネットアップアレイの対応するサブシステムに追加されます（を使用して確認してください） `vserver nvme subsystem host show` コマンド）。



| '/dev/nvme-Fabrics への書き込みに失敗しました：オペレーションはすでに進行中です  a| 
コントローラの関連付けまたは指定された操作がすでに作成されている場合、または作成中に発生した場合に表示されます。これは、上記にインストールされている自動接続スクリプトの一部として発生する可能性があります。
 a| 
なしを実行してみてください `nvme discover` しばらくしてからもう一度コマンドを実行してください。の場合 `nvme connect` および `connect-all`を実行します `nvme list` コマンドを使用して、ネームスペースデバイスが作成済みで、ホストに表示されていることを確認します。

|===


=== テクニカルサポートへの連絡のタイミング

問題が解決しない場合は、次のファイルとコマンドの出力を収集し、テクニカルサポートに問い合わせてトリアージを依頼してください。

[listing]
----
cat /sys/class/scsi_host/host*/nvme_info
/var/log/messages
dmesg
nvme discover output as in:
nvme discover --transport=fc --traddr=nn-0x200a00a098c80f09:pn-0x200b00a098c80f09 --host-traddr=nn-0x20000090fae0ec9d:pn-0x10000090fae0ec9d
nvme list
nvme list-subsys /dev/nvmeXnY
----