---
sidebar: sidebar 
permalink: nvme_windows_2016.html 
keywords: nvme, windows, enterprise 
summary: ONTAP を使用した Windows Server 2016 の NVMe/FC ホスト構成 
---
= ONTAP を使用した Windows Server 2016 の NVMe/FC ホスト構成
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content




== サポート性

NVMe/FC は Windows Server 2016 の ONTAP 9.7 以降でサポートされます。

Broadcom イニシエータは、 NVMe/FC と FCP の両方のトラフィックを同じ 32G FC アダプタポートで処理できます。FCP および FC/NVMe の場合は、 Microsoft Multipath I/O （ MPIO ；マルチパス I/O ）オプションとして MSDSM を使用してください。

を参照してください link:https://hwu.netapp.com/Home/Index["Hardware Universe"^] サポートされる FC アダプタおよびコントローラの一覧を表示するには、を参照してください。サポートされている構成およびバージョンの最新のリストについては、を参照してください link:https://mysupport.netapp.com/matrix/["NetApp Interoperability Matrix を参照してください"^]。



== 既知の制限

ONTAP NVMe/FC では、 ONTAP は現在 NVMe/FC での永続的予約をサポートしていないため、 Windows Failover Cluster （ WFC ； Windows フェイルオーバークラスタ）はサポートされません。


NOTE: Broadcom for Windows NVMe/FC によって出荷された外部ドライバは、真の NVMe/FC ドライバではなく、トランスレーショナル SCSI の一時的な NVMe ドライバです。このトランスレーショナルのオーバーヘッドは必ずしもパフォーマンスに影響するわけではありませんが、 NVMe/FC のパフォーマンス上の利点には影響しません。したがって、 Windows サーバでは、 NVMe/FC と FCP のパフォーマンスは同じです。 Linux などの他のオペレーティングシステムでは、 FCP よりも NVMe/FC のパフォーマンスが大幅に向上します。



== Windows イニシエータホストで NVMe/FC を有効にします

Windows イニシエータホストで FC / NVMe を有効にするには、次の手順を実行します。

. Windows ホストに OneCommand Manager ユーティリティをインストールします。
. 各 HBA イニシエータポートで、次の HBA ドライバパラメータを設定します。
+
** EnableNVMe = 1
** NVMEMode = 0
** 転送サイズ = 1


. ホストをリブートします。




== Windows で NVMe/FC 用に Broadcom FC アダプタを設定します

Windows 環境の FC/NVMe 用 Broadcom アダプタでは '+hostnqn+' が各 HBA ポートに関連付けられます「 + hostnqn+' 」は次のようにフォーマットされます。

....
nqn.2017-01.com.broadcom:ecd:nvmf:fc:100000109b1b9765
nqn.2017-01.com.broadcom:ecd:nvmf:fc:100000109b1b9766
....


=== Windows ホストで NVMe デバイスの MPIO を有効にします

. Windows Host Utility Kit 7.1 をインストールして、 FC と NVMe の両方に共通のドライバパラメータを設定します。
. MPIO のプロパティを開きます。
. [* マルチパスの検出 * ] タブで、 NVMe 用にリストされたデバイス ID を追加します。
+
MPIO は NVMe デバイスを認識し、 NVMe デバイスはディスク管理の下に表示されます。

. 「 * ディスクの管理」を開き、「 * ディスクのプロパティ * 」に移動します。
. [*MPIO*] タブで、 [*Details*] をクリックします。
. 次の MSDSM 設定を設定します。
+
** PathVerififiedPeriod ： * 10 *
** PathVerifyEnabled ： * Enable *
** RetryCount ： * 6 *
** 再試行間隔： * 1 *
** PDORemovedPeriod ： * 130*


. MPIO ポリシー * サブセット付きラウンドロビン * を選択します。
. レジストリ値を変更します。
+
[listing]
----
HKLM\SYSTEM\CurrentControlSet\Services\mpio\Parameters\PathRecoveryInterval DWORD -> 30

HKLM\SYSTEM\CurrentControlSet\Services\mpio \Parameters\ UseCustomPathRecoveryInterval  DWORD-> 1
----
. ホストをリブートします。
+
これで、 Windows ホストで NVMe の設定が完了しました。





== NVMe/FC を検証

. ポートタイプが FC + NVMe であることを確認します。
+
NVMe が有効になったので ' 次のように '+ Port Type+' が +FC+NVMe+' として表示されます

+
[listing]
----
PS C:\Program Files\Emulex\Util\OCManager> .\hbacmd listhba

Manageable HBA List

Port WWN       : 10:00:00:10:9b:1b:97:65
Node WWN       : 20:00:00:10:9b:1b:97:65
Fabric Name    : 10:00:c4:f5:7c:a5:32:e0
Flags          : 8000e300
Host Name      : INTEROP-57-159
Mfg            : Emulex Corporation
Serial No.     : FC71367217
Port Number    : 0
Mode           : Initiator
PCI Bus Number : 94
PCI Function   : 0
Port Type      : FC+NVMe
Model          : LPe32002-M2

Port WWN       : 10:00:00:10:9b:1b:97:66
Node WWN       : 20:00:00:10:9b:1b:97:66
Fabric Name    : 10:00:c4:f5:7c:a5:32:e0
Flags          : 8000e300
Host Name      : INTEROP-57-159
Mfg            : Emulex Corporation
Serial No.     : FC71367217
Port Number    : 1
Mode           : Initiator
PCI Bus Number : 94
PCI Function   : 1
Port Type      : FC+NVMe
Model          : LPe32002-M2
----
. NVMe/FC サブシステムが検出されたことを確認してください。
+
「 +nvme-list+` 」コマンドは、 NVMe/FC によって検出されたサブシステムを一覧表示します。

+
[listing]
----
PS C:\Program Files\Emulex\Util\OCManager> .\hbacmd nvme-list 10:00:00:10:9b:1b:97:65

Discovered NVMe Subsystems for 10:00:00:10:9b:1b:97:65

NVMe Qualified Name     :  nqn.1992-08.com.netapp:sn.a3b74c32db2911eab229d039ea141105:subsystem.win_nvme_interop-57-159
Port WWN                :  20:09:d0:39:ea:14:11:04
Node WWN                :  20:05:d0:39:ea:14:11:04
Controller ID           :  0x0180
Model Number            :  NetApp ONTAP Controller
Serial Number           :  81CGZBPU5T/uAAAAAAAB
Firmware Version        :  FFFFFFFF
Total Capacity          :  Not Available
Unallocated Capacity    :  Not Available

NVMe Qualified Name     :  nqn.1992-08.com.netapp:sn.a3b74c32db2911eab229d039ea141105:subsystem.win_nvme_interop-57-159
Port WWN                :  20:06:d0:39:ea:14:11:04
Node WWN                :  20:05:d0:39:ea:14:11:04
Controller ID           :  0x0181
Model Number            :  NetApp ONTAP Controller
Serial Number           :  81CGZBPU5T/uAAAAAAAB
Firmware Version        :  FFFFFFFF
Total Capacity          :  Not Available
Unallocated Capacity    :  Not Available
Note: At present Namespace Management is not supported by NetApp Arrays.
----
+
[listing]
----
PS C:\Program Files\Emulex\Util\OCManager> .\hbacmd nvme-list 10:00:00:10:9b:1b:97:66

Discovered NVMe Subsystems for 10:00:00:10:9b:1b:97:66

NVMe Qualified Name     :  nqn.1992-08.com.netapp:sn.a3b74c32db2911eab229d039ea141105:subsystem.win_nvme_interop-57-159
Port WWN                :  20:07:d0:39:ea:14:11:04
Node WWN                :  20:05:d0:39:ea:14:11:04
Controller ID           :  0x0140
Model Number            :  NetApp ONTAP Controller
Serial Number           :  81CGZBPU5T/uAAAAAAAB
Firmware Version        :  FFFFFFFF
Total Capacity          :  Not Available
Unallocated Capacity    :  Not Available

NVMe Qualified Name     :  nqn.1992-08.com.netapp:sn.a3b74c32db2911eab229d039ea141105:subsystem.win_nvme_interop-57-159
Port WWN                :  20:08:d0:39:ea:14:11:04
Node WWN                :  20:05:d0:39:ea:14:11:04
Controller ID           :  0x0141
Model Number            :  NetApp ONTAP Controller
Serial Number           :  81CGZBPU5T/uAAAAAAAB
Firmware Version        :  FFFFFFFF
Total Capacity          :  Not Available
Unallocated Capacity    :  Not Available

Note: At present Namespace Management is not supported by NetApp Arrays.
----
. ネームスペースが作成されていることを確認します。
+
「 +nvme-list-ns+` 」コマンドは、ホストに接続されているネームスペースを一覧表示する、指定された NVMe ターゲットのネームスペースを一覧表示します。

+
[listing]
----
PS C:\Program Files\Emulex\Util\OCManager> .\HbaCmd.exe nvme-list-ns 10:00:00:10:9b:1b:97:66 20:08:d0:39:ea:14:11:04 nq
.1992-08.com.netapp:sn.a3b74c32db2911eab229d039ea141105:subsystem.win_nvme_interop-57-159 0


Active Namespaces (attached to controller 0x0141):

                                       SCSI           SCSI           SCSI
   NSID           DeviceName        Bus Number    Target Number     OS LUN
-----------  --------------------  ------------  ---------------   ---------
0x00000001   \\.\PHYSICALDRIVE9         0               1              0
0x00000002   \\.\PHYSICALDRIVE10        0               1              1
0x00000003   \\.\PHYSICALDRIVE11        0               1              2
0x00000004   \\.\PHYSICALDRIVE12        0               1              3
0x00000005   \\.\PHYSICALDRIVE13        0               1              4
0x00000006   \\.\PHYSICALDRIVE14        0               1              5
0x00000007   \\.\PHYSICALDRIVE15        0               1              6
0x00000008   \\.\PHYSICALDRIVE16        0               1              7

----

