---
sidebar: sidebar 
permalink: nvme-rhel-10x.html 
keywords: nvme, linux, rhel, red hat, enterprise 
summary: ONTAPを使用した RHEL 10x 向け NVMe-oF ホストの設定方法 
---
= ONTAPストレージを使用して RHEL 10x を NVMe-oF 用に構成する
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Red Hat Enterpirse Linux (RHEL) ホストは、非対称名前空間アクセス (ANA) を備えた NVMe over Fibre Channel (NVMe/FC) および NVMe over TCP (NVMe/TCP) プロトコルをサポートします。  ANA は、iSCSI および FCP 環境における非対称論理ユニット アクセス (ALUA) と同等のマルチパス機能を提供します。

RHEL 10x 用の NVMe over Fabrics (NVMe-oF) ホストを構成する方法を学習します。詳細なサポートと機能情報については、 link:nvme-rhel-supported-features.html["RHEL ONTAPのサポートと機能"]。

RHEL 10x の NVMe-oF には、次の既知の制限があります。

* その `nvme disconnect-all`このコマンドはルートファイルシステムとデータファイルシステムの両方を切断し、システムが不安定になる可能性があります。  NVMe-TCP または NVMe-FC 名前空間を介して SAN から起動するシステムではこれを発行しないでください。




== 手順1：必要に応じてSANブートを有効にします。

SAN ブートを使用するようにホストを構成すると、展開が簡素化され、スケーラビリティが向上します。使用link:https://mysupport.netapp.com/matrix/#welcome["Interoperability Matrix Tool"^]Linux OS、ホスト バス アダプタ (HBA)、HBA ファームウェア、HBA ブート BIOS、およびONTAPバージョンが SAN ブートをサポートしていることを確認します。

.手順
. https://docs.netapp.com/us-en/ontap/san-admin/create-nvme-namespace-subsystem-task.html["NVMe名前空間を作成し、ホストにマッピングする"^] 。
. SAN ブート名前空間がマップされているポートに対して、サーバー BIOS で SAN ブートを有効にします。
+
HBA BIOS を有効にする方法については、ベンダー固有のマニュアルを参照してください。

. ホストを再起動し、OS が起動して実行されていることを確認します。




== ステップ2: RHELとNVMeソフトウェアをインストールし、構成を確認する

NVMe-oF 用にホストを構成するには、ホストと NVMe ソフトウェア パッケージをインストールし、マルチパスを有効にして、ホストの NQN 構成を確認する必要があります。

.手順
. サーバーに RHEL 10x をインストールします。インストールが完了したら、必要な RHEL 10x カーネルが実行されていることを確認します。
+
[source, cli]
----
uname -r
----
+
RHEL カーネルバージョンの例:

+
[listing]
----
6.12.0-124.8.1.el10_1.x86_64
----
. 「 nvme-cli 」パッケージをインストールします。
+
[source, cli]
----
rpm -qa|grep nvme-cli
----
+
次の例は、  `nvme-cli`パッケージバージョン:

+
[listing]
----
nvme-cli-2.13-2.el10.x86_64
----
. をインストールします `libnvme` パッケージ：
+
[source, cli]
----
rpm -qa|grep libnvme
----
+
次の例は、  `libnvme`パッケージバージョン:

+
[listing]
----
libnvme-1.13-1.el10.x86_64
----
. ホスト上で、hostnqn文字列を確認します。  `/etc/nvme/hostnqn` ：
+
[source, cli]
----
cat /etc/nvme/hostnqn
----
+
次の例は、  `hostnqn`バージョン:

+
[listing]
----
nqn.2014-08.org.nvmexpress:uuid:4c4c4544-0056-5410-8048-c7c04f425633
----
. ONTAPシステムで、 `hostnqn`文字列が一致する `hostnqn`ONTAPストレージ システム上の対応するサブシステムの文字列:
+
[source, cli]
----
::> vserver nvme subsystem host show -vserver vs_coexistence_QLE2872
----
+
.例を示します
[%collapsible]
====
[listing]
----
Vserver Subsystem Priority  Host NQN
------- --------- --------  ------------------------------------------------
vs_coexistence_QLE2872
               subsystem_1
                         regular   nqn.2014-08.org.nvmexpress:uuid:4c4c4544-0056-5410-8048-c7c04f425633
               subsystem_10
                         regular   nqn.2014-08.org.nvmexpress:uuid:4c4c4544-0056-5410-8048-c7c04f425633
               subsystem_11
                         regular   nqn.2014-08.org.nvmexpress:uuid:4c4c4544-0056-5410-8048-c7c04f425633
----
====



NOTE: もし `hostnqn`文字列が一致しない場合は、 `vserver modify`更新するコマンド `hostnqn`対応するONTAPストレージシステムサブシステムの文字列を `hostnqn`文字列から `/etc/nvme/hostnqn`ホスト上。



== ステップ3: NVMe/FCとNVMe/TCPを構成する

Broadcom/Emulex または Marvell/QLogic アダプタを使用して NVMe/FC を構成するか、手動の検出および接続操作を使用して NVMe/TCP を構成します。

[role="tabbed-block"]
====
.NVMe/FC - ブロードコム/エミュレックス
--
Broadcom/Emulexアダプタ用にNVMe/FCを設定します。

. サポートされているアダプタモデルを使用していることを確認します。
+
.. モデル名を表示します。
+
[source, cli]
----
cat /sys/class/scsi_host/host*/modelname
----
+
次の出力が表示されます。

+
[listing]
----
SN1700E2P
SN1700E2P
----
.. モデルの説明を表示します。
+
[source, cli]
----
cat /sys/class/scsi_host/host*/modeldesc
----
+
次の例のような出力が表示されます。

+
[listing]
----
HPE SN1700E 64Gb 2p FC HBA
HPE SN1700E 64Gb 2p FC HBA
----


. 推奨されるBroadcomを使用していることを確認します `lpfc` ファームウェアおよび受信トレイドライバ：
+
.. ファームウェアのバージョンを表示します。
+
[source, cli]
----
cat /sys/class/scsi_host/host*/fwrev
----
+
このコマンドはファームウェアのバージョンを返します。

+
[listing]
----
14.4.393.25, sli-4:6:d
14.4.393.25, sli-4:6:d
----
.. 受信トレイのドライバーのバージョンを表示します。
+
[source, cli]
----
cat /sys/module/lpfc/version
----
+
次の例は、ドライバーのバージョンを示しています。

+
[listing]
----
0:14.4.0.9
----


+
サポートされているアダプタドライバおよびファームウェアバージョンの最新リストについては、を参照してくださいlink:https://mysupport.netapp.com/matrix/["Interoperability Matrix Tool"^]。

. 確認します `lpfc_enable_fc4_type` がに設定されます `3`：
+
[source, cli]
----
cat /sys/module/lpfc/parameters/lpfc_enable_fc4_type
----
. イニシエータポートを表示できることを確認します。
+
[source, cli]
----
cat /sys/class/fc_host/host*/port_name
----
+
次のような出力が表示されます。

+
[listing]
----
0x10005cba2cfca7de
0x10005cba2cfca7df
----
. イニシエータポートがオンラインであることを確認します。
+
[source, cli]
----
cat /sys/class/fc_host/host*/port_state
----
+
次の出力が表示されます。

+
[listing]
----
Online
Online
----
. NVMe/FCイニシエータポートが有効になっており、ターゲットポートが認識されることを確認します。
+
[source, cli]
----
cat /sys/class/scsi_host/host*/nvme_info
----
+
.例を示します
[%collapsible]
=====
[listing, subs="+quotes"]
----
NVME Initiator Enabled
XRI Dist lpfc0 Total 6144 IO 5894 ELS 250
NVME LPORT lpfc0 WWPN x10005cba2cfca7de WWNN x20005cba2cfca7de DID x080f00 *ONLINE*
NVME RPORT       WWPN x2023d039eac03c33 WWNN x2021d039eac03c33 DID x082209 *TARGET DISCSRVC ONLINE*
NVME RPORT       WWPN x200ed039eac03c33 WWNN x200cd039eac03c33 DID x082203 *TARGET DISCSRVC ONLINE*
NVME RPORT       WWPN x2022d039eac03c33 WWNN x2021d039eac03c33 DID x082609 *TARGET DISCSRVC ONLINE*
NVME RPORT       WWPN x200dd039eac03c33 WWNN x200cd039eac03c33 DID x082604 *TARGET DISCSRVC ONLINE*

NVME Statistics
LS: Xmt 0000000501 Cmpl 0000000501 Abort 00000000
LS XMIT: Err 00000000  CMPL: xb 00000000 Err 00000000
Total FCP Cmpl 00000000000583b7 Issue 000000000005840d OutIO 0000000000000056
abort 0000010f noxri 00000000 nondlp 00000000 qdepth 00000000 wqerr 00000000   err 00000000
FCP CMPL: xb 0000010f Err 0000010f

NVME Initiator Enabled
XRI Dist lpfc1 Total 6144 IO 5894 ELS 250
NVME LPORT lpfc1 WWPN x10005cba2cfca7df WWNN x20005cba2cfca7df DID x080b00 *ONLINE*
NVME RPORT       WWPN x2024d039eac03c33 WWNN x2021d039eac03c33 DID x082309 *TARGET DISCSRVC ONLINE*
NVME RPORT       WWPN x200fd039eac03c33 WWNN x200cd039eac03c33 DID x082304 *TARGET DISCSRVC ONLINE*
NVME RPORT       WWPN x2025d039eac03c33 WWNN x2021d039eac03c33 DID x082708 *TARGET DISCSRVC ONLINE*
NVME RPORT       WWPN x2010d039eac03c33 WWNN x200cd039eac03c33 DID x082703 *TARGET DISCSRVC ONLINE*

NVME Statistics
LS: Xmt 00000006eb Cmpl 00000006eb Abort 00000000
LS XMIT: Err 00000000  CMPL: xb 00000000 Err 00000000
Total FCP Cmpl 000000000004d600 Issue 000000000004d65f OutIO 000000000000005f
abort 000001c1 noxri 00000000 nondlp 00000000 qdepth 00000000 wqerr 00000000 err 00000000
FCP CMPL: xb 000001c1 Err 000001c2
----
=====


--
.NVMe/FC - マーベル/QLogic
--
Marvell/QLogicアダプタ用にNVMe/FCを設定します。

. サポートされているアダプタ ドライバーとファームウェア バージョンを使用していることを確認します。
+
[source, cli]
----
cat /sys/class/fc_host/host*/symbolic_name
----
+
次の例は、ドライバーとファームウェアのバージョンを示しています。

+
[listing]
----
QLE2872 FW:v9.15.06 DVR:v10.02.09.400-k
QLE2872 FW:v9.15.06 DVR:v10.02.09.400-k
----
. 確認します `ql2xnvmeenable` が設定されます。これにより、MarvellアダプタをNVMe/FCイニシエータとして機能させることができます。
+
[source, cli]
----
cat /sys/module/qla2xxx/parameters/ql2xnvmeenable
----
+
想定される出力は1です。



--
.NVMe/FC
--
NVMe/TCP プロトコルは自動接続操作をサポートしていません。代わりに、NVMe/TCPサブシステムと名前空間をNVMe/TCPコマンドで検出することができます。 `connect`または `connect-all`手動で操作します。

. イニシエーター ポートが、サポートされている NVMe/TCP LIF 全体で検出ログ ページ データを取得できることを確認します。
+
[source, cli]
----
nvme discover -t tcp -w host-traddr -a traddr
----
+
.例を示します
[%collapsible]
=====
[listing, subs="+quotes"]
----
nvme discover -t tcp -w 192.168.20.21 -a 192.168.20.28
Discovery Log Number of Records 8, Generation counter 10
=====Discovery Log Entry 0======
trtype:  tcp
adrfam:  ipv4
subtype: *current discovery subsystem*
treq:    not specified
portid:  8
trsvcid: 8009
subnqn:  nqn.1992-08.com.netapp:sn.17e32b6e8c7f11f09545d039eac03c33:discovery
traddr:  192.168.21.29
eflags:  *explicit discovery connections, duplicate discovery information*
sectype: none
=====Discovery Log Entry 1======
trtype:  tcp
adrfam:  ipv4
subtype: *current discovery subsystem*
treq:    not specified
portid:  6
trsvcid: 8009
subnqn:  nqn.1992-08.com.netapp:sn.17e32b6e8c7f11f09545d039eac03c33:discovery
traddr:  192.168.20.29
eflags:  *explicit discovery connections, duplicate discovery information*
sectype: none
=====Discovery Log Entry 2======
trtype:  tcp
adrfam:  ipv4
subtype: *current discovery subsystem*
treq:    not specified
portid:  7
trsvcid: 8009
subnqn:  nqn.1992-08.com.netapp:sn.17e32b6e8c7f11f09545d039eac03c33:discovery
traddr:  192.168.21.28
eflags:  *explicit discovery connections, duplicate discovery information*
sectype: none
=====Discovery Log Entry 3======
trtype:  tcp
adrfam:  ipv4
subtype: *current discovery subsystem*
treq:    not specified
portid:  5
trsvcid: 8009
subnqn:  nqn.1992-08.com.netapp:sn.17e32b6e8c7f11f09545d039eac03c33:discovery
traddr:  192.168.20.28
eflags:  *explicit discovery connections, duplicate discovery information*
sectype: none
=====Discovery Log Entry 4======
trtype:  tcp
adrfam:  ipv4
subtype: *nvme subsystem*
treq:    not specified
portid:  8
trsvcid: 4420
subnqn:  nqn.1992-08.com.netapp:sn.17e32b6e8c7f11f09545d039eac03c33:subsystem.Bidirectional_DHCP_1_0
traddr:  192.168.21.29
eflags:  none
sectype: none
=====Discovery Log Entry 5======
trtype:  tcp
adrfam:  ipv4
subtype: *nvme subsystem*
treq:    not specified
portid:  6
trsvcid: 4420
subnqn:  nqn.1992-08.com.netapp:sn.17e32b6e8c7f11f09545d039eac03c33:subsystem.Bidirectional_DHCP_1_0
traddr:  192.168.20.29
eflags:  none
sectype: none
=====Discovery Log Entry 6======
trtype:  tcp
adrfam:  ipv4
subtype: *nvme subsystem*
treq:    not specified
portid:  7
trsvcid: 4420
subnqn:  nqn.1992-08.com.netapp:sn.17e32b6e8c7f11f09545d039eac03c33:subsystem.Bidirectional_DHCP_1_0
traddr:  192.168.21.28
eflags:  none
sectype: none
=====Discovery Log Entry 7======
trtype:  tcp
adrfam:  ipv4
subtype: *nvme subsystem*
treq:    not specified
portid:  5
trsvcid: 4420
subnqn:  nqn.1992-08.com.netapp:sn.17e32b6e8c7f11f09545d039eac03c33:subsystem.Bidirectional_DHCP_1_0
traddr:  192.168.20.28
eflags:  none
sectype: non
----
=====
. 他の NVMe/TCP イニシエーターとターゲット LIF の組み合わせで検出ログ ページ データを正常に取得できることを確認します。
+
[source, cli]
----
nvme discover -t tcp -w host-traddr -a traddr
----
+
.例を示します
[%collapsible]
=====
[listing, subs="+quotes"]
----
nvme discover -t tcp -w 192.168.20.21 -a 192.168.20.28
nvme discover -t tcp -w 192.168.21.21 -a 192.168.21.28
nvme discover -t tcp -w 192.168.20.21 -a 192.168.20.29
nvme discover -t tcp -w 192.168.21.21 -a 192.168.21.29
----
=====
. を実行します `nvme connect-all` ノード全体でサポートされているすべてのNVMe/TCPイニシエータ/ターゲットLIFを対象としたコマンド：
+
[source, cli]
----
nvme connect-all -t tcp -w host-traddr -a traddr
----
+
.例を示します
[%collapsible]
=====
[listing, subs="+quotes"]
----
nvme	connect-all -t	tcp -w	192.168.20.21	-a 192.168.20.28
nvme	connect-all -t	tcp -w	192.168.21.21	-a 192.168.21.28
nvme	connect-all -t	tcp -w	192.168.20.21	-a 192.168.20.29
nvme	connect-all -t	tcp -w	192.168.21.21	-a 192.168.21.29
----
=====


[NOTE]
====
RHEL 9.4以降、NVMe/TCPの設定は `ctrl_loss_tmo timeout`自動的に「オフ」に設定されます。その結果、次のようになります

* 再試行回数に制限はありません（無期限再試行）。
* 特定の設定を手動で行う必要はありません `ctrl_loss_tmo timeout`使用時の持続時間 `nvme connect`または `nvme connect-all`コマンド（オプション -l ）。
* NVMe/TCP コントローラーは、パス障害が発生した場合でもタイムアウトが発生せず、無期限に接続されたままになります。


====
--
====


== ステップ4: オプションとして、udevルールのiopolicyを変更します。

RHEL 10.0ではNVMe-oFのデフォルトのiopolicyを次のように設定します。 `round-robin` 。RHEL 10.0を使用しており、iopolicyを次のように変更したい場合 `queue-depth`、udev ルール ファイルを次のように変更します。

.手順
. ルート権限でテキスト エディターで udev ルール ファイルを開きます。
+
[source, cli]
----
/usr/lib/udev/rules.d/71-nvmf-netapp.rules
----
+
次の出力が表示されます。

+
[listing]
----
vi /usr/lib/udev/rules.d/71-nvmf-netapp.rules
----
. 次の例のルールに示すように、 NetApp ONTAPコントローラの iopolicy を設定する行を見つけます。
+
[listing]
----
ACTION=="add", SUBSYSTEM=="nvme-subsystem", ATTR{subsystype}=="nvm", ATTR{model}=="NetApp ONTAP Controller", ATTR{iopolicy}="round-robin"
----
. ルールを修正して `round-robin`なる `queue-depth`:
+
[source, cli]
----
ACTION=="add", SUBSYSTEM=="nvme-subsystem", ATTR{subsystype}=="nvm", ATTR{model}=="NetApp ONTAP Controller", ATTR{iopolicy}="queue-depth"
----
. udev ルールを再読み込みし、変更を適用します。
+
[source, cli]
----
udevadm control --reload
udevadm trigger --subsystem-match=nvme-subsystem
----
. サブシステムの現在の iopolicy を確認します。  <subsystem>を置き換えます。例: `nvme-subsys0` 。
+
[source, cli]
----
cat /sys/class/nvme-subsystem/<subsystem>/iopolicy
----
+
次の出力が表示されます。

+
[listing]
----
queue-depth.
----



NOTE: 新しい iopolicy は、一致するNetApp ONTAPコントローラ デバイスに自動的に適用されます。再起動する必要はありません。



== ステップ5: オプションでNVMe/FCの1MB I/Oを有効にする

ONTAP は、識別コントローラ データで最大データ転送サイズ (MDTS) が 8 であると報告します。つまり、最大 I/O 要求サイズは 1 MB までになります。  Broadcom NVMe/FCホストに1MBのI/Oリクエストを発行するには、 `lpfc`の価値 `lpfc_sg_seg_cnt`パラメータをデフォルト値の 64 から 256 に変更します。


NOTE: この手順は、Qlogic NVMe/FCホストには適用されません。

.手順
.  `lpfc_sg_seg_cnt`パラメータを256に設定します。
+
[source, cli]
----
cat /etc/modprobe.d/lpfc.conf
----
+
次の例のような出力が表示されます。

+
[listing]
----
options lpfc lpfc_sg_seg_cnt=256
----
. コマンドを実行し `dracut -f`、ホストをリブートします。
. の値が256であることを確認し `lpfc_sg_seg_cnt`ます。
+
[source, cli]
----
cat /sys/module/lpfc/parameters/lpfc_sg_seg_cnt
----




== ステップ6: NVMeブートサービスを確認する

その `nvmefc-boot-connections.service`そして `nvmf-autoconnect.service`NVMe/FCに含まれるブートサービス `nvme-cli`パッケージはシステムの起動時に自動的に有効になります。

起動が完了したら、  `nvmefc-boot-connections.service`そして `nvmf-autoconnect.service`ブート サービスが有効になっています。

.手順
. が有効であることを確認し `nvmf-autoconnect.service`ます。
+
[source, cli]
----
systemctl status nvmf-autoconnect.service
----
+
.出力例を表示します。
[%collapsible]
====
[listing]
----
nvmf-autoconnect.service - Connect NVMe-oF subsystems automatically during boot
     Loaded: loaded (/usr/lib/systemd/system/nvmf-autoconnect.service; enabled; preset: disabled)
     Active: inactive (dead) since Sun 2025-10-12 19:41:15 IST; 1 day 1h ago
 Invocation: 7b5b99929c6b41199d493fa25b629f6c
   Main PID: 10043 (code=exited, status=0/SUCCESS)
   Mem peak: 2.9M
        CPU: 50ms

Oct 12 19:41:15 localhost.localdomain systemd[1]: Starting nvmf-autoconnect.service - Connect NVMe-oF subsystems automatically during boot...
Oct 12 19:41:15 localhost.localdomain systemd[1]: nvmf-autoconnect.service: Deactivated successfully.
Oct 12 19:41:15 localhost.localdomain systemd[1]: Finished nvmf-autoconnect.service - Connect NVMe-oF subsystems automatically during boot.
----
====
. が有効であることを確認し `nvmefc-boot-connections.service`ます。
+
[source, cli]
----
systemctl status nvmefc-boot-connections.service
----
+
.出力例を表示します。
[%collapsible]
====
[listing]
----
nvmefc-boot-connections.service - Auto-connect to subsystems on FC-NVME devices found during boot
     Loaded: loaded (/usr/lib/systemd/system/nvmefc-boot-connections.service; enabled; preset: enabled)
     Active: inactive (dead) since Sun 2025-10-12 19:40:33 IST; 1 day 1h ago
 Invocation: 0ec258a9f8c342ffb82408086d409bc6
   Main PID: 4151 (code=exited, status=0/SUCCESS)
   Mem peak: 2.9M
        CPU: 17ms

Oct 12 19:40:33 localhost systemd[1]: Starting nvmefc-boot-connections.service - Auto-connect to subsystems on FC-NVME devices found during boot...
Oct 12 19:40:33 localhost systemd[1]: nvmefc-boot-connections.service: Deactivated successfully.
Oct 12 19:40:33 localhost systemd[1]: Finished nvmefc-boot-connections.service - Auto-connect to subsystems on FC-NVME devices found during boot.
----
====




== ステップ7: マルチパス構成を確認する

カーネル内のNVMeマルチパスステータス、ANAステータス、およびONTAPネームスペースがNVMe-oF構成に対して正しいことを確認します。

.手順
. それぞれのONTAP名前空間の適切な NVMe-oF 設定 (モデルがNetApp ONTAPコントローラに設定され、負荷分散 iopolicy がラウンドロビンに設定されているなど) がホストに正しく表示されていることを確認します。
+
.. サブシステムを表示します。
+
[source, cli]
----
cat /sys/class/nvme-subsystem/nvme-subsys*/model
----
+
次の出力が表示されます。

+
[listing]
----
NetApp ONTAP Controller
NetApp ONTAP Controller
----
.. ポリシーを表示します。
+
[source, cli]
----
cat /sys/class/nvme-subsystem/nvme-subsys*/iopolicy
----
+
次の出力が表示されます。

+
[listing]
----
queue-depth
queue-depth
----


. ネームスペースが作成され、ホストで正しく検出されたことを確認します。
+
[source, cli]
----
nvme list
----
+
.例を示します
[%collapsible]
====
[listing]
----
Node                  Generic               SN                   Model
--------------------- --------------------- -------------------- ----------------------------------------
/dev/nvme11n1         /dev/ng11n1           81OcqJXhgWtsAAAAAAAI NetApp ONTAP Controller

Namespace  Usage                      Format           FW Rev
---------- -------------------------- ---------------- --------
0x1        951.90  MB /  21.47  GB    4 KiB +  0 B     9.18.1
----
====
. 各パスのコントローラの状態がliveであり、正しいANAステータスが設定されていることを確認します。
+
[role="tabbed-block"]
====
.NVMe/FC
--
[source, cli]
----
nvme list-subsys /dev/nvme9n2
----
.例を示します
[%collapsible]
=====
[listing, subs="+quotes"]
----
nvme-subsys9 - NQN=nqn.1992-08.com.netapp:sn.7c34ab26675e11f0a6c0d039eac03c33:subsystem.subsystem_46
               hostnqn=nqn.2014-08.org.nvmexpress:uuid:4c4c4544-0056-5410-8048-c7c04f425633
\
 +- nvme105 *fc* traddr=nn-0x2018d039eac03c33:pn-0x201bd039eac03c33,host_traddr=nn-0x2000f4c7aa0cd7c3:pn-0x2100f4c7aa0cd7c3 *live optimized*
 +- nvme107 *fc* traddr=nn-0x2018d039eac03c33:pn-0x2019d039eac03c33,host_traddr=nn-0x2000f4c7aa0cd7c2:pn-0x2100f4c7aa0cd7c2 *live optimized*
 +- nvme42 *fc* traddr=nn-0x2018d039eac03c33:pn-0x201cd039eac03c33,host_traddr=nn-0x2000f4c7aa0cd7c3:pn-0x2100f4c7aa0cd7c3 *live optimized*
 +- nvme44 *fc* traddr=nn-0x2018d039eac03c33:pn-0x201ad039eac03c33,host_traddr=nn-0x2000f4c7aa0cd7c2:pn-0x2100f4c7aa0cd7c2 *live optimized*
----
=====
--
.NVMe/FC
--
[source, cli]
----
nvme list-subsys /dev/nvme4n2
----
.例を示します
[%collapsible]
=====
[listing, subs="+quotes"]
----
nvme-subsys4 - NQN=nqn.1992-08.com.netapp:sn.17e32b6e8c7f11f09545d039eac03c33:subsystem.Bidirectional_DHCP_1_0
               hostnqn=nqn.2014-08.org.nvmexpress:uuid:4c4c4544-0054-5110-8039-c3c04f523034
\
 +- nvme4 *tcp* traddr=192.168.20.28,trsvcid=4420,host_traddr=192.168.20.21,src_addr=192.168.20.21 *live optimized*
 +- nvme5 *tcp* traddr=192.168.20.29,trsvcid=4420,host_traddr=192.168.20.21,src_addr=192.168.20.21 *live optimized*
 +- nvme6 *tcp* traddr=192.168.21.28,trsvcid=4420,host_traddr=192.168.21.21,src_addr=192.168.21.21 *live optimized*
 +- nvme7 *tcp* traddr=192.168.21.29,trsvcid=4420,host_traddr=192.168.21.21,src_addr=192.168.21.21 *live optimized*
----
=====
--
====
. ネットアッププラグインで、ONTAP ネームスペースデバイスごとに正しい値が表示されていることを確認します。
+
[role="tabbed-block"]
====
.列（ Column ）
--
[source, cli]
----
nvme netapp ontapdevices -o column
----
.例を示します
[%collapsible]
=====
[listing, subs="+quotes"]
----
Device           Vserver                   Subsystem                 Namespace Path
---------------- ------------------------- ------------------------- ------------------
/dev/nvme0n1     vs_nvme_sanboot_tcp       rhel_sanboot_tcp170       tcp_97

NSID UUID                                   Size
---- -------------------------------------- ---------
1    982c0f2a-6b8b-11f0-a6c0-d039eac03c33   322.12GB
----
=====
--
.JSON
--
[source, cli]
----
nvme netapp ontapdevices -o json
----
.例を示します
[%collapsible]
=====
[listing, subs="+quotes"]
----
{
  "ONTAPdevices":[
    {
      "Device":"/dev/nvme0n1",
      "Vserver":"vs_nvme_sanboot_tcp",
      "Subsystem":"rhel_sanboot_tcp170",
      "Namespace_Path":"tcp_97",
      "NSID":1,
      "UUID":"982c0f2a-6b8b-11f0-a6c0-d039eac03c33",
      "LBA_Size":4096,
      "Namespace_Size":322122547200,
      "UsedBytes":16285069312,
      "Version":"9.18.1"
    }
]
}
----
=====
--
====




== ステップ8: 安全なインバンド認証を設定する

RHEL 10x ホストとONTAPコントローラ間の NVMe/TCP 経由の安全なインバンド認証がサポートされます。

各ホストまたはコントローラは、  `DH-HMAC-CHAP`安全な認証を設定するためのキー。  `DH-HMAC-CHAP`キーは、NVMe ホストまたはコントローラの NQN と管理者によって設定された認証シークレットの組み合わせです。ピアを認証するには、NVMeホストまたはコントローラがピアに関連付けられたキーを認識する必要があります。

CLI または設定 JSON ファイルを使用して、安全なインバンド認証を設定します。サブシステムごとに異なるDHCHAPキーを指定する必要がある場合は、config JSONファイルを使用する必要があります。

[role="tabbed-block"]
====
.CLI の使用
--
CLIを使用してセキュアなインバンド認証を設定します。

. ホストNQNを取得します。
+
[source, cli]
----
cat /etc/nvme/hostnqn
----
. RHEL 10x ホストの dhchap キーを生成します。
+
次の出力は、 `gen-dhchap-key`コマンドパラメータ:

+
[listing]
----
nvme gen-dhchap-key -s optional_secret -l key_length {32|48|64} -m HMAC_function {0|1|2|3} -n host_nqn
•	-s secret key in hexadecimal characters to be used to initialize the host key
•	-l length of the resulting key in bytes
•	-m HMAC function to use for key transformation
0 = none, 1- SHA-256, 2 = SHA-384, 3=SHA-512
•	-n host NQN to use for key transformation
----
+
次の例では、HMACが3に設定されたランダムDHCHAPキー（SHA-512）が生成されます。

+
[listing]
----
nvme gen-dhchap-key -m 3 -n nqn.2014-08.org.nvmexpress:uuid:4c4c4544-0054-5110-8039-c3c04f523034
DHHC-1:03:AppJHkJygA6ZC4BxyQNtJST+4k4IOv47MAJk0xBITwFOHIC2nV/uE04RoSpy1z2SXYqNW1bhLe9hJ+MDHigGexaG2Ig=:
----
. ONTAPコントローラで、ホストを追加し、両方のDHCHAPキーを指定します。
+
[source, cli]
----
vserver nvme subsystem host add -vserver <svm_name> -subsystem <subsystem> -host-nqn <host_nqn> -dhchap-host-secret <authentication_host_secret> -dhchap-controller-secret <authentication_controller_secret> -dhchap-hash-function {sha-256|sha-512} -dhchap-group {none|2048-bit|3072-bit|4096-bit|6144-bit|8192-bit}
----
. ホストは、単方向と双方向の2種類の認証方式をサポートします。ホストで、ONTAPコントローラに接続し、選択した認証方式に基づいてDHCHAPキーを指定します。
+
[source, cli]
----
nvme connect -t tcp -w <host-traddr> -a <tr-addr> -n <host_nqn> -S <authentication_host_secret> -C <authentication_controller_secret>
----
. 検証する `nvme connect authentication` ホストとコントローラのDHCHAPキーを確認してコマンドを実行します。
+
.. ホストDHCHAPキーを確認します。
+
[source, cli]
----
cat /sys/class/nvme-subsystem/<nvme-subsysX>/nvme*/dhchap_secret
----
+
.に、単方向設定の出力例を示します。
[%collapsible]
=====
[listing]
----
cat /sys/class/nvme-subsystem/nvme-subsys4/nvme*/dhchap_secret
DHHC-1:01:2G7lsg9PMO00h1Wf1g4QtP0XT11kREz0qVuLm2xvZdbaWR/g:
DHHC-1:01:2G7lsg9PMO00h1Wf1g4QtP0XT11kREz0qVuLm2xvZdbaWR/g:
DHHC-1:01:2G7lsg9PMO00h1Wf1g4QtP0XT11kREz0qVuLm2xvZdbaWR/g:
DHHC-1:01:2G7lsg9PMO00h1Wf1g4QtP0XT11kREz0qVuLm2xvZdbaWR/g:
----
=====
.. コントローラのDHCHAPキーを確認します。
+
[source, cli]
----
cat /sys/class/nvme-subsystem/<nvme-subsysX>/nvme*/dhchap_ctrl_secret
----
+
.に、双方向設定の出力例を示します。
[%collapsible]
=====
[listing]
----
cat /sys/class/nvme-subsystem/nvme- subsys4/nvme*/dhchap_ctrl_secret
DHHC-1:03:5CgWULVnU5HUOwP1MNg95pkiUAwayiO+IvrALZR8HpeJIHw3xyHdGlTnvEJ81HDjBb+fGteUgIn0fj8ASHZIgkuFIx8=:
DHHC-1:03:5CgWULVnU5HUOwP1MNg95pkiUAwayiO+IvrALZR8HpeJIHw3xyHdGlTnvEJ81HDjBb+fGteUgIn0fj8ASHZIgkuFIx8=:
DHHC-1:03:5CgWULVnU5HUOwP1MNg95pkiUAwayiO+IvrALZR8HpeJIHw3xyHdGlTnvEJ81HDjBb+fGteUgIn0fj8ASHZIgkuFIx8=:
DHHC-1:03:5CgWULVnU5HUOwP1MNg95pkiUAwayiO+IvrALZR8HpeJIHw3xyHdGlTnvEJ81HDjBb+fGteUgIn0fj8ASHZIgkuFIx8=:
----
=====




--
.JSON
--
ONTAPコントローラ上で複数のNVMeサブシステムが利用可能な場合は、 `/etc/nvme/config.json`ファイルに `nvme connect-all`指示。

使用 `-o`JSON ファイルを生成するオプション。詳細な構文オプションについては、NVMe connect-all のマニュアル ページを参照してください。

. JSON ファイルを設定します。
+

NOTE: 次の例では、  `dhchap_key`対応する `dhchap_secret`そして `dhchap_ctrl_key`対応する `dhchap_ctrl_secret` 。

+
.例を示します
[%collapsible]
=====
[listing]
----
[
  {
    "hostnqn":"nqn.2014-08.org.nvmexpress:uuid:4c4c4544-0054-5110-8039-c3c04f523034",
    "hostid":"44454c4c-5400-1051-8039-c3c04f523034",
    "dhchap_key":"DHHC-1:01:2G7lsg9PMO00h1Wf1g4QtP0XT11kREz0qVuLm2xvZdbaWR/g:",
    "subsystems":[
      {
        "nqn":"nqn.1992-08.com.netapp:sn.5857c8c9b22411f08d0ed039eac03c33:subsystem.Bidirectional_DHCP_1_0",
        "ports":[
          {
            "transport":"tcp",
            "traddr":"192.168.20.28",
            "host_traddr":"192.168.20.21",
            "trsvcid":"4420",
            "dhchap_ctrl_key":"DHHC-1:03:5CgWULVnU5HUOwP1MNg95pkiUAwayiO+IvrALZR8HpeJIHw3xyHdGlTnvEJ81HDjBb+fGteUgIn0fj8ASHZIgkuFIx8=:"
          },
          {
            "transport":"tcp",
            "traddr":"192.168.20.29",
            "host_traddr":"192.168.20.21",
            "trsvcid":"4420",
            "dhchap_ctrl_key":"DHHC-1:03:5CgWULVnU5HUOwP1MNg95pkiUAwayiO+IvrALZR8HpeJIHw3xyHdGlTnvEJ81HDjBb+fGteUgIn0fj8ASHZIgkuFIx8=:"
          },
          {
            "transport":"tcp",
            "traddr":"192.168.21.28",
            "host_traddr":"192.168.21.21",
            "trsvcid":"4420",
            "dhchap_ctrl_key":"DHHC-1:03:5CgWULVnU5HUOwP1MNg95pkiUAwayiO+IvrALZR8HpeJIHw3xyHdGlTnvEJ81HDjBb+fGteUgIn0fj8ASHZIgkuFIx8=:"
          },
          {
            "transport":"tcp",
            "traddr":"192.168.21.29",
            "host_traddr":"192.168.21.21",
            "trsvcid":"4420",
            "dhchap_ctrl_key":"DHHC-1:03:5CgWULVnU5HUOwP1MNg95pkiUAwayiO+IvrALZR8HpeJIHw3xyHdGlTnvEJ81HDjBb+fGteUgIn0fj8ASHZIgkuFIx8=:"
          }
        ]
      }
    ]
  }
]
----
=====
. config jsonファイルを使用してONTAPコントローラに接続します。
+
[source, cli]
----
nvme connect-all -J /etc/nvme/config.json
----
+
.例を示します
[%collapsible]
=====
[listing]
----
traddr=192.168.20.28 is already connected
traddr=192.168.20.28 is already connected
traddr=192.168.20.29 is already connected
traddr=192.168.20.29 is already connected
----
=====
. 各サブシステムのそれぞれのコントローラに対して dhchap シークレットが有効になっていることを確認します。
+
.. ホストDHCHAPキーを確認します。
+
[source, cli]
----
cat /sys/class/nvme-subsystem/nvme-subsys4/nvme4/dhchap_secret
----
+
次の例は、dhchap キーを示しています。

+
[listing]
----
DHHC-1:01:2G7lsg9PMO00h1Wf1g4QtP0XT11kREz0qVuLm2xvZdbaWR/g:
----
.. コントローラのDHCHAPキーを確認します。
+
[source, cli]
----
cat /sys/class/nvme-subsystem/nvme- subsys4/nvme4/dhchap_ctrl_secret
----
+
次の例のような出力が表示されます。

+
[listing]
----
DHHC-1:03:5CgWULVnU5HUOwP1MNg95pkiUAwayiO+IvrALZR8HpeJIHw3xyHdGlTnvEJ81HDjBb+fGteUgIn0fj8ASHZIgkuFIx8=:
----




--
====


== 手順9：既知の問題を確認する

既知の問題はありません。
