---
sidebar: sidebar 
permalink: nvme_rhel_82.html 
keywords: nvme, linux, rhel, red hat, enterprise 
summary: ONTAP を使用して RHEL 8.2 用に NVMe/FC ホストを設定する方法 
---
= ONTAPヲシヨウシタRHEL 8.2ノNVMe/FCホストノセツテイ
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NVMe/FCはRed Hat Enterprise Linux（RHEL）8.2でONTAP 9.6以降でサポートされます。RHEL 8.2 ホストは、 NVMe と SCSI の両方のトラフィックを同じ Fibre Channel （ FC ；ファイバチャネル）イニシエータアダプタポートで実行します。を参照してください link:https://hwu.netapp.com/Home/Index["Hardware Universe"^] サポートされる FC アダプタおよびコントローラの一覧を表示するには、を参照してください。

を参照してください link:https://mysupport.netapp.com/matrix/["NetApp Interoperability Matrix Tool で確認できます"^] を参照してください。



== の機能

* RHEL 8.2以降では、 `nvme-fc auto-connect` スクリプトはネイティブに含まれています `nvme-cli` パッケージ。外部ベンダーが提供する outbox 自動接続スクリプトをインストールする代わりに、これらのネイティブ自動接続スクリプトを使用できます。
* RHEL 8.2以降の標準 `udev` ルールは、 `nvme-cli` NVMeマルチパスのラウンドロビンによるロードバランシングを可能にするパッケージ。（ RHEL 8.1 の場合と同様に）これ以上このルールを手動で作成する必要はありません。
* RHEL 8.2以降では、同じホストでNVMeトラフィックとSCSIトラフィックの両方を実行できます。実際、これは想定される導入済みホスト構成です。したがって、SCSIの場合は、 `dm-multipath` 通常のSCSI LUNの場合と同様に実行される `mpath` デバイス。NVMeマルチパスを使用してホストにNVMe-oFマルチパスデバイスを設定できます。
* RHEL 8.2以降の標準のNetAppプラグイン `nvme-cli` パッケージでは、ONTAPネームスペースのONTAPの詳細を表示できます。




== 既知の制限

* RHEL 8.2では、カーネル内NVMeマルチパスはデフォルトで無効になっています。そのため、手動で有効にする必要があります。
* NVMe-oFプロトコルを使用したSANブートは現在サポートされていません。




== NVMe/FC を有効にします

NVMe/FCを有効にするには、次の手順を使用します。

.手順
. Red Hat Enterprise Linux 8.2 GA をサーバにインストールします。
. を使用してRHEL 8.1からRHEL 8.2にアップグレードする場合 `yum update/upgrade`、あなたの `/etc/nvme/host*` ファイルが失われる可能性があります。ファイルが失われないようにするには、次の手順を実行します。
+
.. /etc/nvme/host *' ファイルをバックアップします
.. 手動で「 udev 」ルールを編集した場合は、削除します。
+
[listing]
----
/lib/udev/rules.d/71-nvme-iopolicy-netapp-ONTAP.rules
----
.. アップグレードを実行する。
.. アップグレードが完了したら、次のコマンドを実行します。
+
[listing]
----
yum remove nvme-cli
----
.. ホスト・ファイルを /etc/nvme/' にリストアします
+
[listing]
----
yum install nvmecli
----
.. オリジナルの /etc/nvme/host * の内容をバックアップから /etc/nvme/' にある実際のホスト・ファイルにコピーします


. インストールが完了したら、指定した Red Hat Enterprise Linux カーネルを実行していることを確認します。
+
[listing]
----
# uname -r
4.18.0-193.el8.x86_64
----
+
を参照してください link:https://mysupport.netapp.com/matrix/["NetApp Interoperability Matrix Tool で確認できます"^] サポートされるバージョンの最新のリストについては、を参照してください。

. nvme-CLI パッケージをインストールします。
+
[listing]
----
# rpm -qa|grep nvme-cli
nvme-cli-1.9.5.el8.x86_64
----
. カーネル内の NVMe マルチパスを有効にします。
+
[listing]
----
# grubby –args=nvme_core.multipath=Y –update-kernel /boot/vmlinuz-4.18.0-193.el8.x86_64
----
. RHEL 8.2ホストで、次の場所でホストのNQN文字列を確認します。 `/etc/nvme/hostnqn` と、ONTAPアレイの対応するサブシステムのホストNQN文字列が一致していることを確認します。
+
[listing]
----
# cat /etc/nvme/hostnqn
nqn.2014-08.org.nvmexpress:uuid:9ed5b327-b9fc-4cf5-97b3-1b5d986345d1


::> vserver nvme subsystem host show -vserver vs_fcnvme_141
Vserver      Subsystem        Host           NQN
----------- --------------- ----------- ---------------
  vs_fcnvme_141
    nvme_141_1
        nqn.2014-08.org.nvmexpress:uuid:9ed5b327-b9fc-4cf5-97b3-1b5d986345d1
----
+
ホストのNQN文字列が一致しない場合は、 `vserver modify` 対応するONTAPアレイサブシステムのホストNQN文字列をホストNQN文字列と一致するように更新するコマンド `/etc/nvme/hostnqn` ホスト。

. ホストをリブートします。
. 'enable_foreign' Setting_( オプション )_ を更新します
+
NetAppでは、同じRHEL 8.2に共存したホストでNVMeトラフィックとSCSIトラフィックの両方を実行する場合、ONTAPネームスペースにはカーネル内NVMeマルチパスを、ONTAP LUNにはdm-multipathをそれぞれ使用することを推奨しています。dm-multipath で ONTAP ネームスペースをブラックリストに登録して、これらのネームスペースデバイスが dm-multipath で要求されないようにする必要もあります。これを行うには、 `enable_foreign` に設定します `/etc/multipath.conf`を参照してください。

+
[listing]
----
# cat /etc/multipath.conf
defaults {
   enable_foreign NONE
}
----
. multipathd デーモンを再起動するには、 'ystemctl restart multipathd を実行します。




== Broadcom FC アダプタを NVMe/FC 用に設定します

Broadcom FCアダプタを設定するには、次の手順を使用します。

サポートされているアダプタの最新のリストについては、を参照してください link:https://mysupport.netapp.com/matrix/["NetApp Interoperability Matrix Tool で確認できます"^]。

.手順
. サポートされているアダプタを使用していることを確認します。
+
[listing]
----
# cat /sys/class/scsi_host/host*/modelname
LPe32002-M2
LPe32002-M2
----
+
[listing]
----
# cat /sys/class/scsi_host/host*/modeldesc
Emulex LightPulse LPe32002-M2 2-Port 32Gb Fibre Channel Adapter
Emulex LightPulse LPe32002-M2 2-Port 32Gb Fibre Channel Adapter
----
. lpfc_enable_fc4_type' が *3* に設定されていることを確認します
+
[listing]
----
# cat /sys/module/lpfc/parameters/lpfc_enable_fc4_type
3
----
. イニシエータポートが動作しており、ターゲット LIF を認識できることを確認してください。
+
[listing]
----
# cat /sys/class/fc_host/host*/port_name
0x100000109b1c1204
0x100000109b1c1205
----
+
[listing]
----
# cat /sys/class/fc_host/host*/port_state
Online
Online
----
+
[listing]
----
# cat /sys/class/scsi_host/host*/nvme_info
NVME Initiator Enabled
XRI Dist lpfc0 Total 6144 IO 5894 ELS 250
NVME LPORT lpfc0 WWPN x100000109b1c1204 WWNN x200000109b1c1204 DID x011d00 ONLINE
NVME RPORT WWPN x203800a098dfdd91 WWNN x203700a098dfdd91 DID x010c07 TARGET DISCSRVC ONLINE
NVME RPORT WWPN x203900a098dfdd91 WWNN x203700a098dfdd91 DID x011507 TARGET DISCSRVC ONLINE
NVME Statistics
LS: Xmt 0000000f78 Cmpl 0000000f78 Abort 00000000
LS XMIT: Err 00000000 CMPL: xb 00000000 Err 00000000
Total FCP Cmpl 000000002fe29bba Issue 000000002fe29bc4 OutIO 000000000000000a
abort 00001bc7 noxri 00000000 nondlp 00000000 qdepth 00000000 wqerr 00000000 err 00000000
FCP CMPL: xb 00001e15 Err 0000d906
NVME Initiator Enabled
XRI Dist lpfc1 Total 6144 IO 5894 ELS 250
NVME LPORT lpfc1 WWPN x100000109b1c1205 WWNN x200000109b1c1205 DID x011900 ONLINE
NVME RPORT WWPN x203d00a098dfdd91 WWNN x203700a098dfdd91 DID x010007 TARGET DISCSRVC ONLINE
NVME RPORT WWPN x203a00a098dfdd91 WWNN x203700a098dfdd91 DID x012a07 TARGET DISCSRVC ONLINE
NVME Statistics
LS: Xmt 0000000fa8 Cmpl 0000000fa8 Abort 00000000
LS XMIT: Err 00000000 CMPL: xb 00000000 Err 00000000
Total FCP Cmpl 000000002e14f170 Issue 000000002e14f17a OutIO 000000000000000a
abort 000016bb noxri 00000000 nondlp 00000000 qdepth 00000000 wqerr 00000000 err 00000000
FCP CMPL: xb 00001f50 Err 0000d9f8
----
. 1MB の I/O サイズを有効にします（オプション） _ 。
+
lpfc ドライバから問題 I/O 要求へのサイズが最大 1 MB になるように 'lpfc_sg_seg_cnt' パラメータを 256 に設定する必要があります

+
[listing]
----
# cat /etc/modprobe.d/lpfc.conf
options lpfc lpfc_sg_seg_cnt=256
----
. 「 racut-f 」コマンドを実行してからホストを再起動します。
. ホストの起動後 'lpfc_sg_sg_cnt が 256 に設定されていることを確認します
+
[listing]
----
# cat /sys/module/lpfc/parameters/lpfc_sg_seg_cnt
256
----
. 推奨される Broadcom lpfc ファームウェアと受信トレイドライバを使用していることを確認します。
+
[listing]
----
# cat /sys/class/scsi_host/host*/fwrev
12.6.182.8, sli-4:2:c
12.6.182.8, sli-4:2:c
----
+
[listing]
----
# cat /sys/module/lpfc/version
0:12.6.0.2
----
. lpfc_enable_fc4_type' が *3* に設定されていることを確認します
+
[listing]
----
# cat /sys/module/lpfc/parameters/lpfc_enable_fc4_type
3
----
. イニシエータポートが動作しており、ターゲット LIF を認識できることを確認してください。
+
[listing]
----
# cat /sys/class/fc_host/host*/port_name
0x100000109b1c1204
0x100000109b1c1205
----
+
[listing]
----
# cat /sys/class/fc_host/host*/port_state
Online
Online
----
+
[listing]
----
# cat /sys/class/scsi_host/host*/nvme_info
NVME Initiator Enabled
XRI Dist lpfc0 Total 6144 IO 5894 ELS 250
NVME LPORT lpfc0 WWPN x100000109b1c1204 WWNN x200000109b1c1204 DID x011d00 ONLINE
NVME RPORT WWPN x203800a098dfdd91 WWNN x203700a098dfdd91 DID x010c07 TARGET DISCSRVC ONLINE
NVME RPORT WWPN x203900a098dfdd91 WWNN x203700a098dfdd91 DID x011507 TARGET DISCSRVC ONLINE
NVME Statistics
LS: Xmt 0000000f78 Cmpl 0000000f78 Abort 00000000
LS XMIT: Err 00000000 CMPL: xb 00000000 Err 00000000
Total FCP Cmpl 000000002fe29bba Issue 000000002fe29bc4 OutIO 000000000000000a
abort 00001bc7 noxri 00000000 nondlp 00000000 qdepth 00000000 wqerr 00000000 err 00000000
FCP CMPL: xb 00001e15 Err 0000d906
NVME Initiator Enabled
XRI Dist lpfc1 Total 6144 IO 5894 ELS 250
NVME LPORT lpfc1 WWPN x100000109b1c1205 WWNN x200000109b1c1205 DID x011900 ONLINE
NVME RPORT WWPN x203d00a098dfdd91 WWNN x203700a098dfdd91 DID x010007 TARGET DISCSRVC ONLINE
NVME RPORT WWPN x203a00a098dfdd91 WWNN x203700a098dfdd91 DID x012a07 TARGET DISCSRVC ONLINE
NVME Statistics
LS: Xmt 0000000fa8 Cmpl 0000000fa8 Abort 00000000
LS XMIT: Err 00000000 CMPL: xb 00000000 Err 00000000
Total FCP Cmpl 000000002e14f170 Issue 000000002e14f17a OutIO 000000000000000a
abort 000016bb noxri 00000000 nondlp 00000000 qdepth 00000000 wqerr 00000000 err 00000000
FCP CMPL: xb 00001f50 Err 0000d9f8
----
. 1MB の I/O サイズを有効にします（オプション） _ 。
+
lpfc ドライバから問題 I/O 要求へのサイズが最大 1 MB になるように 'lpfc_sg_seg_cnt' パラメータを 256 に設定する必要があります

+
[listing]
----
# cat /etc/modprobe.d/lpfc.conf
options lpfc lpfc_sg_seg_cnt=256
----
. 「 racut-f 」コマンドを実行してからホストを再起動します。
. ホストの起動後 'lpfc_sg_sg_cnt が 256 に設定されていることを確認します
+
[listing]
----
# cat /sys/module/lpfc/parameters/lpfc_sg_seg_cnt
256
----




== NVMe/FC を検証

NVMe/FCの検証には、次の手順 を使用できます。

.手順
. 以下の NVMe/FC 設定を確認してください。
+
[listing]
----
# cat /sys/module/nvme_core/parameters/multipath
Y
----
+
[listing]
----
# cat /sys/class/nvme-subsystem/nvme-subsys*/model
NetApp ONTAP Controller
NetApp ONTAP Controller
----
+
[listing]
----
# cat /sys/class/nvme-subsystem/nvme-subsys*/iopolicy
round-robin
round-robin
----
. ネームスペースが作成されたことを確認します。
+
[listing]
----
# nvme list
Node SN Model Namespace Usage Format FW Rev
---------------- -------------------- -----------------------
/dev/nvme0n1 80BADBKnB/JvAAAAAAAC NetApp ONTAP Controller 1 53.69 GB / 53.69 GB 4 KiB + 0 B FFFFFFFF
----
. ANA パスのステータスを確認します。
+
[listing]
----
# nvme list-subsys/dev/nvme0n1
Nvme-subsysf0 – NQN=nqn.1992-08.com.netapp:sn.341541339b9511e8a9b500a098c80f09:subsystem.rhel_141_nvme_ss_10_0
\
+- nvme0 fc traddr=nn-0x202c00a098c80f09:pn-0x202d00a098c80f09 host_traddr=nn-0x20000090fae0ec61:pn-0x10000090fae0ec61 live optimized
+- nvme1 fc traddr=nn-0x207300a098dfdd91:pn-0x207600a098dfdd91 host_traddr=nn-0x200000109b1c1204:pn-0x100000109b1c1204 live inaccessible
+- nvme2 fc traddr=nn-0x207300a098dfdd91:pn-0x207500a098dfdd91 host_traddr=nn-0x200000109b1c1205:pn-0x100000109b1c1205 live optimized
+- nvme3 fc traddr=nn-0x207300a098dfdd91:pn-0x207700a098dfdd91 host traddr=nn-0x200000109b1c1205:pn-0x100000109b1c1205 live inaccessible
----
. ONTAP デバイス用ネットアッププラグインを確認します。
+
[listing]
----

# nvme netapp ontapdevices -o column
Device   Vserver  Namespace Path             NSID   UUID   Size
-------  -------- -------------------------  ------ ----- -----
/dev/nvme0n1   vs_nvme_10       /vol/rhel_141_vol_10_0/rhel_141_ns_10_0    1        55baf453-f629-4a18-9364-b6aee3f50dad   53.69GB

# nvme netapp ontapdevices -o json
{
   "ONTAPdevices" : [
   {
        Device" : "/dev/nvme0n1",
        "Vserver" : "vs_nvme_10",
        "Namespace_Path" : "/vol/rhel_141_vol_10_0/rhel_141_ns_10_0",
         "NSID" : 1,
         "UUID" : "55baf453-f629-4a18-9364-b6aee3f50dad",
         "Size" : "53.69GB",
         "LBA_Data_Size" : 4096,
         "Namespace_Size" : 13107200
    }
]
----

