---
sidebar: sidebar 
permalink: overview.html 
keywords: ontap, san, host, rhel, red, hat, linux, sles, suse, esxi, nvme, oracle, linux, windows, enterprise, fc, fcp, isci, aix, powervm, vios, centos, citrix, hp-ux, solaris, veritas, cvo, cloud, volume, ontap, clients, configuration, FSx, instance, netapp 
summary: このコンテンツでは、オンプレミスのONTAP ストレージに接続されたONTAP ホストとSANホストについて、Cloud Volumes ONTAP とAmazon FSXに接続されたクラウドクライアントを設定する方法について、配布に固有のガイダンスを提供します。 
---
= SANホスト構成の詳細
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
SANホストをマルチパス用に設定し、ONTAP LUNで正しく動作するために重要な特定のパラメータと設定を使用して設定する必要があります。ホストの構成は、ホストのオペレーティングシステムとプロトコルによって異なります。最適なパフォーマンスと正常なフェイルオーバーを実現するには、正しい設定が重要です。

NetApp SAN Host Utilitiesを使用するようにSANホストを設定する必要があります。SAN Host Utilitiesは、LUNとHost Bus Adapter（HBA；ホストバスアダプタ）の管理と監視に役立ちます。たとえば、SAN Host Utilitiesを使用して、ホストにマッピングされているすべてのLUNのリストを取得したり、ホストにマッピングされている特定のLUNのすべての属性のリストを表示したりできます。サポートが必要な問題が発生した場合は、NetAppカスタマーサポートでSAN Host Utilitiesを使用して構成に関する情報を収集することもできます。

NetAppでは、SANホストにSAN Host Utilitiesソフトウェアがある場合、そのソフトウェアを使用することを推奨しています。

SAN構成でSANブーティングがサポートされている場合は、SANブーティングを使用するようにホストを設定して、導入を簡易化し、拡張性を向上させることもできます。SANブートを使用すると、複数の新しいサーバをSANに接続して適切なブート設定を構成することで、複数の新しいサーバを導入できます。これにより、各サーバにオペレーティングシステムを個別にインストールする必要がなくなるため、時間を節約できます。

SANホストとONTAP ストレージは、オンプレミス、クラウド、またはその両方に配置できます。


NOTE: クラウド環境では、ホストは一般にクライアントと呼ばれます。このコンテンツに含まれるホスト固有のすべての情報は、環境 クラウドクライアントにも該当します。

たとえば、オンプレミスのONTAPストレージをオンプレミスの SAN ホストまたは SAN クラウド クライアントに接続するように構成できます。クラウド環境で実行されるストレージサービスを構成することもできます。link:https://docs.netapp.com/us-en/cloud-volumes-ontap/index.html["Cloud Volumes ONTAP"^]またはlink:https://docs.netapp.com/us-en/storage-management-fsx-ontap/index.html["NetApp ONTAP 対応の Amazon FSX"^]オンプレミスの SAN ホストまたは SAN クラウド クライアントに接続します。

.関連情報
* link:https://docs.netapp.com/us-en/ontap/san-config/index.html["ONTAP SAN構成のリファレンス"^]
* link:https://docs.netapp.com/us-en/ontap/san-management/index.html["ONTAP SANストレージ管理"^]
* link:https://library.netapp.com/ecm/ecm_download_file/ECMLP2492508["ONTAP 9 リリース ノート"^]
* 『』のSANtricity関連ドキュメントlink:https://docs.netapp.com/us-en/e-series/index.html["Eシリーズシステムのドキュメント"^]

