---
settings:
  name: ONTAP SAN Host Utilities
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: ja-jp,us-en,de-de,es-es,fr-fr,it-it,pt-br,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: ONTAP SANホストとクラウドクライアント
    url: "/index.html"
  - title: SANホスト構成の詳細
    url: "/overview.html"
  - title: SAN Host Utilitiesのインストール
    entries:
    - title: SAN Host Utilitiesの詳細
      url: "/hu_sanhost_index.html"
    - title: AIX Host Utilities の略語
      entries:
      - title: リリースノート
        url: "/hu-aix-release-notes.html"
      - title: AIXホストユーティリティをインストールする
        entries:
        - title: AIX ホスト ユーティリティ 8.0 をインストールする
          url: "/hu-aix-80.html"
        - title: AIX Host Utilities 7.0のインストール
          url: "/hu-aix-70.html"
        - title: AIX ホスト ユーティリティ 6.1 をインストールする
          url: "/hu_aix_61.html"
      - title: AIX SAN Tollkit について学ぶ
        url: "/hu-aix-san-toolkit.html"
      - title: AIX ホスト ユーティリティ コマンド リファレンス
        url: "/hu-aix-command-reference.html"
    - title: HP-UX Host Utilitiesのことです
      entries:
      - title: リリースノート
        url: "/hu-hpux-release-notes.html"
      - title: HP-UX Host Utilities 6.0のインストール
        url: "/hu_hpux_60.html"
      - title: SANツールキットについて学ぶ
        url: "/hu-hpux-sanlun-toolkit.html"
      - title: HP-UXコマンドリファレンスについて学ぶ
        url: "/hu_hpux_60_cmd.html"
    - title: Linux Host Utilities のことです
      entries:
      - title: リリースノート
        url: "/hu-luhu-release-notes.html"
      - title: Linuxホストユーティリティをインストールする
        entries:
        - title: Linuxホストユーティリティ8.0をインストールする
          url: "/hu-luhu-80.html"
        - title: Linux Host Utilities 7.1のインストール
          url: "/hu_luhu_71.html"
      - title: sanlunユーティリティについて学ぶ
        url: "/hu-luhu-sanlun-utility.html"
      - title: Linux ホストユーティリティコマンドリファレンス
        url: "/hu-luhu-command-reference.html"
    - title: Solaris Host Utilities のことです
      entries:
      - title: リリースノート
        url: "/hu-solaris-release-notes.html"
      - title: Solaris Host Utilitiesをインストールします
        entries:
        - title: Solaris ホスト ユーティリティ 8.0 をインストールする
          url: "/hu-solaris-80.html"
        - title: Solaris ホスト ユーティリティ 6.2 をインストールする
          url: "/hu_solaris_62.html"
      - title: SANツールキットについて学ぶ
        url: "/hu-solaris-san-toolkit.html"
      - title: Solarisコマンドリファレンスについて学ぶ
        url: "/hu-solaris-command-reference.html"
    - title: Windows Host Utilities
      entries:
      - title: リリースノート
        url: "/hu-wuhu-release-notes.html"
      - title: Windowsホストユーティリティをインストールする
        entries:
        - title: Windows ホスト ユーティリティ 8.0 をインストールする
          url: "/hu-wuhu-80.html"
        - title: Windows Host Utilities 7.2をインストールする
          url: "/hu_wuhu_72.html"
        - title: Windows Host Utilities 7.1のインストール
          url: "/hu_wuhu_71.html"
      - title: Windowsホストユーティリティの設定を構成する
        url: "/hu_wuhu_hba_settings.html"
      - title: Windows Host Utilitiesのアップグレード
        url: "/hu_wuhu_upgrade.html"
      - title: Windows Host Utilitiesを修復して削除します
        url: "/hu_wuhu_repair_remove.html"
      - title: トラブルシューティングを行う
        url: "/hu_wuhu_troubleshoot.html"
  - title: FCPとiSCSIを使用したホストの設定
    entries:
    - title: 概要
      url: "/hu_fcp_scsi_index.html"
    - title: AIX および PowerVM/VIOS
      entries:
      - title: 7.3/4.x
        url: "/hu-aix-73.html"
      - title: 6.3.1 を参照してください
        url: "/hu_aix_72.html"
      - title: '7.1'
        url: "/hu_aix_71.html"
    - title: CentOS の場合
      entries:
      - title: CentOS 8
        entries:
        - title: '8.5'
          url: "/hu_centos_85.html"
        - title: 8/4
          url: "/hu_centos_84.html"
        - title: '8.3'
          url: "/hu_centos_83.html"
        - title: '8.2'
          url: "/hu_centos_82.html"
        - title: '8.1'
          url: "/hu_centos_81.html"
        - title: '8.0'
          url: "/hu_centos_80.html"
      - title: CentOS 7
        entries:
        - title: '7.9'
          url: "/hu_centos_79.html"
        - title: 7 、 8
          url: "/hu_centos_78.html"
        - title: '7.7'
          url: "/hu_centos_77.html"
        - title: '7.6'
          url: "/hu_centos_76.html"
        - title: '7.5'
          url: "/hu_centos_75.html"
        - title: '7.4'
          url: "/hu_centos_74.html"
        - title: '7.3'
          url: "/hu_centos_73.html"
        - title: '7.2'
          url: "/hu_centos_72.html"
        - title: '7.1'
          url: "/hu_centos_71.html"
        - title: '7.0'
          url: "/hu_centos_70.html"
      - title: CentOS 6
        entries:
        - title: '6.10'
          url: "/hu_centos_610.html"
        - title: '6.9'
          url: "/hu_centos_69.html"
        - title: 6 月 8 日
          url: "/hu_centos_68.html"
        - title: '6.7'
          url: "/hu_centos_67.html"
        - title: '6.6'
          url: "/hu_centos_66.html"
        - title: '6.5'
          url: "/hu_centos_65.html"
        - title: '6.4'
          url: "/hu_centos_64.html"
    - title: Citrix
      entries:
      - title: XenServer 8.4
        url: "/hu_citrix_84.html"
      - title: ハイパーバイザー 8.2
        url: "/hu_citrix_82.html"
    - title: ESXi
      entries:
      - title: VMware vSphere 8
        url: "/hu_vsphere_8.html"
      - title: VMware vSphere 7
        url: "/hu_vsphere_7.html"
      - title: VMware vSphere 6.5 および 6.7
        url: "/hu_vsphere_6.html"
    - title: HP-UX
      entries:
      - title: 11i v3
        url: "/hu_hpux_11iv3.html"
    - title: Oracle Linux の場合
      pdf-filename: OL-FCP
      entries:
      - title: Oracle Linux 9.
        entries:
        - title: '9.5'
          url: "/hu-ol-95.html"
        - title: '9.4'
          url: "/hu_ol_94.html"
        - title: '9.3'
          url: "/hu_ol_93.html"
        - title: 9.2.
          url: "/hu_ol_92.html"
        - title: '9.1'
          url: "/hu_ol_91.html"
        - title: '9.0'
          url: "/hu_ol_90.html"
      - title: Oracle Linux 8.
        pdf-filename: OL-8-FCP
        entries:
        - title: 8.10で
          url: "/hu-ol-810.html"
        - title: '8.9'
          url: "/hu_ol_89.html"
        - title: '8.8'
          url: "/hu_ol_88.html"
        - title: '8.7'
          url: "/hu_ol_87.html"
        - title: '8.6'
          url: "/hu_ol_86.html"
        - title: '8.5'
          url: "/hu_ol_85.html"
        - title: 8/4
          url: "/hu_ol_84.html"
        - title: '8.3'
          url: "/hu_ol_83.html"
        - title: '8.2'
          url: "/hu_ol_82.html"
        - title: '8.1'
          url: "/hu_ol_81.html"
        - title: '8.0'
          url: "/hu_ol_80.html"
      - title: Oracle Linux 7.
        pdf-filename: OL-7 - FCP
        entries:
        - title: '7.9'
          url: "/hu_ol_79.html"
        - title: 7 、 8
          url: "/hu_ol_78.html"
        - title: '7.7'
          url: "/hu_ol_77.html"
        - title: '7.6'
          url: "/hu_ol_76.html"
        - title: '7.5'
          url: "/hu_ol_75.html"
        - title: '7.4'
          url: "/hu_ol_74.html"
        - title: '7.3'
          url: "/hu_ol_73.html"
        - title: '7.2'
          url: "/hu_ol_72.html"
        - title: '7.1'
          url: "/hu_ol_71.html"
        - title: '7.0'
          url: "/hu_ol_70.html"
      - title: Oracle Linux 6.
        pdf-filename: OL-6- FCP
        entries:
        - title: '6.10'
          url: "/hu_ol_610.html"
        - title: '6.9'
          url: "/hu_ol_69.html"
        - title: 6 月 8 日
          url: "/hu_ol_68.html"
        - title: '6.7'
          url: "/hu_ol_67.html"
        - title: '6.6'
          url: "/hu_ol_66.html"
        - title: '6.5'
          url: "/hu_ol_65.html"
        - title: '6.4'
          url: "/hu_ol_64.html"
    - title: RHEL
      entries:
      - title: RHEL 10
        pdf-filename: RHEL-10-FCP
        entries:
        - title: '10.0'
          url: "/hu_rhel_10.html"
      - title: RHEL 9
        pdf-filename: RHEL-9-FCPのいずれかです
        entries:
        - title: '9.6'
          url: "/hu-rhel-96.html"
        - title: '9.5'
          url: "/hu_rhel_95.html"
        - title: '9.4'
          url: "/hu_rhel_94.html"
        - title: '9.3'
          url: "/hu_rhel_93.html"
        - title: 9.2.
          url: "/hu_rhel_92.html"
        - title: '9.1'
          url: "/hu_rhel_91.html"
        - title: '9.0'
          url: "/hu_rhel_90.html"
      - title: RHEL 8
        pdf-filename: RHEL-8-FCPのいずれかです
        entries:
        - title: 8.10で
          url: "/hu_rhel_810.html"
        - title: '8.9'
          url: "/hu_rhel_89.html"
        - title: '8.8'
          url: "/hu_rhel_88.html"
        - title: '8.7'
          url: "/hu_rhel_87.html"
        - title: '8.6'
          url: "/hu_rhel_86.html"
        - title: '8.5'
          url: "/hu_rhel_85.html"
        - title: 8/4
          url: "/hu_rhel_84.html"
        - title: '8.3'
          url: "/hu_rhel_83.html"
        - title: '8.2'
          url: "/hu_rhel_82.html"
        - title: '8.1'
          url: "/hu_rhel_81.html"
        - title: '8.0'
          url: "/hu_rhel_80.html"
      - title: RHEL 7
        pdf-filename: RHEL-7-FCPのいずれかです
        entries:
        - title: '7.9'
          url: "/hu_rhel_79.html"
        - title: 7 、 8
          url: "/hu_rhel_78.html"
        - title: '7.7'
          url: "/hu_rhel_77.html"
        - title: '7.6'
          url: "/hu_rhel_76.html"
        - title: '7.5'
          url: "/hu_rhel_75.html"
        - title: '7.4'
          url: "/hu_rhel_74.html"
        - title: '7.3'
          url: "/hu_rhel_73.html"
        - title: '7.2'
          url: "/hu_rhel_72.html"
        - title: '7.1'
          url: "/hu_rhel_71.html"
        - title: '7.0'
          url: "/hu_rhel_70.html"
      - title: RHEL 6
        pdf-filename: RHEL-6-FCP
        entries:
        - title: '6.10'
          url: "/hu_rhel_610.html"
        - title: '6.9'
          url: "/hu_rhel_69.html"
        - title: 6 月 8 日
          url: "/hu_rhel_68.html"
        - title: '6.7'
          url: "/hu_rhel_67.html"
        - title: '6.6'
          url: "/hu_rhel_66.html"
        - title: '6.5'
          url: "/hu_rhel_65.html"
        - title: '6.4'
          url: "/hu_rhel_64.html"
    - title: Rocky Linux
      entries:
      - title: Rocky Linux 10
        pdf-filename: RL-10-FCP
        entries:
        - title: '10.'
          url: "/hu-rockylinux-10.html"
      - title: Rocky Linux 9
        pdf-filename: RL-9-FCP
        entries:
        - title: '9.6'
          url: "/hu-rockylinux-96.html"
        - title: '9.5'
          url: "/hu-rockylinux-95.html"
        - title: '9.4'
          url: "/hu-rockylinux-94.html"
        - title: '9.3'
          url: "/hu-rockylinux-93.html"
        - title: 9.2.
          url: "/hu-rockylinux-92.html"
        - title: '9.1'
          url: "/hu-rockylinux-91.html"
        - title: '9.0'
          url: "/hu-rockylinux-90.html"
      - title: Rocky Linux 8
        pdf-filename: RL-8-FCP
        entries:
        - title: 8.10で
          url: "/hu-rockylinux-810.html"
        - title: '8.9'
          url: "/hu-rockylinux-89.html"
        - title: '8.8'
          url: "/hu-rockylinux-88.html"
        - title: '8.7'
          url: "/hu-rockylinux-87.html"
        - title: '8.6'
          url: "/hu-rockylinux-86.html"
        - title: '8.5'
          url: "/hu-rockylinux-85.html"
        - title: 8/4
          url: "/hu-rockylinux-84.html"
    - title: Solaris の場合
      entries:
      - title: '11.4'
        url: "/hu-solaris-114.html"
      - title: '11.3'
        url: "/hu_solaris_113.html"
    - title: SUSE Linux Enterprise Server
      entries:
      - title: SUSE Linux Enterprise Server 15
        pdf-filename: SLES-15-FCPの場合
        entries:
        - title: 15 SP7
          url: "/hu_sles_15SP7.html"
        - title: 15 SP6
          url: "/hu_sles_15SP6.html"
        - title: 15 SP5
          url: "/hu_sles_15SP5.html"
        - title: 15 SP4
          url: "/hu_sles_15SP4.html"
        - title: 15 SP3
          url: "/hu_sles_15SP3.html"
        - title: 15 SP2
          url: "/hu_sles_15SP2.html"
        - title: 15 SP1
          url: "/hu_sles_15SP1.html"
        - title: '15'
          url: "/hu_sles_15.html"
      - title: SUSE Linux Enterprise Server 12
        entries:
        - title: 12 SP 5
          url: "/hu_sles_12SP5.html"
        - title: 12 SP 4
          url: "/hu_sles_12SP4.html"
        - title: 12 SP 3
          url: "/hu_sles_12SP3.html"
        - title: 12 SP 2
          url: "/hu_sles_12SP2.html"
        - title: 12 SP 1
          url: "/hu_sles_12SP1.html"
        - title: '12.'
          url: "/hu_sles_12.html"
    - title: Ubuntu
      pdf-filename: Ubuntu - FCP
      entries:
      - title: '24.04'
        url: "/hu_ubuntu_2404.html"
      - title: '22.04'
        url: "/hu_ubuntu_2204.html"
      - title: '20.04'
        url: "/hu_ubuntu_2004.html"
    - title: Veritas の略
      entries:
      - title: Infoscale 8.
        url: "/hu_veritas_8x.html"
      - title: Infoscale 7.
        url: "/hu_veritas_7x.html"
      - title: Storage Foundation 6.
        url: "/hu_veritas_6x.html"
    - title: Windows の場合
      pdf-filename: Windows - FCP
      entries:
      - title: '2025'
        url: "/hu-windows-2025.html"
      - title: '2022'
        url: "/hu_windows_2022.html"
      - title: 2019 年
        url: "/hu_windows_2019.html"
      - title: 2016 年
        url: "/hu_windows_2016.html"
      - title: 2012 R2
        url: "/hu_windows_2012r2.html"
  - title: NVMe-oFを使用したホストの設定
    entries:
    - title: NVMe-oFホストの構成について学ぶ
      url: "/hu-nvme-index.html"
    - title: AIX の場合
      url: "/nvme_aix.html"
    - title: ESXi
      pdf-filename: NVMeoF ESXi
      entries:
      - title: VMware vSphere 8
        url: "/nvme_esxi_8.html"
      - title: VMware vSphere 7
        url: "/nvme_esxi_7.html"
    - title: Oracle Linux の場合
      entries:
      - title: Oracle Linux 9.
        pdf-filename: NVMeネームスペース
        entries:
        - title: '9.5'
          url: "/nvme-ol-95.html"
        - title: '9.4'
          url: "/nvme_ol_94.html"
        - title: '9.3'
          url: "/nvme_ol_93.html"
        - title: 9.2.
          url: "/nvme_ol_92.html"
        - title: '9.1'
          url: "/nvme_ol_91.html"
        - title: '9.0'
          url: "/nvme_ol_90.html"
      - title: Oracle Linux 8.
        pdf-filename: NVMeネームスペース
        entries:
        - title: 8.10で
          url: "/nvme-ol-810.html"
        - title: '8.9'
          url: "/nvme_ol_89.html"
        - title: '8.8'
          url: "/nvme_ol_88.html"
        - title: '8.7'
          url: "/nvme_ol_87.html"
        - title: '8.6'
          url: "/nvme_ol_86.html"
        - title: '8.5'
          url: "/nvme_ol_85.html"
        - title: 8/4
          url: "/nvme_ol_84.html"
        - title: '8.3'
          url: "/nvme_ol_83.html"
        - title: '8.2'
          url: "/nvme_ol_82.html"
        - title: '8.1'
          url: "/nvme_ol_81.html"
      - title: Oracle Linux 7.
        entries:
        - title: '7.9'
          url: "/nvme_ol_79.html"
        - title: 7 、 8
          url: "/nvme_ol_78.html"
        - title: '7.7'
          url: "/nvme_ol_77.html"
    - title: RHEL
      pdf-filename: NVMeoF RHEL
      entries:
      - title: RHEL 10
        entries:
        - title: '10.0'
          url: "/nvme-rhel-10.html"
      - title: RHEL 9
        entries:
        - title: '9.6'
          url: "/nvme-rhel-96.html"
        - title: '9.5'
          url: "/nvme-rhel-95.html"
        - title: '9.4'
          url: "/nvme-rhel-94.html"
        - title: '9.3'
          url: "/nvme-rhel-93.html"
        - title: 9.2.
          url: "/nvme-rhel-92.html"
        - title: '9.1'
          url: "/nvme-rhel-91.html"
        - title: '9.0'
          url: "/nvme-rhel-90.html"
      - title: RHEL 8
        entries:
        - title: 8.10で
          url: "/nvme-rhel-810.html"
        - title: '8.9'
          url: "/nvme-rhel-89.html"
        - title: '8.8'
          url: "/nvme-rhel-88.html"
        - title: '8.7'
          url: "/nvme-rhel-87.html"
        - title: '8.6'
          url: "/nvme-rhel-86.html"
        - title: '8.5'
          url: "/nvme-rhel-85.html"
        - title: 8/4
          url: "/nvme-rhel-84.html"
        - title: '8.3'
          url: "/nvme-rhel-83.html"
        - title: '8.2'
          url: "/nvme-rhel-82.html"
        - title: '8.1'
          url: "/nvme-rhel-81.html"
    - title: Rocky Linux
      pdf-filename: NVMeoF ロッキー Linux
      entries:
      - title: Rocky Linux 10
        entries:
        - title: '10.0'
          url: "/nvme-rockylinux-10.html"
      - title: Rocky Linux 9
        entries:
        - title: '9.6'
          url: "/nvme-rockylinux-96.html"
        - title: '9.5'
          url: "/nvme-rockylinux-95.html"
        - title: '9.4'
          url: "/nvme-rockylinux-94.html"
        - title: '9.3'
          url: "/nvme-rockylinux-93.html"
        - title: 9.2.
          url: "/nvme-rockylinux-92.html"
        - title: '9.1'
          url: "/nvme-rockylinux-91.html"
        - title: '9.0'
          url: "/nvme-rockylinux-90.html"
      - title: Rocky Linux 8
        entries:
        - title: 8.10で
          url: "/nvme-rockylinux-810.html"
        - title: '8.9'
          url: "/nvme-rockylinux-89.html"
        - title: '8.8'
          url: "/nvme-rockylinux-88.html"
        - title: '8.7'
          url: "/nvme-rockylinux-87.html"
        - title: '8.6'
          url: "/nvme-rockylinux-86.html"
        - title: '8.5'
          url: "/nvme-rockylinux-85.html"
        - title: 8/4
          url: "/nvme-rockylinux-84.html"
    - title: SUSE Linux Enterprise Server
      pdf-filename: NVMeoF SLES
      entries:
      - title: SUSE Linux Enterprise Server 15
        entries:
        - title: 15 SP7
          url: "/nvme_sles15_sp7.html"
        - title: 15 SP6
          url: "/nvme_sles15_sp6.html"
        - title: 15 SP5
          url: "/nvme_sles15_sp5.html"
        - title: 15 SP4
          url: "/nvme_sles15_sp4.html"
        - title: 15 SP3
          url: "/nvme_sles15_sp3.html"
        - title: 15 SP2
          url: "/nvme_sles15_sp2.html"
        - title: 15 SP1
          url: "/nvme_sles15_sp1.html"
    - title: Ubuntu
      pdf-filename: NVMeoF Ubuntu
      entries:
      - title: '24.04'
        url: "/nvme_ubuntu_2404.html"
      - title: '22.04'
        url: "/nvme_ubuntu_2204.html"
    - title: Windows の場合
      entries:
      - title: '2025'
        url: "/nvme-windows-2025.html"
      - title: '2022'
        url: "/nvme_windows_2022.html"
      - title: 2019 年
        url: "/nvme_windows_2019.html"
      - title: 2016 年
        url: "/nvme_windows_2016.html"
      - title: 2012 R2
        url: "/nvme_windows_2012r2.html"
    - title: トラブルシューティングを行う
      url: "/troubleshoot.html"
  - title: 法的通知
    url: "/legal-notices.html"
product-family:
  name: ONTAP
  repo: ontap-family
