---
settings:
  name: SAN Host
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: ja-jp,us-en,zh-cn,zh-tw,ko-kr
sidebar:
  entries:
  - title: ホーム
    url: "/index.html"
  - title: SAN Host Utilities の略語
    entries:
    - title: AIX Host Utilities の略語
      entries:
      - title: AIX HU 6.1をインストールします
        url: "/hu_aix_61.html"
      - title: リリースノート
        url: "/hu_aix_61_rn.html"
    - title: HPUX ホストユーティリティ
      url: "/hu_hpux_60.html"
    - title: Linux Unified Host Utilities のこと
      entries:
      - title: Luhu 7.1をインストールします
        url: "/hu_luhu_71.html"
      - title: リリースノート
        url: "/hu_luhu_71_rn.html"
    - title: Solaris Host Utilities のことです
      url: "/hu_solaris_62.html"
    - title: Windows Unified Host Utilities のことです
      url: "/hu_wuhu_71.html"
  - title: NVMe-oF ホスト構成
    entries:
    - title: ESXi
      pdf-filename: NVMeoF ESXi
      entries:
      - title: 7.x
        url: "/nvme_esxi_7.html"
    - title: Oracle Linux の場合
      entries:
      - title: '8.2'
        url: "/nvme_ol_82.html"
      - title: '8.1'
        url: "/nvme_ol_81.html"
      - title: '7.9'
        url: "/nvme_ol_79.html"
      - title: 7 、 8
        url: "/nvme_ol_78.html"
      - title: '7.7'
        url: "/nvme_ol_77.html"
    - title: RHEL
      pdf-filename: NVMeF RHEL
      entries:
      - title: 8/4
        url: "/nvme_rhel_84.html"
      - title: '8.3'
        url: "/nvme_rhel_83.html"
      - title: '8.2'
        url: "/nvme_rhel_82.html"
      - title: '8.1'
        url: "/nvme_rhel_81.html"
    - title: SLES
      pdf-filename: NVMeoF SLES
      entries:
      - title: 15 SP3
        url: "/nvme_sles15_sp3.html"
      - title: 15 SP2
        url: "/nvme_sles15_sp2.html"
      - title: 15 SP1
        url: "/nvme_sles15_sp1.html"
    - title: Windows の場合
      entries:
      - title: 2019 年
        url: "/nvme_windows_2019.html"
      - title: 2016 年
        url: "/nvme_windows_2016.html"
      - title: 2012 R2
        url: "/nvme_windows_2012r2.html"
  - title: FCP および iSCSI ホスト構成
    entries:
    - title: AIX および PowerVM/VIOS
      entries:
      - title: 6.3.1 を参照してください
        url: "/hu_aix_72.html"
      - title: '7.1'
        url: "/hu_aix_71.html"
    - title: CentOS の場合
      entries:
      - title: CentOS 8
        entries:
        - title: '8.5'
          url: "/hu_centos_85.html"
        - title: 8/4
          url: "/hu_centos_84.html"
        - title: '8.3'
          url: "/hu_centos_83.html"
        - title: '8.2'
          url: "/hu_centos_82.html"
        - title: '8.1'
          url: "/hu_centos_81.html"
        - title: '8.0'
          url: "/hu_centos_80.html"
      - title: CentOS 7
        entries:
        - title: '7.9'
          url: "/hu_centos_79.html"
        - title: 7 、 8
          url: "/hu_centos_78.html"
        - title: '7.7'
          url: "/hu_centos_77.html"
        - title: '7.6'
          url: "/hu_centos_76.html"
        - title: '7.5'
          url: "/hu_centos_75.html"
        - title: '7.4'
          url: "/hu_centos_74.html"
        - title: '7.3'
          url: "/hu_centos_73.html"
        - title: '7.2'
          url: "/hu_centos_72.html"
        - title: '7.1'
          url: "/hu_centos_71.html"
        - title: '7.0'
          url: "/hu_centos_70.html"
      - title: CentOS 6
        entries:
        - title: '6.10'
          url: "/hu_centos_610.html"
        - title: '6.9'
          url: "/hu_centos_69.html"
        - title: 6 月 8 日
          url: "/hu_centos_68.html"
        - title: '6.7'
          url: "/hu_centos_67.html"
        - title: '6.6'
          url: "/hu_centos_66.html"
        - title: '6.5'
          url: "/hu_centos_65.html"
        - title: '6.4'
          url: "/hu_centos_64.html"
    - title: Citrix
      entries:
      - title: ハイパーバイザー 8.
        url: "/hu_citrix_8x.html"
      - title: XenServer 7
        url: "/hu_citrix_7x.html"
    - title: ESXi
      entries:
      - title: VMware vSphere 7
        url: "/hu_vsphere_7.html"
      - title: VMware vSphere 6.5 および 6.7
        url: "/hu_vsphere_6.html"
    - title: HP-UX
      entries:
      - title: 11i v3
        url: "/hu_hpux_11iv3.html"
    - title: Oracle Linux の場合
      entries:
      - title: OL 8.
        entries:
        - title: '8.5'
          url: "/hu_ol_85.html"
        - title: 8/4
          url: "/hu_ol_84.html"
        - title: '8.3'
          url: "/hu_ol_83.html"
        - title: '8.2'
          url: "/hu_ol_82.html"
        - title: '8.1'
          url: "/hu_ol_81.html"
        - title: '8.0'
          url: "/hu_ol_80.html"
      - title: OL 7.
        entries:
        - title: '7.9'
          url: "/hu_ol_79.html"
        - title: 7 、 8
          url: "/hu_ol_78.html"
        - title: '7.7'
          url: "/hu_ol_77.html"
        - title: '7.6'
          url: "/hu_ol_76.html"
        - title: '7.5'
          url: "/hu_ol_75.html"
        - title: '7.4'
          url: "/hu_ol_74.html"
        - title: '7.3'
          url: "/hu_ol_73.html"
        - title: '7.2'
          url: "/hu_ol_72.html"
        - title: '7.1'
          url: "/hu_ol_71.html"
        - title: '7.0'
          url: "/hu_ol_70.html"
      - title: OL 6
        entries:
        - title: '6.10'
          url: "/hu_ol_610.html"
        - title: '6.9'
          url: "/hu_ol_69.html"
        - title: 6 月 8 日
          url: "/hu_ol_68.html"
        - title: '6.7'
          url: "/hu_ol_67.html"
        - title: '6.6'
          url: "/hu_ol_66.html"
        - title: '6.5'
          url: "/hu_ol_65.html"
        - title: '6.4'
          url: "/hu_ol_64.html"
    - title: RHEL
      entries:
      - title: RHEL 8
        entries:
        - title: '8.6'
          url: "/hu_rhel_86.html"
        - title: '8.5'
          url: "/hu_rhel_85.html"
        - title: 8/4
          url: "/hu_rhel_84.html"
        - title: '8.3'
          url: "/hu_rhel_83.html"
        - title: '8.2'
          url: "/hu_rhel_82.html"
        - title: '8.1'
          url: "/hu_rhel_81.html"
        - title: '8.0'
          url: "/hu_rhel_80.html"
      - title: RHEL 7
        entries:
        - title: '7.9'
          url: "/hu_rhel_79.html"
        - title: 7 、 8
          url: "/hu_rhel_78.html"
        - title: '7.7'
          url: "/hu_rhel_77.html"
        - title: '7.6'
          url: "/hu_rhel_76.html"
        - title: '7.5'
          url: "/hu_rhel_75.html"
        - title: '7.4'
          url: "/hu_rhel_74.html"
        - title: '7.3'
          url: "/hu_rhel_73.html"
        - title: '7.2'
          url: "/hu_rhel_72.html"
        - title: '7.1'
          url: "/hu_rhel_71.html"
        - title: '7.0'
          url: "/hu_rhel_70.html"
      - title: RHEL 6
        entries:
        - title: '6.10'
          url: "/hu_rhel_610.html"
        - title: '6.9'
          url: "/hu_rhel_69.html"
        - title: 6 月 8 日
          url: "/hu_rhel_68.html"
        - title: '6.7'
          url: "/hu_rhel_67.html"
        - title: '6.6'
          url: "/hu_rhel_66.html"
        - title: '6.5'
          url: "/hu_rhel_65.html"
        - title: '6.4'
          url: "/hu_rhel_64.html"
    - title: Solaris の場合
      entries:
      - title: '11.4'
        url: "/hu_solaris_114.html"
      - title: '11.3'
        url: "/hu_solaris_113.html"
    - title: SLES
      entries:
      - title: SLES 15
        entries:
        - title: 15 SP3
          url: "/hu_sles_15SP3.html"
        - title: 15 SP2
          url: "/hu_sles_15SP2.html"
        - title: 15 SP1
          url: "/hu_sles_15SP1.html"
        - title: '15'
          url: "/hu_sles_15.html"
      - title: SLES 12
        entries:
        - title: 12 SP 5
          url: "/hu_sles_12SP5.html"
        - title: 12 SP 4
          url: "/hu_sles_12SP4.html"
        - title: 12 SP 3
          url: "/hu_sles_12SP3.html"
        - title: 12 SP 2
          url: "/hu_sles_12SP2.html"
        - title: 12 SP 1
          url: "/hu_sles_12SP1.html"
        - title: '12.'
          url: "/hu_sles_12.html"
    - title: Veritas の略
      entries:
      - title: Infoscale 8.
        url: "/hu_veritas_8x.html"
      - title: Infoscale 7.
        url: "/hu_veritas_7x.html"
      - title: Storage Foundation 6.
        url: "/hu_veritas_6x.html"
    - title: Windows の場合
      entries:
      - title: 2019 年
        url: "/hu_windows_2019.html"
      - title: 2016 年
        url: "/hu_windows_2016.html"
      - title: 2012 R2
        url: "/hu_windows_2012r2.html"
