= 手順1：必要に応じてSANブートを有効にします。
:allow-uri-read: 




[[step-1-optionally-enable-san-booting]]
== 手順1：必要に応じてSANブートを有効にします。

SAN ブートを使用するようにホストを構成すると、展開が簡素化され、スケーラビリティが向上します。構成で SAN ブートがサポートされていない場合は、ローカル ブートを使用できます。

[role="tabbed-block"]
====
.SAN ブート
--
SAN ブートは、SAN 接続ディスク (LUN) を AIX/PowerVM ホストのブート デバイスとして設定するプロセスです。  FC プロトコルを使用し、FC または FCoE プロトコルのいずれかで AIX ホスト ユーティリティを実行している AIX マルチパス I/O (MPIO) 環境で動作するように SAN ブート LUN を設定できます。  SAN ブート LUN を作成し、AIX MPIO 環境に新しい OS イメージをインストールする方法は、使用しているプロトコルによって異なります。


NOTE: AIXでは、MPIOが有効になるまで、SANブートディスクに対して見えるパスは1つだけである必要があります。AIXブートディスクをインストールまたは移行する場合、通常はホストのFCゾーニングを一時的に制限し、単一のFCイニシエータと単一のFCターゲットのみが含まれるようにする必要があります。PCMパッケージを含むHost Utilitiesをインストールした後、OSを再起動することでMPIOを完全に有効にできます。その時点で、追加のFCイニシエータとFCターゲットをゾーンに追加します。次に、 `cfgmgr -v`および `bosboot -a`を実行して、ブート構成を更新し、利用可能なすべてのパスを含めます。

.手順
. 使用link:https://mysupport.netapp.com/matrix/#welcome["Interoperability Matrix Tool"^]AIX OS、プロトコル、およびONTAPバージョンが SAN ブートをサポートしていることを確認します。
. ベンダーのドキュメントに記載されている SAN ブートのセットアップに関するベスト プラクティスに従ってください。


--
.ローカルブート
--
SSD、SATA、RAID などのローカル ハード ディスクに AIX OS をインストールして、ローカル ブートを実行します。

--
====