= 
:allow-uri-read: 


ホストでマルチパスが正しく設定されていることを確認するには、ファイルが定義されていること、およびONTAP LUN用にNetAppの推奨設定が設定されていることを確認し `/etc/multipath.conf`ます。

.手順
.  `/etc/multipath.conf`ファイルを見つけます。
+
参照 `/etc/multipath.conf`ファイルに NetApp デバイス固有の構成パラメータが含まれていない場合は、以下のカスタマイズされた `.conf drop-in`ファイルを使用してこれらのパラメータを追加してください。このファイルは以下の場所にあります `/etc/multipath/conf.d/`：

+

NOTE:  `/etc/multipath.conf`ファイルは変更しないでください。システムアップデート中にファイルの内容が上書きされる可能性があります。

+
.ファイルの内容を表示する
[%collapsible]
====
[source, cli]
----
$sudo tee -a /etc/multipath/conf.d/custom.conf >/dev/null <<'EOF'

defaults {
    polling_interval 5
}

blacklist {
    wwid <Insert_LUN_wwid_string>
    devnode "^(ram|raw|loop|fd|md|dm-|sr|scd|st)[0-9]*"
    devnode "^hd[a-z]"
    devnode "^cciss.*"
}

devices {
    device {
    vendor "NETAPP"
    product "LUN.*"
    user_friendly_names no
    path_checker "tur"
    prio "ontap"
    detect_prio yes
    path_grouping_policy "group_by_prio"
    path_selector "service-time 0"
    failback immediate
    fast_io_fail_tmo 5
    dev_loss_tmo infinity
    no_path_retry queue
    features "3 queue_if_no_path pg_init_retries 50"
    flush_on_last_del yes
    hardware_handler "0"
    retain_attached_hw_handler yes
    rr_weight uniform
  }
}

EOF
----
====
. マルチパスを初めて設定する場合は、推奨設定を読み込むために、マルチパスサービスを有効にして起動する必要がある場合があります。
+
[source, cli]
----
systemctl enable multipathd
----
+
[source, cli]
----
systemctl start multipathd
----
. ホストを起動するたびに、 `/etc/multipath/conf.d/custom.conf`ファイルが自動的に NetApp 推奨のホストマルチパスパラメータをデフォルト設定としてロードします。
+
次の表に、Linux OSで標準でコンパイルされたONTAP LUNのマルチパスパラメータの設定を示します。

+
.パラメータ設定の表示
[%collapsible]
====
[[multipath-parameter-settings]]
[cols="2"]
|===
| パラメータ | 設定 


| detect_prio | はい。 


| DEV_DETION_TMO | " 無限 " 


| フェイルバック | 即時 


| fast_io_fail_TMO | 5. 


| の機能 | "3 queue_if_no_path pg_init_retries 50" 


| flush_on_last_del | はい。 


| hardware_handler | 0 


| パスの再試行なし | キュー 


| path_checker です | " tur " 


| path_grouping_policy | 「 group_by_prio 」 


| path_selector | "service-time 0" 


| polling _interval （ポーリング間隔） | 5. 


| Prio | ONTAP 


| プロダクト | LUN 


| retain_attached _hw_handler | はい。 


| RR_weight を指定します | " 均一 " 


| ユーザーフレンドリ名 | いいえ 


| ベンダー | ネットアップ 
|===
====
. ONTAP LUNのパラメータ設定とパスステータスを確認します。
+
[source, cli]
----
/sbin/mpathutil status
----
+
デフォルトのマルチパス パラメータは、 ASA、 AFF、およびFAS構成をサポートします。これらの構成では、単一のONTAP LUN に 4 つを超えるパスは必要ありません。パスが 4 つを超えると、ストレージ障害時に問題が発生する可能性があります。

+
次の出力例は、ASA、AFF、またはFAS構成のONTAP LUNについて、正しいパラメータ設定とパスステータスを示しています。

+
[role="tabbed-block"]
====
.ASA構成
--
ASA構成では、特定のLUNへのすべてのパスが最適化され、アクティブな状態が維持されます。これにより、すべてのパスを同時に経由するI/O処理が行われるため、パフォーマンスが向上します。

.例を示します
[%collapsible]
=====
[listing]
----
/usr/sbin/mpathutil status
show topology
create: 3600a098038315045572b5930646f4b63 dm-1 NETAPP  ,LUN C-Mode
size=9.0G features='4 queue_if_no_path pg_init_retries 50 retain_attached_hw_handle' hwhandler='1 alua' wp=rw
`-+- policy='service-time 0' prio=50 status=active
  |- 15:0:0:0  sdb  8:16    active ready running
  |- 15:0:1:0  sdc  8:32    active ready running
  |- 16:0:0:0  sdcf 69:48   active ready running
  `- 16:0:1:0  sdcg 69:64   active ready running
----
=====
--
.AFFまたはFASの設定
--
AFFまたはFAS構成には、優先度の高いパスと低いパスの2つのグループを設定する必要があります。優先度の高いアクティブ/最適化パスは、アグリゲートが配置されているコントローラで処理されます。優先度の低いパスはアクティブですが、別のコントローラで処理されるため最適化されていません。最適化されていないパスは、最適化されたパスを使用できない場合にのみ使用されます。

次の例は、2つのアクティブ/最適化パスと2つのアクティブ/非最適化パスがあるONTAP LUNの出力を示しています。

.例を示します
[%collapsible]
=====
[listing]
----
/usr/sbin/mpathutil status
show topology
create: 3600a098038315045572b5930646f4b63 dm-1 NETAPP  ,LUN C-Mode
size=9.0G features='4 queue_if_no_path pg_init_retries 50 retain_attached_hw_handle' hwhandler='1 alua' wp=rw
|-+- policy='service-time 0' prio=50 status=active
  |- 15:0:0:0  sdb  8:16    active ready running
  `- 15:0:1:0  sdc  8:32    active ready running
`-+- policy='service-time 0' prio=50 status=active
     |- 16:0:0:0  sdcf 69:48   active ready running
     `- 16:0:1:0  sdcg 69:64   active ready running
----
=====
--
====

