= 
:allow-uri-read: 


[role="tabbed-block"]
====
.Oracle Linuxホスト
--
ホストのマルチパスが正しく構成されていることを確認するには、 `/etc/multipath.conf`が定義されており、NetApp推奨設定がONTAP LUNに対して構成されていることを確認してください。

.手順
.  `/etc/multipath.conf`ファイルが存在することを確認します。ファイルが存在しない場合は、空の0バイトのファイルを作成します：
+
[source, cli]
----
touch /etc/multipath.conf
----
. ファイルの初回作成時には `multipath.conf`、マルチパスサービスを有効にして開始し、推奨設定をロードしなければならない場合があります。
+
[source, cli]
----
systemctl enable multipathd
----
+
[source, cli]
----
systemctl start multipathd
----
. ホストをブートするたびに、空のゼロバイトファイルによって `/etc/multipath.conf`、NetApp推奨のホストマルチパスパラメータがデフォルト設定として自動的にロードされます。オペレーティングシステムは、ONTAP LUNを正しく認識および管理するマルチパスパラメータでコンパイルされているため、ホスト用のファイルを変更する必要はありません `/etc/multipath.conf`。
+
次の表に、Linux OSで標準でコンパイルされたONTAP LUNのマルチパスパラメータの設定を示します。

+
.パラメータ設定の表示
[#multipath-parameter-settings%collapsible]
=====
[cols="2"]
|===
| パラメータ | 設定 


| detect_prio | はい。 


| DEV_DETION_TMO | " 無限 " 


| フェイルバック | 即時 


| fast_io_fail_TMO | 5. 


| の機能 | "2 pg_init_retries 50" 


| flush_on_last_del | はい。 


| hardware_handler | 0 


| パスの再試行なし | キュー 


| path_checker です | " tur " 


| path_grouping_policy | 「 group_by_prio 」 


| path_selector | "service-time 0" 


| polling _interval （ポーリング間隔） | 5. 


| Prio | ONTAP 


| プロダクト | LUN 


| retain_attached _hw_handler | はい。 


| RR_weight を指定します | " 均一 " 


| ユーザーフレンドリ名 | いいえ 


| ベンダー | ネットアップ 
|===
=====
. ONTAP LUNのパラメータ設定とパスステータスを確認します。
+
[source, cli]
----
multipath -ll
----
+
デフォルトのマルチパス パラメータは、 ASA、 AFF、およびFAS構成をサポートします。これらの構成では、単一のONTAP LUN に 4 つを超えるパスは必要ありません。パスが 4 つを超えると、ストレージ障害時に問題が発生する可能性があります。

+
次の出力例は、ASA、AFF、またはFAS構成のONTAP LUNについて、正しいパラメータ設定とパスステータスを示しています。

+
*ASA設定*

+
ASA構成では、特定のLUNへのすべてのパスが最適化され、アクティブな状態が維持されます。これにより、すべてのパスを同時に経由するI/O処理が行われるため、パフォーマンスが向上します。

+
.例を示します
[%collapsible]
=====
[listing]
----
multipath -ll
3600a098038303634722b4d59646c4436 dm-28 NETAPP,LUN C-Mode
size=10G features='3 queue_if_no_path pg_init_retries 50' hwhandler='1 alua' wp=rw
|-+- policy='service-time 0' prio=50 status=active
  |- 11:0:7:6   sdbz 68:208  active ready running
  |- 11:0:11:6  sddn 71:80   active ready running
  |- 11:0:15:6  sdfb 129:208 active ready running
  |- 12:0:1:6   sdgp 132:80  active ready running
----
=====
+
*AFF または FAS 構成*

+
AFFまたはFAS構成には、優先度の高いパスと低いパスの2つのグループを設定する必要があります。優先度の高いアクティブ/最適化パスは、アグリゲートが配置されているコントローラで処理されます。優先度の低いパスはアクティブですが、別のコントローラで処理されるため最適化されていません。最適化されていないパスは、最適化されたパスを使用できない場合にのみ使用されます。

+
次の例は、2つのアクティブ/最適化パスと2つのアクティブ/非最適化パスがあるONTAP LUNの出力を示しています。

+
.例を示します
[%collapsible]
=====
[listing]
----
multipath -ll
3600a0980383036347ffb4d59646c4436 dm-28 NETAPP,LUN C-Mode
size=10G features='3 queue_if_no_path pg_init_retries 50' hwhandler='1 alua' wp=rw
|-+- policy='service-time 0' prio=50 status=active
| |- 16:0:6:35 sdwb  69:624  active ready running
| |- 16:0:5:35 sdun  66:752  active ready running
`-+- policy='service-time 0' prio=10 status=enabled
  |- 15:0:0:35 sdaj  66:48   active ready running
  |- 15:0:1:35 sdbx  68:176  active ready running
----
=====


--
.OLVM - ONTAP HA
--
Oracle Linux Virtualization Manager（OLVM）では、VDSMデーモンがハイパーバイザー上のデフォルトのマルチパスパラメータを制御します。 `/etc/multipath.conf`を直接編集しないでください。代わりに、マルチパスドロップインファイルを使用してデフォルト設定を上書きしてください。

ONTAP高可用性（HA）構成の場合、NetAppでは、 `dev_loss_tmo`と `no_path_retry`をオーバーライドするために次のドロップインファイルを推奨しています。その他のマルチパスパラメータはすべて、Oracle Linuxホストパラメータ設定テーブルの設定と一致させる必要があります。

.手順
. ドロップインファイルを作成します：
+
[source, cli]
----
cat <<'EOF' > /etc/multipath/conf.d/ontap-ha-mpath-netapp.conf
# Finite multipath retry window aligned with sanlock io_timeout
# default sanlock:io_timeout=10s, polling_interval=5s => no_path_retry = (8*10)/5 = 16

devices {
  device {
    vendor "NETAPP"
    product "LUN"
    no_path_retry 16
    dev_loss_tmo "infinity"
  }
}
EOF
----
. マルチパスデーモンを再読み込みします：
+
[source, cli]
----
systemctl reload multipathd
----
. 更新されたマルチパス構成を確認します。
+
[source, cli]
----
multipathd -k"show config"
----


--
.OLVM - ONTAP SnapMirror アクティブ同期
--
Oracle Linux Virtualization Manager（OLVM）では、VDSMデーモンがハイパーバイザー上のデフォルトのマルチパスパラメータを制御します。 `/etc/multipath.conf`を直接編集しないでください。代わりに、マルチパスドロップインファイルを使用してデフォルト設定を上書きしてください。

OLVMホストがONTAP SnapMirror Active Syncを使用している場合は、ストレージのフェイルオーバーイベント中にホストとVMが正しく動作するように、sanlockとマルチパスのタイムアウトパラメータを調整する必要があります。OLVMのデフォルトのタイムアウト値では、マルチパスリカバリが完了する前にリース更新ウィンドウが期限切れになる可能性があるため、計画外のサイトフェイルオーバー中に意図しない高可用性VMフェイルオーバーが発生する可能性があります。

NetApp ナレッジベースの記事 https://kb.netapp.com/on-prem/ontap/DP/SnapMirror/SnapMirror-KBs/Oracle_Linux_Virtualization_Manager_-_Sanlock_Settings_for_ONTAP_SnapMirror_Active_Sync["Oracle Linux Virtualization Manager - ONTAP SnapMirror Active Sync の Sanlock 設定"]の設定手順に従って、ストレージフェイルオーバーイベント中にマルチパスリカバリが完了するのに十分なリース更新ウィンドウが確保されるように、sanlockとマルチパスのタイムアウト値を更新します。

--
====