= 
:allow-uri-read: 


マルチパスデーモンを開始するには、「 multipath.conf 」ファイルが存在している必要がありますが、「 touch /etc/multipath.conf 」コマンドを使用して空のゼロバイトファイルを作成できます

このファイルを初めて作成するときに、マルチパスサービスの有効化と開始が必要になる場合があります。

[listing]
----
# systemctl enable multipathd
# systemctl start multipathd
----
に直接何も追加する必要はありません `multipath.conf` ファイル。マルチパスで管理しないデバイスがある場合、またはデフォルトよりも優先される既存の設定がある場合を除きます。

不要なデバイスを除外するには、「 multipath.conf 」ファイルに次の構文を追加します。

を交換します `<DevId>` を使用して、除外するデバイスのWWID文字列を指定します。

....
blacklist {
        wwid <DevId>
        devnode "^(ram|raw|loop|fd|md|dm-|sr|scd|st)[0-9]*"
        devnode "^hd[a-z]"
        devnode "^cciss.*"
}
....
.例
この例では、 `sda` は、ブラックリストに追加する必要があるローカルSCSIディスクです。

.手順
. 次のコマンドを実行して WWID を特定します。
+
....
# /lib/udev/scsi_id -gud /dev/sda
360030057024d0730239134810c0cb833
....
. /etc/multipath.conf 内のブラックリストスタンザに、次の WWID を追加します。
+
....
blacklist {
     wwid   360030057024d0730239134810c0cb833
     devnode "^(ram|raw|loop|fd|md|dm-|sr|scd|st)[0-9]*"
     devnode "^hd[a-z]"
     devnode "^cciss.*"
}
....


常にを確認する必要があります `/etc/multipath.conf` レガシー設定のファイル、特にデフォルトセクションでは、デフォルト設定を上書きする可能性があります。

次の表に、クリティカルなボリュームの状態を示します `multipathd` ONTAP LUNのパラメータと必要な値。ホストが他のベンダーのLUNに接続されていて、これらのパラメータのいずれかが無効になっている場合は、で後述するstanzasで修正する必要があります `multipath.conf` ONTAP LUNに適用されるファイル。そうしないと、 ONTAP LUN が想定どおりに機能しない可能性があります。これらのデフォルト設定は、影響を十分に理解したうえで、ネットアップや OS のベンダーに相談して無視してください。
