= 


NetApp Linux Unified Host Utilities ソフトウェアパッケージは、にあります link:https://mysupport.netapp.com/NOW/cgi-bin/software/?product=Host+Utilities+-+SAN&platform=Linux["ネットアップサポートサイト"^] 32 ビットまたは 64 ビットの .rpm ファイル。

Linux Unified Host Utilities をインストールすることを強く推奨しますが、必須ではありません。ユーティリティを使用しても、 Linux ホストの設定は変更されません。管理機能が向上し、ネットアップのカスタマーサポートが設定に関する情報を収集できるようになります。

. 現在インストールされている Linux Unified Host Utilities のバージョンがある場合、次のコマンドを使用してそのバージョンを削除します。
+
`rpm -e NetApp_linux_unified-connect host_utilities-7-1'

+
旧バージョンの Linux Host Utilities の場合は ' ホスト・ユーティリティ・ソフトウェアがインストールされているディレクトリに移動し ' uninstall コマンドを入力します

. から、 32 ビットまたは 64 ビットの Linux Unified Host Utilities ソフトウェアパッケージをダウンロードします link:https://mysupport.netapp.com/NOW/cgi-bin/software/?product=Host+Utilities+-+SAN&platform=Linux["ネットアップサポートサイト"^] ホストに接続します。
. ソフトウェアパッケージをダウンロードしたディレクトリに移動し、次のコマンドを使用してインストールします。
+
rpm -ivh NetApp_linux_unified-connect host_utilities-7-1.x86_64 _xx.rpm

+
[listing]
----
Verifying...                          ################################# [100%]
Preparing...                          ################################# [100%]
Updating / installing...
   1:netapp_linux_unified_host_utiliti################################# [100%]
----
. インストールを確認します。
+
「 anlun version 」を参照してください

+
[listing]
----
sanlun version 7.1.386.1644
----

