= 
:allow-uri-read: 


. ストレージ構成にMetroCluster、Oracle Solaris 仮想化、またはSnapMirror Active Sync が含まれている場合は、デフォルト設定を変更します。
+
[role="tabbed-block"]
====
.MetroCluster
--
デフォルトでは、LUN へのすべてのパスが失われた場合、Solaris OS は 20 秒後に I/O 操作の実行に失敗します。これは、 `fcp_offline_delay`パラメータ。デフォルト値は `fcp_offline_delay`標準のONTAPクラスタに適しています。ただし、 MetroCluster構成では、 `fcp_offline_delay`計画外のフェイルオーバーなどの操作中に I/O が早期にタイムアウトしないようにするために、最大 *120 秒* に設定します。

MetroClusterのデフォルト設定に関する追加情報と推奨される変更については、ナレッジベースの記事を参照してください。 https://kb.netapp.com/onprem/ontap/metrocluster/Solaris_host_support_considerations_in_a_MetroCluster_configuration["MetroCluster 構成での Solaris ホストのサポートに関する考慮事項"^] 。

--
.Oracle Solarisの仮想化
--
** Solaris 仮想化オプションには、Solaris 論理ドメイン (LDOM または Oracle VM Server for SPARC とも呼ばれます)、Solaris 動的ドメイン、Solaris ゾーン、および Solaris コンテナが含まれます。これらのテクノロジーは、「Oracle Virtual Machines」とも呼ばれます。
** 特定の Solaris 論理ドメイン内の Solaris コンテナなど、複数のオプションを一緒に使用できます。
** NetAppは、Oracleが全体的な構成をサポートし、LUNに直接アクセスできるパーティションがリストされているSolaris仮想化テクノロジの使用をサポートしています。link:https://imt.netapp.com/matrix/#welcome["IMT にログインします。"]サポートされている構成で。これには、ルート コンテナー、LDOM I/O ドメイン、NPIV を使用して LUN にアクセスする LDOM が含まれます。
** 仮想化されたストレージリソースのみを使用するパーティションまたは仮想マシン（例： `vdsk` ONTAP LUN に直接アクセスできないため、特別な資格は必要ありません。  LDOM I/Oドメインなど、基盤となるLUNに直接アクセスできるパーティションまたは仮想マシンが、link:https://imt.netapp.com/matrix/#welcome["IMT にログインします。"^] 。


.手順
LUN が LDOM 内で仮想ディスク デバイスとして使用される場合、LUN のソースは仮想化によってマスクされ、LDOM はブロック サイズを正しく検出しません。この問題を防ぐには:

.. _Oracle Bug 15824910_ の LDOM OS へのパッチ適用
.. 作成する `vdc.conf`仮想ディスクのブロックサイズを設定するファイル `4096`。詳細については、Oracle DOC: 2157669.1 を参照してください。
.. パッチのインストールを検証し、推奨設定が正しく構成されていることを確認します。
+
... zpool を作成します。
+
[source, cli]
----
zpool create zpool_name disk_list
----
... を実行します `zdb -C` zpoolに対して実行し、* ashift *の値が `12`。
+
*ashift*の値が `12`、再実行 `zdb -C11`正しいパッチがインストールされたことを確認し、 `vdc.conf` 。

+
*ashift*が次の値を表示するまで先に進まないでください `12`。






NOTE: Oracle バグ 15824910 に対するパッチは、いくつかの Solaris バージョンで利用可能です。最適なカーネル パッチを決定する際にサポートが必要な場合は、Oracle にお問い合わせください。

--
.SnapMirrorアクティブ同期
--
ONTAP 9.9.1 以降、Solaris ホストでSnapMirrorアクティブ同期設定がサポートされるようになりました。 SnapMirror Active Sync環境で計画外のサイトフェイルオーバースイッチオーバーが発生したときにSolarisクライアントアプリケーションが中断されないことを確認するには、 `scsi-vhci-failover-override` Solaris ホスト上の設定。この設定はフェイルオーバーモジュールを上書きします `f_tpgs`矛盾を検出するコードパスの実行を防止します。

.手順
.. 設定ファイルを作成する `/etc/driver/drv/scsi_vhci.conf`ホストに接続されているNetAppストレージ タイプについては、次の例のようなエントリを使用します。
+
[listing]
----
scsi-vhci-failover-override =
"NETAPP  LUN","f_tpgs"
----
.. オーバーライド パラメータが正常に適用されたことを確認します。
+
[source, cli]
----
devprop
----
+
[source, cli]
----
mdb
----
+
.例を表示
[%collapsible]
=====
[listing]
----
root@host-A:~# devprop -v -n /scsi_vhci scsi-vhci-failover-override      scsi-vhci-failover-override=NETAPP  LUN + f_tpgs
root@host-A:~# echo "*scsi_vhci_dip::print -x struct dev_info devi_child | ::list struct dev_info devi_sibling| ::print struct dev_info devi_mdi_client| ::print mdi_client_t ct_vprivate| ::print struct scsi_vhci_lun svl_lun_wwn svl_fops_name"| mdb -k
----
[listing]
----
svl_lun_wwn = 0xa002a1c8960 "600a098038313477543f524539787938"
svl_fops_name = 0xa00298d69e0 "conf f_tpgs"
----
=====



NOTE: 実行後 `scsi-vhci-failover-override` が適用されました。 `conf` がに追加されました `svl_fops_name`。追加情報およびデフォルト設定の推奨変更については、NetAppナレッジベースの記事を参照してください。 https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/SnapMirror/Solaris_Host_support_recommended_settings_in_SnapMirror_Business_Continuity_(SM-BC)_configuration["SnapMirrorアクティブ同期構成でのSolarisホストサポートの推奨設定"^]。

--
====

