= 
:allow-uri-read: 


GRUB ブートローダを使用して Linux ゲスト OS の PowerShell Toolkit と MBR アライメントを修正するためにディスク上で「 m bralign 」を実行した後、ゲスト OS が正しく起動するように GRUB を再インストールする必要があります。

仮想マシンの VHD ファイルに対して PowerShell Toolkit のコマンドレットが完了しました。このトピックは、 GRUB ブートローダーと「 SystemRescueCd 」を使用する Linux ゲスト OS にのみ適用されます。

. 仮想マシン用の正しいバージョンの Linux のインストール CD のディスク 1 の ISO イメージをマウントします。
. Hyper-V Manager で仮想マシンのコンソールを開きます。
. VM が実行中で、 GRUB 画面でハングしている場合は、表示領域をクリックして VM がアクティブであることを確認してから、 *Ctrl-Alt-Delete* ツールバーアイコンをクリックして VM をリブートします。VM が実行されていない場合は起動し、表示領域をただちにクリックしてアクティブにします。
. VMware BIOS のスプラッシュ画面が表示されたら、すぐに * Esc * キーを 1 回押します。ブートメニューが表示されます。
. 起動メニューで、 * CD-ROM * を選択します。
. Linux の起動画面で、「 linux rescue 」と入力します
. Anaconda （青 / 赤の設定画面）のデフォルトを使用します。ネットワークはオプションです。
. grub を起動するには、「 grub」 と入力します
. この VM に仮想ディスクが 1 つしかない場合、または複数のディスクがあるが、最初のディスクがブートディスクである場合は、次の GRUB コマンドを実行します。


[listing]
----
root (hd0,0)
setup (hd0)
quit
----
VM 内に複数の仮想ディスクがあり、起動ディスクが最初のディスクではない場合、または正しくアライメントされていないバックアップ VHD からブートして GRUB を修正する場合は、次のコマンドを入力してブートディスクを識別します。

[listing]
----
find /boot/grub/stage1
----
次に、次のコマンドを実行します。

[listing]
----
root (boot_disk,0)
setup (boot_disk)
quit
----

NOTE: 上の「 boot_disk 」は、ブート・ディスクの実際のディスク識別子のプレースホルダであることに注意してください。

. ログアウトするには、 *Ctrl-D* を押します。


Linux のレスキューがシャットダウンし、その後再起動します。
