= 
:allow-uri-read: 


GRUB ブートローダを使用して Linux ゲスト OS の PowerShell Toolkit と MBR アライメントを修正するためにディスク上で「 m bralign 」を実行した後、ゲスト OS が正しく起動するように GRUB を再インストールする必要があります。

.このタスクについて
仮想マシンの VHD ファイルに対して PowerShell Toolkit のコマンドレットが完了しました。この手順は、GRUBブートLoaderおよびを使用するLinuxゲストオペレーティングシステムにのみ適用され `SystemRescueCd`ます。

.手順
. 仮想マシン用の正しいバージョンの Linux のインストール CD のディスク 1 の ISO イメージをマウントします。
. Hyper-V Manager で仮想マシンのコンソールを開きます。
. GRUB画面でVMが実行中でフリーズしている場合は、表示領域内をクリックしてアクティブになっていることを確認し、ツールバーの* Ctrl + Alt + Delete *アイコンを選択してVMをリブートします。VM が実行されていない場合は起動し、表示領域をただちにクリックしてアクティブにします。
. VMware BIOS のスプラッシュ画面が表示されたら、すぐに * Esc * キーを 1 回押します。ブートメニューが表示されます。
. 起動メニューで、 * CD-ROM * を選択します。
. Linux の起動画面で、「 linux rescue 」と入力します
. Anaconda （青 / 赤の設定画面）のデフォルトを使用します。ネットワークはオプションです。
. grub を起動するには、「 grub」 と入力します
. このVMに仮想ディスクが1つしかない場合、または複数のディスクがあり、最初のディスクがブートディスクである場合は、次のGRUBコマンドを実行します。
+
[listing]
----
root (hd0,0)
setup (hd0)
quit
----
+
VMに複数の仮想ディスクがあり、ブートディスクが最初のディスクではない場合、またはミスアライメントされたバックアップVHDからブートしてGRUBを修正する場合は、次のコマンドを入力してブートディスクを特定します。

+
[listing]
----
find /boot/grub/stage1
----
+
次に、次のコマンドを実行します。

+
[listing]
----
root (boot_disk,0)
setup (boot_disk)
quit
----
+

NOTE: の `setup (boot_disk)`は、 `boot_disk`ブートディスクの実際のディスク識別子のプレースホルダです。



. ログアウトするには、 *Ctrl-D* を押します。
+
Linux のレスキューがシャットダウンし、その後再起動します。


